### ISSUE TITLE
hbm: allow to configure package to scan from application.conf

### ISSUE THREAD

**Issue by FrEaKmAn** [jooby-project/jooby#1010]
I'm using Hbm module and it's scan method to define packages to scan. Because I want to have modular structure, I would like to define packages as part of application.conf.

It would be nice to be able to access configuration before application start

**Comment by jknack** [comment]
Just realize this can be done like:

```
  use(new Hbm()
    .doWithSources((sources, conf) -> {
       sources.addPackage(conf.getString("mypackageProperty"));
    });
  );
```

Still, going to add a `hibernate.packagesToScan` property that does the same thing

**Comment by FrEaKmAn** [comment]
Yup, it works great. It would be nice to have hibernate option also
