### ISSUE TITLE
jooby-apitool only applying modifier on first match

### ISSUE THREAD

**Issue by paulovictorv** [jooby-project/jooby#1022]
Hello! I'm giving API Tool its first try. I want to modify the default generated "operationId": Joobys prepends the class name (when using MVC) to the method name, so I want that removed.

So as per the docs, I've implemented a modifier:

```java
use(new ApiTool()
                .modify(routeMethod -> {
                    return true;
                }, routeMethod -> {
                   
                        Optional<String> opsName = routeMethod.name();
                        opsName.ifPresent(name -> {
                            String cleaned = name.replaceAll("/[A-Z][a-z]+Controller\\.", "");
                            routeMethod.name(cleaned);
                        });
                   
                })
                .swagger("swagger")
        );
```

But only the first method of the controller gets the expected modification, all the others remain the same.

Is this the expected behavior, or was it supposed to modify every route that matches the Predicate (which is a tautology here)?

**Comment by jknack** [comment]
Duplicated. See #989
