### ISSUE TITLE
JSON parameters on GET

### ISSUE THREAD

**Issue by dustContributor** [jooby-project/jooby#1032]
Hi! From what I gathered in tests and from the docs, I am expected to use request.body(SomeClass.class)
if I am deserializing a JSON file, and to use request.params(SomeClass.class) if I am deserializing forms.

request.params should work with both GET (url parameters) and POST/etc (request body), but request.body is confined to request body contents as far as I know.

Is there any "idomatic" way of getting JSON out of a GET request parameter? Or could you give me an example of how you'd do it?

Request url would be a simple http://domain.com/api/order?{id:23}
```
// Escaped url
http://domain.com/api/order?{%22orderId%22:23}
```

Also, is there any way to allow both forms and JSON into the same request? Or do I always have to do one implementation using request.params for one and request.body for the other?

**Comment by jknack** [comment]
>  I am expected to use request.body(SomeClass.class) if I am deserializing a JSON file

Correct, if HTTP body is in `json` format.

> and to use request.params(SomeClass.class) if I am deserializing forms.

Yea, but I recommend to use `request.form(SomeClass.class)`. It is more specific and clear.

> Is there any "idomatic" way of getting JSON out of a GET request parameter? Or could you give me an example of how you'd do it?

There is, but you need to name the parameter: ` http://domain.com/api/order?q={id:23}`, then:

    SomeClass q = req.param("q").to(SomeClass.class, "json");

> Also, is there any way to allow both forms and JSON into the same request? Or do I always have to do one implementation using request.params for one and request.body for the other?

Kind of, either form or json are submitted in the HTTP body. So, no you can't using both (not sure if that is what you ask). Still, your handler could check content type and read body using form or json:

```java
  if (req.type().name().equals("application/json")) {
    SomeClass body = req.body(SomeClass.class);
  } else {
    SomeClass body = req.form(SomeClass.class);
  }
```

Also, if you send a json body and then a query string in json format would be like:

```java
SomeClass queryString = req.param("q").to(SomeClass.class, "json");
SomeClass body = req.body(SomeClass.class);
```

cool?

**Comment by dustContributor** [comment]
Ah I see, the parameter needs to have a name.

Yeah, I think that's all. Thanks!
