### ISSUE TITLE
Pac4j2 module provides less injection support than the previous version

### ISSUE THREAD

**Issue by yholkamp** [jooby-project/jooby#1046]
With version 1.3.0 the Pac4j module and its `Auth` class were deprecated in favor of the Pac4j2 module. While migrating my app I noticed that the new module favors objects over classes when configuring clients, making it seemingly impossible to use dependency injection for `Authenticator` objects. 

One such example is configuring a form client. [In the old module](https://github.com/yholkamp/jooby/blob/4718e4c33219114a8536406d8b61d82d97240190/modules/jooby-pac4j/src/main/java/org/jooby/pac4j/Auth.java#L586-L587) you could pass `DbProfileService.class` as argument, while [in the new module](https://github.com/yholkamp/jooby/blob/79899455ba048be8300e4455322b497513c34fd4/modules/jooby-pac4j2/src/main/java/org/jooby/pac4j/Pac4j.java#L557-L583) you can provide a `Authorizer` class and a function that creates a `Client` instance. As the function only receives a `Config` object, there is no way to access the Guice injector. Due to this it's seemingly impossible to use dependency injection to build a `FormClient` with a `DbProfileService`, as the latter would require a `DataSource` instance to be injected.

I might be missing workaround to still achieve this with the new module but at first glance this makes it complicated to upgrade to the new module when using a database as profile service.

**Comment by jknack** [comment]
You're right and this was intentional. Feel I added too much options to 1.x (Auth) and didn't want to do the same for 2.x.

I could probably get back the `form` options for 2.x but not sure bc wanted to keep it simple.

There is a workaround for your use case. It consists on applying a proxy/delegate pattern:

```
{
   use(new Pa4j().client(conf -> {
      return new FormClient(loginUrl, (creds, ctx) -> require(DbProfileService.class).validate(creds, ctx);
   });
}
```

Not so bad and a simply way to deal with different lifecycle options (pac4j configuration time vs jooby bootstrap)

**Comment by yholkamp** [comment]
@jknack alright makes sense, it's not too much of a hassle.
