### ISSUE TITLE
Provide own spec to ApiTool

### ISSUE THREAD

**Issue by mgeorge** [jooby-project/jooby#1047]
If we go to the effort of creating an OpenAPI spec using one of the various OpenAPI editors, it would be nice to be able to get ApiTool to use that spec rather than generated one.

Can we get support for this in ApiTool please?  Something like:
```
use(new ApiTool().swagger(swag -> {swag.useSpec('my-spec.json')}));
```
Note that we can do this now by hijacking the URI that provides the swagger.json file to Swagger UI:

```assets("/swagger/swagger.json", "my-spec.json")```

This is a bit of a dodgy hack though.

**Comment by jknack** [comment]
Nice addition, yea
