### ISSUE TITLE
Path params in some POST requests wrongly interpreted by APITool as form params

### ISSUE THREAD

**Issue by haggish** [jooby-project/jooby#1056]
Path parameters in POST requests that don't have `Body` annotation are interpreted as form parameters. This happens when endpoints are defined MVC style, not sure whether this is related to the lambda style. Tried versions 1.2.3, 1.3.0 and 1.3.1-SNAPSHOT.

Example 1 (POST without body):
```
@POST
@Path("/:handle/cancel")
public void cancel(final String handle) {
	...
}
```
will result in intermediate APITool data of 
```
{
  "response" : {
    "type" : "void"
  },
  "method" : "POST",
  "pattern" : "/api/update/messages/{handle}/cancel",
  ...
  "parameters" : [ {
    "kind" : "FORM",
    "name" : "handle",
    "type" : "java.lang.String"
  } ]
}
```

Example 2 (POST with multipart file upload, nevermind there's no other form fields than the file...)
```
@POST
@Path("/printers/:printer")
@Consumes("multipart/form-data")
public void print(String printer, Upload data) {
	...
}
```
will result in 
```
{
  "response" : {
    "type" : "void"
  },
  "method" : "POST",
  "pattern" : "/api/printing/printers/{printer}",
	...
  "parameters" : [ {
    "kind" : "FORM",
    "name" : "printer",
    "type" : "java.lang.String"
  }, {
    "kind" : "FILE",
    "name" : "data",
    "type" : "org.jooby.Upload"
  } ]
}
```
I would expect to see parameters `handle` and `printer` both as kind `PATH` and not `FORM`.

Digging into the source code, would this be solved by moving the `isPathParam` check in `BytecodeRouteParser.toRouteParameter` method _before_ the form parameter check?

**Comment by jknack** [comment]
Probably yea, want to give a try and send a pull request?

**Comment by haggish** [comment]
Sure, I'll see tomorrow if I'm able to make one
