### ISSUE TITLE
Can Jooby use full power of multi-core?

### ISSUE THREAD

**Issue by thomasguo** [jooby-project/jooby#1066]
Hi @jknack ,

I was doing simple perf test on Jooby(v1.3.0) using a Hello World app.   I had 2 VMs, which both run on CentOS 7.x and Java 8.

(1)  1 core cpu, 1GB mem.    It got about 60,000 rps .
(2)  8 core cpu, 32GB mem.  It got about 115,000 rps.

 Considering the second VM is 8x power than the first one, but only get less 2x performance.  I like to know whether Jooby can use fully the power of multi-core CPU?  Or did I miss any configuration option to tune that?  

Thanks.

**Comment by jknack** [comment]
Depends on server:

[Netty](https://github.com/jooby-project/jooby/blob/master/modules/jooby-netty/src/main/resources/org/jooby/spi/server.conf)

```
netty {

  threads {
    Min = ${server.threads.Min}

    Max = ${server.threads.Max}

    Name = netty task

    Boss = 1

    Worker = ${runtime.processors-x2}
  }

```

[Undertow](https://github.com/jooby-project/jooby/blob/master/modules/jooby-undertow/src/main/resources/org/jooby/spi/server.conf):

```
undertow.workerThreads = ${server.threads.Max}
```

[Jetty](https://github.com/jooby-project/jooby/blob/master/modules/jooby-jetty/src/main/resources/org/jooby/spi/server.conf):

```
jetty {

  threads {
    MinThreads = ${server.threads.Min}

    MaxThreads = ${server.threads.Max}
}
```

By default `server.threads.Min=Math.max(4, processors)` and `server.threads.Max=Math.max(32, processors * 8)` 

You need to play and test.

**Comment by jknack** [comment]
Here is another example/setup for [Techempower benchmarks](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/jooby/conf/application.conf). It uses Netty.

**Comment by thomasguo** [comment]
Thank you for the information. @jknack 
With the 8-core VM and undertow server,  I config the undertow.workerThreads option as  8, 16, 32, 64,  but I didn't see obvious difference.   Among those the 32 performs best, which I think is also jooby's default value.  Seems we could not get a linar scalability in terms of throughout.

Also I'd like to share some of my test result information:
(1) When there are more cpu cores, Netty can reach to higher throughout than undertow, though it needs more warm up time.  On my 8 core VM test, Netty finally got 180000 rps while Undertow got just 115000 rps.   
(2)  Jooby's out-of-box configuration could give us a good throughout in most cases.
