### ISSUE TITLE
API tool can't load definitions added in private function

### ISSUE THREAD

**Issue by marcelstoer** [jooby-project/jooby#1071]
This configuration starts the application just fine, all routes in place:

```kotlin
class ServiceMain : Kooby({
    use(Jackson().doWith { it.registerModule(KotlinModule()) })
    ...
    registerRoutes()
})

private fun Kooby.registerRoutes() {
    use(Currencies())
}
```

The API tool, however, produces a `swagger.json` with no `paths` and no `definitions`. Looks it somehow misses the entry point to scan the routes.

If you inline the private function all is well. This works:
```kotlin
class ServiceMain : Kooby({
    use(Jackson().doWith { it.registerModule(KotlinModule()) })
    ...
    use(Currencies())
})
```

**Comment by jknack** [comment]
Yea, this is not supported :(

**Comment by marcelstoer** [comment]
Oh, "not supported" as in "won't/can't _ever_ be supported, go away" or as in "not yet implemented"?

**Comment by jknack** [comment]
Won't ever be supported... Reason is this is not exactly a `scanner` we look at java/kotlin initializers and then jump when `use` like instruction is found, follow me? It isn't easy to follow every single call to see if there are routes inside.
