### ISSUE TITLE
Error parsing parameter to java.time.ZonedDateTime

### ISSUE THREAD

**Issue by marcelstoer** [jooby-project/jooby#1073]
Route as follows:

```kotlin
delete {
  val start = param<ZonedDateTime>("start")
```
Processing `2017-01-27T15:12:07+01:00` for the `start` parameter fails with 

> org.jooby.Err: Bad Request(400): Failed to parse parameter 'start' to 'java.time.ZonedDateTime'

I tried both with and without URL encoding:

```
curl -X DELETE "my-entry-point?start=2017-01-27T15%3A12%3A07%2B01%3A00" -H "accept: application/json"
curl -X DELETE "my-entry-point?start=2017-01-27T15:12:07+01:00" -H "accept: application/json"
```

I also checked the documentation to see if it mentioned any special procedure for the `java.time.` classes.

**Comment by marcelstoer** [comment]
> @jknack if there is an easy way to convert to zoneddatetime (without extra library) then it should be supported by Jooby

https://gitter.im/jooby-project/jooby?at=5ae33970dad6fb186ff2ac07

The correct date time formatter pattern is `yyyy-MM-dd'T'HH:mm:ss[.S]XXX`. OpenAPI 2.0 uses https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14 to define what format `format: date-time` actually represents; it's strict and only millis are optional. Sample code:

```java
DateTimeFormatter fmt = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss[.S]XXX");
System.out.println(ZonedDateTime.parse("2017-01-27T15:12:07.6+01:00", fmt));
System.out.println(ZonedDateTime.parse("2017-01-27T15:12:07+01:00", fmt));
System.out.println(ZonedDateTime.parse("2017-01-27T15:12:07.6Z", fmt));
System.out.println(ZonedDateTime.parse("2017-01-27T15:12:07Z", fmt));
System.out.println(ZonedDateTime.parse("2017-01-27T15:12:07.6-08:30", fmt));
System.out.println(ZonedDateTime.parse("2017-01-27T15:12:07-08:30", fmt));
System.out.println(ZonedDateTime.parse("2017-01-27T15:12:07.6-08:00", fmt));
System.out.println(ZonedDateTime.parse("2017-01-27T15:12:07-08:00", fmt));
```
Output
```
2017-01-27T15:12:07.600+01:00
2017-01-27T15:12:07+01:00
2017-01-27T15:12:07.600Z
2017-01-27T15:12:07Z
2017-01-27T15:12:07.600-08:30
2017-01-27T15:12:07-08:30
2017-01-27T15:12:07.600-08:00
2017-01-27T15:12:07-08:00
```

**Comment by marcelstoer** [comment]
For folks who might find this issue through a web search here's a sample parser for `ZonedDateTime` in Kotlin. Put this into your `Kooby` class:

```kotlin
parser { type, ctx ->
    val rfc3339Formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss[.S]XXX")
    if (type.rawType == ZonedDateTime::class.java) {
        return@parser ctx.param { values ->
            ZonedDateTime.parse(values.get(0), rfc3339Formatter)
        }
    }
    ctx.next()
}
```

**Comment by jknack** [comment]
done https://github.com/jooby-project/jooby/commit/5723bce1ae188bb87564de85482cfde1472124a0
