### ISSUE TITLE
Environment is getting cleared on application startup

### ISSUE THREAD

**Issue by dbartel** [jooby-project/jooby#1078]
*Background:* I'm trying to use [on](https://jooby.org/doc/#conf-env-and-logging-environment) to toggle some endpoints off that should only exist in my DEV environment. I have some code in my Server app like the following

```kotlin
on("dev", Runnable {
        use(DebugEndpoint::class)
})
```

In my *application.conf* I have the following environment set:

```
application.env = "dev"
```

When starting up the server, I see the following logged:

```
[&@netty]: Server started in 4355ms
```

The DebugEndpoints are not available because the server thinks its in no environment, (or an empty string?)

Note - I haven't been able to reproduce this 100% of the time, so it may be an issue with the environment I deployed the jar to, but I haven't found anything . On my local machine, it's running as expected.

*More info that may help:*

* I'm using MVC routes
* I'm using Kotlin with the Kooby DSL
* I'm using the [shadow](https://github.com/johnrengelman/shadow) plugin to create a fat jar for deployment 
* I'm starting the application using this command:
```
java -Xmx1024m -XX:MaxMetaspaceSize=256m -XX:NewSize=200m -XX:MaxNewSize=200m -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=7080 -Dcom.sun.management.jmxremote.local.only=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -classpath ./server.jar com.server.app.ServerKt
```

**Comment by jknack** [comment]
Try:

> java -Xmx1024m -XX:MaxMetaspaceSize=256m -XX:NewSize=200m -XX:MaxNewSize=200m -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=7080 -Dcom.sun.management.jmxremote.local.only=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -classpath ./server.jar com.server.app.ServerKt dev

**Comment by jknack** [comment]
did you figure it out?

**Comment by dbartel** [comment]
@jknack No, I'm at the same place as before. I've tried both using application.conf and passing the environment as an ARGV. 

Like I said, this isn't happening on my machine, only in the AWS environment I'm deploying to.

The conclusion I've come to is there's _something_ I've configured in the AWS environment which is causing Jooby to clear out the environment variable, but I don't know enough about the Jooby internals to determine if that's what's going on.

**Comment by jknack** [comment]
Did you add a `&` (run in background) to your command line? Make sure is correctly set so the JVM don't think it is a program argument.

**Comment by dbartel** [comment]
@jknack Looks like we have a winner! It looks like the bash script that's starting this up on the AWS environment is passing & incorrectly. I had a feeling it'd be something silly like that. Thanks for the help, I'll close this guy out!

**Comment by jknack** [comment]
Cool! My preferred deploy method is via [stork](https://jooby.org/doc/stork/). In my experience is a lot better than a simply `java -jar ...` command.

Please consider to star/follow the project if you found it useful.

Thanks
