### ISSUE TITLE
Can a Parser access the raw Content-Type/Accept?

### ISSUE THREAD

**Issue by mralves** [jooby-project/jooby#1080]
I need to create a custom Parser/Renderer, but I have a "custom" MediaType. Can I register a new one or access the raw value of the header inside my Parser?

Thanks.

**Comment by jknack** [comment]
You can parse based on `custom mediatype` or by a `java type`.

**Comment by mralves** [comment]
Thanks, I figured out a way to do it.

**Comment by jknack** [comment]
Cool, let me know if you have questions and/or ask question into the [gitter channel](https://gitter.im/jooby-project/jooby)
