### ISSUE TITLE
Second call to Request.body() results in empty data

### ISSUE THREAD

**Issue by verunder** [jooby-project/jooby#1081]
```
Mutant first = request.body();
Mutant second = request.body();

log.info("First: {}, Second: {}", first, 
    Strings.isNullOrEmpty(second.value()) ? "None": second.value()
);
```

yelds

`First: {..my content..}, Second: None`

Am I missing something? Is there a way to rewind my request?

**Comment by jknack** [comment]
Nope, it is the way it works. Why do you need two calls?

**Comment by verunder** [comment]
A set of routes, serving the same requests. 
Basically, we wanted to separate our own validation nicely. I guess we would need to come up with a different design.

**Comment by jknack** [comment]
Nope,  you can't (servers netty/undertow/jetty don't support this)

You can apply validation using a custom parser:

```
{
  parser((type, ctx) -> {
    Object result = ctx.next();
    if (type.getRawType() == MyClass.class) {
       MyClass myClass = (MyClass) result;
       ... do something ...
    }
    return result;
  }}
```

This is how it works the [Hibernate Validator module](https://jooby.org/doc/hbv/)

**Comment by vera-dobryanskaya** [comment]
Thanks! I will try it.  Should I close the issue?
