### ISSUE TITLE
Runtime.availableProcessors() in virtualized environments

### ISSUE THREAD

**Issue by nedtwigg** [jooby-project/jooby#1082]
On a heroku hobby instance, there is only 1 virtual CPU available.  However, `Runtime.availableProcessors` returns 8, so everything keyed off of `runtime.processors` is way too high.

https://github.com/jooby-project/jooby/blob/ad711b1101184e0bb692e7818037c670c29457f2/jooby/src/main/java/org/jooby/Jooby.java#L3355-L3378

Starting with Java 10, [the JVM detects this better and has a flag to set the value returned by availableProcessors()](https://bugs.openjdk.java.net/browse/JDK-8146115).  But in the meantime, for apps which are running on JVM 8 or 9, what's the best way for us to override `runtime.processors` in a way that will cause all the plugins that key off of that to set their size correctly?

**Comment by jknack** [comment]
Run your application and set `runtime.processors` as program argument (probably need to set/override the `runtime.processors-*` too.

    java -jar myapp.jar runtime.processors = 1

**Comment by jknack** [comment]
Another (probably better) alternative is to create a `application.heroku.conf` file:

```
runtime.processors = 1
```

Then:

    java -jar myapp.jar heroku

**Comment by nedtwigg** [comment]
Thanks, works perfect!  I wasn't sure about the order-of-application, but indeed setting it in `application.heroku.conf` reduces the count of dependent threads (specifically quartz and netty worker threads).
