### ISSUE TITLE
Suggestions for running on Google App Engine

### ISSUE THREAD

**Issue by mgeorge** [jooby-project/jooby#1083]
Google App Engine has some fairly generous free quotas, and it would be nice to be able to take advantage of that when I want to deploy a Jooby service.

I have deployed many servlet based applications to GAE in the past, but am not sure where to start with Jooby.  The servlet 'server' seems to be discouraged -- currently that section doesn't even have any content in the Jooby docs (https://jooby.org/doc/servers/#servlets).

Has anyone deployed a Jooby service to GAE?  Any suggestions?

**Comment by mgeorge** [comment]
Never mind.  I thought GAE only supported servlet style services.  There is now a 'flexible' deployment option that can likely run Jooby services.

**Comment by mgeorge** [comment]
Actually, the flexible deployment is not free.  So, I guess servlets are the only option.

What is the status of the servlet support in Jooby?

**Comment by jknack** [comment]
It works with some limitations. Need to fix the web site to shows the `servlets` documentation, meanwhile you can read from [here](https://github.com/jooby-project/jooby/blob/master/doc/war.md)

**Comment by husayt** [comment]
Isn't appengine standard using Jetty? WHy can't then to take advantage of jooby's jetty support?

**Comment by mgeorge** [comment]
Because the standard App Engine uses the WAR format to deploy into a managed instance of Jetty.  Jooby on the other hand uses an embedded Jetty.
