### ISSUE TITLE
JDBC session module

### ISSUE THREAD

**Issue by sahilm** [jooby-project/jooby#1084]
I would like to store sessions in a JDBC store. I see that there is no module for it. I prefer storing sessions in an RDBMS because -

* Most apps have an RDBMS backend.
* Other stores such as Redis are often used as caches. Users lose their sessions when such cache stores are cleared.
* Storing sessions in the cookie often bloats the cookie size.

Would there be any interest if I contributed such a module?

**Comment by jknack** [comment]
Absolutely, please do.

**Comment by sahilm** [comment]
Cool. I'll send a PR across soon :)

**Comment by sahilm** [comment]
I've lost interest. Thanks for being welcoming.
