### ISSUE TITLE
Default Freemarker configuration allows XSS injection

### ISSUE THREAD

**Issue by sahilm** [jooby-project/jooby#1095]
The default freemarker configuration allows XSS injection. To escape HTML by default the user must know how to explicitly configure [Freemarker](https://freemarker.apache.org/docs/dgui_quickstart_template.html#dgui_quickstart_template_autoescaping).

To be XSS safe by default, the user must do the following:

* Update config

```scala
freemarker {
  recognize_standard_file_extensions = true
}
```

* Change default file extension to `.ftlh`
```java
use(new Ftl("/", ".ftlh"));
```

I see two options -

* Change to default to the above. This will obviously break some existing users. Though this can be called out in the release notes and docs.

* Keep the default as-is. Put a warning in the docs and explain how to do the above?

I think we should do one of the above. What do you think @jknack?

**Comment by jknack** [comment]
Odd, but why the extension change?

**Comment by sahilm** [comment]
That's how Freemarker identifies the escaping mode. `.ftlh`(HTML auto-escaping) and `.ftlx`(XML auto-escaping).

**Comment by jknack** [comment]
is there a way to enable html escaping and keep the `.ftl` extension? Think that should be the default
