### ISSUE TITLE
APITool and param object

### ISSUE THREAD

**Issue by aclowkey** [jooby-project/jooby#1096]
The parameter objects are great to have a reasonable route method signature.
However, what is lost is the documentation of the API tool.

You can see this happen in a sample project:  [jooby-apitool-param-obj](https://github.com/aclowkey/jooby-apitool-param-obj)

At the moment we're working around this by writing custom **ApiPaser**, **ApiProvider** and **ApiTool** and annotations to hack our way around this using reflection. This will be difficult to maintain as Jooby upgrades.

I think there must be other projects which use the same method of accepting many GET params, and losing the documentation tool. 

What do you think?

**Comment by aclowkey** [comment]
I think we can introduce another annotation `@ParameterObject` and use reflection to get declared public fields. But I'm not sure, since it only affects APITool.

**Comment by jknack** [comment]
To be clear: the issue is we don't expand single object parameter as query parameter, right?

Thanks.

**Comment by aclowkey** [comment]
Yes, exactly.
