### ISSUE TITLE
Route matching should always prefer exact path over variable path

### ISSUE THREAD

**Issue by huysamen** [jooby-project/jooby#1107]
When presented with the following 2 MVC routes (assuming declarative routing is the same),

`@PUT("/users/:id")`
`@PUT("/users/password")`

the route is always matched in the order it was specified in the source file (i.e. sending a `PUT` request to `/users/password` will try to parse 'password' into the `id` variable, which fails).

Having route matching dependant on the order of source code is not great, and very bug prone.  This can quite easily be rectified when using a trie as a matcher (have not looked at what Jooby uses).

My thought is that it should always first match exact paths, and if that fails, see if there is a variable path.

I implemented something very similar a few years ago using a trie:
https://github.com/huysamen/vertx-ext-rest/blob/master/src/main/java/org/huysamen/vertx/ext/rest/route/ResourceTrie.java

**Comment by jknack** [comment]
what you saying makes sense... but didn't want to add any crazy logic (precedence/order/etc..)

The route execution makes lot of sense in script routes:

```java
  ...first...
  ...second...
  ...
  ...N...
```

what do you see is how they run. I strongly believe it is easier to understand and follow and I force MVC routes to do same.
