### ISSUE TITLE
dependency-reduced-pom.xml is malformed?

### ISSUE THREAD

**Issue by feniix** [jooby-project/jooby#111]
After running the instructions in the in the quickstart see relativePath:
```
  <parent>
    <artifactId>jooby-project</artifactId>
    <groupId>org.jooby</groupId>
    <version>0.5.3</version>
    <relativePath>../pom.xml/pom.xml</relativePath>
  </parent>
```

**Comment by jknack** [comment]
yea, the is generated by maven-shade-plugin but isn't use it at all. I will turn off the generation of the this file.
