### ISSUE TITLE
AssetHandler breaks class routes in 1.4

### ISSUE THREAD

**Issue by aclowkey** [jooby-project/jooby#1116]
Upgrading Jooby to 1.4 introduced a new bug with the AssetHandler.

Here is a repo with sample project that uses simple MVC route, and an AssetHandler, which is commented out, that makes the route breaks.

https://github.com/aclowkey/asset-handler.

I'm attempting this on 1.3 now.

**Comment by aclowkey** [comment]
Tested on 1.2, and 1.3 and it works there.

**Comment by aclowkey** [comment]
I've realized the issue was resolved in https://github.com/jooby-project/jooby/issues/1105
Is there a list of breaking changes or upgrade guides?

**Comment by jknack** [comment]
Yea, changed the way it works. For example if your asset handle is suppose to serve files from `/images` and client ask for `/images/missing.png` it must returns a 404. That is what #1105 does.

Also, in your example the asset handler should not be so permissive: `/**`. It should be restricted to some prefix pattern: `/assets/**`, `/images/**`, '/js/**', etc..

Complete list of changes is available here: https://github.com/jooby-project/jooby/milestone/55?closed=1

**Comment by aclowkey** [comment]
Yah i think so too. My architect is quite stubborn about this. His point
was about requesting favicon.
