### ISSUE TITLE
NPE on /swagger/swagger.json

### ISSUE THREAD

**Issue by aclowkey** [jooby-project/jooby#1117]
Swagger builder get NPE ~~for parameters which have no fields.~~ 

I guess this is an edge case. We happens to have a filter which isn't complete yet.  It shouldn't break the swagger.

**Comment by aclowkey** [comment]
Not sure why it happens. The class it fails is just an implementation of an interface. I tried adding some fields and it still broke.

**Comment by jknack** [comment]
Did you fix it in your pull, right?

**Comment by aclowkey** [comment]
Yup.
