### ISSUE TITLE
Java 9+ support

### ISSUE THREAD

**Issue by dustContributor** [jooby-project/jooby#1120]
Hi! I imagine that with how many dependencies there are in a web project these days, these kind of things get pretty complex but I'll ask anyway.

How's Java 9+ support? Modules and all.

The particular reason I'm asking is a few nice syntax additions that are present today in Java 10 (like var) and some that are coming soon (switch expressions, pattern matching, etc).

**Comment by jknack** [comment]
I haven't try to run and deploy in Java 9 yet, but all the issues that were reported has been fixed.

Give it a try and share your experience

**Comment by aclowkey** [comment]
+1 We also would be happy for an upgrade to Java 10, what does this entail?

**Comment by dustContributor** [comment]
> Give it a try and share your experience

Yeah you're right, no better test than that :smile: I'll see how it goes, need to read up a bit first.

**Comment by dustContributor** [comment]
Well I setup Maven to compile against Java 10
```xml
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-compiler-plugin</artifactId>
	<configuration>
		<!-- Force use of Java 10 -->
		<source>10</source>
		<target>10</target>
		<release>10</release>
	</configuration>
</plugin>
```

I'm getting this exception in what seems to be Jooby code:
```
java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class org/jooby/whoops/SourceLocator. Method lambda$local$1(Ljava/nio/file/Path;Ljava/nio/file/Path;Ljava/nio/file/Path;Ljava/lang/String;)Lorg/jooby/whoops/SourceLocator$Source; at index 73 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
```

**Comment by aclowkey** [comment]
@dustContributor Did you try upgrading?
I upgraded maven-compiler to 10.
JOOQ to 3.11, which resulted in some naming changes and --add-modules tricks, and I got stuck on having bad generated sources..They're importing jooq.Index classes which don't actually exist in the package

**Comment by dustContributor** [comment]
I upgraded jOOQ, re-generated the classes for my database with the updated codegen, updated jOOQ on my Jooby site, everything works so far.

The only extra module flag I needed was '--add-modules java.xml.bind'

The only issue I've had in jOOQ's generated code is a bunch of javax.annotation.Generated imports that should be javax.annotation.processing.Generated instead, which I've already created an issue for in jOOQ's repo.

**Comment by aclowkey** [comment]
@dustContributor Did you import the package org.jooq:jooq:3.11.0, or org.jooby:jooq:1.4.0? or Both?

**Comment by jknack** [comment]
Guys, what else did you find?

I found we need to upgrade all these libraries:

- guice:4.2.0 (but still shows a couple of illegal access warnings)
- maven-compiler-plugin:3.7.0
- maven-assembly-plugin:3.1.0 (stork)
-rest-assured:3.1.0 (for running tests)

**Comment by aclowkey** [comment]
I didn't update guice and it worked fine with the rest of the changes.
Had some issue with external libraries.

**Comment by jknack** [comment]
Working sample: https://github.com/jooby-project/hello-java10-starter

**Comment by jknack** [comment]
shared the feeling, but we have to deal with it for a bit :(
