### ISSUE TITLE
Jooby uses inline definition instead of schema ref describing a POST body parameter

### ISSUE THREAD

**Issue by haggish** [jooby-project/jooby#1126]
Hi !

I have the following controller endpoint:
```	
@POST
public Boolean doPing(@Body PingCommand pingCommand) {
//...
}
```

In v1.3.0, this resulted in the following endpoint parameter definition:
```
"parameters": [
	{
		"in": "body",
		"name": "pingCommand",
		"required": true,
		"schema": {
			"$ref": "#/definitions/PingCommand"
		}
	}
]
```

In v1.4.0 (apparently as a result of changes from #1096),  the definition is the set of `PingCommand` properties instead of schema reference :
```
"parameters": [
	{
		"name": "host",
		"in": "query",
		"required": false,
		"type": "string"
	},
	{
		"name": "timeout",
		"in": "query",
		"required": false,
		"type": "integer",
		"format": "int32"
	}
]
```
The `PingCommand` is generated but not referenced.

The problem being that
- I would like it to refer to the schema (or is this intentional design) and
- the parameter type is wrong (`query` instead of `body`).

**Comment by jknack** [comment]
Seems a bug to me. This:

```
@POST
public Boolean doPing(@Body PingCommand pingCommand) {
//...
}
```

Should be a schema ref. The parameters expansion should only apply to form post.
