### ISSUE TITLE
not found jooby-gson dependency on parent pom.xml

### ISSUE THREAD

**Issue by halflite** [jooby-project/jooby#1131]
Please add jooby-gson dependency to `jooby/pom.xml` .

**Comment by jknack** [comment]
Gson is part of the parent [pom.xml](https://github.com/jooby-project/jooby/blob/master/pom.xml#L883-L888).

We won't add it to jooby core (jooby/xml) bc jooby doesn't depends on it.

**Comment by halflite** [comment]
I need Parent Maven BOM(Bill of Materials) for jooby-gson.
Would you write this on [pom.xml](https://github.com/jooby-project/jooby/blob/25991d52e67807a1799c9f6a6bbc0be735acce30/pom.xml#L121).

```xml
      <dependency>
        <groupId>org.jooby</groupId>
        <artifactId>jooby-gson</artifactId>
        <version>${jooby.version}</version>
      </dependency>
```

**Comment by jknack** [comment]
> We won't add it to jooby core (jooby/xml) bc jooby doesn't depends on it

Ignore that comment.

Got confused with`gson` library when you asked for `jooby-gson`. Will do.
