### ISSUE TITLE
Upgrade com.google.guava:guava to version 24.1.1 or higher

### ISSUE THREAD

**Issue by feffi** [jooby-project/jooby#1132]
✗ Medium severity vulnerability found on com.google.guava:guava@21.0
- info: [Deserialization of Untrusted Data](https://snyk.io/vuln/SNYK-JAVA-COMGOOGLEGUAVA-32236)

**Comment by feffi** [comment]
for a parent list, have a look at: https://github.com/jooby-project/jooby/issues/1129

**Comment by jknack** [comment]
done here: https://github.com/jooby-project/jooby/commit/00892a49d4ca8e4f3bf97cd635ddfd5fa1005ff7
