### ISSUE TITLE
Upgrade commons-beanutils (not yet)

### ISSUE THREAD

**Issue by feffi** [jooby-project/jooby#1133]
✗ High severity vulnerability found on commons-beanutils:commons-beanutils@1.8.3
- info: [Arbitrary Code Execution](https://snyk.io/vuln/SNYK-JAVA-COMMONSBEANUTILS-30077)

**Comment by feffi** [comment]
for a parent list, have a look at: https://github.com/jooby-project/jooby/issues/1129

**Comment by feffi** [comment]
currently, there is no mitigation/fix available.

**Comment by jknack** [comment]
transitive dependency from assets-less4j. We are safe here due we don't expose dynamic property usage to external source.

still we are going to upgrade to 1.9.3
