### ISSUE TITLE
Upgrade io.undertow:undertow-core

### ISSUE THREAD

**Issue by feffi** [jooby-project/jooby#1134]
✗ Medium severity vulnerability found on io.undertow:undertow-core@1.4.25.Final
- info: [Directory Traversal](https://snyk.io/vuln/SNYK-JAVA-IOUNDERTOW-32074)

**Comment by feffi** [comment]
for a parent list, have a look at: https://github.com/jooby-project/jooby/issues/1129

**Comment by feffi** [comment]
There is no fixed version for io.undertow:undertow-core available yet.

**Comment by jknack** [comment]
Jooby doesn't expose undertow or raw utow handlers. We are safe here.
