### ISSUE TITLE
Upgrade org.jasig.cas.client:cas-client-core

### ISSUE THREAD

**Issue by feffi** [jooby-project/jooby#1141]
✗ High severity vulnerability found on org.jasig.cas.client:cas-client-core@3.4.1
- info: [XML External Entity (XXE) Injection](https://snyk.io/vuln/SNYK-JAVA-ORGJASIGCASCLIENT-31192)

**Comment by feffi** [comment]
Fix/mitigation is dependant on https://github.com/apereo/java-cas-client/issues/191

**Comment by jknack** [comment]
Same here a transitive dependency from pac4j:

```xml
[INFO] +- org.pac4j:pac4j-cas:jar:2.2.1:compile
[INFO] |  +- org.jasig.cas.client:cas-client-core:jar:3.4.1:compile
[INFO] |  \- org.jasig.cas.client:cas-client-support-saml:jar:3.4.1:compile
```

**Comment by jknack** [comment]
dependencies are automatically updated with dependabot now
