### ISSUE TITLE
pac4j2 session handling

### ISSUE THREAD

**Issue by martinfluchmfmfmf** [jooby-project/jooby#1148]
Hi, 

after fixing the issues we discussed here #1128 i'am facing another problem, which worked pretty well with pac4j version1.x & jooby 1.3:

```
ParameterClient paramclient=new ParameterClient("token",new MfAuthTokenAuthenticator(mfuserswebinstance));
		paramclient.setSupportGetRequest(true);
		paramclient.setSupportPostRequest(true);
		
 
use(new Pac4j()
				.client("/p/**", conf -> { return new FormClient("/login", new MfAuthUserPasswdAuthenticator(mfuserswebinstance)); })
				.client("/p/**", conf -> { return new CookieClient(mfuserswebinstance.getCookiename(), new MfAuthCookieAuthenticator(mfuserswebinstance)); })
				.client("/p/**", conf -> { return paramclient; })
				);
```

Explanation:
- if the user logges in with a formclient, a checkbox "rememberme" forces the MfAuthUserPasswdAuthenticator to deploy a cookie to the client indicating the "rememberme" with a special token
- in the same time the jooby.sid cookie is sent to the client via the framework and any further request is not handled via the authentication client as the session is valid. 

The Problem (since upgrade pac4j2 and jooby 1.4.0) 
- when i come back to the page without a valid session id (jooby.sid missing or invalid) the cookie authenticator is triggered (based on the rememberme cookie)
- login is ok, a new jooby.sid exists in the client 
- but at any further call to the page the cookie client is triggered again. seems like the session id is invalid. 

I checked
- the existence of the jooby.sid cookie in the browser = OK
- the existence of the sessionid in the sessionstore = OK

what is neccesary that the pac4j2 jooby implementation accepts the session as correct ? only jooby.sid and existence ? am I right?

Martin

**Comment by jknack** [comment]
Hi Martin,

 We will need to isolate the issue so I can reproduce it. Try to create a standalone example (or better send a pull request).

Thanks.

**Comment by martinfluchmfmfmf** [comment]
Hi,

attached a Sample to reproduce (as .txt as .java is not accepted to upload). I extended the relevant lines to our already discussed pac4j starter app. 

built a CookieClient
```
@Override
		public void validate(TokenCredentials credentials, WebContext context) throws HttpAction, CredentialsException {
			final String token = credentials.getToken();
			boolean ok = validCookies.contains(token);

			log.info("cookie token={} ok={}", token, ok);
			if (ok == false)
				throw HttpAction.unauthorized("AJAX request token not found -> 401", context, null);

			final CommonProfile profile = new CommonProfile();
			String dummyusername = "dummy_" + token;
			profile.setId(dummyusername);
			profile.addAttribute(Pac4jConstants.USERNAME, dummyusername);
			profile.addAttribute(CommonProfileDefinition.DISPLAY_NAME, dummyusername);
			credentials.setUserProfile(profile);
		}
```

included in my client implementation
```
}).client("p/**", conf -> {
					return new CookieClient(COOKIENAME, new MfAuthCookieAuthenticator());
				}));
```

extended the form client to issue a cookie
```
boolean rememberme = true;

						if (rememberme) {
							SecureRandom random = new SecureRandom();
							byte bytes[] = new byte[20];
							random.nextBytes(bytes);
							String token = bytes.toString();
							Cookie c = new Cookie(COOKIENAME, token);
							c.setMaxAge(60 * 60 * 24 * 7);
							if (c != null) {
								context.addResponseCookie(c);
							}
							log.info("cookie {} set to token {}", COOKIENAME, token);
							validCookies.add(token);
						}
```

The produce the Error following Steps are neccesary
* open page /p/test2
* formclient appears -> ok
* login -> ok
* check the cookies of your browser, a TESTC Cookie with generated token exists
* as long as the session is valid, reload the browser -> everything is ok 
* delete the jooby session cookie in the browser (jooby.sid), so invalidate the session
* reload the browser -> cookie client call, token check -> ok, a new session is generated (jooby.sid)

in my understanding every reload at this point should not call the cookieauth handler as a valid session exists but that's not the case. with every reload the cookie handler is called (as the session does not exist in the sessionstore)
[2018-06-23 09:12:46,007]-[netty task-4-1] INFO  starter.pac4j.App - cookie token=[B@e87b14 ok=true
[2018-06-23 09:12:54,373]-[netty task-4-1] INFO  starter.pac4j.App - cookie token=[B@e87b14 ok=true
[2018-06-23 09:14:19,282]-[netty task-4-1] INFO  starter.pac4j.App - cookie token=[B@e87b14 ok=true

Hope that helps

Martin 
 






[App.txt](https://github.com/jooby-project/jooby/files/2129719/App.txt)

**Comment by jknack** [comment]
It does, thanks.

I think it works as suppose to be. Why? A direct client like CookieClient/HeaderClient/JWT/etc won't use the HTTP Session, so on every call they run the auth function.

Now, if you don't care about creating a HTTP session and cookie, you can easily override this like:

```
.doWith(pac4j -> {
      DefaultSecurityLogic securityLogic = new DefaultSecurityLogic();
      securityLogic.setSaveProfileInSession(true);
      pac4j.setSecurityLogic(securityLogic);
})
```

The `saveProfileInSession` flag controls whenever save or not the user in the HTTP session. Default is `false`. See [DefaultSecurityLogic](http://www.pac4j.org/apidocs/pac4j/2.2.1/org/pac4j/core/engine/DefaultSecurityLogic.html)

Here is the full example:

```
use(new Pac4j()
        .doWith(pac4j -> {
          DefaultSecurityLogic securityLogic = new DefaultSecurityLogic();
          securityLogic.setSaveProfileInSession(true);
          pac4j.setSecurityLogic(securityLogic);
        })
        /** Fallback to form login: */
        .client("/p/**", conf -> {
          return new FormClient("/login", ((credentials, context) -> {
            // Create default profile:
            String username = ((UsernamePasswordCredentials) credentials).getUsername();
            final CommonProfile profile = new CommonProfile();
            profile.setId(username);
            profile.addAttribute(Pac4jConstants.USERNAME, username);
            profile.addAttribute("displayName", username);

            boolean rememberme = true;

            if (rememberme) {
              SecureRandom random = new SecureRandom();
              byte bytes[] = new byte[20];
              random.nextBytes(bytes);
              String token = bytes.toString();
              Cookie c = new Cookie(COOKIENAME, token);
              c.setMaxAge(60 * 60 * 24 * 7);
              context.addResponseCookie(c);
              log.info("cookie {} set to token {}", COOKIENAME, token);
              validCookies.add(token);
            }
            credentials.setUserProfile(profile);
          }));
        })
        .client("p/**", conf -> {
          return new CookieClient(COOKIENAME, new MfAuthCookieAuthenticator());
        }));
```

**Comment by martinfluchmfmfmf** [comment]
ok, understand. is there a chance to implement that behaviour on one client? 

```
	ParameterClient paramclient=new ParameterClient("token",new MfAuthTokenAuthenticator(mfuserswebinstance));
		paramclient.setSupportGetRequest(true);
		paramclient.setSupportPostRequest(true);
		
		
		 
		use(new Pac4j()
				.client("/p/**", conf -> { return new FormClient("/login", new MfAuthUserPasswdAuthenticator(mfuserswebinstance)); })
				.client("/p/**", conf -> { return new CookieClient(mfuserswebinstance.getCookiename(), new MfAuthCookieAuthenticator(mfuserswebinstance)); })
				.client("/p/**", conf -> { return paramclient; })
				);
```

for CookieClient it should act es described above. For the ParameterClient no Session should be created. 

Martin

**Comment by jknack** [comment]
This is question for **pac4j**, but think is possibly with a custom **SecurityLogic** that test for client:

```
/**
     * Whether we need to save the profile in session after the authentication of direct client(s). <code>false</code> 
     * by default as direct clients profiles are not meant to be saved in the web session.
     *
     * @param context the web context
     * @param currentClients the current clients
     * @param directClient the direct clients
     * @param profile the retrieved profile after login
     * @return whether we need to save the profile in session
     */
    protected boolean saveProfileInSession(final C context, final List<Client> currentClients, final DirectClient directClient, 
                                           final CommonProfile profile) {
        return directClient instanceof CookieClient;
    }
```

**Comment by martinfluchmfmfmf** [comment]
ok thank you ! considering a change of the logic for the parametermerclient so that i can work without session which is for sure the right way for the api calls..

the TokenAuthenticator is similar to the above shown cookieclient. currently i'm using the sessionstore to  inform the following code parts about the successful login (you know the logic from the #1128 ticket). what is the right way to check wheter a user is authenticated without a session? only with the  UserProfile profile = require(UserProfile.class); ? 

so at the current version my only chance is session, otherwise the discussed workaround from #1128  does not work..
```
private CommonProfile getPac4jProfile(Request req)
	{
		//workaround for https://github.com/jooby-project/jooby/issues/1128
		ProfileManager pm = req.require(ProfileManager.class);
	    List<CommonProfile> profiles = pm.getAll(req.ifSession().isPresent());
		
	    //log.info("searching for sessionid: {}",req.session().id());
	    CommonProfile foundprofile=null;
	    
	    for (CommonProfile p:profiles)
	    {
	    	//log.info("found profile: {}",p.getAttribute(Pac4jConstants.USERNAME));
	    	String sessionid=(String)p.getAttribute(SESSIONSESSIONID);
	    	if (sessionid!=null&&sessionid.equals(req.session().id()))
	    			{
	    				foundprofile=p;
	    				break; 
	    			}
	    }
	    return foundprofile; 
	}
```

 
right or is there another way?

**Comment by jknack** [comment]
This is the right way. This is what pac4j provides. The only comment I have is that you don't need the session check, but not 100% sure (this is a question for pac4j).

Also, if you have 1 profile at any time probably easy to use the `get(boolean session)` method:

```java
ProfileManager pm = require(ProfileManager.class);
Optional<UserProfile> profile = pm.get(req.ifSession().isPresent());
```
