### ISSUE TITLE
APITool: Annotating fields in parameter object

### ISSUE THREAD

**Issue by aclowkey** [jooby-project/jooby#1182]
Follow up to the issue #1096 

Some of the parameter objects have internal fields which shouldn't be exposed to Swagger.
When I implemented a temporary fix, I used a custom `Api` annotation with single field of 'ignore' and skip parameters which were ignored.

We could implement something similar here, and additionally add all of the `@ApiParam` annotation fields: description, hidden, type, etc.

**Comment by jknack** [comment]
Please provide an example of fields you want to ignore, your suggested solution and swagger output. Thanks.

**Comment by jknack** [comment]
So, `ApiParam` is now (partially) supported for mvc parameter, like:

```
public String list(@ApiParam(hidden = true) String internal)
```

While Query/Form parameter expansion is done via `ApiModelProperty`

```
public static class Query {

    @ApiModelProperty(hidden = true)
    public String internal;

    @ApiModelProperty("Search query")
    public String q;

    @ApiModelProperty(hidden = true)
    public String getInternalFoo() {
      return q + "foo";
    }
  }

  @GET
  public String list(Query q) {
    return ...;
  }
```

**Comment by aclowkey** [comment]
Thank you! this is great!
