### ISSUE TITLE
Upgrade dropwizard metrics dependency

### ISSUE THREAD

**Issue by marcelstoer** [jooby-project/jooby#1183]
[dropwizard-metrics 3.1.2](https://github.com/jooby-project/jooby/blob/master/pom.xml#L3090) is over three years old, please upgrade.

Two reasons specifically:
- 3.1.2 doesn't have extendable `HealthCheck.Result`, fixed upstream
- 3.1.2 has a classloader leak as thread-local objects aren't cleared, fixed upstream

**Comment by feffi** [comment]
I'm on it...
