### ISSUE TITLE
Deferred.resolve() without result body doesn't finished the request

### ISSUE THREAD

**Issue by DrorBuhnik** [jooby-project/jooby#1194]
Hi,
Currently when using `deferred.resolve(Results.ok())` or `deferred.resolve(Results.with(Status.NO_CONTENT))` or any other means to return result without any body Jooby doesn't "finished" the request and it will left open until server/client/middle man closes on timeout

Once we change to simple `deferred.resolve(Results.ok("dummy"))` everything works as expected

**Comment by DerDackel** [comment]
Verified this on Netty. Undertow and Jetty seem to work fine. Recommend switching the engine until this is fixed.
I might be mistaken, aber it looks to me like Netty is never even sending out a response.
