### ISSUE TITLE
add sonarcloud analysis

### ISSUE THREAD

**Issue by feffi** [jooby-project/jooby#1197]
@see https://sonarcloud.io/

**Comment by jknack** [comment]
found impossible to push from Travis. I tried all without lock keep getting:

> You're only authorized to execute a local (preview) SonarQube analysis without pushing the results to the SonarQube server. Please contact your SonarQube administrator. -> [Help 1]
[ERROR] 

I did pushed from my laptop (without coverage), but isn't the same. Travis should works too

https://sonarcloud.io/dashboard?id=org.jooby%3Ajooby-project%3Amaster

**Comment by feffi** [comment]
I'll look into this.

**Comment by JeffLeFoll** [comment]
Hello
I had a look to this issue, I managed to have travis pushed data to sonarcloud.
You can have a look to my jooby's fork results here : https://sonarcloud.io/dashboard?id=jooby-sonarcloud
The only remaining issue I have is that the coverage report are not at all the same as the coveralls one.

**Comment by JeffLeFoll** [comment]
Here is the Sonar report from travis : https://sonarcloud.io/dashboard?id=jfl-sonar-jooby-test

**Comment by marcelstoer** [comment]
I guess you know that but you may use `<sonar.exclusions>` and `<sonar.coverage.exclusions>` for that.

https://docs.sonarqube.org/latest/project-administration/narrowing-the-focus/

**Comment by jknack** [comment]
Outdated
