### ISSUE TITLE
Send email asynchronously

### ISSUE THREAD

**Issue by nedtwigg** [jooby-project/jooby#1204]
I'm using `jooby-commons-email`, jooby version `1.3.0`, protocol SMTP to send transactional emails to users.  The problem is that the SMTP call is pretty slow, which makes the server response seem sluggish to the user.

When the user clicks "Send me an email", I want to send them a response right away, and send the SMTP email on a different thread.  The downside is that if the email fails to send, it's too late to show that failure to the user, but that's okay.

I wrote this little module to do that:

https://github.com/mytakedotorg/mytakedotorg/blob/599175f84c74f41864236afafeca22c832609995/server/src/main/java/common/EmailSender.java#L32-L40

Which gets used like this:

https://github.com/mytakedotorg/mytakedotorg/blob/526bc65bc79807e13b9505b31ff827834878d97a/server/src/main/java/auth/LoginForm.java#L78-L81

It seems to me that the request should be able to serve a response before the email is sent, but the behavior I'm seeing is that it doesn't serve until the email is sent.  Any guesses why?  Does anybody have a better way for serving a response and sending an email without the email blocking the response?

Thanks for any hints :)

**Comment by jknack** [comment]
This is what I usually do. Your code looks OK, don't think is blocking the response. Try to add more logging

**Comment by nedtwigg** [comment]
Turned out to be that `SecureRandom.getInstanceStrong()` was starved for entropy on Heroku.  The emails have links with signed URLs, and that was the issue.
