### ISSUE TITLE
Request a new default method on Registry object

### ISSUE THREAD

**Issue by Gapmeister66** [jooby-project/jooby#1209]
Currently, it's not possible to lookup a Guice object based on the name **_and_** a TypeLiteral. Please could we have a new method such as:

```
  <T> T require(final String name, final TypeLiteral<T> type) {
     return require(Key.get(type, Names.named(name)));
  }
```

Or perhaps direct access to the injector?

**Comment by jknack** [comment]
Sure, will add it. Guess you already noticed the `require(Key)` method, right?

**Comment by Gapmeister66** [comment]
Good idea ;o)
