### ISSUE TITLE
error: package org.jooby.json does not exist import org.jooby.json.Jackson;

### ISSUE THREAD

**Issue by Myolisi** [jooby-project/jooby#1223]
Hi all, have a problem here am trying to use the Jackson module for my application and keep getting this error

public class App extends Jooby {

    {

        use(new Jackson());
        use(new Jdbc());

        //use routes in here
        use(Routes.class);
        use(PersonRoutes.class);

        parser((type, ctx) -> {
            if (ctx.type().name().equals("application/json")) {
                return ctx.body(body -> ResponseTransformer.transformResponse(new ObjectMapper().readTree(body.text()), type.getRawType()));
            }
            return ctx.next();
        });

        //swagger route
        use(new ApiTool()
                .swagger("/swagger")
        );

    }
    

    public static void main(String[] args) throws JsonProcessingException {
        run(App::new, args);
    }
}

error: package org.jooby.json does not exist
import org.jooby.json.Jackson;

error: cannot find symbol use(new Jackson());

**Comment by jknack** [comment]
Hi,

 Make sure the [jooby-jackson](http://mvnrepository.com/artifact/org.jooby/jooby-jackson/1.5.0) jar is in your pom.xml (Maven) or build.gradle (Gradle)

Also, why the custom parser?

```
parser((type, ctx) -> {
        if (ctx.type().name().equals("application/json")) {
            return ctx.body(body -> ResponseTransformer.transformResponse(new ObjectMapper().readTree(body.text()), type.getRawType()));
        }
        return ctx.next();
    });
```

The jackson module takes care of this already:

```
use(new Jackson());
```

**Comment by Myolisi** [comment]
Well, I do have the dependency on my  build.gradle file:

testCompile group: 'org.jooby', name: 'jooby-jackson', version: '1.5.0'

and this is how my App.class looks like:

import org.jooby.Jooby;
import org.jooby.apitool.ApiTool;
import org.jooby.jdbc.Jdbc;
import org.jooby.json.Jackson;

public class App extends Jooby {

    {
        use(new Jackson());
       
        use(new Jdbc());
        use(new Jdbi3());

        //use routes in here
        use(Routes.class);
        use(PersonRoutes.class);

        //swagger route
        use(new ApiTool()
                .swagger("/swagger")
        );

    }

    public static void main(String[] args){
        run(App::new, args);
    }
}


but every time I build the project I keep getting the same error message

**Comment by jknack** [comment]
I'm not a Gradle user, but think you need `compile` (not `testCompile`)

Here is the [gradle-starter](https://github.com/jooby-project/gradle-starter/blob/master/build.gradle) as example

**Comment by Myolisi** [comment]
Am also a newbie. Ok, changed it to ```compile``` and its now working. I thought by simply coping the declaration as is in mvnrepository would get it to work straight away.
```
// https://mvnrepository.com/artifact/org.jooby/jooby-jackson
testCompile group: 'org.jooby', name: 'jooby-jackson', version: '1.5.0'
```
anyways thanks for your time @jknack
