### ISSUE TITLE
Question: Using mvc routes how do I get the session id?

### ISSUE THREAD

**Issue by martinfluchmfmfmf** [jooby-project/jooby#1227]
Hi what is the right way to get the Session Id when I use mvc routes similar to req.ifSession... ?

Martin

**Comment by jknack** [comment]
Try:

```
mvcMethod(Optional<Session> session) {
   ...
}
```

**Comment by martinfluchmfmfmf** [comment]
looks promising ;-) when I migrate from "req/rsp" to mvc routes the documentation answers nearly anything. two questions are open:

1) how can I migrate the following scenario: 

for example to access the profile manager I used: 
```
ProfileManager pm = req.require(ProfileManager.class);
```

can I simply use ProfileManager p as Parameter or do I have to use a different approach?

2) in regard to the registration process of mvc routes, based on documentation
```
use(MyRoutes.class);
```

do I have to do this command even toe I already have a instantiation of the class (use(new MyRoutes()); ?

Thanks a lot

Martin

**Comment by jknack** [comment]
> 1. how can I migrate the following scenario:

You need a constructor like:

```
@Inject
public MyRoutes(ProfileManager pm) {
  ...
}
```

> 2. in regard to the registration process of mvc routes, based on documentation

You need to use `use(MyRoutes.class)` so Guice can instantiate the controller and inject depenendencies

**Comment by martinfluchmfmfmf** [comment]
Hi Edgar, 

partly solved, the registration of my mvc class works - I can access the route now. Only to understand it:  what is behind the use(AssetsMvcTest.class)? An instance is created (new AssetsMvcTest, binding to the guice,...) have I missed anything ? Why are then all the examples to the different Modules implemented with use(new Modulename())? 

where I fail is the guice injection. I hat the same behavior in my beginnings with jooby. 

example code:
```
@Path("/p/assetsmvc")
public class AssetsMvcTest extends AssetsGenericModule {
	private final Logger log = LoggerFactory.getLogger(AssetsMvcTest.class);
	public AssetsMvcTest() {
		super("assetsmvc", "/p/assetsmvc", false);
	}
	
	@Inject
	public AssetsMvcTest(ProfileManager pm)
	{
		log.info("profileManager inject: {}",pm);
	}
	
	{

		use((env, config, binder) -> {
			binder.bind(AssetsMvcTest.class).toInstance(this);

		});

		onStart(registry -> {
			log.info("Start {}", getName());
		});

		onStop(registry -> {
			log.info("Stop {}", getName());
		});
	}
	
	@GET
	@Path("/assetmanager")
	public Result assetmanager(String command, Optional<Session> session , Optional<Integer> parent, Optional<Integer> id, Optional<String> tag, Optional<String> uniquetype) throws Throwable {
```

in App.java

```
...
use(AssetsMvcTest.class);
...
```

When I got you right the ProfileManager Class should be injected via the constructor annotated with Inject. I don't find the log Line showing me that the constructor gets called. 

Any Idea? I'm not familiar with guice injection. Up to now I used the onStart Methods and requested the necessary Objects with registry.require...

Martin

**Comment by jknack** [comment]
Because module is a different API. Modules provide and manage lifecycle of services, routes, etc...

You are mixing [mvc routes](https://jooby.org/doc/#routes-mvc-routes) with [modules](https://jooby.org/doc/#modules).

**Comment by martinfluchmfmfmf** [comment]
Thank you - it works (btw. in both ways) - the injection takes place after calling the page (not at system start. quite clear..)
Martin

**Comment by jknack** [comment]
Cool, glad it works
