### ISSUE TITLE
APITool: Nested list causes TypeBinding error

### ISSUE THREAD

**Issue by aclowkey** [jooby-project/jooby#1230]
This only happens when the json is generated maven `jooby:apitool`
Example

```
    @GET
    public List<List<Integer>> getAll(Request req, Response res) {
        return Collections.singletonList(Arrays.asList(1, 2, 3));

    }
```

Stacktrace:

> org.jooby.Err: Bad Request(400)
> 	at org.jooby.internal.HttpHandlerImpl.handleErr(HttpHandlerImpl.java:589)
> 	at org.jooby.internal.HttpHandlerImpl.cleanup(HttpHandlerImpl.java:562)
> 	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:504)
> 	at org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:274)
> 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)
> 	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:353)
> 	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.IllegalArgumentException: Cannot create TypeBindings for class java.util.List with 2 type parameters: class expects 1
> 	at com.fasterxml.jackson.databind.type.TypeBindings.create(TypeBindings.java:139)
> 	at com.fasterxml.jackson.databind.type.TypeBindings.create(TypeBindings.java:98)
> 	at com.fasterxml.jackson.databind.type.TypeFactory._fromParamType(TypeFactory.java:1446)
> 	at com.fasterxml.jackson.databind.type.TypeFactory._fromAny(TypeFactory.java:1213)
> 	at com.fasterxml.jackson.databind.type.TypeFactory._fromParamType(TypeFactory.java:1444)
> 	at com.fasterxml.jackson.databind.type.TypeFactory._fromAny(TypeFactory.java:1213)
> 	at com.fasterxml.jackson.databind.type.TypeFactory.constructType(TypeFactory.java:623)
> 	at com.fasterxml.jackson.databind.ObjectMapper.constructType(ObjectMapper.java:1687)
> 	at org.jooby.internal.apitool.FriendlyTypeName.name(FriendlyTypeName.java:218)
> 	at org.jooby.internal.apitool.SwaggerBuilder.lambda$buildResponse$13(SwaggerBuilder.java:479)
> 	at java.util.Optional.orElseGet(Optional.java:267)
> 	at org.jooby.internal.apitool.SwaggerBuilder.buildResponse(SwaggerBuilder.java:479)
> 	at org.jooby.internal.apitool.SwaggerBuilder.build(SwaggerBuilder.java:432)
> 	at org.jooby.apitool.ApiTool.lambda$swagger$8(ApiTool.java:1054)
> 	at org.jooby.Route$OneArgHandler.handle(Route.java:1817)
> 	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:280)
> 	at org.jooby.internal.RouteChain.next(RouteChain.java:262)
> 	at org.jooby.Route$Chain.next(Route.java:2163)
> 	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:496)
> 	... 9 common frames omitted

**Comment by jknack** [comment]
Thanks

**Comment by aclowkey** [comment]
I tried to find a solution to this, but I got lost in the code..

It seems like it's a jackson issue, it gives the list 2 integer parameters..

`[GET /dummy(): java.util.List<java.util.List<java.lang.Integer, java.lang.Integer>>`

**Comment by jknack** [comment]
That's correct either the TypeSerializer/TypeDeserializer that I wrote has a bug... couldn't find easy way to serialize/deserialize a java.lang.Type :S
