### ISSUE TITLE
jdbc/hikari: configuration should be based on datasource name (db key) instead of database name

### ISSUE THREAD

**Issue by shalinmangar** [jooby-project/jooby#1234]
I have two hikari pools referring to the same database. The first is referring to the master and is supposed to have read/write connections. The other is referring to a loadbalanced set of replicas having read only connections. However if the readonly configuration is set using hikari then jooby sets readonly on both pools because the database name is the same.

Here's a dumbed down version of my application.conf:

```
# mysql master configuration
db.master.xyz.url = "jdbc:mysql://localhost/xyz?useUnicode=true"
db.master.xyz.user = "xyz"
db.master.xyz.password = "xyz"
db.master.xyz.useSSL=false

# mysql slave configuration
# jdbc:mysql:loadbalance://[host1][:port],[host2][:port][,[host3][:port]]...[/[database]] »
#  [?propertyName1=propertyValue1[&propertyName2=propertyValue2]...]
db.xyz.url = "jdbc:mysql:loadbalance://localhost/xyz?useUnicode=true&loadBalanceAutoCommitStatementThreshold=5"
db.xyz.user = "xyz"
db.xyz.password = "xyz"
db.xyz.useSSL=false

# hikari connection pool configuration
# master
db.master.xyz.hikari.autoCommit = true

# replicas
db.xyz.hikari.readOnly = true
```

Here's a simple App that reproduces the issue:
```java
package com.andify;

import org.jdbi.v3.core.Jdbi;
import org.jdbi.v3.sqlobject.SqlObjectPlugin;
import org.jooby.Jooby;
import org.jooby.jdbc.Jdbc;
import org.jooby.jdbi.Jdbi3;

public class XYZ extends Jooby {
    {
        use(new Jdbc("db.xyz"));
        use(new Jdbi3("db.xyz").doWith(jdbi -> jdbi.installPlugin(new SqlObjectPlugin())));

        use(new Jdbc("db.master.xyz"));
        use(new Jdbi3("db.master.xyz").doWith(jdbi -> jdbi.installPlugin(new SqlObjectPlugin())));

        get("/", () -> require("db.master.xyz", Jdbi.class).withHandle(handle -> handle.isReadOnly() ? "readOnly" : "readWrite"));
    }

    public static void main(final String[] args) {
        run(XYZ::new, args);
    }
}
```

I tried to workaround this by setting readOnly=true in the jdbc url passed to the replicas pool but due to https://github.com/brettwooldridge/HikariCP/issues/1116 that is overriden by hikaricp.

Finally, I was able to workaround this by setting readonly in code like this:
```java
use(new Jdbc("db.xyz").doWith((hikariConfig, config) -> hikariConfig.setReadOnly(true)));
```

**Comment by jknack** [comment]
Thanks for your detailed report. You're correct, but for now we are going to change the way it works today. Mainly to keep backward compatibility.

The workaround you did is also correct and let you achieved your goal.

This is something that going to keep in mind for 2.x

**Comment by shalinmangar** [comment]
Thank you @jknack
