### ISSUE TITLE
MockUnit.class not in a jar for end-user usage

### ISSUE THREAD

**Issue by paul-hammant** [jooby-project/jooby#1237]
https://www.programcreek.com/java-api-examples/index.php?api=org.jooby.test.MockRouter shows an example that is attractive, if a little verbose.

I'm wanting to do that because ...

```
String result = new MockRouter(new App())
        .get("/");
```

.. blows up if the prod code sets a status (method not implemented)

Refer also #1238

**Comment by jknack** [comment]
This came before. MockUnit is a jooby internal class and this is reason why there is no documentation/usage examples... still some users (who look at the source code) use it.

If that is your case then you need to add the `tests` classifier, like:

```xml
<dependency>
      <groupId>org.jooby</groupId>
      <artifactId>jooby</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
      <classifier>tests</classifier>
    </dependency>
```

There is more... MockRouter depends on EasyMock and PowerMock and this is another reason of why I never make it public and/or add documentation, users might prefer another mocking library.

I wrote MockRouter to make my life easier but was not my intention to be used publicly.

**Comment by paul-hammant** [comment]
It's in the HelloWorld generated code fragments though, Edgar. Its the first thing I delete from that given it has upper limits.

**Comment by jknack** [comment]
Yea, MockRouter is part of the generated example, not MockUnit. You asked here for MockUnit, which is an internal class
