### ISSUE TITLE
jooby-run: add supports for multi-module maven/gradle projects

### ISSUE THREAD

**Issue by pipinet** [jooby-project/jooby#1239]
1、jboos dev tool do not import compile dependencies from other sub modules into classpath.
2、hbm auto scan can not found entity class from other sub modules.
3、gradle jooby run not have watchdirs  args.  so hot reload will does not work.

**Comment by jknack** [comment]
Hi, please add/share an example project to reproduce the issue.

Thanks

**Comment by pipinet** [comment]
https://github.com/qwlabs/jooq-dev-tool-error-demo

**Comment by jknack** [comment]
Got it. Unfortunately, there is no support for multi-module projects in Maven/Gradle.

Would you like to submit a pull request?

**Comment by jknack** [comment]
Fixed in 2.0.0
