### ISSUE TITLE
Serving video stream as response.

### ISSUE THREAD

**Issue by adrian5632** [jooby-project/jooby#1244]
Hello! I have a specific scenario - I need to deal with external SDK for video streaming from recorders over the network.

It works as such:
1. Init SDK.
2. Connect to device (obtain login handle).
3. Call startPlayBack(handle, dataCallback, disconnectCallback) method.

The dataCallback is called by SDK and provides video stream bytes periodically when new bytes are fetched from the recorder. My problem is that I should serve these bytes from my backend as video stream (for example to be used in `<video>` objects in HTML client) and I have no clue how to approach this.

I tried PipedInput/OutputStreams but that seems not to be working. Ideally I'd like to use RxJava for managing the stream of bytes (this could be shared when multiple users want to stream the same video).

1. Is it possible to achieve this with Jooby? Any suggestions would be appreciated.
2. If yes, then additionally - is it possible to detect that no-one is 'reading' anymore (the user requests have been cancelled/stopped), so that I could close SDK stream handle as appropriate.

**Comment by jknack** [comment]
Not sure about 2, you will have to test and play.

Jooby provides built-in support for playing videos and byte-range requests for static files:

```
{
   assets("/video/*.mp4");
}
```

This will look for a `public/video` folder and serve .mp4 files, but I'm afraid this is not going to work for your use case.
