### ISSUE TITLE
Strategy needed to overcome "already registered with Guice" error

### ISSUE THREAD

**Issue by paul-hammant** [jooby-project/jooby#1246]
```
public class AllApps extends Jooby {
  {
     use(new AppOne());
     use(new AppTwo());
  }

  public static void main(final String[] args) {
    run(AllApps::new, args);
  }
```

AppOne and AppTwo both do `use(new Jackson);`

Internally there's a `A binding to org.jooby.Renderer annotated with @com.google.inject.name.Named(value=json) was already configured at org.jooby.json.Jackson.configure(Jackson.java:481) at org.jooby.json.Jackson.configure(Jackson.java:481)` error.

If there were a `Jooby.relaxIfApplicationScopedComponentsAreAlreadyRegistered(true);` that would be great. Note, I say "Application Scoped" because I hate using the world singleton.

Ref: [Prior GoogleGroups posting](https://groups.google.com/forum/#!topic/jooby-project/9YLDaOtq3_g)

**Comment by jknack** [comment]
yea, goal was to use Jooby subclasses to provide routes like an alternative to MVC routes, not for providing the exactly same services as parent/composer app.

Still we figure this out by using `Consumer` and reusing them from child/parent apps.
