### ISSUE TITLE
shadow plugin fails to build executable jar

### ISSUE THREAD

**Issue by lapots** [jooby-project/jooby#1249]
I am trying to build executable jar using `shadow` plugin. My `build.gradle` (I am using 4.10.2) looks like this
```
buildscript {
        repositories {
            jcenter()
        }
    
        dependencies {
            classpath "org.jooby:jooby-gradle-plugin:1.5.1"
            classpath "com.github.jengelman.gradle.plugins:shadow:1.2.4"
        }
    }
    
    apply plugin: "com.github.johnrengelman.shadow"
    
    apply plugin: "application"
    apply plugin: "jooby"
    
    repositories {
        jcenter()
    }
    
    mainClassName = "com.project.Main"
    
    dependencies {
        compile "org.neo4j:neo4j-ogm-core:3.1.3"
        compile "org.neo4j:neo4j-ogm-bolt-driver:3.1.3"
    
        compile "org.jooby:jooby-netty:1.5.1"
        compile "org.jooby:jooby-neo4j:1.5.1"
        compile "org.jooby:jooby-jackson:1.5.1"
    }
```

And my `main` class looks like this

```
    public static void main(String[] args) {
        var app = new Jooby().port(8888);
        app.use(new Neo4jOGM());
        app.use(new Jackson());
        app.path("movies", () -> {
           app.get(req -> {
               var session = app.require(SessionFactory.class).openSession();
               return session.loadAll(Movie.class);
           });
           app.get(":id", req -> {
               var session = app.require(SessionFactory.class).openSession();
               long value = req.param("id").longValue();
               return session.load(Movie.class, value);
           });
        });
        app.start();
    }
```

When I try to run `gradlew clean shadowJar` it fails with ` org.apache.tools.zip.Zip64RequiredException: archive contains more than 65535 entries` and at the same time incomplete jar has 100MB weight!

What's the problem?

**Comment by lapots** [comment]
I tried to use this option before and it still resulted in 100MB jar file which I think is way too much.

**Comment by jknack** [comment]
I'm not a gradle user, but you should try to [minimize the output](http://imperceptiblethoughts.com/shadow/#minimizing)?

If that doesn't work, there isn't much else we can do.

**Comment by lapots** [comment]
It seems the issue was the plugin version - I used `1.2.4` while the current one is already `4.0.1`!

**Comment by lapots** [comment]
I suggest to update documentation for `fat jar` as it references to outdated `1.2.4` of the plugin

**Comment by jknack** [comment]
send a pull request and fix it 😄

**Comment by Daniel-Dos** [comment]
Hi @lapots ,

with version 4.0.1 work well ?

**Comment by Daniel-Dos** [comment]
closed this issue .
