### ISSUE TITLE
Doco needs update to show how to pass 'env=prod' to mvn-jooby-run

### ISSUE THREAD

**Issue by paul-hammant** [jooby-project/jooby#1257]
Ref https://github.com/jooby-project/jooby/blob/master/doc/conf.md

This one's clear:

```
java -jar myapp.jar application.env=prod
```

These are missing, and it'd be great if it were detailed because it isn't clear if jooby:run is really exec:exec under the hood.

```
mvn jooby:run ?application.env=prod?
mvn clean test ?application.env=test?
```

Not that the documentation for exec:exec contains real examples either :(

**Comment by CDPrete** [comment]
Have you tried with `mvn jooby:run -Dapplication.env=prod`?
