### ISSUE TITLE
license-maven-plugin functionality in root pom should be disableable with a property

### ISSUE THREAD

**Issue by paul-hammant** [jooby-project/jooby#1258]
End-user usages of Jooby that extend the base Jooby pom (per the getting-started generator) activate the license-maven-plugin by default. That redoes sources on build, if there's a license present in the pom.xml

It could be the policy of a team to have a license element in the pom, but NOT to have sources changes on build. Specifically, the team may not want the license copied into the source at all.

https://github.com/jooby-project/jooby/blob/master/pom.xml#L2960 (and elsewhere in the same file).

Could the license-maven-plugin using in the base-pom depend on a property too?

```
<properties>
   <license-maven-plugin.active>false</jlicense-maven-plugin.active>
</properties>
```

.. or whatever is possible with profile (de)activation, if it is profiles that is guiding this.

**Comment by jknack** [comment]
Fixed in 2.0.0 (bit harder to active the license plugin)
