### ISSUE TITLE
There seems to be a problem connecting to a ssl enabled mongo connection

### ISSUE THREAD

**Issue by Myolisi** [jooby-project/jooby#1260]
These are the error messages I get when running the application
```
com.mongodb.MongoSocketWriteException: Exception sending message
   at com.mongodb.internal.connection.InternalStreamConnection.translateWriteException(InternalStreamConnection.java:525)

Caused by: javax.net.ssl.SSLHandshakeException.....
   at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
Caused by: java.security.cert.CertificateException.....
  at sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:231)
```
Any help would be apprenticed ..

**Comment by jknack** [comment]
Sounds like a mongo-client/jdk issue. Try to upgrade the mongo client

**Comment by Lunga-myolisi** [comment]
@jknack that doesn't seem to solve the issue. One thing I've noticed is that when you connect to the database without specifying the db configurations in the application.config file and then adding that db config in the ```app.java``` class it works fine. 

Also if I try connecting two mongo databases  using the method here https://jooby.org/doc/mongodb/ I get the following error message -->

 ```Caused by: java.lang.IllegalArgumentException: Database not found: {url for the 2nd database connetion}```

**Comment by Myolisi** [comment]
@jknack that doesn't seem to solve the issue. One thing I've noticed is that when you connect to the database without specifying the db configurations in the application.config file and then adding that db config in the app.java class it works fine.

Also if I try connecting two mongo databases using the method here https://jooby.org/doc/mongodb/ I get the following error message -->

Caused by: java.lang.IllegalArgumentException: Database not found: {url for the 2nd database connetion}

this is what I have in App.java class 
       ```use(new Mongodb("db1"));
        use(new Mongodb("db2"));```

**Comment by jknack** [comment]
Outdated
