### ISSUE TITLE
Upgrade Jackson dep (2.9.6 to 2.9.7)

### ISSUE THREAD

**Issue by paul-hammant** [jooby-project/jooby#1262]
```
git grep -l '2\.9\.6' | xargs sed -i '' -e 's/2\.9\.6/2.9.7/g'
```

^ works fine in that all tests pass for a full build.

**Comment by paul-hammant** [comment]
What are you asking, Daniel? I'm not understanding what you wrote.

**Comment by Daniel-Dos** [comment]
I asked if it's just to do an update on the lib.

thanks.

**Comment by Daniel-Dos** [comment]
done here -> #1256

**Comment by paul-hammant** [comment]
Ahh - good work. I wouldn't have done the work if I knew there was a PR with it there already.

**Comment by Daniel-Dos** [comment]
I'm changing a little, because I had updated everyone and the local build was working, but Travis was not making a mistake.

More if you have any PR to do, please also send.

**Comment by Daniel-Dos** [comment]
merge -> #1256
