### ISSUE TITLE
Guava upgrade woes.

### ISSUE THREAD

**Issue by paul-hammant** [jooby-project/jooby#1264]
```
git grep -l '25\.1-jre' | xargs sed -i '' -e 's/25\.1-jre/27.0-jre/g'
```

^ would update Guava, but there's problems in Jooby-Cassandra's tests.

Adding an extra param `unit.capture(Executor.class)` to methods that suggest they need that extra parameter with the dependency on v27, should work but does not. It is not enough as Cassandra's DataStax dep attempt so be compatible with a **prior** breakage in backwards compatibility, but using reflection, but it is not enough as the new breaking backwards compatibility with v27 isn't supported. Upstream (Cassandra and/or DataStax team need to do work). 

I did work on a DataStax shaded-Guava module (https://github.com/datastax/java-driver-shaded-guava/pull/2) to upgrade the Guave version to v27, but it is unclear to me as to whether this helps anything or not.

**Comment by paul-hammant** [comment]
Guava deleted deprecated code with v27 - https://github.com/google/guava/commit/87d87f5cac5a540d46a6382683722ead7b72d1b3 - we do, but should not, use the methods in our testbase.

**Comment by jknack** [comment]
2.x doesn't required Guava anymore
