### ISSUE TITLE
Add CSRF Example

### ISSUE THREAD

**Issue by tomhillrails** [jooby-project/jooby#1268]
The documentation does not mention how to handle CSRF vulnerabilities even though this is already baked into Jooby through the CSRFHandler.  A short example should be provided in the security section explaining the workflow of

-  Requesting a CSRF token in the GET request
-  Adding the CSRF token as a hidden field in the view
-  Having the CSRF token automatically validated in the POST request

**Comment by Daniel-Dos** [comment]
Hi @tomhillrails 

feel free to submit a PR about this example in the documentation.

**Comment by agrothe** [comment]
Was CSRF removed? I can't find it under the io.jooby namespace, only reference is under the org.jooby when I search the code.

**Comment by jknack** [comment]
Added back: https://jooby.io/#handlers-csrfhandler
