### ISSUE TITLE
Gson: support raw string as json response 

### ISSUE THREAD

**Issue by vvandertas** [jooby-project/jooby#1269]
Similar to Jackson's behavior listed in #618, Gson doesn't allow raw responses to be returned either.

Given:

```
{
 use(new Gzon());

 get("/raw", () -> {
    return "{\"json\": \"raw\"}";
 });
}
```

You receive an escaped response for Gson at `/raw`:

    "{\"json\": \"raw\"}"

**Comment by Daniel-Dos** [comment]
As soon as I have time, I try to implement this feature.
