### ISSUE TITLE
logback.[env].xml not working

### ISSUE THREAD

**Issue by aclowkey** [jooby-project/jooby#1275]
I've set up a logback.qa.xml file, which has no appenders or anything, but it still outputs the with  logback.xml config.

https://github.com/aclowkey/jooby-logback-env

**Comment by jknack** [comment]
Example app looks good. How did you start it? Here are some examples:

fatjar:
```
java -jar jooby-logback-env.jar qa
```

stork
```
bin/jooby-logback-env --start qa
```

**Comment by aclowkey** [comment]
I tried that, It still doesn't seem to load the loadback.qa.xml.
I added a breakpoint at https://github.com/jooby-project/jooby/blob/09651e4bc2e823f2396e1b8c5e2182cfff568e65/jooby/src/main/java/org/jooby/Jooby.java#L3485 and it doesn't reach there

**Comment by jknack** [comment]
oh yea, I know what it is... jooby:run instantiate the app directly, it doesn';t call the main method which is the one that bootstrap logback via `run(App::new, args)` :S

There is no easy fix for this :(

**Comment by aclowkey** [comment]
Actually it was by chance, and I don't need a fix.
In the original project the issue was I defined the logger in a static block, which was already too late to set correct logback.xml file.
