### ISSUE TITLE
multiple caches with different names raises exception

### ISSUE THREAD

**Issue by yan5** [jooby-project/jooby#1278]
I've configured the Caffeine cache as follows:

 `use(new CaffeineCache<String, String>() {});`

```
//in application.conf
caffeine.cache = "maximumSize=10"
caffeine.cache1 = "maximumSize=10"
```

But when I try to get the cache1 as follows it throws below exception:
`Cache<String, String> cache1 = req.require("cache1", Cache.class);`
```
Caused by: com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for com.github.benmanes.caffeine.cache.Cache annotated with @com.google.inject.name.Named(value=cache1) was bound.
  Did you mean?
    * com.github.benmanes.caffeine.cache.Cache
  while locating com.github.benmanes.caffeine.cache.Cache annotated with @com.google.inject.name.Named(value=cache1)
```

Not sure if I'm missing something, any idea?

**Comment by jknack** [comment]
Sorry, for not looking at this before... but it works as expected.

Usage is like:

```
Cache<String, String> cache1 = req.require("cache1", new TypeLiteral<Cache<String, String>>(){})
```

Non-default cache requires a type literal with the correct generics signature :S

This is a Guice requirement
