### ISSUE TITLE
Real request and response loggers

### ISSUE THREAD

**Issue by marcelstoer** [jooby-project/jooby#1280]
Related to #1279

For production use I keep seeing one requirement over and over again (based on 15+y experience): change log levels at runtime to turn on/off request & response trace log. This is to better debug issues in production without affecting the environment.

The prerequisite for this is to have
- a request logger that also logs the request body e.g. JSON document
- a matching response logger that logs response headers and response body

**Comment by jknack** [comment]
We are not going to change the existing implementation 1.x. AccessLogHandler in 2.x allow you to specify additional request and response headers. But isn't safe to log request/response body, that should be application specific
