### ISSUE TITLE
Redis Sentinel support

### ISSUE THREAD

**Issue by AmaranthLIS** [jooby-project/jooby#1281]
Redis can work in [cluster mode](https://redis.io/topics/sentinel) with Sentinel and Jedis client support that, but current integration jooby-jedis doesn't implement that part.

This is really important thing if you need high availability with Redis.

**Comment by AmaranthLIS** [comment]
I've send pull request.
Honestly what kind of information about License need to put, i've copied yours. 
I hope it's okey.
May some changes need to do, just give me know.

**Comment by jknack** [comment]
Done in #1282
