### ISSUE TITLE
Change default path for Config

### ISSUE THREAD

**Issue by martinbe1io** [jooby-project/jooby#1283]
Hi, 

is there a chance to preserve the functionality of class path based configfiles and providing config files (with higher ranking) in a special directory? 

I tried the following

```
public App()
	{
		log.info("START workingdir={}",System.getProperty("user.dir"));	
		conf(new File(configfile));																	
		log.info("START set configfile to {}",configfile);
	}
```

it seems the the config file is loaded from the new location, but 
- only the exact name of "configfile" not altered with environement marker. 
- secondly the read from the class path seem to be "stronger" as they are not overwritten with the parameters from the file based configfile. 

does somebody have a hint for me how to achieve the behavior mentioned at the top 

Martin

**Comment by jknack** [comment]
Hi,
  Just put an `application[.env].conf` in `user.dir` and Jooby will read/override any property from a classpath file.

**Comment by martinbe1io** [comment]
ok, but that means that there is no way to set a directory other than userdir with the same behavior easily ?

**Comment by jknack** [comment]
correct, only two: `${user.dir}` or `${user.dir}/conf`

**Comment by martinbe1io** [comment]
Thx
