### ISSUE TITLE
Hazelcast module + session store

### ISSUE THREAD

**Issue by jerrinot** [jooby-project/jooby#129]
Add Hazelcast support + session store

```java
{
  use(new Hazelcast());

  session(HazelcastSessionStore.class);
}
```

I can contribute the implementation if you think it's useful.

**Comment by jknack** [comment]
please do!

**Comment by jknack** [comment]
Hello, I'm close to release 0.8.0 and I will like to know if this is coming soon or not :)

should I wait before releasing 0.8.0?

Thanks

**Comment by jknack** [comment]
hey, I will take and do this.

**Comment by jerrinot** [comment]
ops, I just noticed your questions!
thanks for implementing it yourself.

**Comment by jknack** [comment]
np and 0.9.0 is out with Hazelcast. Happy to get feedback from you
