### ISSUE TITLE
Health Check fills session store

### ISSUE THREAD

**Issue by martinbe1io** [jooby-project/jooby#1302]
Hi, 

My Openshift health check checks whether a call to /version is successful. Due to the fact that this call is run every minute I fill my session database.

I thought that I can destroy the session immediately but it does not work. Any hint how i can destroy session entry for calls to a certain location? 

Thx 

```
get("/version", (req,rsp) -> {
            PlatformTools pt=req.require(PlatformTools.class);
            if (req.ifSession().isPresent())
            {
                log.info("try to destroy session");
                req.session().destroy();
            
            }
            String targettimezone=pt.getClientTimezone(req);
            if (pt!=null)
            {
                rsp.send(Results.json(pt.getEnvironmentMap(targettimezone)));
            }
        });
```

**Comment by jknack** [comment]
I need more details on how to reproduce this. Also, you probably just need to define/put the health check at before any other route and no session should be created it.
