### ISSUE TITLE
Hibernate & JPAQuery with Kotlin returns zero records from MySQL

### ISSUE THREAD

**Issue by JavierFuentes** [jooby-project/jooby#1303]
I've cloned [apitool-kotlin-starter](https://github.com/jooby-project/apitool-kotlin-starter) repo and made this changes:

1. Change H2 to MySQL
1. Change from script-mode to mvc-mode

All the endpoints worked OK with jooby-jdbi3.

Now, I would like to replace Jdbi3 with Hibernate and QueryDSL following the other examples like [hibernate-starter](https://github.com/jooby-project/hibernate-starter) but when I run my first `/api/pet/all` endpoint **I get always zero records from the database**. 

I'm probably doing something wrong, but I would need help to solve it...

My code looks like this:

### pom.xml
```xml
    <!-- Hibernate -->
    <dependency>
      <groupId>org.jooby</groupId>
      <artifactId>jooby-hbm</artifactId>
    </dependency>

    <dependency>
      <groupId>com.querydsl</groupId>
      <artifactId>querydsl-jpa</artifactId>
      <version>4.2.1</version>
    </dependency>
```

### App.kt
```kotlin
class App : Kooby({
    [...]

    /** Database: */
    use(Jdbc())
    use(Flywaydb())
    use(Hbm().classes(Pet::class.java))

    /** Register Controllers */
    use(PetsController::class)
})
```

### Pet.kt
```kotlin
package starter.apitool
import javax.persistence.Entity
import javax.persistence.GeneratedValue
import javax.persistence.GenerationType
import javax.persistence.Id

@Entity
data class Pet (
        @Id
        @GeneratedValue(strategy = GenerationType.IDENTITY)
        val id: Long = 0,

        val name: String
)
```

### QPet.java (autogenerated)
```java
package starter.apitool;
import static com.querydsl.core.types.PathMetadataFactory.*;
import com.querydsl.core.types.dsl.*;
import com.querydsl.core.types.PathMetadata;
import javax.annotation.Generated;
import com.querydsl.core.types.Path;

/**
 * QPet is a Querydsl query type for Pet
 */
@Generated("com.querydsl.codegen.EntitySerializer")
public class QPet extends EntityPathBase<Pet> {
    private static final long serialVersionUID = -984590108L;
    public static final QPet pet = new QPet("pet");
    public final NumberPath<Long> id = createNumber("id", Long.class);
    public final StringPath name = createString("name");
    public QPet(String variable) {
        super(Pet.class, forVariable(variable));
    }
    public QPet(Path<Pet> path) {
        super(path.getType(), path.getMetadata());
    }
    public QPet(PathMetadata metadata) {
        super(Pet.class, metadata);
    }
}
```

### PetController.kt
```kotlin
package starter.apitool
import org.jooby.mvc.GET
import org.jooby.mvc.Path
import javax.inject.Inject

/**
 * Everything about your Pets.
 */
@Path("/api/pet")
class PetsController @Inject constructor(val db: PetRepository) {
    /**
     * List all pets.
     * @return All Pets.
     */
    @GET
    @Path("/all")
    fun all(): List<Pet> {
        return db.all()
    }
}
```

### PetRepository.kt
```kotlin
package starter.apitool
import com.querydsl.jpa.impl.JPAQuery
import starter.apitool.QPet.pet
import javax.inject.Inject
import javax.persistence.EntityManagerFactory

/**
 * Database access for pets.
 */
class PetRepository @Inject constructor(val emf: EntityManagerFactory) {
    /**
     * List all pets
     * @return Available pets.
     */
    fun all(): List<Pet> {
        val em = emf.createEntityManager()
        val query = JPAQuery<Pet>(em)  // select pet\nfrom Pet pet
        val pets = query.from(pet).select(pet).fetch()  // always ZERO pets are fetched

        return pets
    }
}
```

**Comment by jknack** [comment]
Hi

add `@Table` annotation to Pet class:

```
@Entity
@Table(name = "pets")
data class Pet (
```

or renamte the table in the .sql file to `pet`

**Comment by JavierFuentes** [comment]
Hi, @jknack,
thank you very much... I had not seen that the new and void `Pet` table had been created in MySQL.

My entity class looks now like this:

### Pet.kt
```kotlin
package starter.apitool
import javax.persistence.*

@Entity
@Table(name = "pets")
data class Pet (
        @Id
        @GeneratedValue(strategy = GenerationType.IDENTITY)
        val id: Long = 0,

        val name: String
)
```

However, after doing this change compiler throws this error: `org.hibernate.InstantiationException: No default constructor for entity Pet`

To fix it, I've added `kotlin-maven-noarg` dependency to pom.xml

### pom.xml
```xml
    <plugins>
      <plugin>
        <artifactId>kotlin-maven-plugin</artifactId>
        <groupId>org.jetbrains.kotlin</groupId>
        <version>${kotlin.version}</version>

        <configuration>
          <compilerPlugins>
            <plugin>jpa</plugin>
          </compilerPlugins>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-maven-noarg</artifactId>
            <version>${kotlin.version}</version>
          </dependency>
        </dependencies>

        [...]
      </plugin>
    </plugins>

    [...]
```

Maybe, you could add this to jooby documentation or add a new starter project to jooby portfolio...

I am a beginner with Java, Kotlin, Hibernate and JPA and for that reason I am having some difficulties to join the necessary pieces **to mount a not-so-basic API-REST project with jooby based on Kotlin, MySQL, MVC and Hibernate** ...

Fortunately, you are helping me a lot.

The next step for me would be **to secure the API-REST in some way** but I have no idea how to start doing it ... any example of help would come in handy.

**Comment by jknack** [comment]
Welcome to Java! (and Jooby of course)

Glad you figure it out the error and as you can see they are unrelated to Jooby. In this case was a mix of Hibernate and Kotlin so it is hard to predict and document all possible errors of this stack. A probably better starter will be https://github.com/jooby-project/hibernate-starter which is hibernate ready, but on Java :(

**Comment by JavierFuentes** [comment]
Hi @jknack,
yes `hibernate-starter` is other of multiple sources I've been watching to do this work...

What about securing API-REST in jooby? 
Is there any jooby starter project I can watch to try to transform it to Kotlin?
