### ISSUE TITLE
Parsing nested param values

### ISSUE THREAD

**Issue by aclowkey** [jooby-project/jooby#1312]
I know there is support for specifing nested request params like:
`example.com/api?person.name=Alex&person.country=blah`,
But I was wondering if I can send this object encoded,so it wiill be like
`example.com/api?person="name%3DAlex%26country%3Dblah"`
Is there some java function that I can use? I tried digging in the code, but got last..

**Comment by jknack** [comment]
unfortunately, parsing functions are not accessible in 1.x. I changed it in 2.x

anyway, not sure I follow what you are trying to do. Encoded is supported

**Comment by aclowkey** [comment]
Say I have a class
```
public class person {
    String name ;
    String country;
    person child;
}
```

and a route which accepts an instance of that class
```
public void handle(Request req, person p){
     // p.child isn't populated!
}
```

**Comment by jknack** [comment]
hmm well no. Query/form parameter must be urlencoded:

    /?name=P&country=AR&child.name=X&child.country=UY
