### ISSUE TITLE
From handler: return text result

### ISSUE THREAD

**Issue by altmind** [jooby-project/jooby#1316]
There is a clear way to return html, json or xml from jooby route handler:
```
    get("/test") { req ->
        Results.html("<b>hi</b>")
    }
 get("/test2") { req ->
        Results.json("<b>hi</b>")
    }
 get("/test3") { req ->
        Results.xml("<b>hi</b>")
    }
```

It feels like an omission of text result. When you return a string from the handler - the user gets the string json-encoded(extra escaping for quotes and \r\n).

The following also returns double-encoded string(with \\")
```
get("/test") { req ->
        Results.with("\"test\"", 200)
    }
```

```
get("/test") { req ->
        Results.with("\"test\"", 200)
    }.produces("text/plain")
```
return correct string without double escaping, still with incorrect Content-Type: text/html;charset=UTF-8

should we just create Results.text() ?

**Comment by jknack** [comment]
Fixed this in 2.x branch. Strings are treat as "native/raw" responses we don't render them.

In 1.x and Jackson in particular you need to enable the `raw` response flag: https://github.com/jooby-project/jooby/blob/master/modules/jooby-jackson/src/main/java/org/jooby/json/Jackson.java#L416-L432
