### ISSUE TITLE
ApiTool App.json parsing response wildcard type exception

### ISSUE THREAD

**Issue by walkman90** [jooby-project/jooby#1317]
If generated by apitool plugin App.json contains wildcard types like  
  
```json
{  
  "response" : {  
    "type" : "java.util.List<? extends com.foo.Bar>"  
  },   
}
```

then `org.jooby.internal.apitool.BytecodeRouteParser#read` fails with exception

`read of /com/foo/bar/App.json resulted in exception
com.fasterxml.jackson.databind.JsonMappingException: ?extendscom.foo.Bar`

**Comment by walkman90** [comment]
Looks like this fix is missing at http://central.maven.org/maven2/org/jooby/jooby-apitool/1.6.1/

**Comment by jknack** [comment]
1.6.2 is on central now

**Comment by walkman90** [comment]
Thanks!
