### ISSUE TITLE
2.x Hikari example appears to be broken when used with Guice

### ISSUE THREAD

**Issue by yholkamp** [jooby-project/jooby#1318]
https://github.com/jooby-project/jooby/blob/2.x/examples/src/main/java/examples/HikariApp.java defines an example to use the Hikari module, which is great to clarify the usage. Due to the lack of dependency injection in the core of 2.x running the example seems to result in a 'No registry available' error. 

On the other hand, adding a `install(new Guiceby());` module definition to the app results in a `No implementation for javax.sql.DataSource was bound.` Guice exception. 

Is there additional configuration required to make the Hikari module available through DI?

**Comment by jknack** [comment]
Fixed it
