### ISSUE TITLE
Chrome sends large websocket packets that jooby-netty cannot decode with default settings

### ISSUE THREAD

**Issue by altmind** [jooby-project/jooby#1322]
This is not bug of jooby per-se, but a great design defect of websockets themselves. Websockets frames can be any size under 2^63 and the websocket protocol itself does not support frame size negotiation. For that, you cannot handle websockets frames with fixed buffers.

By default, chrome will send up to 131072 bytes in a single message(1<<17). The default netty buffer is 64K, default jooby configured buffer size is 16k.
https://cs.chromium.org/chromium/src/net/websockets/websocket_channel.cc?type=cs&q=17+file:%5Esrc/net/websockets/+package:%5Echromium$&g=0&l=48 https://github.com/jooby-project/jooby/blob/master/jooby/src/main/resources/org/jooby/jooby.conf#L154

That leads that with the default config settings, large websocket frames fail to decode.

I believe there is no proper way to fix this for arbitrary browsers and arbitrary frame sizes. Changing the websocket api to be non-buffered is a great undertaking too.

Can we change the default values of `server.ws.MaxBinaryMessageSize` and `MaxTextMessageSize` to be at least 1<<17 so new users wont be surprised their websockets are failing in chrome ?

https://i.imgur.com/9L7ncB0.png

**Comment by jknack** [comment]
Why increasing for your app isn't a solution?
The 16k buffer size is the best/recommend default value

**Comment by altmind** [comment]
>Why increasing for your app isn't a solution?

It IS a solution. I'm not blocked on this, its just a quality-of-life improvement for the people hitting the same problem as me.

Just to reassert - if the buffer size is insufficient its not just less effective recv() or lost messages - its straight websocket disconnect.

**Comment by jknack** [comment]
Can you send a pull request increasing the size for websocket only to 64k?

**Comment by altmind** [comment]
Why 64k and not 131072?

**Comment by altmind** [comment]
@jknack lets increase to 131072 to reduce the users suffering.
