### ISSUE TITLE
2.x does not allow port to be changed via settings

### ISSUE THREAD

**Issue by yholkamp** [jooby-project/jooby#1323]
With 1.x it was possible to specify the port to use in the config file via `application.port`. It appears that Jooby 2.x still uses this setting but only accepts it as program argument or JVM property. 

It'd be great if this could still be configured via the config as it allows you to easily run different environments on different (but explicit) ports. If that's not possible due to the way the environment is loaded, it'd still be great to include this behavior in the docs.

**Comment by yholkamp** [comment]
Actually it looks like using the following code (included in the static initializer) will still start Jooby 2 on another port;

    Environment env = getEnvironment();
    System.setProperty("application.port", String.valueOf(env.getConfig().getInt("application.port")));

So I think this can be solved.

**Comment by jknack** [comment]
Done here: https://github.com/jooby-project/jooby/commit/0036f57d58f1c3cc7674c1cd3d26b862d97d83c4

and release in 2.0.0.RC2 (forgot to send the notes)
