### ISSUE TITLE
Request.body() returns empty body after first call

### ISSUE THREAD

**Issue by lhgravendeel** [jooby-project/jooby#1326]
Request handlers can call `request.body()` to obtain a reference to the body. For requests with data in the body, this should return a BodyReferenceImpl that keeps the request in memory if it's small enough, or else offload it to a temporary file. This implementation will read everything from the native request's input stream.

If you call request.body() again, this will create a new BodyReferenceImpl, but this time it won't be able to get any new data from the native request's input stream. As a result, subsequent request.body() calls show 0-length body data.

For app implementations where a previous before() filter requests the full body, for instance to calculate a content digest for request signature checks, this prevents the actual request handler from still reading the body, or using `@Body` annotated method parameters.

Is the `body()` method always returning a new BodyReference instance by design? Due to the offloading of large requests that already happens, I think there is no real memory or performance penalty incurred by caching the BodyReference just within the scope of its own request. I would suggest changing https://github.com/jooby-project/jooby/blob/master/jooby/src/main/java/org/jooby/internal/RequestImpl.java#L462 to keep a request-scoped cache of the BodyReference if one was created already and returning this same instance for subsequent calls to `request.body()` in the same request.

If this is not the appropriate solution for this issue, is there any recommended way to read the body within a before() filter and still access it from a regular request processor?

The same issue is mentioned here as well: https://stackoverflow.com/questions/50181762/is-it-possible-to-access-request-body-multiple-times-in-jooby-java

**Comment by jknack** [comment]
Answered from StackOverflow is correct. It is not possible to ensure multiple read of HTTP body across the 3 server implementation but also for HTTP body where data is not in memory.

**Comment by lhgravendeel** [comment]
I found a work-around to still get the request body more than once, by adding this as the first `use()` statement:

```
// Cache body in request scope
use("*", "*", (req, res, chain) -> {
  final Mutant body = req.method().equalsIgnoreCase("post") ? req.body() : null;
  Request.Forwarding wrappedReq = new Request.Forwarding(req) {

    @Override
    public Mutant body() throws Exception {
      if(body != null) {
        return body;
      }
      return super.body();
    }

    @Override
    public <T> T body(Class<T> type) throws Exception {
      return body().to(type);
    }

  };
  chain.next(wrappedReq, resp);
});
```

You can now call `req.body(String.class)` in a before filter for e.g. content digest checks, and still access your request body as a custom bean using `@Body` annotated parameters.

All 3 server implementations seem to use https://github.com/jooby-project/jooby/blob/master/jooby/src/main/java/org/jooby/internal/BodyReferenceImpl.java, which seems like it can be called safely multiple times under all circumstances.
