### ISSUE TITLE
Jooby webpack assets not included in Jar

### ISSUE THREAD

**Issue by AZWN** [jooby-project/jooby#1328]
Hi,

When using `jooby-frontend` with webpack, I noticed the webpack bundle (`public/dist` directory) is not packaged in the generated jar file. Therefore, production applications can not serve client resources.

I created a [small reproduction](https://github.com/AZWN/JoobyWebpack).

When using `mvn jooby:run`, the files are served properly, but when doing `mvn package` and `java -jar target/joobywebpack-1.0.0.jar application.env=prod`, a 404 error is returned.

Is there any guideance on how to include these assets when bundling the application?

PS: I tried to figure out how [webpack-starter](https://github.com/jooby-project/webpack-starter) is doing it, but it gave me a 404 when doing `mvn jooby:run`, and a `java.lang.NoClassDefFoundError: org/jooby/frontend/Npm` after packaging.

**Comment by jknack** [comment]
Yea, if you created the jar with maven-shade-pluin, look [here](https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#AppendingTransformer)
