### ISSUE TITLE
How to use with Vaadin

### ISSUE THREAD

**Issue by nurmuhammad** [jooby-project/jooby#1332]
I want use jooby with vaadin. 
How can i implement

**Comment by jknack** [comment]
someone asked for Vaadin (probably in the gitter channel)... Think it is not possible,  but never try it.

if vaadin let you provide your own req/resp objects, should be possible

**Comment by nurmuhammad** [comment]
vaadin works on servlets, can jooby works with servlets

**Comment by jknack** [comment]
yes, there is a servlet integration module. https://jooby.org/doc/servers/#servlets but to be honest not sure how many people use it

**Comment by nurmuhammad** [comment]
is there any solution like ...
```
***
use("/servlet/", VaadinServlet.class)
***
```

**Comment by jknack** [comment]
not today, unfortunately

**Comment by nurmuhammad** [comment]
do you have any plans implement this on second version of jooby?

**Comment by jknack** [comment]
It is a good a clean solution (never think of it), but to be honest... don't think is possible for 1.x (unless someone send a PR).

I can try to add it to 2.x, but not in near future.
