### ISSUE TITLE
Hibernate Bean Validation does not respect modularity

### ISSUE THREAD

**Issue by alexanderfedinatnasa** [jooby-project/jooby#1333]
Hibernate Bean Validation does not respect modularity.
If I configure Bean Validation right in the App.java, then the validation happens.
If I do the same within the MVC Route initialization block, then it gets ignored.
`{`
`		parser(Parser.bean(true));`
`		use(new Hbv(`
`			MetaDataTestSite.class, `
`			ConPreRunRange.class,`
`			LatLonAltArray.class`
`		).doWith(cfg -> {`
`			cfg.failFast(true);`
`		}));`
`}`
Also, validator does not render any precise error messages about what exactly did not match the validation rules.

**Comment by jknack** [comment]
what do you mean with: `MVC Route initialization block `?

I need a complete example including the Mvc route.

Thanks
