### ISSUE TITLE
decorator not working when defined in route jooby 2.x 

### ISSUE THREAD

**Issue by humar82** [jooby-project/jooby#1344]
With the following code, the "decorator" is not being called when accessing /foo path

public class Foo extends Jooby {
  {
   decorator(next -> ctx -> {
     System.out.println("decorator");
     return next.apply(ctx);
   });
    get("/foo", Context::pathString);
  }
}

public class App extends Jooby {
  {
    use(new Foo());                     
  }
}

**Comment by jknack** [comment]
Don't follow, what is the issue? Please the describe the actual vs expected behavior.

Thanks

**Comment by humar82** [comment]
sorry for the typos on the comment

the above code is from the jooby documentation, and the decorator defined is not being called

**Comment by jknack** [comment]
fun bug, thanks for finding and reporting.
