### ISSUE TITLE
Use Java APT for MVC annotations to generate ASM bytecode

### ISSUE THREAD

**Issue by agentgt** [jooby-project/jooby#1346]
I noticed Jooby 2.0 uses reflection initially to generate the byte code for MVC handlers for handlers that are using annotations (aka JAXRS).

I assume subsequently after the byte code is generated reflection is no longer at play (ie the RouteAnalyzer finishes).

This initial reflection is problematic for a couple of reasons:

 * Startup performance speed
 * Initial memory usage is higher
 * However the biggest reasons is GraalVM compatibility. Most dynamic reflection isn't compatible with graalvm as well as I believe dynamic use of ASM.

The way to fix this which I have done and Micronaut does this as well is to pre-generate the MVC Handlers during the compile phase use the Java APT API.

Luckily half the the solution is already done which is the code generation via that MvcCompiler. However instead of modifying existing code you generate new synthetic classes and write out the bytecode during the compile phase. Then you use the ServiceLoader to load the generated MvcHandlers at runtime.

The hardest part is using the APT API (TypeElement, and TypeMirror) instead of reflection.

Let me know if you are interested and I might try to put some work into doing this.

**Comment by jknack** [comment]
I'm this was the initial intention, but then didn;t find time of looking at APT API, but also:

1. Not sure how to transparently bind/load generates routes at runtime. For example would love to still have: `mvc(new MyController())`, `mvc(MyController.class)` instead of `mvc(new GeneratedMyController())`

2. If we goes this path, feel we should write source code not bytecode (easy to understand

3. we can get rid of reflection... but I'm afraid we can't remove asm byte code analysis. We need this for script route so we are able to detect return types. Return type is used today to do transparent reactive integration, but also increase/improve response of some special types. Even more, we need to add analysis of route parameters like `path(String)/query(String)/etc`. This will be required for getting back the Swagger/OpenApi module.

Thoughts?

**Comment by jknack** [comment]
one More: what about APT and kotlin?

**Comment by agentgt** [comment]
> 1. Not sure how to transparently bind/load generates routes at runtime. For example would love to still have: mvc(new MyController()), mvc(MyController.class) instead of mvc(new GeneratedMyController())

Basically you have `Map<Class<?>,MvcHandlerDefinition>` that comes entirely from the ServiceLoader.

`MvcHandlerDefinition` implementations are generated by our custom APT. Once all the beans that have annotations are processed we generate a META-INF/services/org.jooby.MvcHandlerDefinition with all the implementations.

While the service loader technical does class loading and/or reflection GraalVM allows it.

> 2. If we goes this path, feel we should write source code not bytecode (easy to understand

Yes but bytecode makes compatibility easier with other languages. For example if you have to generate code for say Kotlin you would need a source code generator for Kotlin or any other new language you want to support (provided they have annotation processing).

Speaking of:

> one More: what about APT and kotlin?

Kotlin has kapt its version of annotation processing. I haven't looked into the differences but Dagger uses it IIRC so that would be a place to look for code examples as well as Micronaut. 

> 3. we can get rid of reflection... but I'm afraid we can't remove asm byte code analysis. We need this for script route so we are able to detect return types. Return type is used today to do transparent reactive integration, but also increase/improve response of some special types. Even more, we need to add analysis of route parameters like path(String)/query(String)/etc. This will be required for getting back the Swagger/OpenApi module.

I'm not familiar enough yet with jooby 2.0 script route but parameter analysis as well as Swagger can be pre-generated. Micronaut is a framework that already does this and it uses ASM for code generation.

Parameter analysis and modeling is the most difficult part. It is far more difficult than java.lang.reflect or even ASM but it is rather complete.

Micronaut already does lots of this type of introspection at compile time and thus is a good place to look. You might even be able to use Micronaut core API instead of writing your own since it generates the reflection like meta-data.

> Return type is used today to do transparent reactive integration,

Like looking for RxJava, Flow or Flux types? Not sure I follow that.

Anyway in the meantime I will look more into the Script route. 

Thank you for the time and quick response!

**Comment by jknack** [comment]
Started something and going to push an apt branch later today. It is WIP but mvc-method -> route handler conversion is working.
Started with source code, but then moved to byte code using ASM (as you suggested)

Another major thing that is used by script and mvc routes are: bean param:

```
{
   get("/", ctx -> {
     BeanParam bean = ctx.query(BeanParam.class);
  });
}
```

or mvc version:

```
mvc(@QueryParam BeanParam bean) {
   ...
}
```

This feature uses reflection too :S

**Comment by agentgt** [comment]
Yeah ASM is the way to go for multiple language compatibility and performance despite it making obscure.

With ASM you can construct calls directly and thus minimize the callstack that would otherwise be very difficult or not possible with Java code generation.

I am still learning Jooby's codebase but hopefully I can be of help soon.

**Comment by jknack** [comment]
What do you mean:

> With ASM you can construct calls directly and thus minimize the callstack that would otherwise be very difficult or not possible with Java code generation.

Do you have an example?

**Comment by agentgt** [comment]
I don't as my ASM ninja skills are fairly weak but I saw Micronaut doing it. It was nontrivial when I looked at it but I do know from generating Java code that I needed interfaces and abstract classes to make calling from the library easier as well as the generation of code itself.

For example in Java code generation if you need to call some method with a single parameter you might generate a wrapping lambda/anonymous class in your generated class. In ASM you could avoid this and just call the method directly. Basically with Java you have to massage the compiler.

I'll try to find the code in Micronaut later today that does things like this.

**Comment by agentgt** [comment]
Granted in Java 8 this has somewhat been mitigated as you can make static references to methods and thus the compiler in theory will do the right thing.

**Comment by jknack** [comment]
Here is: https://github.com/jooby-project/jooby/tree/2.x/modules/jooby-apt

work is done over the compilers, have two so far:
- one for mvc method -> Route.Handler
- one for mvc class -> Jooby module/extension

APT processor need work and for now uses a couple of package variables/method to simplify tests.
