### ISSUE TITLE
Script routes with variables in path don't generate doc in ApiTool

### ISSUE THREAD

**Issue by iris-hunkeler** [jooby-project/jooby#1347]
When a variable is used in the path of a script route, the ApiTool doesn't generate documentation for that route.
(Tested with Jooby 1.6.0 and 1.6.3)

```
    path("/foobar/bar") {

        /**
         * This docu will be visible in swagger
         */
        get("/") {
            true
        }
    }

    const val FOOBAR = "/foobar"
    path("$FOOBAR/foo") {

        /**
         * This docu will NOT be visible in swagger
         */
        get("/") {
            true
        }
    }
```

**Comment by marcelstoer** [comment]
This one is missing the ApiTool label.

**Comment by jknack** [comment]
all effort are now in 2.x where the new openapi 3 module is almost ready.
still I couldn't find a good way to support this in 2.x
