### ISSUE TITLE
Maven test configuration

### ISSUE THREAD

**Issue by paulovictorv** [jooby-project/jooby#135]
Hello, before anything else, congratulations! Jooby is a joy to work with.

I've searched through the docs and I couldn't find nothing on where the unit test classes should be placed for maven to pick them up. I think there's a missing configuration on the archetype (or it isn't implemented yet).

I've managed to configure maven manually after the archetype creation to find my unit test classes, but it would be very nice if the archetype provided that automatically.

Thanks!

**Comment by jknack** [comment]
hey! thank you! glad you like to work with Jooby!! I love to work with it!

will add ```src/test/java``` dir to the archetype but also I will release #136 (test support)

**Comment by paulovictorv** [comment]
That's great! I have some ideas that I think will be good improvements to jooby towards its 1.0 version, will be opening up issues for discussion.

**Comment by jknack** [comment]
done see #136
