### ISSUE TITLE
List request parameters are always handled as required by ApiTool

### ISSUE THREAD

**Issue by CDPrete** [jooby-project/jooby#1355]
Hi!
If I've a request parameter which is a list, the ApiTool generates a contract out of it where such parameter is required although in the real contract is optional.
This makes the contract validation fail.
The should be a `toOptional()` also for such parameters.

Example: `req.param("id").toList()`

Jooby version: 1.6.3

**Comment by jknack** [comment]
all effort are now in 2.x where the new openapi 3 module is almost ready.
