### ISSUE TITLE
Default response is not generated if additional responses are added

### ISSUE THREAD

**Issue by CDPrete** [jooby-project/jooby#1359]
Hi!
This is a follow-up of https://github.com/jooby-project/jooby/issues/1354

Seems like that if additional responses are manually added with the procedure specified in the linked issue, the default response (aka 200 or so) is not generated.
Is that expected?

**Comment by jknack** [comment]
believe it each ApiResponse carry hid own status code

**Comment by CDPrete** [comment]
But actually it should not be the case. I'm adding responses for the statuses 400, 500 and 503, so 2xx should not be overridden

**Comment by jknack** [comment]
I see, so probably a missing thing... going to look later

**Comment by CDPrete** [comment]
Thanks!

**Comment by jknack** [comment]
all effort are now in 2.x where the new openapi 3 module is almost ready.
