### ISSUE TITLE
Weird response status code mapping

### ISSUE THREAD

**Issue by CDPrete** [jooby-project/jooby#1360]
Hi!
I found out a weird behavior that happens depending on own the Response object is obtained.

If the Response object is obtained through the handler (classical res, rsp -> code), then according to ApiTool the route should return 204.

If the Response object is obtained by DI (`require(Response::class.java)`), then according to ApiTool the route should return 200.

IMO this is quite inconsistent.
Moreover, there is no way to specify which the status code for the normal response is and using the class `Result`/`s` actually produces a `Result` definition in the Swagger contract which it actually doesn't exist in the real contract.

**Comment by jknack** [comment]
all effort are now in 2.x where the new openapi 3 module is almost ready.
This has been fixed/improved it in 2.x
