### ISSUE TITLE
Response headers don't get generated

### ISSUE THREAD

**Issue by CDPrete** [jooby-project/jooby#1361]
Hello!
Still on Jooby 1.6.3, seems like that response headers are not visible on ApiTool, probably because they're not generated (they're actually missing from the generated `swagger.json`).

I'm defining the headers with `rsp.header("My-Header", 123)` where `rsp` is the `Response` object.

**Comment by jknack** [comment]
all effort are now in 2.x where the new openapi 3 module is almost ready.
