### ISSUE TITLE
2.X session how to/modules

### ISSUE THREAD

**Issue by stackoverflow** [jooby-project/jooby#1369]
I saw Jooby 1.x has docs about how to set up a session and many modules (like redis).
The docs for 2.x don't mention session at all and all the session modules are 1.x only on the repo.

How do I use redis for session management with Jooby 2? Should I make an `Extension`? Should I use 1.x?

**Comment by jknack** [comment]
Hi, so session is there in 2.x but there is no additional session storage mechanism like in 1.x.

You can implement your own [SessionStore](https://static.javadoc.io/io.jooby/jooby/2.0.5/io/jooby/SessionStore.html) for redis

**Comment by stackoverflow** [comment]
Nice, that's exactly what I need.
I think it would be nice to add this information to the docs.
