### ISSUE TITLE
Handlebars custom Helper

### ISSUE THREAD

**Issue by DreamTexX** [jooby-project/jooby#1370]
I want to register a custom helper in Handlebars:

```
{
    Handlebars handlebars = new Handlebars();
    handlebars.registerHelper("equals", (Helper<String>) (s, options) -> {
        ...
    });
    install(new HandlebarsModule(handlebars));

    get("/", ctx -> new ModelAndView("index.hbs", ...));
}
```
Now when I call my index page, i got a 404 Error, saying that the file `index.hbs.hbs` couldn't be found.

**Comment by jknack** [comment]
Yea, need to add a note on doc... but the HandlebarsModule does a bit of configuration/defaults values. Try this:

```
Handlebars handlebars = HandlebarsModule.create().build(getEnvironment());
```

The create+builder will apply the same sensible defaults

**Comment by DreamTexX** [comment]
This worked, thanks. You should write that in the docs!
