### ISSUE TITLE
Context.getRemoteAddress() not returning IP address 

### ISSUE THREAD

**Issue by paul-hammant** [jooby-project/jooby#1371]
Releases 2.0.4 & 2.0.5.

For some localhost scenarios: `ctx.getRemoteAddress()` returns "0:0:0:0:0:0:0:1%0" whereas is in 2.0.3 and before it returned  "0:0:0:0:0:0:0:1".  Handing the former string to InetAddresses.isInetAddress(..) causes an "no an IP address" exception.

**Comment by jknack** [comment]
Seems the `%N` is possible: https://superuser.com/questions/99746/why-is-there-a-percent-sign-in-the-ipv6-address

**Comment by paul-hammant** [comment]
My workaround was to remove the % and rightwards before handing the string to Guava's InetAddresses.isInetAddress(ip). I guess this is a bug in Guava really.

**Comment by paul-hammant** [comment]
So `getRemoteAddress()` can return IPv6 strings ending in `%0` that when passed to `InetAddresses.isInetAddress(..)` return false - is that intended?
