### ISSUE TITLE
More Value types supported for query parameters especially java.time

### ISSUE THREAD

**Issue by agentgt** [jooby-project/jooby#1377]
It would be nice if a some of the `java.time` classes were supported as Values. Most of the `java.time` objects have a static `parse(String s)` method instead of `valueOf`. So reflection using `parse` could work but I would much rather the ValueInjector have a mapping.

For example `LocalDate` would be a nice to have as that provides type safe dates in the format
of `2019-08-01`.

However it would be even nicer if you could plugin in custom `Value` types for query parameters however that would add quite a bit of complexity.

BTW I noticed looking at `Value` that ValueInjector is instantiated quite frequently when it appears to be thread safe and singleton like. Perhaps lazy load memoize in some other class to avoid putting new `ValueInjectors` on the heap for each request.

```
  @Nonnull default <T> T to(@Nonnull Type type) {
    return new ValueInjector().inject(this, type, Reified.rawType(type));
  }
```

**Comment by jknack** [comment]
>> It would be nice if a some of the java.time 
Which one else? (beside LocalDate)

ValueInject is a stateless class (no cache, nothing like in 1.x) so can easily be a single instance... but still not sure how bad is to create a new one per call (Garbage collector is good on short-live objects)

**Comment by agentgt** [comment]
> ValueInject is a stateless class (no cache, nothing like in 1.x) so can easily be a single instance... but still not sure how bad is to create a new one per call (Garbage collector is good on short-live objects)

Well yes and no ... the garbage collector is good for short live objects.... but you do want to be as high up on this list right? :)
https://www.techempower.com/benchmarks/#section=data-r18&hw=ph&test=fortune&l=zik0vz-f

There are a couple of reasons why Jooby isn't as high up. 

1. Jooby doesn't use async database access. 
1. Jooby is not garbage free.
1. Jooby is using reflection for some things (e.g. Jackson)

The Java libraries that are ahead of Jooby are doing the above and at scale putting objects on the heap does matter.

At extreme request handling on massive servers that have the bandwidth GC pressure does matter. Reflection usage does matter. I admit number 2 is a hard goal to achieve but with diligence it can be done if not at least improved.

Numbers 1 and 3 are just simple library changes. Particularly 3 as you can just use a compile time json library like `dsl-json`.

While micro performance like this perhaps doesn't matter much it is a huge marketing win for your project for every notch up you can go IMO.

But yeah I much rather have the the LocalDate support then rearchitecting for garbage free :)

I can't think of any other date formats at this time for my needs but I'm sure someone might want `Period` and or `Duration`.

**Comment by jknack** [comment]
> Jooby doesn't use async database access.

This right but at the same time is a liar too. Does everyone uses the pgclient for postgres? does everyone uses postgres only? Still, I send the pgclient test which will be ready in the next build (current do have a bug or something).

> Jooby is not garbage free.

Those tests uses script API,  `.value()/intValue()` etc...

> Jooby is using reflection for some things (e.g. Jackson)

I know and have a feeling that truly-complex applications do requires something like Jackson and not the manually created JSON string the top framework do. Also, if you check the top-1 Java JSON tests result there isn't a super huge difference with Jooby using Jackson.

This is my view of most of top level results:

- most of them are too much low level (but not all)
- most of them uses some JVM options (which I just discovered yesterday) and send a pull for Jooby doing the same trick https://github.com/TechEmpower/FrameworkBenchmarks/commit/cfea12fc9ddd07dcba7a54210b9fe65728d8751d
- most of them uses a static routing ("path".equals(req.path)) which isn't realistic

**Comment by agentgt** [comment]
Fair enough but I know from dealing with financial clients using jvm heap allocation does matter and the top ones are avoiding heap allocation particular for the plaintext test. Google rapidoid on HN and just like log4j2 they used all the simple tricks to avoid heap allocation to gain performance (ie thread locals with object pools).


Do I care that jooq is not at the tippity top... not really but I do want more people to use the project. 

Anyway it’s just bizarre to see it (new valueinjector) and I think you are asking for problems later (I suppose not if you only commit). I immediately assumed it had state in it (because if it didn’t it would be a static method).

I rather not get lazy about simple things to optimize particularly when doing it is also good coding.


Anyway I agree with you on benchmarks being lies :)

**Comment by agentgt** [comment]
I change my mind on adding an extension point for custom `Value` s.

I'm going to fork and add it if you don't mind.

The reason is we have a large custom annotation processing library for mapping lots of things to Java Beans (e.g. jdbc ResultSets to HttpServletRequests). I would like to plug that in for `Value` conversion. 

My plan is to use the `ServiceLocator` to load up a new extension point. Let's call it `ValueConverter` and `ValueConverterProviders` for now. The reason I need to use the `ServiceLocator` is because `Value` doesn't have access to the `Registry`... Or I don't think it does.

Thus the ValueInjector would now check something like `Map<Class<?>,ValueConverter>` and retrieve the custom ValueConverter to do the conversion of String -> Object.

I also would like to fix:

```
    try {
      Method valueOf = rawType.getMethod("valueOf", String.class);
      if (Modifier.isStatic(valueOf.getModifiers())) {
        String enumKey = value.iterator().next().value();
        try {
          return valueOf.invoke(null, enumKey);
        } catch (InvocationTargetException x) {
          Throwable cause = x.getCause();
          if (cause instanceof IllegalArgumentException) {
            // fallback to upper case
            return valueOf.invoke(null, enumKey.toUpperCase());
          } else {
            throw SneakyThrows.propagate(cause);
          }
        }
      }
    } catch (NoSuchMethodException x) {
      // Ignored
    }
```

Now I know your probably quite tired of me bringing up performance but if a Value isn't a native Value then this check happens on every request. The `valueOf` method check should be cached as well as the method itself since method retrieval IIRC comes at a cost before `resolve` is called. 

**I also think enums should not use the reflection from above but the `Enums.valueOf` which is far faster!** 

I bolded that because its a trivial change and I think you can put that in right away (or if you like I can put in a PR).

Let me know what you think of ValueConverter extension. I'll go ahead and fork and put it in and send a PR unless you think it isn't worth it or too far out of scope.

**Comment by jknack** [comment]
All your comments make sense.

ServiceLocator+ValueConverter make sense too and more less reduce reflection. 

Didn't want to add cached for java.lang.Method, the class itself already have one.

There is no direct reference between Value and almost any other Jooby concept (Context/ServiceRegistry). I did it this way to simplify usage in general (including testing). In 1.x there was no clear limit between one component and the other, causing lot of issues, hard testing, etc.

Send a pull request and we can check and discuss.

Thanks

**Comment by agentgt** [comment]
I have sort of stalled on doing the work for now particularly because I saw you did work on making `ValueInjector` is static which is good.

I think the general problem with `Value` is that it is just a little too generic and does not have any context (hence why the ServiceLocator is needed). I also mean quite literally it doesn't have the request `Context` let alone the running router aka `Jooby`.

Thus `Value` is stuck to just transforming strings, list of strings, and hash of strings. In most cases where MVC methods are being used its a single string coming from the query/path parameters.

Coming from Spring MVC and JAXRS this is a little problematic as often the object to be provided as an argument to the REST/MVC method might need more than just a single request parameter.

For example you might want a logged in User object loaded for each request passed in as an argument or some other object that needs cookie, header, and query parameters to fully resolve. 

In Spring MVC this can be done with Argument Resolvers.  

In Jooby for now you are stuck using decorators and binding the object to the context or resolving from the context directly in the MVC method (ie a Context parameter).

So while I can add the feature for more `Value`(s) it will only get us half way as we still have lots objects that need more than just simple string transformation.

I think the proper way to do this is for there to be a ValueService or ValueConverter that is part of a Router and thus the ServiceLoader need is removed and a lot more future flexibility gained albeit the context will have to be passed around.... consequently a change like this would be a pretty large API breaking undertaking.

Still I want to investigate it before I go off and finish the static Value ServiceLoader work.

**Comment by jknack** [comment]
Started to work on websocket API and found need to do some changes in Value API. I do have something working with ServiceLoader and removed all the static checks like:

```
if (type == Something) {
   convertToSomething...
}
```

> Coming from Spring MVC and JAXRS this is a little problematic as often the object to be provided as an argument to the REST/MVC method might need more than just a single request parameter.

Not sure what do you mean here. Jooby supports complex/bean object as arguments too, which basically are a composition of single values


```
class Search {
   String q;

    int offset;
  
    int size;
}
```

Script:
```
  Search search = ctx.query(Search.class);
   ///
  Search search = ctx.form(Search.class);
```

Mvc:
```
public .. query(@QueryParam Search search) {
  ...
}

public .. query(@FormParam Search search) {
  ...
}

```

Value API it is OK as it is. Jooby 1.x gave it context (along with others thing) and got with super complex API. Don't want that for 2.x

**Comment by agentgt** [comment]
Yes I know about the following:

> Mvc:
> ```
> public .. query(@QueryParam Search search) {
>   ...
> }
> 
> public .. query(@FormParam Search search) {
>   ...
> }
> ```

However for the logged in user or session object case there isn't:

```java
public .. query(@ContextParam LoggedInUser user) {
}
```

You could maybe use cookie param 
```java
// this might work if you have a cookie parameter set that you can then load
public .. query(@CookieParam LoggedInUser user) {
}
```

But a from an extension point is that the ValueConverter doesn't know if the value is coming from a cookie  `@CookieParam` or a `@FormParam` or `@QueryParam`. Second a value converter ... in this case let's call it argument resolver might need to know a header and cookie to properly resolve. This is where the idea of @ContextParam using context attributes come from. Otherwise I'm not sure how you are supposed to handle security in Jooby? Thread Locals?

Also for the case of the `@QueryParam` I can't recall if there is something to bind the whole query string (and not just one parameter) to an object in the MVC api? 

Finally the issue I had given the above was trying to come up with a proper API.

A naive SPI implementation would do something like:

```java
public interface ValueConverter {
  public boolean supportsType(Class<?> c);
  public Object convert(Value v, Class<?> c);
}
```

The problem with the above is if a ValueConverter calls some `Value.into` while in `convert`.

Thus I recommend `Value` extend a subset let's call it `ValueContainer` and pass that subset to the SPI.

The subset I came up with is the following:
```java
public interface ValueContainer {
  
  /**
   * Get a value at the given position.
   *
   * @param index Position.
   * @return A value at the given position.
   */
  @Nonnull ValueContainer get(@Nonnull int index);

  /**
   * Get a value that matches the given name.
   *
   * @param name Field name.
   * @return Field value.
   */
  @Nonnull ValueContainer get(@Nonnull String name);
  
  @Nonnull String value();
  
  @Nullable String valueOrNull();
  
  /**
   * True for missing values.
   *
   * @return True for missing values.
   */
  boolean isMissing();

  /**
   * The number of values this one has. For single values size is <code>0</code>.
   *
   * @return Number of values. Mainly for array and hash values.
   */
  int size();
  
  /**
   * True if this value is an array/sequence (not single or hash).
   *
   * @return True if this value is an array/sequence.
   */
  boolean isArray();

  /**
   * True if this is a single value (not a hash or array).
   *
   * @return True if this is a single value (not a hash or array).
   */
  boolean isSingle();

  /**
   * True if this is a hash/object value (not single or array).
   *
   * @return True if this is a hash/object value (not single or array).
   */
  boolean isObject();

}
```

```java
public interface Value extends Iterable<Value>, ValueContainer
````
Let me know how far you plan on working on the ServiceLoader portion. I'll go ahead this weekend when I have time to possible push something.

**Comment by jknack** [comment]
> Otherwise I'm not sure how you are supposed to handle security in Jooby? Thread Locals?

In 1.x there was a `@Local` annotation for injecting things from `ctx.attributes`. We need to add that back in 2.x as well as a `@SessionParam`

> Also for the case of the @QueryParam I can't recall if there is something to bind the whole query string (and not just one parameter) to an object in the MVC api?

Yes, the `@QueryParam Search search` example does that, bind all matching attributes from queryString

> A naive SPI implementation would do something like:

Makes perfect sense, I have something similar, except that value is an String type:

```java
public interface ValueConverter {
  public boolean supportsType(Class<?> c);
  public Object convert(Class<?> c, String value);
}
```

This new value things will be just for simple/single values (or collection of them), then:

- Complex query/form/path objects are composed from single values (this is implemented today)
- Context/Session attributes are provided via middleware/decorator and save as context or session attributes (there is no parsing/conversion process).
- We need to `@ContextParam` and `@SessionParam` for MVC, but all it does is a lookup of existing attribute in the correct context: attributes or session (still no parsing/conversion)

`@ContextParam` and `@SessionParam` are a problem to solve in MVC routes, but they have nothing to do with value converter.

Going to push the Value changes tomorrow.

**Comment by agentgt** [comment]
> @ContextParam and @SessionParam are a problem to solve in MVC routes, but they have nothing to do with value converter.

Agree. They are orthogonal in implementation. It was more of an explanation of why I had stalled in Value work as I was investigating our own use cases. One being objects coming from session like and the other being conversion from request parameters/headers. 

I’ll proceed forth with my value work independently and do a PR to figure what combination of things works best.

I’m inclined to have the value converter do more than simple string (ie hash) but I see your use case to keep it simple.

**Comment by agentgt** [comment]
See PR #1386 @jknack 

Let me know what you think. I wrote it rather hastily but it appears to work. Some consolidation and refactoring still needs to happen (ie move newInstance reflection as perhaps its own ValueConverter).

**Comment by jknack** [comment]
we added some java.time using the ISO_LOCAL_DATE pattern. Going to release ValueConverter and BeanConverter in 2.2.0

still there is no documentation on public web site
