### ISSUE TITLE
MVC void and context argument causes exception

### ISSUE THREAD

**Issue by agentgt** [jooby-project/jooby#1378]
If I define a MVC method like:

```
	@GET("/threads")
	public void threads(
			Context context)
			throws IOException {
		ThreadDump threadDump = new ThreadDump(ManagementFactory.getThreadMXBean());
		try (OutputStream o = context.responseStream()) {
			threadDump.dump(o);
		}
		//return context; -- returning context fixes it
	}
```

The request gets handled but an exception is thrown (varies by server type) because the response is already started so it can't set the status code.

However if I return the `Context` instead of `void` all is fine. I did the `void` because lots of other frameworks (e.g. Spring MVC) expect void if you are handling the response. Even if I set the status code prior to opening the `context.responseStream` (code not show for that) I get the error.

So I'm not sure if this is by design and/or a limitation as I believe doing nothing will do a `204` (a previous bug #168).

At the minimum it probably should be documented?

**Comment by jknack** [comment]
It is documented here: https://jooby.io/#responses-streaming-chunked. Agreed it needs more doc and examples.

Still, feel what you did is something obvious/natural and should be supported too.

Let's keep this as bug to be fixed in next release

**Comment by agentgt** [comment]
Well what makes sort of bad is that it doesn't fail fast. It will actually serve the request and the only error you get happens in the logs. I have to check to see what status code gets served but the response does contain the contents that are written.

I guess the question is how do you know how to dispatch on the request when its `void`? I assume if you do implement something then all `void` returns would automatically be blocking?

**Comment by jknack** [comment]
It is a `204`.

Running the app in `DEFAULT` or `WORKER` mode does dispatch. Running the app in `EVENT_LOOP` mode doesn't.

Just change the return type to `Context` for now
