### ISSUE TITLE
2.0.6 Getting started app would be even better if 

### ISSUE THREAD

**Issue by paul-hammant** [jooby-project/jooby#1381]
1. There was a second inegration test that showed restAssured:

```
  @Test
  public void rootEndpointShouldRespondWithWelcome(int serverPort) {

    when().
            get("http://localhost:" + serverPort).
    then().
            assertThat().
            contentType("text/plain").
            body(equalTo("Welcome to Jooby!")).
            statusCode(200);
  }
```

2. welcome(..) method name was more "should" centric

3. `serverPort` as a method param had a link back to the online documentation as to what @JoobyTest automatically sets up for Junit5 tests. As a comment, I mean, for noobs

**Comment by jknack** [comment]
No restassured for generated code (that is a user decision). I add it 2 and 3
