### ISSUE TITLE
Docs: typos

### ISSUE THREAD

**Issue by webleaf** [jooby-project/jooby#1385]
I can't understand:
1. Why `/2` => `5` here? https://jooby.io/#router-pipeline
2. But `/2` => `4` here? https://jooby.io/#router-pipeline-order
3. And why `/4` => `9` and `/1` => `2` here? https://jooby.io/#router-pipeline-scoped-decorator

**Comment by jknack** [comment]
seems there is a typo on `1.` should be `4`, so `1.` and `2.` are the same

Now `.3` looks OK:

```
// Increment +1
  decorator(next -> ctx -> {
    Number n = (Number) next.apply(ctx);
    return 1 + n.intValue();
  });

  route(() -> {                          
    // Multiply by 2
    decorator(next -> ctx -> {
      Number n = (Number) next.apply(ctx);
      return 2 * n.intValue();
    });

    get("/4", ctx -> 4);                 
  });

  get("/1", ctx -> 1);                   
```

The `route(() ..> {})` introduces a new scope so the `2*` is only for `/4` => 4 => 4 *2 => 8 => 8 + 1=> 9


scope is like a block statement in Java `{...}` what you defined there isn't visible outside it

Try it and send a pull request fixing the doc examples

**Comment by webleaf** [comment]
@jknack Thank you for quick answer. Now it make more sense.
I'm just reading docs now. Will not try it in near future.

**Comment by webleaf** [comment]
Seems like there are also typo (extra bracket) here for Kotlin https://jooby.io/#router-pipeline-scoped-decorator:
```kotlin
{
  // Increment +1
  decorator {
    val n = next.apply(ctx) as Int
    return 1 + n
  }

  route {                                
    // Multiply by 2
    decorator {
      val n = next.apply(ctx) as Int
      1 + n
    }

    get("/4") { 4 }               
  }); // <-------------------------------------- extra bracket

  get("/3") { 3 }                 
}
```

**Comment by webleaf** [comment]
typo for Kotlin in https://jooby.io/#router-composing-routes
```kotlin
class Bar: Kooby({ // <-------- should be:  class App: Kooby
  use(Foo())                       

  use(Bar())                       

  get("/app") { ctx.pathString() } 
})
```

**Comment by webleaf** [comment]
typo in https://jooby.io/#context-value-api-default-and-optional-value

`Requesting an java.uti.Optional object` should be `Requesting an java.util.Optional object`

**Comment by webleaf** [comment]
typos in https://jooby.io/#context-request-body-message-decoder

```kotlin
decoder(MediaType.json, { ctx, type ->    

    val body = ctx.body().bytes()          

    lib.fromJson(body, type)               
  } // <---------------------------- missing parenthesis
```

Also `(3) Ready the body as byte[]` should be ``(3) Read the body as byte[]``

**Comment by webleaf** [comment]
typo in https://jooby.io/#static-files-options
`Las-Modified` should be `Last-Modified`

**Comment by webleaf** [comment]
typos in examples for both Java and Kotlin
in https://jooby.io/#templates
and in https://jooby.io/#templates-template-engine

`ModelAndModel` should be `ModelAndView`
