### ISSUE TITLE
Minify results of Rocker template engine

### ISSUE THREAD

**Issue by DragonBanana** [jooby-project/jooby#1388]
Hi, I just started to use Jooby, and I was wondering if there is a way to minify Rocker rendered pages.

**Comment by jknack** [comment]
minify how?

You can enable [gzip](https://static.javadoc.io/io.jooby/jooby/2.1.0/io/jooby/ServerOptions.html#setGzip-boolean-)

**Comment by DragonBanana** [comment]
I resolved by using the Template Engine in a better way. It was not an issue related to Jooby.
