### ISSUE TITLE
Redirect static assets requests to a CDN

### ISSUE THREAD

**Issue by paulovictorv** [jooby-project/jooby#139]
It's a common practice to store static assets such as minified assets and compressed images to a CDN. But it's a pain to change all your local references in your HTML's to point to your CDN. It would be nice if there was a built-in way in jooby to redirect these requests to a CDN based on your deployment env.

So if you're running locally e.g using jooby:run maven goal, jooby would fetch your static assets from the public directory, but if you started your app using the Main class (not using the maven goal) it would redirect the static assets requests to a CDN endpoint.

What are your thoughts on that?

**Comment by jknack** [comment]
totally sense!

now, how do you think it should be implemented? and use it?

**Comment by paulovictorv** [comment]
First off, do Jooby supports multiple env configurations? Such as dev, prod?

If so, we could have a configuration parameter that provided the root CDN url to redirect to, and the asset router would check 1) what env the app is running on and 2) decide whether to redirect to a CDN or fetch locally.

If not, we could implement a v1 of this feature chaining a call on the ``asset()`` method.

    assets("/assets/**").redirectTo(config -> { .. });

I've seen it done on Play Framework described in this [post](http://www.jamesward.com/2012/08/08/edge-caching-with-play2-heroku-cloudfront). It's pretty much what we're trying to accomplish here, adding the possibility to switch environments.

The actual "upload to a CDN" may be left to the asset compiler (grunt, gulp and so on).

**Comment by jknack** [comment]
It does:

```java
{

   on("dev", () -> {
     assets("/assets/**");
   });

   on("prod", () -> {
     get("/assets/**", req -> Results.redirect("http://cdn" + req.path()));
   });
}

```

previous example works, but I do like the the way wrote too:

```java
assets("/assets/**").redirectTo(config -> { .. });
```

will add something similar to that in the next release.

another option is to add a property and use it from your views:

```html
<script src="{{assets}}/js/index.js"></script>
```

application.conf
```
assets="/assets"
```

application.prod.conf
```
assets="http://my.cdn.com"
```

It is better bc there is NO redirect, but we have to make sure to prefix every asset with a property: ```{{asset}}```

**Comment by paulovictorv** [comment]
I believe that using the syntax that you use as of now (``assets("/assets/**")``), and let the framework work out where to redirect to on it's own, without the user having to write code works better, I think.

I'm not a huge fan of server-generated views, so I would not use the second option if it was available. But hey, that's only my opinion :)

**Comment by jknack** [comment]
hehe, yea. next version will have a super powered version of ```asset``` with cdn support! :)
