### ISSUE TITLE
jooby-apt: MVC annotations with intellij partial build

### ISSUE THREAD

**Issue by ajcamilo** [jooby-project/jooby#1390]
Intellij partially builds, so not all classes are "processed". Only when doing a full rebuild.

The problem is the `META-INF/services/io.jooby.MvcFactory` file is overwritten with only the "compiled" classes and not all MVC classes.

(Jooby 2.x)

**Comment by jknack** [comment]
if that is the case... then we are lost. how can we fix this?

**Comment by jerouris** [comment]
@ajcamilo Have you tried doing an initial full compilation from inside the IDE? IDEA keeps a kind of an index which is properly updated only when you do the compilation from inside it.

**Comment by ajcamilo** [comment]
@jerouris yes, with the full compilation works, but when you change some of the MVC classes, the problem reappears (because the annotation processor only "sees" that class).

@jknack the MvcFactory is really needed? Can't you load the class `mvcClass + "API$Factory" in code? The services framework is really needed for "discovery", but this case you don't need to discover, because in the Jooby App, there will be an `mvc(MvcClass.class)` call.
