### ISSUE TITLE
Unable to use SessionBuilder with jooby-hbm

### ISSUE THREAD

**Issue by imeszaros** [jooby-project/jooby#1392]
In our project we need to wire-in a session scoped hibernate interceptor. As far as i know this is currently not possible with `jooby-hbm`, since it must be done using `SessionFactory.withOptions().<your config calls here like .interceptor(...) >.openSession()`, and jooby-hbm's `SessionProvider` and `UnitOfWorkProvider` directly calls to `SessionFactory.openSession()`.

I have a workaround as described here: https://groups.google.com/forum/#!topic/jooby-project/qG6O4zKBHGI

Can I make a PR based on it?

**Comment by jknack** [comment]
Yes, go for it. (sorry, for not looking at the group)

**Comment by imeszaros** [comment]
Okay! (no problem!)

**Comment by jknack** [comment]
Released in 1.6.5

**Comment by imeszaros** [comment]
Thanks!
