### ISSUE TITLE
JRebel support

### ISSUE THREAD

**Issue by agentgt** [jooby-project/jooby#1396]
My company uses JRebel extensively and vastly prefer it over other hot reloading solutions (its way more reliable when dealing with projects that use other frameworks in combination than say jboss modules).

Sadly JRebel does not have some sort of discovery of plugins. They either support your framework or they don't.

Thus we are looking into making a custom plugin: https://manuals.zeroturnaround.com/jrebel/advanced/custom.html

The annoying part of this that you have to do a lot more setup as a user however in theory if the plugin works well enough JRebel might include it by default but I have to go check with them.

Currently JRebel I think works for the scripted routes but it will not work for the MVC because I think there is some routing cache that isn't being cleared.

Thus @jknack  I may need a little help to figure out which cache I need to blow away on class change from there I can probably piece everything else together.

**Comment by jknack** [comment]
I'm not planning to do work on JRebel support. I believe existing jooby:run on top of jboss-modules take cares of almost all possible reloading issues (due that it start fresh), it is reliable (no need to find what an external library does and right code to fit it). Also, a good number of users don't even use jooby:run.

There is no cache to blow up in MVC, it is all annotation processing and byte code generation (your request ;)

Still, you are able to work on it, happy to add to Jooby.

**Comment by agentgt** [comment]
The problem with jboss-modules is that its basically a restart and thus not even really hot reloading (that is it will kick of the reconnection of the database pool as well as flyway revalidation).

But I agree its out of scope and I did find out it was byte code generation that was causing :) . For some reason I thought jrebel would not have a problem with that.

Ironically the APT support almost make it work (I guess jrebel sees generated classes)! 

I'll eventually figure it out but I wanted to make sure there wasn't any static class caching I didn't know about.

**Comment by jknack** [comment]
No caching yea.
