### ISSUE TITLE
Intermittent "Bind address already in use" running Jooby's own build

### ISSUE THREAD

**Issue by paul-hammant** [jooby-project/jooby#1398]
OpenJDK 11.0.4 on Linux Mint 19 (4.15.0-54-generic)

```
[ERROR] Errors: 
[ERROR]   FeaturedTest.errorHandler:935 » Bind Address already in use: 9999
[ERROR]   HttpsTest.https:17->lambda$https$3:18 » SSLHandshake PKIX path building failed...
[INFO] 
[ERROR] Tests run: 103, Failures: 0, Errors: 2, Skipped: 0
```

Ran it again straight after, and that didn't happen.

Nothing else was running on the machine. I've seen this with Jetty over the years - stop() then start() can be too fast for Jetty.

**Comment by jknack** [comment]
Should be better now

**Comment by paul-hammant** [comment]
This was the fix - https://github.com/jooby-project/jooby/commit/601fe28e7a01ac871c9f6b2f3ae1f27f7f457e48 ?

**Comment by jknack** [comment]
might help, yea. but to be honest I'm not sure.

I added a graceful shutdown to undertow, reported a couple of issue on jetty and now upgrade to latest.

I fired like 30 builds using docker (was a linux issue) and won't be able to reproduce it (before it was failing every 3/5 builds)
