### ISSUE TITLE
Questions: Coroutines support

### ISSUE THREAD

**Issue by webleaf** [jooby-project/jooby#1401]
1. Why handlers (`get()`, `post()`, `ws()` etc.) are not implemented as coroutine builders themselves?
I think, it so strange for Kotlin developers to wrap handlers with coroutine builder `coroutine`.
2. There are own thread pool and dispatching mechanism for coroutines in Kotlin . Could it be used some how? (instead of EVENT_LOOP / WORKER modes)

**Comment by jknack** [comment]
1. don't follow, can you explain me and add an example of what do you mean? Or if you ask about the `coroutine {  }` thing is mostly for:
 - keep the kotlin version similar to java version (for people that don't use coroutines)
 - an coroutine version of `get` produces compiler error issue with non-coroutine version

2. I need an example (I'm not a coroutine user), but in theory you could provide your own worker thread pool

```
{
 worker = my coroutine thread pool
 executionMode = WORKER
}
```

and coroutines should use that one
