### ISSUE TITLE
jooby-2.2.x - after handle not working with exceptions

### ISSUE THREAD

**Issue by ajcamilo** [jooby-project/jooby#1405]
The `after` handles are not being executed when other route handles throw an exception.

I'm using jooby-2.2.1.

Example:

```
app.after(ctx -> {
  log.trace("after was called");
});
app.get("/", ctx -> {
  throw new IllegalStateException("some error");
});
```

**Comment by jknack** [comment]
in 1.x we did have after and complete they both were similar except that after was for success while complete for success or error.

what do you think? should we add back complete? or just make after to take an exception argument?

would like to modify after

**Comment by ajcamilo** [comment]
my only use case is the `complete` one. 

I see no problem with adding the exception argument to `after`. Having only one is less confusing.
