### ISSUE TITLE
Delayed flyway execution

### ISSUE THREAD

**Issue by AZWN** [jooby-project/jooby#1406]
Hi,

I am using flyway to correct some requery issues (not supporting [indices on mysql](https://github.com/requery/requery/issues/610)  and table changes), but I am running into the problem that Flyway runs _before_ Requery.

I was wondering if [this code](https://github.com/jooby-project/jooby/blob/1bacab24c2456711468fd767f8cd8190959c0991/modules/jooby-flyway/src/main/java/io/jooby/flyway/FlywayModule.java#L97-L99) could therefore be wrapped in an `onStarted` handler? And (since I am not ready to upgrade to 2.0), could it be backported to 1.6 as well?

**Comment by jknack** [comment]
flyway in latest 1.6.x works like in 2.x, just make sure you install flyway before requery:

https://github.com/jooby-project/jooby/blob/1.x/modules/jooby-flyway/src/main/java/org/jooby/flyway/Flywaydb.java#L382

**Comment by AZWN** [comment]
I'm not sure if that solves the issue, since the actual problem (flyway running _before_ requery) is not solved by installing flyway earlier.

**Comment by jknack** [comment]
probably something else is going on, bc flyway in 1.x run at creation/initialization time in the order you defined:

```
use(flyway) -> run here
use(requery) -> schema is ready due flyway is before requery
```

**Comment by AZWN** [comment]
Yeah, buy the point is that the flyway scripts need the schemes generated by requery (it is only adding indexes to existing tables). That means requery should run before flyway, and not the other way around as your example is doing.Op 31 okt. 2019 2:20 p.m. schreef Edgar Espina <notifications@github.com>:probably something else is going on, bc flyway in 1.x run at creation/initialization time in the order you defined:
use(flyway) -> run here
use(requery) -> schema is ready due flyway is before requery

**Comment by jknack** [comment]
that is not how flyway is supposed to be use it. Flyway must own the db schema
