### ISSUE TITLE
Query parameters with commas resolving to ArrayValues

### ISSUE THREAD

**Issue by agentgt** [jooby-project/jooby#1407]
The QueryString parser will try to turn string values that have commas into ArrayValues.

```java
	@Test
	public void testCommas()
			throws Exception {
		QueryString qs = QueryString.create("x=a");
		assertEquals("a", qs.get("x").value());
		qs = QueryString.create("x=a,b");
		assertEquals("a,b", qs.get("x").value()); //failure here
	}
```

Fails with 

```
io.jooby.TypeMismatchException: Cannot convert value: 'x', to: 'java.lang.String'
	at io.jooby.internal.ArrayValue.value(ArrayValue.java:68)
	at 
```

I'm feel pretty strong that that this attempted autodetection oh you want an array behavior is extremely wrong. 

Like what if a label or something has a comma in it?

Not to mention I have never seen this in any other URI query parsing library or Web framework.

**Comment by agentgt** [comment]
In fact this is such a bad bug that I'm going to have to call the raw query string and do the parsing myself in a dozen or so (probably more) endpoints.

Should I submit a PR?

**Comment by jknack** [comment]
This is wrong, shouldn't work like that. Can you fix it? Then the value API works 'ala javascript' more or less, so 'x=a&x=b'  give us:

q.get("x") .value() => a
q get("x").get(0) => a
q.get("x").toList() => [a,b]

**Comment by agentgt** [comment]
Yes multi-parameters does work.

Apparently you already fixed it? https://github.com/jooby-project/jooby/commit/168241be4af400fd3a739342a0e1d70d45d9c9c9#diff-18d5587a133011cbdfdae7371558f2e6

The particularly microservice hasn't updated its jooby to the latest yet

**Comment by agentgt** [comment]
My mistake. It has been fixed. The service that had issues wasn't updated to the latest jooby.
