### ISSUE TITLE
Feature request: Mock Context for 2.2

### ISSUE THREAD

**Issue by agentgt** [jooby-project/jooby#1408]
Now that Context is a needed collaborator for most things it might be nice to have a module like `jooby-test`.

`jooby-test` would be akin to say `spring-test` and have a traditional POJO Context to mock a Context. Perhaps named `MockContext`.

I saw the private internal test `ValueHelperTest`. While Mockito is always an option I think its always nice to have pre-made mock objects supported by the framework that do not require Mocking library.

I need this myself as I use `QueryString` quite frequently but that now requires a `Context`.

I can look into making a first stab / PR if you (@jknack) are interested? 

(PS apologies about the previous bug of CSV params. I should have checked the Jooby version.)

**Comment by jknack** [comment]
Module already exists look at unit tests doc. I'm  sure we need more work, but is there already.

Or look at the UnitTest.java or tests in the jooby-apt module.

(no worries about the csv bug, wasn't sure if I reverted or not... I can't look at code right now :)

**Comment by agentgt** [comment]
Damn this is my fault again. I just recent upgraded eclipse and I’m apparently having strange issues with my maven / eclipse m2e cache not pulling the most updated code so I missed this (jooby test).
