### ISSUE TITLE
Ebean support in jooby-2.x

### ISSUE THREAD

**Issue by thomasguo** [jooby-project/jooby#1410]
Hi guys,

Just wanna know if there is any plan to support ebean ORM in jooby-2.x in the near future?

**Comment by jknack** [comment]
no plans to add it in near future. Pull requests are welcome

**Comment by fwgreen** [comment]
@jknack As an alternative to Ebean, is there a way to use Hibernate's [Panache](https://quarkus.io/guides/hibernate-orm-panache) add-on from Red Hat's Quarkus project?

**Comment by jknack** [comment]
Should be no problem (guess) in adding Panache.

I will look again at Ebean... but find it a bit harder to add and maintain. There were a confusion about what version is the right now between core and multiple modules... and then some issue with their bytecode enhancer and jooby:run :S

**Comment by jknack** [comment]
did you using ebean in 1.x? what is your experience?

**Comment by fwgreen** [comment]
I've never used Jooby 1.x.  I was using Ebean with SparkJava and later I moved to Javalin.  While Ebean is my favorite ORM, I can see where your coming from:  I wouldn't use it in a Java EE or Spring project.  Panache would be an acceptable substitute.

**Comment by jknack** [comment]
I couldn't figure it out how to configure Panache outside quarkus :S

**Comment by jknack** [comment]
Ebean module was added it. Going to be in next release
