### ISSUE TITLE
Add a Jongo module

### ISSUE THREAD

**Issue by paulovictorv** [jooby-project/jooby#144]
[Jongo](http://jongo.org/) is a simple ORM framework that I've been having a lot of success using in a lot of projects. However setting up singletons for using it certainly is a pain.

Currently in Jooby I would have to require Mongodb mondule, get the client, get the DB and then instantiate Jongo using this.

If Jooby had a module for it, it would be great.

PS: if you can provide instructions on creating modules for jooby, I can try and implement this one.

**Comment by jknack** [comment]
there some guidelines here: http://jooby.org/doc/#modules but no real example on how to build your own.

It is more or less Guice. Did you work with Guice?

A jongo module should be simple and straightforward to implement. So, yes go ahead and implement it, please!

**Comment by jknack** [comment]
Hi @paulovictorv,

Any progress on this?

Thanks

**Comment by paulovictorv** [comment]
Hello, still haven't got the time to stop and implement this

Regarding this, what should be the approach to create this module? Should I fork this repo and submit a pull request with a new directory or should I create a new repo, with only this new module?

If it's the second option, how to proceed on deploying the module to maven central?

Thanks

**Comment by jknack** [comment]
fork and send a pull request. it should be simple to implement and you need to go with source+tests+doc, you think is best for me to do it :)

cool! is it public? or private? If public we can share it with the community

**Comment by paulovictorv** [comment]
OK, no problem!

Sorry, it's private :( But I will share my overall experience as an user

Will open more issues when I have a little more free time to contribute

**Comment by jknack** [comment]
np, btw 0.7.0 is out with: http://jooby.org/doc/#using-a-cdn

**Comment by paulovictorv** [comment]
awesome!

2015-06-30 15:58 GMT-03:00 Edgar Espina <notifications@github.com>:

> np, btw 0.7.0 is out with: http://jooby.org/doc/#using-a-cdn
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jooby-project/jooby/issues/144#issuecomment-117303079>
> .
>



-- 
Paulo Victor Vieira de Melo
Graduando em Ciência da Computação
Lattes : http://lattes.cnpq.br/7418993216312941
Currículo StackOverflow Carrers:
http://careers.stackoverflow.com/paulovictorv
UFAL - IC

**Comment by jknack** [comment]
do you have a name for the module?

I usually pick the name of the library, but here it can't be ```Jongo``` bc there is class with that name already. So far I have three possible names:

```java
use(new Monshell());
```
or
```java
use(new Joongo());
```
or
```java
use(new Jongoby());
```

**Comment by paulovictorv** [comment]
Jongoby!

2015-07-08 13:22 GMT-03:00 Edgar Espina <notifications@github.com>:

> do you have a name for the module?
>
> I usually pick the name of the library, but here it can't be Jongo bc
> there is class with that name already. So far I have three possible names:
>
> use(new Monshell());
>
> or
>
> use(new Joongo());
>
> or
>
> use(new Jongoby());
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jooby-project/jooby/issues/144#issuecomment-119647670>
> .
>



-- 
Paulo Victor Vieira de Melo
Graduando em Ciência da Computação
Lattes : http://lattes.cnpq.br/7418993216312941
Currículo StackOverflow Carrers:
http://careers.stackoverflow.com/paulovictorv
UFAL - IC
