### ISSUE TITLE
Feature request: SessionRequest Decorator

### ISSUE THREAD

**Issue by Blquinn** [jooby-project/jooby#1443]
I'm using the hibernate module currently and was noticing that there is a TransactionRequest Decorator which wraps each request in a transaction. However for my use case, I really just want each request to have access to the same session, not necessarily a transaction because I prefer to have more control over my transactions. Therefore I wrote a SessionRequest decorator which does just that. I modeled it after the Tx one that lives in jooby today.

```kotlin
class SessionRequest(
    private val key: ServiceKey<SessionFactory> = ServiceKey.key(SessionFactory::class.java)
): Decorator {
    override fun apply(next: Route.Handler): Route.Handler {
        return Route.Handler { ctx: Context ->
            val sessionFactory = ctx.require(key)

            var session: Session? = null

            try {
                session = sessionFactory.openSession()
                ManagedSessionContext.bind(session)
                next.apply(ctx)
            } finally {
                session?.close()
            }
        }
    }
}
```

I was wondering if there are any inherent problems with this design. If not, is there any desire to add this to jooby itself? I would imagine that others would like to have something like this.

I've also created a TransactionalMixin which allows you to wrap a block of code with a simple lambda, committing the transaction if there was no exception thrown in the block.

```kotlin
abstract class TransactionalMixin(private val sessionFactory: SessionFactory) {
    fun <T> transactional(sess: Session = sessionFactory.currentSession, fn: (sess: Session) -> T): T {
        val trans = sess.beginTransaction()
        return try {
            val retVal = fn(sess)
            trans.commit()
            retVal
        } catch (ex: Throwable) {
            trans.rollback()
            throw ex
        }
    }
}
```

Which allows you to write something like:

```kotlin
    fun createUser(request: CreateUserRequest): UserDTO {
        return transactional {
            userRepository.save(User.fromRequest(request))
           // Do something that might throw to rollback the tx.
        }.toDTO() // access returned value from lambda.
    }
```

I'd be happy to PR either, or both of those concepts into jooby if there's a desire!

Happy Sunday.

**Comment by jknack** [comment]
PR for SessionRequest (+documentation) is welcome. Still to be completely safe will add a check for active transaction before closing the session? will be nice to rollback any active transaction and log an error describing the leak/bad usage.

I'm not so sure about Transactional mixin due it is for Kotlin only.

**Comment by Blquinn** [comment]
Ok, I re-wrote SessionRequest in java. Will look into documentation later. 

The TransactionallMixin is fairly straight forward in java as well. I will make a separate PR for that and feel free to close it if you don't think it fits.

```java
public abstract class TransactionalMixin {
    private final SessionFactory sessionFactory;

    public TransactionalMixin(SessionFactory sessionFactory) {
        this.sessionFactory = sessionFactory;
    }

    public <T> T transactional(Session sess, Function<Transaction, T> cb) {
        Transaction tx = sess.beginTransaction();
        try {
            T result = cb.apply(tx);
            tx.commit();
            return result;
        } catch (Throwable ex) {
            tx.rollback();
            throw ex;
        }
    }

    public <T> T transactional(Function<Transaction, T> cb) {
        return transactional(sessionFactory.getCurrentSession(), cb);
    }
}
```
