### ISSUE TITLE
Swagger support in jooby-2

### ISSUE THREAD

**Issue by TijoloAzul** [jooby-project/jooby#1455]
Hi,

I'm using jooby 2 and I was panning to use swagger though jooby's module apitool.
But, as far as I know, this do not exist for jooby 2.

Is there any plans for swagger in jooby 2?

**Comment by jknack** [comment]
it is going to be added, but not sure when exactly (requires lot of times)

**Comment by TijoloAzul** [comment]
Thanks for the quick answer. Is there any workaround?

**Comment by jknack** [comment]
not for lambda/script routes, for mvc you could use swagger annotations and add the swagger maven plugin

**Comment by TijoloAzul** [comment]
Thanks

**Comment by jknack** [comment]
Available in 2.7.0 https://jooby.io/modules/openapi/
