### ISSUE TITLE
jooby-cli error on mac terminal

### ISSUE THREAD

**Issue by weisebrazil** [jooby-project/jooby#1470]
Hi, 

I'd like to suggest some extra verifications on JVM or delete the code below, because it's crashing the right configurations founded before this. Code at line 415.

Wrong Code
```
    # special case on mac os x
    if isOperatingSystemOSX; then
    .... 
    fi
```

Right Code
```
    # special case on mac os x
    if [ -z "$java_cmds" ]; then
       if isOperatingSystemOSX; then
        .... 
       fi
   fi
```

Change the replace command at line 379.

Wrong Code
```
local java_ver=`"$java_bin" -version 2>&1 | grep "version" | awk '{print $3}' | tr -d \"`
```

Right Code
```
local java_ver=`"$java_bin" -version 2>&1 | grep "version" | awk '{print $3}' | sed "s|\"||g"`
```

### All this code are in jobby shell cli.

**Comment by jknack** [comment]
pull request is welcome... BUT! we don't generate such code,  it is done by https://github.com/remkop/picocli

**Comment by weisebrazil** [comment]
Yeah, I'll study how the picocli works. Thank's.
