### ISSUE TITLE
Example of usage of pac4j with database

### ISSUE THREAD

**Issue by asm0dey** [jooby-project/jooby#1475]
Most common scenario of authentication is authentication with database — we get hashed pass from DB, check it and if it's correct — we're reading roles/permissions of user and rendering page accordingly.

Could you please post example of pac4j with database?

Thing is it's not statically configured with config — it should have several components — DAO, service etc underneath.

**Comment by jknack** [comment]
PR is welcome. Just add a new class inside the `pac4j-starter` project.

**Comment by asm0dey** [comment]
For me it was a pain even with jooby v1, warks like this: https://github.com/asm0dey/school-crm/blob/master/src/main/java/org/ort/school/app/service/DBAuth.kt
And it uses DI and config. I have no idea if it'll work the same way on jooby v2

**Comment by jknack** [comment]
not sure what you mean with pain... but it is how Pac4j works

Going to try to add it... but is going to be simply... I can't confirm is going have several components.. That's an application architecture decision and is way out of the scope of a simple starter project

**Comment by asm0dey** [comment]
That's why I think it should be separate example, not part of starter. It's very common pattern of usage, and it's how it's being implemented in spring apps. But it's not that straightforward in jooby

**Comment by jknack** [comment]
just pushed https://github.com/jooby-project/jooby/tree/2.x/starters/pac4j-form-starter which is very similar to what you did around authenticator... main differences: no DI and use of jdbi as db layer.

If you like Guice starter, you should look into: https://github.com/jooby-project/jooby/tree/2.x/starters/guice-starter

**Comment by asm0dey** [comment]
Actually there is DI, it's just not declarative.
Looks perfect, thank you!

**Comment by jknack** [comment]
haha, you're right.

Feel free to modify, make it better, etc..
