### ISSUE TITLE
checkstyle via maven

### ISSUE THREAD

**Issue by jknack** [jooby-project/jooby#148]
enabled http://checkstyle.sourceforge.net/ on Jooby projects.

Checkstyle will be automatically generated via maven profile if ```checkstyle.xml``` file is located at: ```src/etc```

```src/etc/checkstyle.xml``` + ```mvn clean package``` will run checkstyle at the end of the build

**Comment by joseluisdiaz** [comment]
perhabs a good idea is to include findbugs as well?

**Comment by jknack** [comment]
good call, can you file an issue for findbugs?

:)
