### ISSUE TITLE
MVC controller is compiled to multiple class files in jooby-2

### ISSUE THREAD

**Issue by thomasguo** [jooby-project/jooby#1482]
Hi @jknack ,

I am a fan of MVC route pattern.  But in jooby-2.x I found that every mvc controller is compiled to multiple class files. It seems that every route in a controller has been converted into an inner class and finally compiled to a single class file.  Is that true?  Can we avoid this situation?  I am asking because in my project there will be hundred controllers and maybe nearly thousand routes.  I prefer to keep the compiled jar file as light as possible. 
Thanks.

**Comment by jknack** [comment]
Not sure how can avoid it. Each controller/mvc method is compiled into a Route.Handler that are all collected into a Extension. So for each controller you have N(number of mvc method) + 1

**Comment by thomasguo** [comment]
I got it.  So what is your recommendation to organize  this scale of routes number if not using the mvc pattern?  I saw the grouping routes pattern but they are still all in the main jooby App class.

**Comment by jknack** [comment]
The compiled jar won't be lot lot bigger. These handlers are just wrappers.
There are multiple alternatives to group and organize routes:

1. Multiple Apps:

```
Foo extends Jooby {
   {
      // foo routes
   }
}

App extends Jooby {
   {
      use(new Foo());
   }
}
```

See https://jooby.io/#router-composing-routes

2. Group routes into their own class:

```
FooRoutes {
   public String doSomething(Context ctx) {
     ...
   }
}

App extends Jooby {
    {
        FooRoutes foo = new FooRoutes();
        get("/path", foo::doSomething)
    }
}
```

Still, there is probably a way to reduce the number of classes in MVC. So, let;s keep this open for now

**Comment by thomasguo** [comment]
OK. Thanks for your help !

**Comment by jknack** [comment]
just pushed 2.5.0 to Maven central. Now, for each controller C there is only one generated class: C$Module
