### ISSUE TITLE
jooby-2 does not respect 'Produces' annotation 

### ISSUE THREAD

**Issue by thomasguo** [jooby-project/jooby#1500]
Hi @jknack ,

I use MVC pattern. It seems the annotations in jooby-2 doesn't respect 'Produces' feature. Saying I want to specify the content-type header of response.  I tried the following: 
```
    @GET("hi")
    @Produces("text/plain;charset=utf-8")
    public String sayHi() {
        return "I am rendering some chinese chars";
    }
```
or 
```
    @GET(value="hi", produces = "text/plain;charset=utf-8")
    public String sayHi() {
        return "I am rendering some chinese chars";
    }
```
but neither work.

Please have a look at this when you are available. Thanks.

**Comment by jknack** [comment]
yea I wasn't sure about this... the produces attribute, checks for what client send in the `Accept` header and based on it executes the route or not (content negotiation), but it doesn't set the content-type on response.

**Comment by thomasguo** [comment]
Okay. So is this a bug or not and will you improve it in a way?  In springMVC the produce attrubute sets content-type header. Thought I could set the content-type explicitly like following, it looks some ugly and error prone.

```
    @GET("hi")
    public String sayHi(Context ctx) {
        ctx.setDefaultResponseType(MediaType.text);
        return "I am rendering some chinese chars";
    }
```
Any suggestion to do this more generally and elegantly, please?

**Comment by jknack** [comment]
Got it. I can try to set it but it doesn't work on generic types like `produces = "text/*"` ...but probably not real use case in practice :S, so think we could use as content-type too.

for now you could add a decorator on top of mvc route that set the default response type:

```
decorator(next -> ctx -> next.apply(ctx.setDefaultResponseType(MediaType.text));
mvc(...);
```

**Comment by thomasguo** [comment]
OK got it.  thanks.
