### ISSUE TITLE
Rocker does not have TemplateEngine implementation

### ISSUE THREAD

**Issue by altmind** [jooby-project/jooby#1511]
Reading https://jooby.io/#templates
```
Templates are available via ModelAndView and requires a TemplateEngine implementation.
```

Is it intended that only handlebars, freemarker and pebble englines have `TemplateEngine` implementation, but not rocker?

**Comment by jknack** [comment]
Yes, we need an example as part of docs. TFB has one example: 

- https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/jooby/pom.xml#L80-L98

- https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/jooby/src/main/java/com/techempower/App.java#L127-L143

**Comment by jknack** [comment]
rocker documentation also describes how to integrate it: https://jooby.io/modules/rocker/
