### ISSUE TITLE
Dagger, Kotlin, Maven, DaggerAppComponent is not getting generated

### ISSUE THREAD

**Issue by altmind** [jooby-project/jooby#1514]
I'm new to dagger. I tried to follow the steps in https://jooby.io/#dependency-injection-dagger : 

* defined dagger-compiler dep in pom.xml and added dagger-compiler build plugin
* defined a @Singleton class, 

`val dagger = DaggerAppComponent.builder().build()`

In App.kt, it seems that DaggerAppComponent class is not getting code-gen'd, `mvn install` fails with `kotlin: Unresolved reference: DaggerAppComponent`

Was anybody successful using Dagger in a Kotlin project?

**Comment by altmind** [comment]
Do I need to define some execution for plugin in pom.xml? I dont see any logging from dagger when building the project, so looks like its annotation processing its not getting called?

**Comment by jknack** [comment]
try adding kapt https://kotlinlang.org/docs/reference/kapt.html

let me know how it goes

**Comment by altmind** [comment]
Using this pom.xml https://gist.github.com/altmind/6650dd57c1aa6060be217df89b0e0d42#file-pom-xml-L80-L119

I see that there are some code gen'd classes in target/kaptStubs/compile
But nothing dagger-specific. The DaggerApplicationComponent still not found.

**Comment by altmind** [comment]
I used guice instead.
