### ISSUE TITLE
Multiple regexps don't work in the same route definition

### ISSUE THREAD

**Issue by angryziber** [jooby-project/jooby#1515]
Example:
`get("/{lang:[a-z][a-z]}/{page:[^.]+}/") {...}`

will match anything as `lang`, numbers and longer stings. If `page` regexp is removed, then `lang` matching works as expected.

Another problem is that route parser doesn't allow regexp quantity declarations inside of {}, e.g.
`get("/{lang:[a-z]{2}}/") {...}`

Tested with 2.5.1

**Comment by angryziber** [comment]
@jknack that was quick, thanks!
However, the route matching code is not easy to understand, I tried to look at it before submitting the issue. Are you sure variables, like `xsearch` cannot have more understandable names?

**Comment by jknack** [comment]
you're welcome 2.6.0 is out with these fixes.

**Comment by jknack** [comment]
oh a quick note about how the routing algorithm works:

this is supported:

```
get("/{lang:[a-z][a-z]}/{page:[^.]+}/") {...}

get("/{lang:[a-z][a-z]}/") {...}
```

OR:

```
get("/{lang:[a-z]{2}}/{page:[^.]+}/") {...}

get("/{lang:[a-z]{2}/") {...}
```

but you can't mix them (use quantifier in one but not in the other):

```
get("/{lang:[a-z][a-z]}/{page:[^.]+}/") {...}

get("/{lang:[a-z]{2}}/") {...}
```
