### ISSUE TITLE
Kooby.require(KClass) is not available

### ISSUE THREAD

**Issue by angryziber** [jooby-project/jooby#1519]
Kooby class should overload `register()` so that `Service::class` could be passed as parameter instead of `Service::class.java` for convenience when using Kotlin.

This method signature is actually used in documentation, but doesn't exist.

**Comment by angryziber** [comment]
Maybe also an extension function `ServiceRegistry.register(c: KClass<*>, instance: Any)` would be useful.

Note: the current put() function cannot be called dynamically from Kotlin without casting, e.g.
```
listOf(UserRepository::class, CompanyRepository::class).forEach {
    services.put(it.java, it.createInstance())
}
```

**Comment by jknack** [comment]
can you check Kooby.kt and send the PR with the missing extension function?

Thanks

**Comment by angryziber** [comment]
Even better would be
```
inline fun <reified T: Any> Registry.require() = require(T::class.java)
```

To use `require<Service>()` or event `val service: Service = require()`

I'll check if I can make a PR

**Comment by angryziber** [comment]
OK, actually it exists, I just couldn't find it first because it needs to be imported. Thanks!
