### ISSUE TITLE
jooby-undertow : java.lang.IllegalStateException: UT000002

### ISSUE THREAD

**Issue by bmathewemc** [jooby-project/jooby#1534]
Below is the stack trace

java.lang.IllegalStateException: UT000002: The response has already been started
at io.undertow.server.HttpServerExchange.setStatusCode(HttpServerExchange.java:1406)
at org.jooby.internal.undertow.UndertowResponse.statusCode(UndertowResponse.java:303)
at org.jooby.internal.ResponseImpl.status(ResponseImpl.java:434)
at org.jooby.Response.status(Response.java:807)

**code that is causing the issue**
get(
"/app-plugin.zip",
(req, rsp) -> {
rsp.download(new File("/opt/files/app-plugin.zip"));
rsp.status(200);
rsp.end();
})
.name("Download App plug-in.");

 **pom.xml**
    _< parent >
        < groupId >org.jooby< /groupId >
        < artifactId >jooby-project< /artifactId >
        < version >1.6.6< /version >
    < /parent>
........................
        < dependency >
            < groupId>org.jooby< /groupId>
            < artifactId>jooby-undertow< /artifactId>
        < /dependency>_

Appreciate any pointers anyone has !
Thanks.
BM

**Comment by jknack** [comment]
try to switch the order of call and remove .end

```
get("/app-plugin.zip", (req, rsp) -> {
  rsp.status(200);
  rsp.download(new File("/opt/files/app-plugin.zip"));
})
```
