### ISSUE TITLE
decoder example gives an error

### ISSUE THREAD

**Issue by pcbt** [jooby-project/jooby#1547]
Hi I am usign this code snippet for decoder:

```
decoder(MediaType.json, (ctx, type) -> {
			byte[] body = ctx.body().bytes();
			return gson.fromJson(body,type);
		});
```

but it gives this error in Eclipse:

> Description	Resource	Path	Location	Type
Illegal lambda expression: Method decode of type MessageDecoder is generic 	restServer.java	/Server/src/main/java/Server/management	line 39	Java Problem

**Comment by jknack** [comment]
It is a java lambda limitation. We can;'t have a lambda that returns a generic type.

GOing to change the decoder result type to Object.
