### ISSUE TITLE
POST endpoint with Pac4j module kills Jooby server

### ISSUE THREAD

**Issue by rjaros** [jooby-project/jooby#1548]
A very simple `post` endpoint put after `Pac4jModule` kills Jooby server when called. 
Jooby hangs and consumes a lot of memory and cpu power untill killed.  `get` requests work ok.
A minimal example:
```kotlin
fun main(args: Array<String>) {
    runApp(args) {
        install(Pac4jModule())
        post("/test") {
            "ok"
        }
    }
}
```

**Comment by jknack** [comment]
I can't reproduce the: high resource consumption. I need an example project to reproduce it.

Also, form login on pac4j generates a redirect call after successful login...so its a GET not POST and with your example what . I got is:

```
Method Not Allowed
message: GET
status code: 405
```

Which is right.

**Comment by rjaros** [comment]
I've modified the the pac4j-form-starter here: https://github.com/rjaros/jooby/tree/2.x/starters/pac4j-form-starter. I've noticed that only POST request with `Content-Type: application/json` header makes the bug appear.
Run the `pac4j-form-starter` app and execute post request with curl:
```
curl -d '{"key1":"value1", "key2":"value2"}' -H "Content-Type: application/json" -X POST http://localhost:8080/test
```
