### ISSUE TITLE
@Before for MVC classes

### ISSUE THREAD

**Issue by angryziber** [jooby-project/jooby#1568]
Thanks again for great work.

We are writing a bigger app using Jooby and I am trying to find how to run security checks before any handler in an MVC class. There seems to be no `@Before` annotation.

Another thing is that how to return a custom status code from a MVC controller. Is there a more elegant way than:

```
fun method(ctx: Context): String {
  ctx.responseCode = StatusCode.CREATED
  return "{}"
}
```

i.e. by injecting a Context. Also, if I keep this method as void/Unit, the responseCode gets changed to StatusCode.NO_CONTENT, despite it was set explicitly to another value.

**Comment by jknack** [comment]
Hi,

 There is no before annotation for 2.x what you do is something like:

```
   before(ctx -> {
      // run checks
   });

   mvc(new MyController());

```

The void/unit thing is fixed on master see #1545 and will be released it today/tomorrow.
Another more "elegant" way is:

```kt
fun method(ctx: Context): StatusCode {
  return StatusCode.CREATED
}
```

**Comment by angryziber** [comment]
Thanks for the hint! Maybe it would be good to document the various things you can return from controller methods?

And before in the controller class would be very nice because it allows for better encapsulation of functionality.

So far, I have created by own `Before` insterface and I use my own `mvc()` registration method that adds before if interface is implemented as well. Not hard to do, but probably this simple thing would be useful in the framework itself.

**Comment by jknack** [comment]
Response documented: https://jooby.io/#mvc-api-responses
