### ISSUE TITLE
How to express an optional path parameter elegantly

### ISSUE THREAD

**Issue by thomasguo** [jooby-project/jooby#1573]
Hi @jknack ,

I want to express a route with an optional parameter.  For example,
```
get("/edit/{id:[0-9]*}",  ctx -> ctx.path("id").valueOrNull());  
``` 
I hope it will match the following request URI:
`/edit/3`
`/edit/`
`/edit`

How can we get there?

**Comment by jknack** [comment]
No way yet. I would like to support the laravel syntax: `"/edit/{id?}"` or `"/edit/{id}?"`

For now you need two/three mappings:

```
get("/edit/{id:\\d+}", this::edit);
get("/edit/", this::edit);
get("/edit", this::edit);
```

**Comment by thomasguo** [comment]
I see.  Looking forward to it.  Thank you.

**Comment by jknack** [comment]
Done on master branch: https://github.com/jooby-project/jooby/commit/5d464100a2ec9456be80355357793fa47f4ffe4e
