### ISSUE TITLE
Jooby2 openapi generation fails with NPE for mvc route with @Body and @PathParam

### ISSUE THREAD

**Issue by walkman90** [jooby-project/jooby#1580]
Example:

`@Path("/pets")
public class PetsController {

  @PUT
  @Path("/{id}")
  public Pet updatePet(Pet body, @PathParam String id) {   // ->  leads to NPE
    return ...;
  }
}`

Error: 

`[ERROR] Failed to execute goal io.jooby:jooby-maven-plugin:2.7.0:openapi (default) on project myapp: execution of openapi resulted in exception: NullPointerException -> [Help 1]
`

Maven 3.6.0 , JDK 11

**Comment by jknack** [comment]
Fixed in master. As a workaround you could add an annotation to body param, like:

`(@Nonnull Pet body, ...)`
