### ISSUE TITLE
Jooby2 openapi generation put openapi.json file in a wrong place

### ISSUE THREAD

**Issue by walkman90** [jooby-project/jooby#1582]
App.json/App.yaml probably should be under

`target/classes/com/myapp/App.json` right near App.class by location
`target/classes/com/myapp/App.class`

but instead, openapi plugin creates few more directories starting from App.class location, and the path to App.json looks like:

`target/classes/com/myapp/com/App.json` and swagger-ui unable to find it.

At least for maven3.6.0/jdk-11

**Comment by jknack** [comment]
Odd. For now use a single package level: `myapp`
