### ISSUE TITLE
openapi: disable generation on hot-reload

### ISSUE THREAD

**Issue by walkman90** [jooby-project/jooby#1597]
Is there any option to disable openapi generation when hot reload is triggering ?
Probably could be an issue on a large projects.

**Comment by jknack** [comment]
Maven? Try a different maven phase

**Comment by walkman90** [comment]
yes, that's did the trick, thanks. Maybe worth to mention in docs

**Comment by jknack** [comment]
what phase did you set? Can you send a PR? https://github.com/jooby-project/jooby/blob/2.x/docs/asciidoc/modules/openapi.adoc

**Comment by walkman90** [comment]
`package` phase worked for me. Will do.
