### ISSUE TITLE
[spring-starter] Spring security

### ISSUE THREAD

**Issue by thaingo** [jooby-project/jooby#1608]
Could you please provide references implementation of:
1. Integration of Spring Security into the starter
2. User authentication to from a Spring Security based IDM to application leveraging on the starter

Thanks.

**Comment by jknack** [comment]
do you have experience with spring security? I don't and not sure if possible...

We are able to use spring as long as we don't depends on spring-mvc (which I think spring-security does). Jooby has his own API for doing web.

**Comment by thaingo** [comment]
Spring-security does depend on the spring-mvc framework. I do have experience but doubt that I can help here, especially I am totally new to jooby and have just spent a few hours learning it. Jooby is quite impressive to me.

How about the second use-case which is dealing (out-of-box) with an existing IDM solution?

**Comment by jknack** [comment]
There is Pac4jModule: https://jooby.io/modules/pac4j/ with
- Simple user/password form example: https://github.com/jooby-project/jooby/tree/2.x/starters/pac4j-form-starter
- Oauth example: https://github.com/jooby-project/jooby/tree/2.x/starters/pac4j-starter
