### ISSUE TITLE
How to cleanly override ServiceRegistry?

### ISSUE THREAD

**Issue by angryziber** [jooby-project/jooby#1612]
I have come up with the following lightweight Dependency Injection framework:

```kotlin
class AutoCreatingServiceRegistry: ServiceRegistryImpl(), Extension {
  private val log = LoggerFactory.getLogger(javaClass)

  override fun install(app: Jooby) {
    app.router.javaClass.getDeclaredField("services").also { services ->
      services.isAccessible = true
      services.set(app.router, this)
    }
  }

  override fun <T: Any?> getOrNull(key: ServiceKey<T>): T? =
    super.getOrNull(key) ?: autoCreateService(key.type).also { put(key, it) }

  private fun <T> autoCreateService(type: Class<T>): T? {
    val constructor = type.constructors.find { it.parameterCount == 0 } ?:
                      type.constructors.find { !it.isSynthetic } ?: return null
    try {
      val args = constructor.parameters.map { require(it.type) }.toTypedArray()
      return (constructor.newInstance(*args) as T).also {
        log.info("Auto-created ${type.simpleName}${args.map {it.javaClass.simpleName}}")
      }
    }
    catch (e: RegistryException) {
      throw RegistryException("Failed to auto-create ${type.simpleName} with dependencies on ${constructor.parameters.map{it.type.simpleName}}: ${e.message}")
    }
  }
}
```

Basically it auto-creates services and their dependencies using construtor injection when they are first used using `require()`. This totally replaces the need for more complex DI frameworks.

However, the `install()` implementation above is problematic: there is no way to easily set a service registry globally, for the whole app and all routes. Or am I missing something?

**Comment by jknack** [comment]
I suggest to not go that path and use one of the existing DI solution (like Guice)... but if you feel strong about it: you need your own Registry implementation.

Use the Guice implementation as example: https://github.com/jooby-project/jooby/blob/2.x/modules/jooby-guice/src/main/java/io/jooby/di/GuiceModule.java

once you add your own Registry it delegates all the `require` calls to it. You will see that all the existing components of ServiceRegistry are registered in Guice: https://github.com/jooby-project/jooby/blob/2.x/modules/jooby-guice/src/main/java/io/jooby/di/JoobyModule.java

**Comment by jknack** [comment]
One more comment: All under `io.jooby.internal` is private and you should not use it in your code.

**Comment by angryziber** [comment]
I like the simplicity of it - reimplementing the whole Registry is more work. When using Kotlin it also feels that heavyweight DI framework is not needed. What I am showing works pretty well in a fairly complex project.

But even if I implement the full Registry, what is the correct way to start using it?

**Comment by angryziber** [comment]
I have figured that in Kotlin it is also easy to use delegation instead of inheritance, so it avoids depending on internal class ServiceRegistryImpl and allows using `app.registry()` without reflection.

```kotlin
class AutoCreatingServiceRegistry(private val original: ServiceRegistry): ServiceRegistry by original {
  private val log = LoggerFactory.getLogger(javaClass)

  override fun <T: Any?> getOrNull(key: ServiceKey<T>): T? =
    original.getOrNull(key) ?: autoCreateService(key.type).also { put(key, it) }

  private fun <T> autoCreateService(type: Class<T>): T? {
    val constructor = type.constructors.find { it.parameterCount == 0 } ?:
                      type.constructors.find { !it.isSynthetic } ?: return null
    try {
      val args = constructor.parameters.map { require(it.type) }.toTypedArray()
      return (constructor.newInstance(*args) as T).also {
        log.info("Auto-created ${type.simpleName}${args.map {it.javaClass.simpleName}}")
      }
    }
    catch (e: RegistryException) {
      throw RegistryException("Failed to auto-create ${type.simpleName} with dependencies on ${constructor.parameters.map{it.type.simpleName}}: ${e.message}")
    }
  }
}
```

But this is probably not how it was intended? So, basically, the question is:

How to get access to existing services in custom Registry implementation?

**Comment by jknack** [comment]
> How to get access to existing services in custom Registry implementation?

`getServices` allow you to access existing services.

> Is it expected to iterate all of them in application.services and put to own one? This will depend on order of initialization of other jooby modules/extensions.

That's correct. Order is required for some modules (jdbc > migrations > jdbi/hibernate).

> Wouldn't it be simpler to combine Registry with ServiceRegistry and just replace the built-in one completely?

It depends on registry implementation. The one provided by Jooby does actually merge all services making the ServiceRegistry obsolete.

Also, jooby modules don't depend on DI so if for some reason they need a service they must to be able to access to it via ServiceRegistry.

**Comment by angryziber** [comment]
But why not only leave ServiceRegistry?

The thing is: once I register a custom `app.registry()`, the `app.services` still remains and some other modules use `app.services.put()` without affecting the custom registry.

IMHO, a single interface and instance would be more easy to understand. If the underlying registry doesn't support `put()` then it can throw a very descriptive exception that will force the developer to change the order.

Or maybe there could be a special case: if developer provides a custom registry, which also implements ServiceRegistry` - then it will be completely replaced without the need to copy stuff over, because without delegation as I've shown above, it is difficult to find the correct moment of copying.

**Comment by jknack** [comment]
Got it. All the DI implementations are `io.jooby.Extension`. Extensions come with a `lateinit()` flag, which is set to `false` by default. If you override that method with `true`, the extension is initialized once all the other extensions were configured (all the lateinit=false). At that time just before starting the app the. DI modules read all the available services.

**Comment by angryziber** [comment]
What about the relatively simple change: allow registering of ServiceRegistry implementations via `app.registry()` to override the `app.services`?

This special case will make light-weight implementaions like mine a lot easier for those you don't want Guice or Spring or others.

**Comment by jknack** [comment]
The existing way is simple enough:
- Create a new Extension and set lateinit = true
- Set the app.registry with your own implementation. From your implementation you decided if want to merge or not existing services (it is just a map).

**Comment by angryziber** [comment]
But what if something adds more stuff to ServiceRegistry after the initialization?

**Comment by jknack** [comment]
That is not a valid use case. Initialization must occurs before web server blocks the caller/main thread.

Today is possible to modify the service registry bc it is a simple map... but you shouldn't trust that is going to be for ever possible.
