### ISSUE TITLE
How to implement request log?

### ISSUE THREAD

**Issue by angryziber** [jooby-project/jooby#1625]
I am trying to implement a thorough request log. It should run as the very last handler, so that it will see the correct `ctx.responseCode`.

So far, it seems that `decorator`s are run before any `after` handlers and `error` handlers run after `after` handlers. Does it also depend on the order of adding the handlers?

And finally, where to put code that needs access to the **final** state of the `Context`?

**Comment by jknack** [comment]
Hi, 
  There is one already: https://jooby.io/#handlers-accessloghandler.

 Then to access to final state: https://jooby.io/#router-handler-complete

**Comment by angryziber** [comment]
Thanks for the insights.

Note: there is a typo in complete in the docs: `The complte listener`

**Comment by jknack** [comment]
can you send a PR and fix the typo?

Thanks
