### ISSUE TITLE
Pac4j authorizers ignored

### ISSUE THREAD

**Issue by csisy** [jooby-project/jooby#1629]
It seems that there is no way to add an authorizer to the jooby-pac4j module.

It is possible to register an authorizer to the pac4j itself by calling
`config.addAuthorizer("name", authorizer);`
however I cannot find a way to tell the auth clients to use that authorizer.

In the `Pac4jModule` the security handlers are registered to the router as `SecurityFilterImpl` objects (`Pac4jModule:232`).  However these objects have no idea about the authorizers we'd like to use. There is a public function in the `SecurityFIlterImpl` class that could be used to register the authorizers:
`public SecurityFilterImpl addAuthorizer(String authorizer)`
but this method is never called.

So when the security logic is executed (`SecurityFilterImpl:81`) the `authorizers` parameter is always null which causes the auth checker to use the default CSRF authorizer only.

### Jooby 1.x

Previously it was possible to set the authorizer at the time of auth client registration. And the authorizer itself was propagated down to the security logic (and the auth checker) properly.

### Proposal

1. Add an `authorizer(s)` parameter to the `Pac4jModule::client` method
1. Since the clients are grouped by route pattern it would be nice to have an `authorizer(pattern, authorizer)` method (as well?)
1. Use the provided authorizer(s) when adding the `SecurityFilterImpl` objects to the router

**Comment by jknack** [comment]
Yea, I'm not familiar with Pac4j  4.x API but thought it was everything possible via pac4j config object.

Can you double check if we are missing something while using config.addAuthorizer?

**Comment by csisy** [comment]
### Auth flow

The pac4j config itself handles the registered authorizers, however when there is no authorizer provided to the `org.pac4j.core.authorization.checker.DefaultAuthorizationChecker` it defaults to the CSRF authorizer:

```
// no authorizers defined, we default to CSRF_CHECK
if (isBlank(authorizerNames)) {
	authorizerNames = DefaultAuthorizers.CSRF_CHECK;
}
```

When the `Pac4jModule` is installed it registers the clients to the router:

```
// Pac4jModule:232
for (Map.Entry<String, List<Client>> entry : allClients.entrySet()) {
  String pattern = entry.getKey();
  if (!pattern.equals("*")) {
	List<String> keys = Router.pathKeys(pattern);
	if (keys.size() == 0) {
	  application.get(pattern, new SecurityFilterImpl(null, pac4j, options, entry.getValue()));
	} else {
	  application.decorator(new SecurityFilterImpl(pattern, pac4j, options, entry.getValue()));
	}
  }
}
```
The `SecurityFilterImpl` class itself has an `authorizers` member variable which is null by default. There is a method `addAuthorizer(String authorizer)` that could be used to add authorizers to this object but it is never called anywhere.

And these `SecurityFilterImpl` are executed by the router and eventually it reaches the following code block:

```
private Object perform(Pac4jContext ctx, GrantAccessAdapterImpl grantAccessAdapter) {
  SecurityLogic securityLogic = config.getSecurityLogic();
  String clients = ctx.getContext().query(clientName(securityLogic))
	.value(this.clients);
  return securityLogic.perform(ctx, config, grantAccessAdapter, config.getHttpActionAdapter(),
	clients, authorizers, null, options.getMultiProfile());
}
```

And here the `authorizers` member variable is null (since it is never modified) and is passed to the `securityLogic`. By default the securityLogic is a `DefaultSecurityLogic` instance which calls the `authorizationChecker` (`DefaultSecurityLogic:140`) with the provided null authorizers. This causes the default CSRF authorizer to be used (see code block 1).

### App setup

Nothing special, the setup code is something like this:

```
final var pac4jOptions = new Pac4jOptions();
final var pac4jConfig = new org.pac4j.core.config.Config();

pac4jConfig.addAuthorizer("test", new Authorizer<CommonProfile>() {

	@Override public boolean isAuthorized(WebContext context, List<CommonProfile> profiles) {
		return false;
	}
});

final var pac4j = new Pac4jModule(pac4jOptions, pac4jConfig);

// setup clients...
pac4j.client("/api/*", conf -> { /* ... */ });
// etc

install(pac4j);
```

### Jooby 1.x

Previously when the auth clients were registered we had an `Class<? extends Authorizer> authorizer` parameter. This was saved with the client factory and was registered to both pac4j (`Pac4j:689`) **and** the security filter (now called handler) (`Pac4j:828`)

**Comment by csisy** [comment]
Thank you for the quick solution! :)
