### ISSUE TITLE
router: Add setTrustProxy option

### ISSUE THREAD

**Issue by angryziber** [jooby-project/jooby#1634]
There is `Context.getRequestURL(boolean)` that resolves X-Forwarded-Host and X-Forwarded-Proto,
but `Context.getRemoteAddress()` will always return only the real IP, i.e. proxy IP.

An easy solution is to add `Context.getRemoteAddress(boolean)` as analogy for `getRequestURL()`,
but an even better solution would be a flag in conf that enables using `X-Forwarded-*` headers by default. Most Java web apps run behind some kind of proxy or load-balancer in production.

This also affects `AccessLogHandler` that will log only proxy IPs if behind one.

**Comment by jknack** [comment]
We definitely  need it, but I'm not happy with how it works today: `Context.getRequestURL(boolean)`

Would like to add a getter/setter for Host/Proto/etc and then a XForwarded decorator:

```
{
    decorator(new XForwarded());

    get("/", ctx -> {
       String url = ctx.getRequestURL()
    });
}
```

So .getRequestURL/getRemoteAddress will use the `X-Forwarded-*` if they are present.

This way we don't need a special `(trustProxy)` flag for each of them

**Comment by angryziber** [comment]
Great idea.

Please also keep in mind that X-Forwarded-Host is much less common (proxies usually just forward the normal Host header)

Current implementation of `getRequestURL(true)` would skip `X-Forwarded-Proto` if there is no `X-Forwarded-Host`. This doesn't for in Heroku, for example, which sends `X-Forwarded-Proto`, but not `X-Forwarded-Host`.

**Comment by jknack** [comment]
Your suggestion is better, just we are not going to add a configuration properties, just a public setter:

```
{
    setTrustProxy(true);
}
```

But of course you can read from a configuration property of your choice:

```
{
    setTrustProxy(getConfig().getBoolean("trustProxy"));
}
```

> Current implementation of getRequestURL(true) would skip X-Forwarded-Proto if there is no X-Forwarded-Host. This doesn't work in Heroku, for example, which sends X-Forwarded-Proto, but not X-Forwarded-Host.

The new implementation fixes all these.

**Comment by jknack** [comment]
Released: https://jooby.io/#router-trust-proxy.
