### ISSUE TITLE
HEAD - method not allowed

### ISSUE THREAD

**Issue by angryziber** [jooby-project/jooby#1655]
It seems that Jooby doesn't handle HEAD requests with GET routes by default.
HEAD requests are often used by monitoring tools, and most web servers/frameworks just need to run the GET handler, but return only the headers.

I think Jooby should also do that by default, otherwise monitoring tools get 405 Method Not Allowed.

**Comment by jknack** [comment]
That's right not by default: https://jooby.io/#handlers-headhandler
