### ISSUE TITLE
netty: Gzip encoding seems to break AssetHandler

### ISSUE THREAD

**Issue by angryziber** [jooby-project/jooby#1656]
When I enable gzip by adding:
```kotlin
  serverOptions {
    gzip = true
  }
```

My custom html routes returning html are successfully encoded and decoded by the browser, but any assets fail to decode (example from Chrome console):
```
GET http://localhost:8080/build/main.js net::ERR_CONTENT_DECODING_FAILED 200 (OK)
```

**Comment by jknack** [comment]
what web server is this? Jetty? Netty? or Undertow?

**Comment by jknack** [comment]
found: netty. As workaround you might want to try one of the other servers: https://jooby.io/#server
