### ISSUE TITLE
Access to multipart form data file names

### ISSUE THREAD

**Issue by walkman90** [jooby-project/jooby#1676]
Hi Edgar,

A question regarding handling multipart\form-data requests.
Is there any option to get a list of files with their keys from FormData

I see we can get all files from Context with `ctx.files()` or `ctx.multipart().files()`.
But those methods return the list of `io.jooby.FileUpload` which has public API to get filename
but not the key under which it is placed in FormData object.

Long story short, it would be nice to have some kind of public API for
`Map<String, List<FileUpload>> io.jooby.internal.MultipartNode.files`
where formData keys used as keys for files map

**Comment by jknack** [comment]
never found it useful, but guess we could add it. yea
