### ISSUE TITLE
From jackson 2.11 mapper  creation code has changed

### ISSUE THREAD

**Issue by husayt** [jooby-project/jooby#1677]
Code here refers to old syntax
https://github.com/jooby-project/jooby/blob/ee13299c59ba194a48fbdb0b600c0140d55dc015/modules/jooby-jackson/src/main/java/io/jooby/json/JacksonModule.java#L161

This is  how it should look now
```
    ObjectMapper mapper = JsonMapper.builder() // or different mapper for other format
   .addModule(new ParameterNamesModule())
   .addModule(new Jdk8Module())
   .addModule(new JavaTimeModule())
   .addModule(new AfterburnerModule())
   // and possibly other configuration, modules, then:
   .build();
```

Mentioned [here](https://github.com/FasterXML/jackson-modules-java8)

**Comment by jknack** [comment]
can you send PR? Also, update javadoc and co if there is an old reference.

Thank you.
