### ISSUE TITLE
CORS settings ignored with Netty

### ISSUE THREAD

**Issue by husayt** [jooby-project/jooby#1680]
I have tried to enable CORS as it is described in docs and it failed with Netty, after trying many other things I just changed to Jetty and that worked fine.

So there must be an issue with `decorator(new CorsHandler());` in Jooby for Netty

**Comment by jknack** [comment]
Hi, 

 Is there any error/stacktrace? I need something to reproduce the issue.  The existing tests works ok across all the server implementations

**Comment by husayt** [comment]
Sadly no error messages, I was trying to get it working for hours as I was
deploying to Google Cloud Run. Tried all kind of different combinations,
then just switched to jetty and all worked fine.

I will try to get some more info for you. But it's great to be able to
switch from jetty to netty by just changing one letter.
