### ISSUE TITLE
Unable to set POST method for DirectFormClient

### ISSUE THREAD

**Issue by asm0dey** [jooby-project/jooby#1686]
There is just no way to change HTTP methods for clients

**Comment by jknack** [comment]
don't follow. What is DirectFormClient?

Thanks.

**Comment by asm0dey** [comment]
Excuse me, 'm talking about pac4j module. It has concepts of clients — ways to authenticate. But I think that there should be way to change HTTP method which is used for authentication.

**Comment by jknack** [comment]
Got it: pac4j. I need an example of what are you doing and what are you expecting/requesting.

Thanks.

**Comment by asm0dey** [comment]
Please consider following example:

```kotlin
    install(Pac4jModule(Pac4jOptions().setLogoutPath("/api/logout").setCallbackPath("/api/callback"))
            .client("/api/login") { conf ->
                BasicAuthClient { creds, ctx ->
                    if (creds !is UsernamePasswordCredentials) throw IllegalArgumentException()
                    // credentials vlidation and profile creation goes here
                }
            }
```

As you can see I can protect `/api/login` endpoint with `BasicAuthClient`. But this way authentication will work only with `GET` HTTP method. But I believe it should work at least with `POST` too.

**Comment by jknack** [comment]
Found the issue. It is related on how pac4j works with POST/PUT/PATCH requests.

At some point (not sure exactly which version) pac4j adds a default authorizer when you don't provide one: `CsrfAuthorizer`. This authorizer doesn't run on GET, this is why GET request works and POST doesn't.

Workaround (guess) is to provide your own authorizer (to override the default one):

```
install(new Pac4jModule()
        .client(new Authorizer() {
          @Override public boolean isAuthorized(WebContext context, List profiles) {
            return true;
          }
        }, conf -> new IndirectBasicAuthClient(authenticator()))
    );
```

**Comment by asm0dey** [comment]
What if I want to allow only POST requests?

**Comment by asm0dey** [comment]
And, BTW, it looks like that having 2 Csrf handlers at same time is a little overehad.

**Comment by jknack** [comment]
Yea, there is no way to control which method is supported. It is GET and POST today.

The Csrf of jooby has nothing to do with the one provided with pac4j. Also, I didn't even know about the pac4j one until now.

It is probably better to turn it off by default in pac4j

**Comment by csisy** [comment]
Why do you want to protect the login path? It makes no sense. The login paths must be unprotected (or at least there must be another authentication mechanism that authenticates the user beforehand). Anyway, if you use the built-in form client the Jooby's Pac4j module automatically reigsters a GET and POST callback route.

I still don't understand what do you wish to achieve. If you have trouble with POST requests and you did not register any authorizers then @jknack 's response is the answer you're looking for. See #1629

**Comment by jknack** [comment]
There is one provided by pac4j: `CsrfAuthorizer` which is the default authorizer if we don't specify one. Wonder if jooby should removed this by default?

Then jooby has one too: https://jooby.io/#handlers-csrfhandler, but it is not related to pac4j in any way.

**Comment by asm0dey** [comment]
@csisy my workflow is following:

1. User tries to login with DirectFormClient (by sending login and password as URL parameters)
2. If authentication is successful — user obtains JWT token
3. On every other path user should be authenticated by this login token

Why do I want only `POST` to be allowed for initial authentication? Because I want to avoid csrf there.

Is my logics flowed somewhere? It there any way to improve this flow?

**Comment by jknack** [comment]
Going to turn off the default CsrfAuthorizer for pac4j in next release. If you want it, must be add it explicitly
