### ISSUE TITLE
No API for setting Csrf mechnics

### ISSUE THREAD

**Issue by asm0dey** [jooby-project/jooby#1691]
`CsrfHandler` supports 3 ways to work — cookie, header and form parameter. But There is no constructor params to define preferred mechanics. Current workaround is via `setTokenGenerator`, like this:

```kotlin
CsrfHandler().setTokenGenerator { a ->
        val uuid = UUID.randomUUID().toString()
        a.setResponseCookie(Cookie("csrf", uuid))
        uuid
}
```

But this is not that beautiful as could be. I think that preferred way is to set this up via enum or possibly some interface.

**Comment by jknack** [comment]
The token is saved in HTTP Session and then read it back from cookie, header or form parameter. From your code you need to find a way to provide the token as cookie, header or form field. The handler read it back from one of these three locations and compares with the one saved in session.

The token generator is just for generate the token.

**Comment by asm0dey** [comment]
Is the `before` methos the best place for this logics? I still think that `CsrfHandler` could accept it as constructor arguement.

**Comment by jknack** [comment]
Right. Here is an example with a hardcode token: https://github.com/jooby-project/jooby/blob/e58e31b6ce4ea25739ea04461df8611234245541/tests/src/test/java/io/jooby/FeaturedTest.java#L2881
