### ISSUE TITLE
pac4j: turn off csrf authorizer

### ISSUE THREAD

**Issue by jknack** [jooby-project/jooby#1693]
Pac4j uses the `CsrfAuthorizer` by default when no other authorizer is provided. Next release is going to turn it off by default so we don't get unexpected responses. This causes confusion on how it works evidence of this is the #1686 question and got some other similar questions on gitter.

**Comment by moromindful** [comment]
Pac4j csrf token generator should also be turned off by default as it generates session value and a cookie.
