### ISSUE TITLE
ModelAndView Return Specific Part of Page

### ISSUE THREAD

**Issue by Sayyiditow** [jooby-project/jooby#1704]
I am not sure if this is possible with jooby's ModelAndView, but in Spring, one can return a specific part of the page using ModelAndView's constructor or setViewName method. For example, in the index.html, return only part of the page with id test, this would be done easily with:

```
ModelAndView modelAndView = new ModelAndView("index :: #test");
modelAndView.addObject("objectForTest", 123);

//Or
modelAndView.setViewName("index :: #somethingElse");

```

Is this doable?

**Comment by jknack** [comment]
for thymeleaf right? I'm not a thymeleaf user... can you point me on how to do it? Or even better send a PR ;)

**Comment by Sayyiditow** [comment]
Not necessarily thymeleaf, I believe this should work with any templating engine. It just returns a part of the html page based on id. Useful when you want to run ajax/mimic SPAs by just sending responses of part of the html page and not the whole view. Let me dive into it more and see what I can find.

**Comment by jknack** [comment]
yea not sure about it... thought it was supported by thymeleaf. I'm sure handlebars/rocker and (think) freemarker don't support this.

if you need to implement such feature what you usually. do is to write different templates:

- index.ext
- test.ext

and some how index.ext includes the content from test.ext. So later you can make a reference to any of these two from ModelAndView.

Any other global solution have to take template engine output, treat it as HTML, parse and find something with `test` id (too expensive), no?

**Comment by Sayyiditow** [comment]
> and some how index.ext includes the content from test.ext. So later you can make a reference to any of these two from ModelAndView.

This was actually something I was thinking about. Break down part of pages that can be returned individually as fragments (th:fragment) then embed them into the main page. And when needed call the fragments only, use Ajax to update only these fragments.

And yes, a global solution will be too expensive. I think the fragment approach will work. This feature is quite important when you don't want to refresh the whole page content.

Thanks!

**Comment by jknack** [comment]
Cool

**Comment by Sayyiditow** [comment]
I'm closing this, the fragment approach works just fine.
