### ISSUE TITLE
pac4j: access to user from unprotected paths

### ISSUE THREAD

**Issue by Sayyiditow** [jooby-project/jooby#1706]
I have this simple implementation on login:

```
install(new Pac4jModule().client("/dashboard*", config ->
                new FormClient("/login", userAuthenticator)));
```

The userAuthenticator is a class that implements Authenticator<UsernamePasswordCredentials>. I can login successfully and but say I visit an unprotected page like "/" - I want to be able to get the user details from the context like:

```
@GET("/")
    public ModelAndView getHomePage(@QueryParam String asyncPage, Context context) {
        ModelAndView modelAndView = new ModelAndView("index.html");
        modelAndview.put("user", context.getUser());
        return modelAndView;
}
```

Unfortunately this does not return the user? Am I missing something? I am however able to get the user on the protected "dashboard**" pages.

**Comment by Sayyiditow** [comment]
Managed to get this on different pages using ProfileManager. For others who might want to do this:

`
@GET("/") public ModelAndView getHomePage(@QueryParam String asyncPage, Context context) { 
        ModelAndView modelAndView = new ModelAndView("index.html"); 
        WebContextImpl webContext = new WebContextImpl(context, new Pac4jOptions());
        ProfileManager<CommonProfile> profileManager = new ProfileManager<>(webContext);
        Optional<CommonProfile> commonProfile = profileManager.get(true);
        if (commonProfile.isPresent()) {
            modelAndView.put("user", commonProfile.get());
        }
        return modelAndView;
 }

`

**Comment by jknack** [comment]
going to reopen and fix it:

- we should be able to get the user once authenticated (no matter if we ask from unprotected path)
- what you did is the correct way: ask ProfileManager for logged user. But your code make use of some internal API (everything inside the `internal` package should not be used it). So need to provide better access to ProfileManager.

For now keep your code as workaround, but is going to be better in next release

**Comment by Sayyiditow** [comment]
Thanks! That makes sense.
