### ISSUE TITLE
CSRF token with Thymeleaf

### ISSUE THREAD

**Issue by Sayyiditow** [jooby-project/jooby#1710]
Is the CSRF not automatically passed to the requested page? I've tried to check the value using:

`<input name="csrf" th:value="${csrf}" type="hidden" id="registerCsrf"/>`

But it is empty. I have also noticed that post requests still go through without a CSRF token. Am I missing something? Based on the doc from https://jooby.io/, the csrf is automatically created and automatically validated using the CsrfHandler, we just need to pass it in the form, header etc.

Can't seem to be able to pass it.

**Comment by jknack** [comment]
just try it, works as expected:

```java
      install(new ThymeleafModule());

      before(new CsrfHandler());

      get("/csrf", ctx -> new ModelAndView("csrf.html"));
```

csrf.html
```
<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org">
<body>
<p>
  <input name="csrf" th:value="${csrf}" type="hidden" id="registerCsrf"/>
</p>
</body>
</html>
```

**Comment by Sayyiditow** [comment]
Ah thanks! I was missing the:

`before(new CsrfHandler());`

Now works! Thanks.
