### ISSUE TITLE
process working directory is wrong when running application using gradle joobyRun task cause FileNotFoundException

### ISSUE THREAD

**Issue by abnud1** [jooby-project/jooby#1758]
I'm using jooby 2.8.4 with gradle 6.4, running my application using `joobyRun` task, I need to access files using relative paths in my application but almost all of them fail. both java NIO and regular java `File` APIs fail.

The strange thing is that when running the application using regular `run` task from the application plugin the working directory is correct.

Note that `System.getProperty("user.dir")` even if correct is not enough since many APIs seem to not respect it.
Below you find a sample application illustrating the problem, as you'll see `System.getProperty("user.dir")` is correct but `File("").absolutePath` and `Paths.get(".").toAbsolutePath().toString()` are wrong, they point to gradle daemon home directory.
[sample application](https://github.com/jooby-project/jooby/files/4727887/testJooby.zip)

**Comment by jknack** [comment]
Hi,

 I'm not a gradle user :(. I think from Jooby application (actually any Java application) can't control the current directory due this comes from process that started the JVM: gradle daemon.

Unless gradle provides something the only option is to use: `System.getProperty("user.dir")`

You probably need to design something to resolve the path in dev(gradle daemon) vs prod(no issue)
