### ISSUE TITLE
How can I access config / environment from controller / mvc method?

### ISSUE THREAD

**Issue by fabiangebert** [jooby-project/jooby#1774]
Since we're using OpenAPI, we've put our business logic in functions as such:
```
/// App.kt:
...
get("/compute", ::compute)
...
/// in another file:
@Operation(...)
fun compute(ctx: Context): Result {
    val config = ???
}
```
How do I retrieve the config? I tried `ctx.require(Config::class)` and `ctx.require(Environment::class).config` - none of them work.

**Comment by jknack** [comment]
The `ctx.require` should work, so we can consider this a bug.

As workaround it depends:

```
class App extends Jooby {
  {
     get("/compute", ::compute)
  }

  fun compute(ctx: Context): Result {
    val config = this.getConfig(); // This is Kooby/Jooby getConfig
}
}
```

For mvc you can pass as argument:
```
{
   mvc(new Controller(getConfig());
}
```
