### ISSUE TITLE
HTTP2 with 2.x

### ISSUE THREAD

**Issue by hc-codersatlas** [jooby-project/jooby#1780]
Hi, believe this was in 1.x. Can't find any settings for it in 2.x. Is it coming soon? Thanks.

**Comment by jknack** [comment]
I don't think so. Probably for 3.x.

When we got something we should validate the implementation with: https://github.com/summerwind/h2spec

**Comment by abnud1** [comment]
@hc-codersatlas  if you use undertow you can enable HTTP2 like I did, I copied jooby-utow module source code into my application code and just added this statement to Utow.java file:
`.setServerOption(UndertowOptions.ENABLE_HTTP2, true)`, you add this statement to `Undertow.builder`. oh and you should probably remove the `KEEP_ALIVE` statement as it's irrelevant for HTTP2. my application works perfectly doing this and browser shows h2. 

I think jetty would be easy too but haven't looked at it, netty is the complex one, I tried doing it but failed, it sure is a lot of work and `HttpConversionUtil` which converts between HTTP2 API and HTTP1.1 API didn't help much.

If jooby-netty moved to HTTP2 I think this issue would be closed as the other servers are straightForward

**Comment by hc-codersatlas** [comment]
@abnud1 thanks for the suggestion. Too many constant changes to be keeping up with a forked module (not that changes are a bad thing).
