### ISSUE TITLE
@javax.annotation.Nonnull with MVC and @QueryParam

### ISSUE THREAD

**Issue by extbe** [jooby-project/jooby#1786]
Hi! 
I use MVC routes and annotated one of the query parameters with `javax.annotations.Nonnull`
```java
@GET("/requiredStringParam")
public String getRequiredStringParam(@QueryParam @Nonnull String name) {
    return name;
}
```
But if I don't send the parameter, then variable's value will still contain `null`.
I looked into `jooby-apt` sources and found this line:
https://github.com/jooby-project/jooby/blob/08715ce4a776319152e3b342d8978a6e421c7e4b/modules/jooby-apt/src/main/java/io/jooby/internal/apt/ParamDefinition.java#L113
I checked some implementations of `javax.lang.model.type.DeclaredType` and didn't find overriding of `equals` that checks for equality of canonical type names. Maybe this line of code should look like this? (I've checked this version and now `MissingValueException` will be thrown)
```java
if (annotation.getAnnotationType().toString().equals(type)) {
```

Also, I receive `null` if I annotate with `Nonnull` a parameter with a type other than `String`, e.g. `UUID`. Is the behavior correct?

**Comment by jknack** [comment]
Definitely a bug, can you send a PR?

**Comment by extbe** [comment]
Yes, I'll do it
