### ISSUE TITLE
Is it possible to make jooby join eureka as a microservice?

### ISSUE THREAD

**Issue by rainmanhhh** [jooby-project/jooby#1793]
I want to migrate old services from springboot(mvc) to jooby

**Comment by jknack** [comment]
I'm sure is possible, but never try eureka. Would you like to send a PR?

**Comment by jknack** [comment]
Eureka documentation is not good. I tried the eureka client... but don't think it works.

More comments:

- There isn't a clean example of how to do it without Spring (all examples are with Spring)
- The eureka client depends on Guice
- The EurekaModule depends not only on Guice but also in some other library: Governator

I will mark as question. We could still integrate as Jooby module (ideally without Guice), but we need a clean working example.
