### ISSUE TITLE
UtowContext send response before transaction commit

### ISSUE THREAD

**Issue by walkman90** [jooby-project/jooby#1803]
Hi @jknack 

It seems that UtowContext implementation has an issue for the use case:

`
public class PetsController {

    @Inject
    private final PetsRepository petsRepo;

    @DELETE
    public void deleteAllPets(Context ctx) {
        petsRepo.deletePets();
        ctx.send("Done!");
    }

}
`

use `TransactionalRequest` decorator and jdbiSqlObject for `PetsRepository`  
then send response with `ctx.send()` method in controller.

In this particular case, the client will receive response before the database transaction will commit.
After switching from `utow` to `netty` issue has gone - the client receives response only after transaction commit.

**Comment by jknack** [comment]
Almost sure that isn't the case. If you call send with something... web server is going to send that to client... transaction commit (or any other decorator in pipeline) has nothing to do with the explicit call to send.

**Comment by walkman90** [comment]
That is a tricky change for Jooby 2.
I believe it is a common approach while migrating from Jooby 1.x to Jooby 2.x
to replace expressions like 

`response.status(s).send(data);`

to 

`ctx.setResponseCode(c).send(data)` - the closest equivalent AFAIK

in jooby1.x it was `TransactionalRequest` friendly...
and now `ctx.send` is not. It could probably play a dirty trick for those who migrate.

Also, different behavior on `utow` and `netty `makes it even more dangerous

**Comment by jknack** [comment]
Now you mentioned there is a sightly difference between them in relation to the `onComplete` event. The `onComplete` event is generated when response was already sent. Undertow implementation used his own mechanism while Netty uses a future listener approach. 

Still all the 3 implementations send content when you call: `send`. Also these two are equivalent: (1x. vs 2.x):

    response.status(s).send(data)

    ctx.setResponseCode(c).send(data)

What works differently is the TransactionlRequest from jdbi. In 2.x is a raw filter:

```
return ctx -> {
   return inTransaction (next.apply(ctx));
}
```

In 1.x was a bit more complex.

Going back to `send` the intention is to work as it is. Leaving you as final user the option and absolute control (for some specific application usage) of sending the response to client when you asked for it. In your example if you just do:

```
@DELETE
public String deleteAllPets(Context ctx) {
    petsRepo.deletePets();
    return "Done!";
}
```

It should works. So here you give the change to the TransactionalRequest filter to commit or rollback and then Jooby to send the success or. errored response

**Comment by jknack** [comment]
are we good here?

**Comment by walkman90** [comment]
yeah, thank you for the detailed explanation!
