### ISSUE TITLE
Graphql query cache

### ISSUE THREAD

**Issue by hc-codersatlas** [jooby-project/jooby#1804]
https://www.graphql-java.com/documentation/v15/execution/ has a section query cache that enables caching of the parsed Document. Is this something that can be added to Jooby as an option to enable? 

Would be good to be able to specify the cache size. 

Thanks!

**Comment by jknack** [comment]
Hi Harry,

Try this:

```java
Cache<String, PreparsedDocumentEntry> cache = Caffeine.newBuilder().maximumSize(10_000).build(); (1)

    PreparsedDocumentProvider preparsedCache = PreparsedDocumentProvider {
        @Override
        public PreparsedDocumentEntry getDocument(ExecutionInput executionInput, Function<ExecutionInput, PreparsedDocumentEntry> computeFunction) {
                Function<String, PreparsedDocumentEntry> mapCompute = key -> computeFunction.apply(executionInput);
                return cache.get(executionInput.getQuery(), mapCompute);
        }
    }    

    GraphQL graphQL = GraphQL.newGraphQL(StarWarsSchema.starWarsSchema)
            .preparsedDocumentProvider(preparsedCache) (2)
            .build();

   install(new GraphQLModule(graphQL));
```

**Comment by hc-codersatlas** [comment]
Thanks for that. It requires a custom schema entirely though vs just supplying the wiring as per the website's example.

**Comment by jknack** [comment]
Well yea, the general concept with modules is to provide a default usage (wiring will be here) and advanced/custom usage (GraphQL here). Advanced usage requires few more lines of code but give you absolute power on target library (graphql).

Also, as you see in GraphQL example it requires an external library: `Caffeine`. If we add this to GraphQLModule we will have to depends on that library. This is why feel we shouldn't add it.

Hope it make senses.
