### ISSUE TITLE
pac4j used in scoped route on logout it doesn't add the context path.

### ISSUE THREAD

**Issue by moromindful** [jooby-project/jooby#1808]
Hello, I am new to jooby and I am trying to get the hang of it and it's modules.

I am using pac4j inside a path()
`
    path("/client", () -> {

      get("/login", ctx -> new ModelAndView("client/login.peb").put("error", ctx.query("error").valueOrNull()));

      decorator(new TransactionalRequest());

      Pac4jOptions clientWebAuthOptions = new Pac4jOptions();
      clientWebAuthOptions.setCallbackPath("/auth");
      clientWebAuthOptions.setDefaultUrl("/dashboard");
      clientWebAuthOptions.setDefaultClient("web");
      Config clientWebAuthConfig = new Config();
      install(new Pac4jModule(clientWebAuthOptions, clientWebAuthConfig)
        .client(conf -> {
          FormClient clientFormClient = new FormClient("/client/login", (Credentials credentials, WebContext ctx) -> {
            ClientAuthenticator authenticator = require(ClientAuthenticator.class);
            if (credentials instanceof UsernamePasswordCredentials) {
              authenticator.validate((UsernamePasswordCredentials)credentials, ctx);
            }
          });
          clientFormClient.setName("web");
          clientFormClient.setUsernameParameter("email");
          clientFormClient.setPasswordParameter("password");    
          clientFormClient.setCallbackUrlResolver(new NoParameterCallbackUrlResolver());
          return clientFormClient;
        })  
      );

      get("/dashboard", ctx -> new ModelAndView("client/dashboard.peb"));

    });
`

As you can see my login page is at /client/login ... the callback url is at /client/auth when I login successfully I get redirected to the /client/dashboard, but when I send a request to /client/logout it makes the logout but it redirects me to /dashboard and by looking at LogoutImpl code 
`redirectTo = options.getDefaultUrl();`
it is missing the context path.

**Comment by jknack** [comment]
Hi,

 I can't reproduce it. Something else is going on... I checked what you mentioned and you're  right we do: `redirectTo = options.getDefaultUrl();`. But after that we also do:

```
    redirectTo = ctx.getRequestURL(redirectTo);
```

The `ctx.getRequestURL` generates an entire URL with contextPath (if any).

**Comment by moromindful** [comment]
Sorry for the late reply. In the mean time as a workaround I used the routes() with full paths:

`
routes(() -> {

      get("/client/login", ctx -> new ModelAndView("client/login.peb").put("error", ctx.query("error").valueOrNull()));

      decorator(new TransactionalRequest());

      Pac4jOptions clientWebAuthOptions = new Pac4jOptions();
      clientWebAuthOptions.setCallbackPath("/client/auth");
      clientWebAuthOptions.setDefaultUrl("/client/dashboard");
      clientWebAuthOptions.setDefaultClient("web");
      clientWebAuthOptions.setLogoutPath("/client/logout");
      Config clientWebAuthConfig = new Config();
      install(new Pac4jModule(clientWebAuthOptions, clientWebAuthConfig)
        .client("/client/*", conf -> {
          FormClient clientFormClient = new FormClient("/client/login", (Credentials credentials, WebContext ctx) -> {
            ClientAuthenticator authenticator = require(ClientAuthenticator.class);
            if (credentials instanceof UsernamePasswordCredentials) {
              authenticator.validate((UsernamePasswordCredentials)credentials, ctx);
            }
          });
          clientFormClient.setName("web");
          clientFormClient.setUsernameParameter("email");
          clientFormClient.setPasswordParameter("password");    
          clientFormClient.setCallbackUrlResolver(new NoParameterCallbackUrlResolver());
          return clientFormClient;
        })  
      );

      get("/client/dashboard", ctx -> new ModelAndView("client/dashboard.peb"));

    });

`

And it works accordingly, while the code that i started this issue still does the same thing. on logout it doesn't redirect me to /client/dashboard but to /dashboard. Just like the path pattern is ignored.

**Comment by moromindful** [comment]
So after a little more debugging i found that if I don't set the DefaultUrl (  clientWebAuthOptions.setDefaultUrl("/dashboard"); ) it works as is being handled by Pac4jModule:
`
    if (options.getDefaultUrl() == null) {
      int index = application.getRoutes().size();
      application.onStarted(() -> {
        List<Route> routes = application.getRoutes();
        String defaultUrl = application.getContextPath();
        if (index < routes.size()) {
          Route route = routes.get(index);
          if (route.getPathKeys().isEmpty()) {
            defaultUrl = contextPath + route.getPattern();
          }
        }
        options.setDefaultUrl(defaultUrl);
      });
    }
`
otherwise if i set/override it it doesn't get the contextpath "/client" only when it redirects from logout.

**Comment by jknack** [comment]
Ok, so I think missed something from your first comment:

```java
path("/client", () -> {
   ...
}):
```

That isn't necessarily the application context path. It is just syntax sugar for prefixing everything with `/client`. If you want to keep like this, then your default url must be set explicitly to `/client/dashboard`:

```java
path("/client", () -> {

  get("/login", ctx -> new ModelAndView("client/login.peb").put("error", ctx.query("error").valueOrNull()));

  decorator(new TransactionalRequest());

  Pac4jOptions clientWebAuthOptions = new Pac4jOptions();
  clientWebAuthOptions.setCallbackPath("/client/auth");
  clientWebAuthOptions.setDefaultUrl("/client/dashboard");
  clientWebAuthOptions.setDefaultClient("web");
  Config clientWebAuthConfig = new Config();
  install(new Pac4jModule(clientWebAuthOptions, clientWebAuthConfig)
    .client(conf -> {
      FormClient clientFormClient = new FormClient("/client/login", (Credentials credentials, WebContext ctx) -> {
        ClientAuthenticator authenticator = require(ClientAuthenticator.class);
        if (credentials instanceof UsernamePasswordCredentials) {
          authenticator.validate((UsernamePasswordCredentials)credentials, ctx);
        }
      });
      clientFormClient.setName("web");
      clientFormClient.setUsernameParameter("email");
      clientFormClient.setPasswordParameter("password");    
      clientFormClient.setCallbackUrlResolver(new NoParameterCallbackUrlResolver());
      return clientFormClient;
    })  
  );

  get("/dashboard", ctx -> new ModelAndView("client/dashboard.peb"));

});
```

Alternative here is the same setup with a truly context path:

```java
setContextPath("/client");

get("/login", ctx -> new ModelAndView("client/login.peb").put("error", ctx.query("error").valueOrNull()));

  decorator(new TransactionalRequest());

  Pac4jOptions clientWebAuthOptions = new Pac4jOptions();
  clientWebAuthOptions.setCallbackPath("/auth");
  clientWebAuthOptions.setDefaultUrl("/dashboard");
  clientWebAuthOptions.setDefaultClient("web");
  Config clientWebAuthConfig = new Config();
  install(new Pac4jModule(clientWebAuthOptions, clientWebAuthConfig)
    .client(conf -> {
      FormClient clientFormClient = new FormClient("/login", (Credentials credentials, WebContext ctx) -> {
        ClientAuthenticator authenticator = require(ClientAuthenticator.class);
        if (credentials instanceof UsernamePasswordCredentials) {
          authenticator.validate((UsernamePasswordCredentials)credentials, ctx);
        }
      });
      clientFormClient.setName("web");
      clientFormClient.setUsernameParameter("email");
      clientFormClient.setPasswordParameter("password");    
      clientFormClient.setCallbackUrlResolver(new NoParameterCallbackUrlResolver());
      return clientFormClient;
    })  
  );

  get("/dashboard", ctx -> new ModelAndView("client/dashboard.peb"));
```

Does it make sense? Pac4j is an external library doesn't know anything about a path prefix (your submitted example). That's why if you add it one, you must indicates pac4j the correct path.

A path prefix isn't the same as application context path (second example).

Hope it makes sense

**Comment by moromindful** [comment]
I get the idea the problem is if I go with the path prefix then I need to set the default url to `clientWebAuthOptions.setDefaultUrl("/client/dashboard");` but the callback path I need to set it to /auth not /client/auth because if I do that it will create a /client/client/auth, this is also available with logout path. So this is more than a consistency issue because inside a path prefix "/client", I need to set the callbackpath /auth, logout path /logout but the default url to /client/dashboard. So this issue is turning more into a wish :) Inside a path prefix in pac4j we should be able to have consistency like all the pac4j path and url methods to begin with the prefix itself or without, not a mix of them.

**Comment by jknack** [comment]
The `/auth` callback works differently and it is tied to a route (here jooby knows how to apply the path prefix).

This is not the case for any other use case (like saving a string and later use it for redirect). If you look closely you are doing the same in your form client: `new FormClient("/client/login")`. It is the same use case.

Here is an alternative example that using the default url strategy:

```java
path("/client", () -> {
      get("/login", ctx -> ...);

      Pac4jOptions clientWebAuthOptions = new Pac4jOptions();
      clientWebAuthOptions.setCallbackPath("/auth");

      install(new Pac4jModule(clientWebAuthOptions)
          .client(conf -> new FormClient("/client/login", authenticator()))
      );

      get("/dashboard", ctx -> new ModelAndView("welcome.hbs")
          .put("user", ctx.getUser())
      );
    });
```

This example will redirect you to `/client/dashboard` on logout. So you have two options:

- explicit set the default url to a valid path
- use defaults
