### ISSUE TITLE
ebean module

### ISSUE THREAD

**Issue by jknack** [jooby-project/jooby#182]
```java
{
   use(new Ebeanby(P));
}
```
see http://www.avaje.org/

**Comment by noboomu** [comment]
I built a working version (though it could use a lot of work), what's the best way to get it to you? Also, check the docs on http://ebean-orm.github.io/ since ajave.org is years out of date I think.

**Comment by jknack** [comment]
thanks, I realize that after a while!

send a pull request, can you? I will merge what you did + mine version of ebean.

what about akka? did you built something?

**Comment by noboomu** [comment]
It was a completely separate project so I just created a repo that should be a good starting point: https://github.com/noboomu/jooby-ebean. Working on akka next :)

**Comment by jknack** [comment]
cool, it is similar to what I did (will push it later today), except for:

1. my module extends Jdbc module, which give us HikariDS
2. it does some black magic in order to detect and run the enhancement at runtime (but build-time enhancement is also supported)

Akka: can you file an issue? Also, have no experience with Akka, so I will wait for your contribution and start from there.

Thanks

**Comment by jknack** [comment]
0.10.0 out: http://jooby.org/doc/ebean/
