### ISSUE TITLE
Since 2.8.7, #1737 issue is back, Once logged out, "ERR_TOO_MANY_REDIRECTS" is returned when trying any page.

### ISSUE THREAD

**Issue by Sayyiditow** [jooby-project/jooby#1822]
2.8.7 breaks pac4j module. Once logged out, you cannot visit any page, protected or unprotected. This is related to #1737 I presume.

**Comment by jknack** [comment]
Hi,

 There is an integration test for #1737 and today it still work (no regression). The `2.8.7` was a quick release to fix the Guice integration module. Then `2.8.8` comes with a pac4j upgrade (4.0.2 to 4.0.3),  but not changes in jooby integration
 
 Please try again make sure you don't have stale data (session). If problem persist please add a working example to reproduce it.

Thanks.

**Comment by jknack** [comment]
Another thing to check is your project dependencies and make sure all them are set to same Jooby version (2.8.8) and you don't have multiple versions of it.

**Comment by Sayyiditow** [comment]
Hi,

All dependencies are using 2.8.8 as this is a variable in my pom.xml. I have seen that this is related to the pac4j module as without it, the app works fine. The moment I remove the line:

`install(new Pac4jModule().client("/dashboard*", config -> new FormClient("/login", userAuthenticatorService)));`

The app works, but if I install the module, the error comes back. Is it the redirect sending to the /login page which is causing this? The issue does not seem to be related with the sessionStore or csrfHandler as with/without them, the error still persists.
I think there are too many redirects the the loginUrl (/login) which is related to the FormClient. When visiting any url, it tries to redirect to /login for some reason.

As for a working example, here is what I have in my main class:
```
        assets("/static/*", Paths.get(EnvironmentBuilder.RESOURCES + "static/"));

        install(new FreemarkerModule());

        *CSRF handler*/
        before(new CsrfHandler());

        /*7 Day Session*/
        setSessionStore(SessionStore.signed((sessionStore), new Cookie("Sayyiditow-Tech").setMaxAge(Duration.ofDays(30))));

        /*Pac4j Login module*/
        install(new Pac4jModule(UserRepositoryService.getPac4jOptions()).client("/dashboard*", config -> new FormClient("/login", 
        userAuthenticatorService)));
```

After this its the usual scripts paths.

**Comment by jknack** [comment]
Where is the login form in your example? You are missing something. The example as is not valid:

- There is no login form. Your form client says path is: `/login`
- You set callback path to `/login`. The pac4j module adds `GET` and `POST` at that path: `/login`.

Correct example looks like:

```
  get("/login", this is the login form with free access)

  install(pac4j with form client saying the form is at `/login` path)
```

If you tell pac4j callback url is also at `/login` the router algorithm overrides the `get /login` route with login form with the new callback handler (there is path collision).

This has been like this since first Jooby release (last route definition overrides any previous), so I doubt this worked before and that is the reason why I think you are missing something in your example.

Anyway, don't use `/login` as callback path

**Comment by Sayyiditow** [comment]
Nope, it is not missing. I just forgot to include it. Here is the get request to the login form.

```
get("/login", ctx -> {       
            return new ModelAndView("login.ftl");;
        });
```

I don't think the path has any issues. I have tried to change the path completely. Still did not work.

`pac4jOptions.setCallbackPath("/login-api");`

Login form:

```
<form action="/login-api?client_name=FormClient" method="post" id="loginForm">
                        <input type="hidden" id="csrf" value="${csrf}" name="csrf"/>
                        <h5 class="text-center">Login</h5>
                        <div class="inputBox text-center row">
                            <label for="username" class="text-center">Email</label>
                            <input type="email" name="username" id="username"
                                   class="six columns offset-by-three text-center"
                                   required
                                   placeholder="Your Email" title="Valid Email">
                        </div>
                        <br>
                        <div class="inputBox text-center row">
                            <label for="password" class="text-center">Password</label>
                            <input type="password" name="password" id="password"
                                   class="six columns offset-by-three text-center"
                                   required
                                   placeholder="Your Password">
                        </div>
    <div class="text-center">
        <br>
        <input type="submit" class="button-primary submitButton" value="Submit"/>
        <div class="loader display-none"></div>
        <br><br>
        <span class="formReplyMessage"></span>
    </div>                      
                    </form>
```

![image](https://user-images.githubusercontent.com/13337779/86307156-a4fe0700-bc48-11ea-8051-96dac0dc4b7b.png)

**Comment by jknack** [comment]
You're right. Finally found it. It is side a effect of #1831 

It was not directly related to pac4j

**Comment by Sayyiditow** [comment]
Thank you!

**Comment by jknack** [comment]
jooby 2.8.9 is out. Sorry for the inconvenience
