### ISSUE TITLE
List query param always contains a null value

### ISSUE THREAD

**Issue by csisy** [jooby-project/jooby#1839]
Jooby version: 2.8.1

We have a class in a controller that groups the query params together. It works nice with single values, however, collections always contain a single null value if the specific query param is empty/missing. Example:

```
public static class SomeFilter {

    // ...
    private final List<Integer> aList;

    public SomeFilter(
        // ...
        @Named("aList") List<Integer> aList,
    ) {
        // ...
        this.aList = aList;
    }
}

@GET
public <whatever> list(Context context) {
    final var filter = context.query(SomeFilter.class);
}

// ?aList=10          --> filter.aList = [10]
// ?aList=10&aList=20 --> filter.aList = [10, 20]
// ?                  --> filter.aList = [null] --> should be null or []

```

A workaround for this is to filter the result by hand:

`final var realList = filter.getAList().stream().filter(Objects::nonNull).collect(Collectors.toList());`

Can you please confirm that it is a bug, or are we doing something wrong?

**Comment by walkman90** [comment]
FYI #1806

**Comment by csisy** [comment]
> FYI #1806

Thanks, I was not aware about that issue.
