### ISSUE TITLE
Hotreload status

### ISSUE THREAD

**Issue by paulovictorv** [jooby-project/jooby#185]
Hello, I've been noticing that the hotreload feature doesn't seem to work. 

How is it suppose to work? Auto detect .java files notifications and recompile?

Thanks

**Comment by jknack** [comment]
instructions are here: http://jooby.org/doc/maven-plugin/

for the time being... the plugin detects changes in .class you need a compiler (like an IDE)

**Comment by paulovictorv** [comment]
Ok, got it!
