### ISSUE TITLE
Possible support for incremental annotation processing with Gradle (2.x)

### ISSUE THREAD

**Issue by imeszaros** [jooby-project/jooby#1860]
Gradle supports incremental compilation _and_ incremental annotation processing. The prerequisite is that an annotation processor must report whether it's compatible with incremental processing or not. If an annotation processor is not compatible, or does not report that it is, when one annotated source file is changed, the __whole project__ must be recompiled. This is especially annoying if building in the IDE is delegated to the build tool (by default now in IDEA).

According to [the Gradle documentation](https://docs.gradle.org/4.7/userguide/java_plugin.html#_making_an_annotation_processor_incremental) processors can be categorized as __isolationg__ or __aggregating__ processors. After a brief look on the source code, my assumption is that `jooby-apt` could be an isolating processor. However, there are two requirements which currently arent met by `jooby-apt`:

- Can’t write resources
- Must provide exactly one originating element for each file generated with the Filer API

The first one is because the processor creates a service descriptor file used to load the MVC factories at runtime. My question would be here that what advantages come with using a service loader instead of instantiating with reflection? MVC extensions are installed at bootstrapping, so I guess it only could affect the startup performance?

The second thing should be easy to fix, the controller class could be provided as originating element for each generated module.

**Comment by imeszaros** [comment]
I made a quick test by changing the annotation processor to provide the originating element and the Gradle metadata, and disabled the service descriptor generation:

https://github.com/imeszaros/jooby/commit/28f53bc77fa79095da414d371aea022f3b208189

After this I tested the compilation with this small example project:

https://github.com/imeszaros/jooby-apt-incremental

And it looks like it's working properly, Module class only for the changed controller is regenerated.

The only questions what could be done about the service descriptions?

**Comment by jknack** [comment]
It looks good. 

>  My question would be here that what advantages come with using a service loader instead of instantiating with reflection? MVC extensions are installed at bootstrapping, so I guess it only could affect the startup performance?

The APT for mvc was created for removing reflection entirely. The performance thing is just a bit here (doubt there is a huge difference between ServiceLoader and reflection). Still, we did it with ServiceLoader bc it is supported by GraalVM.

Anyway, for development there is a reflection fallback that helps IDE to pick a MVC extension when the services loader isn't ready.

Fallback: https://github.com/jooby-project/jooby/blob/2.x/jooby/src/main/java/io/jooby/Jooby.java#L323
Implementation: https://github.com/jooby-project/jooby/blob/2.x/jooby/src/main/java/io/jooby/Jooby.java#L1125

Make sure your changes work as expected and please send a PR.
