### ISSUE TITLE
jooby-apt and Lombok processing

### ISSUE THREAD

**Issue by walkman90** [jooby-project/jooby#1866]
[Lombok](https://projectlombok.org/) is a well-known and widely used project which is served to eliminate a lot of java boilerplate code.

As you probably know `Lombok` does its stuff at build time thus its code doesn't need at runtime. 
I believe it is a common approach to remove it from uber jar. And usually, it works great(with jooby1 also) but
`jooby-apt` generate sources which reference some `Lombok` classes directly.

For example for the code:

```java
import io.jooby.annotations.GET;
import io.jooby.annotations.Path;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import javax.inject.Inject;

@Path("/")
@RequiredArgsConstructor(onConstructor = @__(@Inject))
public class PetsController {

  private final @NonNull PetsService petsService;

  @GET
  @Path("/ping")
  public String ping() {
    petsService.ping();
    return "Welcome to Jooby!";
  }
}
```

Next lines will be generated by the jooby-apt

```java
        var2.attribute("RequiredArgsConstructor.staticName", "");
        var2.attribute("RequiredArgsConstructor.access", AccessLevel.PUBLIC);
```
 so if we remove Lombok jar from uber jar we will catch

`Caused by: java.lang.ClassNotFoundException: lombok.AccessLevel`

Don't know if there is any good solution for this, but at least should be known.
Maybe we can add some configuration to `jooby-apt`, to mark annotations(packages) which `jooby-apt` should ignore.

**Comment by imeszaros** [comment]
Since I was in the flow with jooby-apt, I created a possible solution but it builds on some of the changes within #1861.

You can pass a comma separated list of annotation or package names to `jooby.skipAttributeAnnotations`: https://github.com/imeszaros/jooby/commit/6be2dea354cdd2f10a41937d4ac09c6e4dd1bb0d

Let me know if it's useful and I'll create a PR.

**Comment by jknack** [comment]
@imeszaros Ideally we should check for current usage of annotation and in addition to a skip list, we should check if the annotation has a non-runtime retention and ignore them (not sure if possible)

**Comment by imeszaros** [comment]
I added filtering on the retention policy, had to modify the tests though to pass it: https://github.com/imeszaros/jooby/commit/13c605d739410de9296f06ae94804bab0970feca

What do you mean by
>we should check for current usage of annotation

?

**Comment by jknack** [comment]
> What do you mean by

Bad English I guess 😄

Your code looks good, waiting for a PR. Can you add test case with non-runtime annotation?
