### ISSUE TITLE
advanced routing (like play .lift)

### ISSUE THREAD

**Issue by kinocz** [jooby-project/jooby#187]
I like how jooby is working with routes, chain, excludes and so on, but...
lets say I have some router logic based on Object(lets say on http hostname), which defines how routes should be treated. For example I need to serve different content under "/" and even the routes stack is different. where somewhere I have "/a/" but on other ones I dont.
In Play there are many routes and I can call lift on them. for example:
https://jazzy.id.au/2013/05/08/advanced_routing_in_play_framework.html
is something like this possible in jooby? I'm asking about n (two or more) sets of routes and then call on them something like play has (lift)?

**Comment by jknack** [comment]
isn't possible today... excludes can give you something but not everything.

I read the blog from play, but that looks very complex to me... and seems you have experience with that, right? It will be great if you can help me to define an API to do the same in Jooby but easily :)

**Comment by kinocz** [comment]
Excludes are nice, but not such powerful. I see use case where you have multiple projects (admin, frontend, endpoints for mobile devices and so on), which are normally stand alone - each runs in separate JVM, but someone decides that all them should run under one JVM - small client with not enough money for big infrastructure. And here comes the problem with lifting routes - each module/project compiled into one comes with own routes and main project deciding which routes it should use. Merging them together with excludes or some kind of logic in controller and then call chain next might work, but it is not so nice.

I'm asking because in one company I work with, we have a lot of projects and want to use same stack over all of them so it is easy to migrate programmers from one to another. In one project we need to have something as I described above.

If the company decided that Jooby is fine for try, it might give it a little boost for development to implement some missing features and still KISS. Play is a bit of pain in the ass lately. We have spent a lot of time trying to do stuff in play which in Jobby would be piece of cake.

Anyway I like Jooby as person and for simple prototyping. Still I might help with some stuff, but would not be much, because I don't know what to do first. But if at least one of the projects I'm interested in takes Jooby as part of the stack I might have more time to improve Jooby.

**Comment by jknack** [comment]
I see it! next release: ```0.10.0``` comes with #180, which basically let you reuse routes defined in another app.

#180 let you mount a whole app in one path:

```java
public class Admin extends Jooby {
  {
    ...
  }
}

public class Frontend extends Jooby {
  {
    ...
  }
}

...

public class App extends Jooby {
  {
    use("/admin", new Admin());
    use("/frontend", new Frontend());
  }
}
```

Is that enough?

**Comment by kinocz** [comment]
seen this one, it only chains them, which for is fine for some use cases, but not enough as play has and we are using.

Based on hostname we serve totally diferent content. For example admin.foo.com serves on "/" something different than www.foo.com. Even there is different logic how to use it.

```java
public class App extends Jooby {
  {
    use("adminRoutes", new Admin());
    use("frontendRoutes", new Frontend());

   onRequest((req,res) -> {
      if (foo) {
         routes.get("adminRoutes").lift(req, res);
      } else {
         routes.get("frontendRoutes").lift(req, res);
      }
   });
  }
```

play only lifts with request, because of it's scala magic.

**Comment by jknack** [comment]
got it! I will add it!

**Comment by jknack** [comment]
resolved using .name and a new chain.next method, like:

```java
{
   use("*", (req, rsp, chain) -> {
     if (...) {
       chain.next("/admin", req, rsp);
     } else {
       chain.next("/normal", req, rsp);
     }
   });

   get("/", () -> "Hello admin").name("admin");

   get("/", () -> "Hello user").name("normal");
}
```

**Comment by jknack** [comment]
out 0.10.0: http://jooby.org/doc/#dynamic-advanced-routing

**Comment by kinocz** [comment]
great thx

**Comment by jknack** [comment]
did you try it? let me know how it goes
