### ISSUE TITLE
[Jooby 2] StackOverflowError when OS has a lot of environment variables

### ISSUE THREAD

**Issue by extbe** [jooby-project/jooby#1881]
Hi! 

This issue is related to Lightbend Config. I've described it here: https://github.com/lightbend/config/issues/700

Jooby 2 is affected because `ConfigFactory.systemEnvironment()` is used while creating application config: [Environment#loadEnvironment](https://github.com/jooby-project/jooby/blob/e8710285c2d2eecab53098aa5d3909cefb7587fb/jooby/src/main/java/io/jooby/Environment.java#L291)

**Comment by jknack** [comment]
Odd. We will have to wait for a fix. Alternative you can create a custom environment and skip the systemEnv while creating your own config (not. sure if that works for you). Probably use a sub-set of systemEnv

**Comment by extbe** [comment]
New 1.4.1 version of Config library released. It includes a fix for this bug. Could you add the new version to Jooby 2.9.2?

**Comment by jknack** [comment]
sure yea.
