### ISSUE TITLE
How to unit test with MockRouter with modules?

### ISSUE THREAD

**Issue by lawkai** [jooby-project/jooby#1891]
Hi, I have a simple Jooby Application that relies on Hikari Module to create a connection to a Datasource. 
Is it possible to unit test Application with a MockRouter? 
```kotlin
val router = MockRouter(App())
```

```kotlin
class App: Kooby({
    install(HikariModule())
    get("/") { ctx ->
         val ds = ctx.require(DataSource::class)
    }
})
```
will fail to start as the Hikari is trying to load/connect to the configured datasource defined in application.conf. I can use test container to start a database before the unit test start but I am not sure how I can override the connection setting using MockRouter(App()) when it starts? What is the proper and recommended way to unit test Jooby application that requires a database? Any help would be appreciated. Thanks!

**Comment by jknack** [comment]
Hi,

 MockRouter is for doing unit tests. A datasource won't be available while doing unit tests. What do you need to do is to choose a mocking library to provide a DataSource. Here is a Mockito example:

```java
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

public class TestApp {

  @Test
  public void test() {
    DataSource ds = mock(DataSource.class);

    Context context = mock(Context.class);
    when(context.require(DataSource.class)).thenReturn(ds);

    MockRouter router = new MockRouter(new App());

    assertEquals(..., router.get("/", context).value());
  }
}
```
