### ISSUE TITLE
Question: ActiveJ Server

### ISSUE THREAD

**Issue by a1730** [jooby-project/jooby#1892]
Thank you for the Jooby project. We have found it to be an excellent lightweight REST server.
We liked the jooby-netty server, but, future-proofing netty makes us nervous. Their public api changes too much for our taste, and it changes in non-backward conforming ways (this was our experience in the past). Undertow would have been nice but they are moving to netty:( Jetty? We'd rather be programming servlets.

So, we found [ActiveJ](https://github.com/activej/activej) but wondered if you have looked at it, and what suggestions do you have for us to implement a actvej-server in the spirit of jooby-netty. Is there a server api that we should implement? We looked but it looks like no-cigar.

**Comment by jknack** [comment]
Agreed with your comment around Netty. I do prefer undertow for simplicity and performance.

Implementing a new Server is not an easy task due to complexity but also there is no real documentation on how to do it.

A quick look at ActiveJ seems it is a lot more than a web server implementation. Also, do they run on top of vert.x? Vert.x is Netty!!!

Vert.x looks is a better fit for a Jooby web server.

**Comment by sirinath** [comment]
ActiveJ is faster than Vert.x

**Comment by jknack** [comment]
Yea probably not the best test name... but most of the features are here: https://github.com/jooby-project/jooby/blob/e3004775d092df1139b4678eb5a5a89cbe7ebce0/tests/src/test/java/io/jooby/FeaturedTest.java

While test support (code that run an app against servers) is here: https://github.com/jooby-project/jooby/tree/e3004775d092df1139b4678eb5a5a89cbe7ebce0/tests/src/test/java/io/jooby/junit

**Comment by a1730** [comment]
Thanks for the pointer, @jknack.

**Comment by a1730** [comment]
In summary, 
We decided to enrich the current Jetty server rather than create an ActiveJ server.
1. We needed a responsive websocket/sse server these are not available with ActiveJ and are easily added to Jooby version 2 Jetty server. We looked at socket.io, sockjs but decided against them. We are staying with web standards.
2. We will use standards compliant websocket. We have good experience with Redis, we will enrich the ws client-server dialog with Redis RESP if needed. We try to avoid any dependency on Netty.
3. ActiveJ does not support HTTP/2 nor haproxy protocol. These are **required** technologies for us.
4. There is no Server API on the Jooby side for us to validate our implementation. We would essentially be shooting in the dark and chasing our tail with every release of Jooby, and we will essentially be on our own.

Jooby is a joy to develop against. @jknack Thank you for a fantastic project.

**Comment by jknack** [comment]
It is a good decision. Sometime ago someone asked for rapidoid backend, something similar happened. In general we need to look for stable, fully compliant web server with a large active community. I believe ActiveJ is still young we can look at adding it in couple of years if still a need.

**Comment by sirinath** [comment]
@a1730 Maybe you can ask the ActiveJ what features you require which are missing. If many request them then there might be a chance these features get prioritised.

**Comment by a1730** [comment]
I did. We are keeping an eye on both projects - Jooby and ActiveJ.
I spied that someone is looking at implementing websockets but it will take some time to mature. There is still no support for sse, HTTP2 (specifically h2c), haproxy protocol - we have proxies that depend on this, and other minor concerns


 On Tuesday, August 25, 2020, 03:53:13 PM UTC, Suminda Sirinath Salpitikorala Dharmasena <notifications@github.com> wrote:
@a1730 Maybe you can ask the ActiveJ what features you require which are missing. If many request them then there might be a chance these features get prioritised.

**Comment by sirinath** [comment]
ActiveJ now has WebSocket support and [SSE support](https://gist.github.com/eduard-vasinskyi/65287c900a70288a1b298a9027b26ca5).

**Comment by a1730** [comment]
Thank you @sirinath , we are already using a modified version of the code in some ways.

**Comment by a1730** [comment]
> A quick look at ActiveJ seems it is a lot more than a web server implementation. Also, do they run on top of vert.x? Vert.x is Netty!!!

FYI, ActiveJ has nothing to do with Vert.x nor Netty. Using the code, and quoting from their [web site](https://activej.io/net.html)  

> Handy and efficient alternative to Netty, Apache Mina, and other similar solutions for high performance networking.

**Comment by jknack** [comment]
I'm not planning to support ActiveJ for the reasons I explained before. Please, let's keep this issue closed.

Thanks.

**Comment by a1730** [comment]
Oops, 
The intention was to inform you that ActiveJ has nothing to do with Vert.x nor Netty and not to ask for ActiveJ support but my Github-fu is not that great. My apologies if I was not clear.
Agreed that it should remain closed - Please leave it closed.
