### ISSUE TITLE
Pac4jModule doesnt work correctly when Jooby.lateInit flag is activated.

### ISSUE THREAD

**Issue by Inzagher** [jooby-project/jooby#1908]
I've tried to init Pac4jModule using Guice as DI framework.
```
new Pac4jModule()
    .client("/api/auth/*", (config) -> require(DirectFormClient.class))
    .client("/api/other/*", (config) -> require(CookieClient.class));
```
When jooby.lateInit flag is deactivated, DI framework can't resolve required dependencies. Then i activate flag, DI work perfectly, but DirectFormClient does not handle any request.
The same behaviour we can see in pac4j-starter application when lateInit is activated. Fallback to login url doesn't work.

**Comment by Inzagher** [comment]
Any thoughts?

**Comment by jknack** [comment]
don't think there is a simply solution to this. Pac4j requires these clients at application startup time and at that time DI isn't ready. This is the issue to resolve.

LateInit was added mostly for unit testing purpose.

**Comment by Inzagher** [comment]
Thanks for the feedback. I suppose that it needs to play a lot!

**Comment by jknack** [comment]
we probably need to add new signature and delay initialization after startup.

```
new Pac4jModule()
    .client("/api/auth/*", DirectFormClient.class)
```

**Comment by imeszaros** [comment]
Could that be that the problem is that when `lateinit` is activated the security filter decorator is not added in the right order to the pipeline?

Maybe there should be an `eagerInstall()` method in extensions to install the filter and do the rest of the initialization at startup.

**Comment by jknack** [comment]
It is unrelated to `lateinit`.

what we need to do is something like:

- add a method signature that support a class as client: `client(Class, ...)`. we have to day a `client(Function<Config, Client>)`
- if there are any client as class... we initialize them once application started and register them as pac4j clients

This is very similar to what you did in Metrics module (use a class and initialize them once Guice/DI is ready)

**Comment by Inzagher** [comment]
Thanks a lot!
