### ISSUE TITLE
Allow automatic redirects to https if running behind proxy

### ISSUE THREAD

**Issue by paulovictorv** [jooby-project/jooby#191]
The industry default today is to have the application running behind some sort of proxy, be it nginx or a load balancer such as ELB or the likes of Heroku.

For those applications, it would be nice to allow an easy way to redirect to HTTPS by flipping a switch, always depending on the running environment.

As an example:

`` redirect_https=true `` on a config file, and so on.

**Comment by jknack** [comment]
done, but via a String property with one placeholder: ```{0}``` for current path.

example:

```properties
application.redirect_https="https://my.domain.com/{0}"
```
