### ISSUE TITLE
MockRouter does not support MVC Coroutines

### ISSUE THREAD

**Issue by cojo** [jooby-project/jooby#1917]
It seems like the CoroutineRouter might make a few different assumptions around not using the MVC mode in general, but the main one blocking us at the moment is the MockRouter not working properly.

I see this commit fixed this for the other mode by setting a new attribute: https://github.com/jooby-project/jooby/commit/8ed3364810a811844095fdf4182ecbf7b81d8c05

But it appears it wasn't implemented for the MVC side of things - am I understanding that correctly?

Thanks!

**Comment by jknack** [comment]
yea, you're right. The reason is that MVC router is just a plain Java Class, so you are free to write unit test against them easily.

Opposite to script routes where is not possible to access to a route handler easily. This is the reason of why MockRouter exists.

**Comment by cojo** [comment]
Got it - makes sense / I can see not wanting to have MVC users use MockRouter.

I think my confusion was because the Unit Test was also automatically generated by jooby CLI using MockRouter even though I chose MVC, so I thought it was intended to still be used for other less obvious reasons.  Perhaps it might be worth excluding that test autogeneration for MVC projects if they are not intended to go together?

Thanks for the quick response! Feel free to close this if no action is desired / needed (if this is as-intended on CLI as well).

**Comment by jknack** [comment]
Going to remove the tests. That is a good suggestion. Let's keep it open so I remember my self to do it.

Thank you for using my product.
