### ISSUE TITLE
asset module

### ISSUE THREAD

**Issue by jknack** [jooby-project/jooby#192]
next version will comes with an asset module (similar to grails/rails asset pipeline)

```java
{
  use(
     new Assets()
       .on("dev", () -> Arrays.asList(new Replacer(), new JsHint(), new Sass()))
       .on("*", () -> Arrays.asList(new Replacer(), new Concat(), new Sass(), new Uglify()))
     );
}
```

In dev, processors run at runtime, otherwise at build time via maven plugin.

Asset descriptor will look like:

```properties
filesets {
  base: [lib/jquery.js, css/normalize.css]

  home {
    src: [js/home.js, css/home.css]
    ext: [base]
  }
}
```

Where ```home``` is the name of the view that requires these assets:

```html
<html>
<head>
{{home.css}}
</head>
<body>
{{home.js}}
</body>
</html>
```

```{{home.css}}``` and ```{{home.js}}``` on ```dev``` will be expanded to each of the files defined in the asset descriptor.  on ```prod```  to just one line with the bundled/minified version.

@paulovictorv I know you have preference for node.js/grunt/... but I would love to get your feedback here for a Java solution.

**Comment by paulovictorv** [comment]
This looks promising, actually.

I only have a preference for node/gulp because of the plugin ecosystem. Is there an easy way to invoke, lets say, ``gulp-ng-annotate`` (or its grunt counterpart) plugin from Java? I'm not familiar with Nashorn, is it able to do such a thing?

If this is a possibility, I would rather prefer to use a pure Java solution instead of a node based one: the least stuff I have to install and configure on my developers machines, the least moving parts I get, which hopefully means less trouble.

**Comment by jknack** [comment]
I'm not sure, is there a browser version of ng-annotate?

**Comment by paulovictorv** [comment]
Not really, it's not supposed to be used on the browser..

If we get a compiled form of the ng-annote (with all its dependencies), can Nashorn run it?

If it works, we can start releasing ``jooby-ng-annotate`` sort of modules, that encapsulates the plugin within Jooby's pipeline.

**Comment by jknack** [comment]
I run browserify over ng-annotate, this give me a single bundle with all the dependencies.

the browserify version of ng-annotate seems to work OK in Nashorn.

**Comment by paulovictorv** [comment]
That's indeed promising.

**Comment by davydotcom** [comment]
You could just implement `asset-pipeline-core` and get all the features of the asset-pipeline and their extension modules in one shot ;) for an example of implementation look at the (ratpack-asset-pipeline)[https://github.com/bertramdev/ratpack-asset-pipeline]

**Comment by jknack** [comment]
@davydotcom  didn't know that was possible!! will have a look... one concern I have is the use of: Rhino. Jooby is targeted Java 8+, so we can safely depends/use nashorn.

**Comment by davydotcom** [comment]
Nashorn is actually 3x slower than rhino on cold start compiling. Also we are not using Rhino like you think we are. it is being used by the Closure Minifier library solely for its AST Tree. It is not using the actual runtime. But all extension libraries including say coffee and handlebars still use Rhino. @craigburke can attest to this as He tried to move his angular ones to Nashorn and found it to be 3 times slower on cold start compile which is what is commonly needed during a build phase. Nashorn is actually not great in this area.

**Comment by jknack** [comment]
yea, cold start is a good point for build solution, but think for development Nashorn works better than Rhino (runtime solution).

Beside I did some progress on this.. will play with asset-pipeline and see how it integrates in Jooby. Asset-pipeline has an active community, nice plugins and has been tested.

**Comment by davydotcom** [comment]
It is on the road map don’t get me wrong but its just not there yet. once rhino JIT warms up its plenty fast enough too and the core cache helps but nashorn is highly desirable for that

**Comment by craigburke** [comment]
@jknack I'm still looking at Nashorn, but yeah that's been my experience so far. If you manage to make some make some headway on this I'd be extremely interested in that. 

I've extracted all the JS related asset pipeline stuff for my modules to a separate project and I'd love to use Nashorn there if the performance can be helped:
https://github.com/craigburke/javascript-core-asset-pipeline

I think @davydotcom is right on this though, Nashorn just doesn't seem well suited for the asset pipeline right now. I could be wrong about that though (and would love to be proven wrong).

**Comment by jknack** [comment]
I found Nashorn more slow than I thought. For example jshint with a source like:
```js
x = 1;
```
took 500-700ms (warm).

I have lessjs, jshint, uglifyjs2 and ng-annotate working with Nashorn. All them are around 500/700ms (warm).

is groovy/grails a hard dependency for asset-pipeline? or is it optional? want to keep dependencies to minimum.

**Comment by davydotcom** [comment]
Grails of course not. Groovy yes at least for development mode. Technically the core libs aren’t really used in production mode just at build and development. So you can actually exclude most of those in your production build.

**Comment by jknack** [comment]
It is done. documentation is here: https://github.com/jooby-project/jooby/tree/master/md/doc/assets and here: https://github.com/jooby-project/jooby/blob/master/md/asset-processor.md

I moved away from nashorn! and give it a try to: https://github.com/eclipsesource/J2V8

will release in a few days (next week probably) but if you can have a look at the commit and provide feedback, I will appreciate very much!

**Comment by jknack** [comment]
release it: http://jooby.org/doc/assets/

give it a try and let me know how it goes
