### ISSUE TITLE
TransactionalRequest will make all router slower 10x，can it filter by attribute(@transactional)?

### ISSUE THREAD

**Issue by kindywu** [jooby-project/jooby#1920]
TransactionalRequest make all router slower，can it filter by attribute(@transactional)

example:decorator(new TransactionalRequest("transactional"));

**Comment by jknack** [comment]
we could try to add something like that. but most application I wrote what I do is to put transactional where I know all the routes behind it are transactional:

```java

{
   // non transactional
   assets("...")
   ...

   // transactional
  decorator(new TransactionalRequest());

  ....
}
```

**Comment by imeszaros** [comment]
Nobody misses the good old `UnitOfWork` concept? :) Our team does not like the transactional request concept, and we implemented the `UnitOfWork` from 1.x on our own. Is there a particular reason it's not the part of the 2.x module?

**Comment by jknack** [comment]
isn't the same as transactional request we have today? or what did you miss from 1.x?

**Comment by imeszaros** [comment]
In 1.x you could do something like this:

```
get('/do-something', req -> {
    req.require(UnitOfWork.class).apply(session -> {
        // do something
    });

    // and now something different
    req.require(UnitOfWork.class).apply(session -> {
        // do something else in an entirely new session/transaction
    });
});
```

But in 2.x, as far as I know, if you want the same functionality (i.e. use multiple sessions in the same request) you need to manually fetch and close the session, handle transaction etc.. I know it's not a very common use-case, but we really liked this idiom in 1.x.

**Comment by jknack** [comment]
I see yea, don't think lot of people use it, but we could add it back for Hibernate (jdbi already have something similar). Not 100% sure about the name: `UnitOfWork` probably `SessionHandler`/`EntityManagerHandler`, others?

**Comment by imeszaros** [comment]
`EntityManagerHandler` sounds OK to me, but `UnitOfWork` is a slightly more descriptive imho, though it does not say what kind of work it is about 😄 

There are a couple slight changes we made in our implementation, what do you think about them?
- It provides `EntityManager` instead of `Session` (we would like to use as little Hibernate specific features as possible.)
- It does not declare that it throws any exceptions (uses `sneakyThrow()`)
- does not support nesting anymore: this feature led to some confusion and misuse and therefor our implementation throws an exception if you try to instantiate while another session is open.

**Comment by jknack** [comment]
Sounds perfect. I said *Handler bc that is the name in Jdbi. I would like t add couple more feature:

- let user decided whenever pick the current session (thread scoped integration with transactional request) or create a new session (and close after callback is done)
- set transaction isolation level

**Comment by imeszaros** [comment]
Sounds great to me :) You would like to code it yourself, or should I contribute?

**Comment by jknack** [comment]
better if you do. can you do the `@Transactional` annotation feature too?

**Comment by imeszaros** [comment]
Okay. I'll have a look on it.

**Comment by jknack** [comment]
Actually, ignore the transactional annotation for now. We need to build something more to support that in generic manner.

**Comment by imeszaros** [comment]
For this topic I have the idea that maybe we could use route attributes? `TransactionalRequest` could be extended with an `enabledByDefault(boolean)` option, and then there would be an annotation `@Transactional(value = true/false)` which can change the default setting, i.e.:

- `enabledByDefault = true`
  - not annotated routes have session / transaction automatically
  - `@Transactional(true)` has no effect
  - `@Transactional(false)` disables the decorator for the route

- `enabledByDefault = false`
  - not annotated routes *don't* have session / transaction automatically
  - `@Transactional(true)` enabled the decorator for the route -> session / transaction is available
  - `@Transactional(false)` has no effect

For lambda routes we could have a constant for the attribute name in `@Transactional`:

```
{
  get("/", ctx -> ...).attribute(Transactional.ATTRIBUTE, true);
}
```

**Comment by jknack** [comment]
makes sense. I was thinking on something else... like more infrastructure for a generic way of support this requirements... but nope, we do have everything  we need.

Go for it.
