### ISSUE TITLE
'jooby-commons-email' dependency cannot be declared without version number

### ISSUE THREAD

**Issue by imeszaros** [jooby-project/jooby#1927]
In a `build.gradle` I must write:

```
implementation "io.jooby:jooby-commons-email:$joobyVersion"
```

instead of:

```
implementation 'io.jooby:jooby-commons-email'
```

Most probably I've made a mistake in commit 50dc02ebe8771d45ab61fec353d2eae89431a07a because I only declared the dependency library and the version number of it in the main POM file, but not the module itself.

Could this be the problem? Sorry I'm totally noob to maven.

https://github.com/jooby-project/jooby/commit/50dc02ebe8771d45ab61fec353d2eae89431a07a#diff-600376dffeb79835ede4a0b285078036

**Comment by jknack** [comment]
We missed to add it as managed dependency.

1. Go to root pom.xml
2. Add to the `dependencyManagement ` section
3. Like https://github.com/jooby-project/jooby/blob/2.x/pom.xml#L449-L453

On new release the https://github.com/jooby-project/jooby/blob/2.x/modules/jooby-bom/bom.groovy script read them all and generates the `jooby-bom.pom`

**Comment by imeszaros** [comment]
Should I create a PR?

**Comment by jknack** [comment]
Please do.
