### ISSUE TITLE
Accessing the Context via DI

### ISSUE THREAD

**Issue by imeszaros** [jooby-project/jooby#1937]
For various reasons we need to be able to get the `Context` object of the current request via DI / Service Registry.

We're using the Guice extension and our current solution is another custom extension that wraps the Guice extension and creates the request scope as in 1.x and registers the `Context` in it.

Now I came up with a much simpler (and DI framework independent) solution:

```java
// install before any route:

public class ContextAsService implements Extension {

    private static final ThreadLocal<Context> provider = new ThreadLocal<>();

    @Override
    public void install(@Nonnull Jooby application) {
        application.getServices().putIfAbsent(Context.class, (Provider<Context>) provider::get);
        application.before(provider::set);
    }
}
```

My question would be, is there any better / preferred / official way to achieve this?

**Comment by imeszaros** [comment]
Thanks for the feedback! You mean something like this?

https://github.com/imeszaros/jooby/commit/2fa58813889d9321cd0f8c8a12a1fb910724ea06

It seems to work, but I don't know how should I hook into request completion to clear the thread local. I was considering an 'after' handler but there is no way to remove it if someone calls the method again with `false` (though it does not make any sense :) )

And in my opinion the DI modules should not activate this by default, since it's not a commonly used feature. Or did you mean a config attribute for each of them that is a proxy for `setContextAsService()`?

**Comment by jknack** [comment]
Your code looks great. There is a `io.jooby.RequestScope` utility class, we probably could use it here

Cleanup/unbind context once it is done:
```
apply(Context ctx) {
   bind(ctx);
   ctx.onComplete(context -> unbind(context));
}
```
