### ISSUE TITLE
stork install fails on windows

### ISSUE THREAD

**Issue by ross-oreto** [jooby-project/jooby#1942]
Environment:
- java 8
- jooby 2.8.10
- Windows 10 (latest)
- maven 3.6.3

Steps:
```
jooby create test --stork
cd stork
```
- in stork.yml
```
platforms: [ WINDOWS ]
```
- package
```
mvn clean package
```
- extract /target/test-1.0.0.stork.zip and run
```
\bin\test.bat --install
```

### Expected Result: 
 - The application is installed and can then be started using the start command.

### Actual Result:
```
bin\test64.exe is not compatible with the version of Windows you're running. 
Check your computer's system information and then contact the software publisher.
```

**Comment by jknack** [comment]
Hi,

 can you please report this on https://github.com/fizzed/stork?

Thanks.

**Comment by ross-oreto** [comment]
Shall I report this giving reference to the jooby-stork plugin? Also what version of stork is being used in this scenario?

**Comment by jknack** [comment]
Sure yea. It is 3.1.0 https://github.com/jooby-project/jooby/blob/2.x/pom.xml#L151

**Comment by ross-oreto** [comment]
https://github.com/fizzed/stork/issues/40
