### ISSUE TITLE
Intellij IDEA can't stop jooby plugin completely

### ISSUE THREAD

**Issue by longkerdandy** [jooby-project/jooby#1947]
Using Intellij IDEA(2020.2) & gradle (6.6) & jooby plugin (latest version)
If I press the red square stop button, the joobyRun task failed to stop completely.
When I start joobyRun task again, it gives me "Address already in use: 8080" exception.
I have to kill the underline java process manunly

**Comment by jknack** [comment]
I'm not aware of IDEA plugin for Jooby.

**Comment by imeszaros** [comment]
I think he meant the `jooby-gradle-plugin`. My colleagues also experienced this in the past occasionally, therefore we decided to only use it voluntarily. Maybe I'll do some experiments again and try to track down the problem.

**Comment by jknack** [comment]
Ok, but what is the red square button? When I do gradle I open a terminal view and run jooby from there.

Anyway, most of these issues are related to gradle daemon. I found that doing CTR/CMDL+C doesn't reuse the daemon.. so next run start a new one. That is why I added the `press any key` to exit, this method successfully stop Jooby.

**Comment by imeszaros** [comment]
Ah I see.. i think he used IDEA to launch the gradle task, just as we used to do it...

![kép](https://user-images.githubusercontent.com/691942/91663496-73d77100-eae9-11ea-9b22-f2b53b8cdebf.png)

**Comment by jknack** [comment]
Cool. @imeszaros can you look? You are more experience gradle user than me. The issue is the Ctrl+C (shutdown signal) and how gradle notifies a plugin about it. Jooby Maven/gradle plugin used a shutdown hook for exit the application. I believe sometimes gradle daemon exists early and doesn't wait for all shutdown hook to finish.
