### ISSUE TITLE
Broken links to module documentation

### ISSUE THREAD

**Issue by GrandPoohBear** [jooby-project/jooby#1948]
Docs page: https://jooby.io/modules/

Currently, all of the links to modules are broken.  For example:
The AWS module links here: https://jooby.io/modules/modules/aws (note the extra "modules")
... but it should be: https://jooby.io/modules/aws

I'm not quite sure what generates this, or I'd submit a PR!

**Comment by imeszaros** [comment]
It's only broken if you navigate directly to `https://jooby.io/modules/`. If you load `https://jooby.io/` and then select `Modules` on the left nav menu it works ok.
