### ISSUE TITLE
how do jooby modules support mq(kafka,activemq,eq...),like spring AMQP?

### ISSUE THREAD

**Issue by kindywu** [jooby-project/jooby#1965]
i can't found any about amqp in doc.i need to integer with mq like RabbitMQ ...

**Comment by jknack** [comment]
No modules for mq yet. If you want one open an issue and ideally send a PR!

Thank you.

**Comment by jknack** [comment]
kafka was added in 2.9.3 https://jooby.io/modules/kafka/
