### ISSUE TITLE
Error trying to recreate Hibernate example

### ISSUE THREAD

**Issue by FKernler** [jooby-project/jooby#1982]
I'm trying to recreate the [Hibernate module example](https://jooby.io/modules/hibernate/) but I'm getting an error when starting the application:

`java.lang.RuntimeException: java.lang.ClassNotFoundException: org.postgresql.ds.PGSimpleDataSource from [Module "ai" from ExtModuleLoader@7a8ebd0c for finders [io.jooby.run.FlattenClasspath@40b00ab7]]`

I've attached the stacktrace: [error.txt](https://github.com/jooby-project/jooby/files/5188162/error.txt)
Also, my gradle config: [build.gradle.txt](https://github.com/jooby-project/jooby/files/5188174/build.gradle.txt)
And my App.java: [App.java.txt](https://github.com/jooby-project/jooby/files/5188175/App.java.txt)

From the example it seems like this should work, but maybe I'm missing something?

**Comment by jknack** [comment]
Hi, you need to add the postgres driver to your classpath: https://search.maven.org/artifact/org.postgresql/postgresql/42.2.16/jar

**Comment by FKernler** [comment]
Ahhh yes, thank you very much!
