### ISSUE TITLE
OpenAPI Generation doesn't work with nested routes block

### ISSUE THREAD

**Issue by abnud1** [jooby-project/jooby#1987]
I have code like this: 
```kotlin
class App : Kooby({
    install(OpenAPIModule())    
    // some before filters
    get("/someroute"){
          // do something
    }
    routes {        
        // before filters specific to these controllers
        mvc(Controller1())
        mvc(Controller2())
        ...
    }
})
```
Controller1,Controller2,etc are kotlin classes which uses MVC style and they work perfectly.

The only problem is that The generated openapi.yaml only contains the outside `get` route, the mvc routes inside `routes` block isn't found at all at openapi.yaml

In [this](https://github.com/abnud1/jooby-openapi-mvc-demo) project you find a demonstration of this problem.

Right now this is a blocker to me from OpenAPI since I have some routes on which I don't want to apply some before filters that's why I'm isolating those routes outside the `routes` block.

Oh and putting `install(OpenAPIModule())` inside `routes` block doesn't work either.

**Comment by jknack** [comment]
Try:

```kotlin
path("/") {        
        // before filters specific to these controllers
        mvc(Controller1())
        mvc(Controller2())
        ...
}
```

It is the same, just `path` is supported in OpenAPI
