### ISSUE TITLE
stork based build doesn't extract lib contents

### ISSUE THREAD

**Issue by ravihara** [jooby-project/jooby#1988]
I have used jooby-cli to create a sample project using --mvn --stork and --docker options. It all went fine and mvn clean jooby:run and mvn clean package work perfectly but, when I try to run target/stork/bin/myapp, it complains about missing lib folder.

It looks like, the myapp-<version>.stork.zip contents should have been extracted into target/stork for things to work properly but, that is not happening! Am I missing something here?! The issue persists when I try to build and run a docker image too. The reason being the same.

**Comment by jknack** [comment]
Hi!

I just tried it and works OK. The only thing to keep in mind is from where do you start the application:

<img width="240" alt="Screen Shot 2020-09-26 at 7 33 29 PM" src="https://user-images.githubusercontent.com/1301129/94351470-2b02d180-002f-11eb-8c8a-21b77b117ae0.png">

I ran `mvn clean package`, then look for the zip file and unzip it and finally start the application from the unzip directory.

`bin/myapp --run` or `bin/myapp --start`

Don't run inside the `bin` directory. Just from parent dir (application directory)

**Comment by ravihara** [comment]
> Hi!
> 
> I just tried it and works OK. The only thing to keep in mind is from where do you start the application:
> 
> <img alt="Screen Shot 2020-09-26 at 7 33 29 PM" width="240" src="https://user-images.githubusercontent.com/1301129/94351470-2b02d180-002f-11eb-8c8a-21b77b117ae0.png">
> 
> I ran `mvn clean package`, then look for the zip file and unzip it and finally start the application from the unzip directory.
> 
> `bin/myapp --run` or `bin/myapp --start`
> 
> Don't run inside the `bin` directory. Just from parent dir (application directory)

Ok thanks. I'll retry this. Closing the issue for now.
