### ISSUE TITLE
Chrome cookie SameSite issue

### ISSUE THREAD

**Issue by horace-coinful** [jooby-project/jooby#1998]
When redirecting in Chrome, set-cookie will be ignored if SameSite is not set.
Please refer: [Chrome's Changes Could Break Your App: Prepare for SameSite Cookie Updates](https://blog.heroku.com/chrome-changes-samesite-cookie)
After review codes, I found maybe these classes need to be modified:

1. For every Context implementation, must set secure to true in cookie if using https.
    In my case, I am using NettyContext, so I must do this:
```
@Nonnull public Context setResponseCookie(@Nonnull Cookie cookie) {
    if (responseCookies == null) {
      responseCookies = new HashMap<>();
    }
    cookie.setPath(cookie.getPath(getContextPath()));
    cookie.setSecure(isSecure());   // <== Add this line
    responseCookies.put(cookie.getName(), cookie.toCookieString());
    setHeaders.remove(SET_COOKIE);
    for (String cookieString : responseCookies.values()) {
      setHeaders.add(SET_COOKIE, cookieString);
    }
    return this;
  }
```
2. In **Cookie.java**, modify toCookieString():
```
  public @Nonnull String toCookieString() {
    ...
    // Secure
    if (secure) {
      sb.append(";Secure;SameSite=None");
    }
    ....
    return sb.toString();
  }
```

**Comment by imeszaros** [comment]
@jknack what do you think? Imho the secure flag should be set by the user (or caller code like pac4j `WebContextImpl` does), but `SameSite` support would be cool.

Jooby could have an enum that represent `SameSite` values. The question is should it be possible to create a cookie without the `SameSite` parameter? The general advice is now to always set it to avoid browser default behavior differences.

**Comment by jknack** [comment]
Let's add it.

> The question is should it be possible to create a cookie without the SameSite parameter?

Does all major browser support it?

Another alternative will be to allow to create a cookie without samesite in 2.x and change it in 3.x to a default value.
