### ISSUE TITLE
configure JdbiModule to use mapper from JacksonModule

### ISSUE THREAD

**Issue by fabiangebert** [jooby-project/jooby#2003]
Using
```
install(JacksonModule(customObjectMapper))
```
Doesn't define the object mapper for JDBI. Instead, it's using the default one from Jackson2Plugin:
```
install(
            JdbiModule("userdata") { dataSource ->
                val jdbi = Jdbi.create(dataSource)
                jdbi.installPlugin(Jackson2Plugin())
                jdbi
            }
)
```
Is there a way to make JdbiModule use the JacksonModule's mapper?

**Comment by jknack** [comment]
Hi,

 Unfortunately the `Jackson2Plugin` from jdbi doesn't allow you to provide a custom ObjectMapper, but I'm sure should be possibly by looking at the https://github.com/jdbi/jdbi/blob/master/jackson2/src/main/java/org/jdbi/v3/jackson2/Jackson2Plugin.java source code.

Something similar to this should work (didn't check):

```java
val jdbi = Jdbi.create(dataSource)
jdbi.installPlugin(Jackson2Plugin())
jdbi.getConfig(Jackson2Config.class).setMapper(customObjectMapper)
jdbi
```

**Comment by fabiangebert** [comment]
Yes, thanks @jknack - that works. I'd suggest to add this to the documentation.

**Comment by jknack** [comment]
It is not related to Jooby. It is something from Jdbi (was even aware of it)
