### ISSUE TITLE
OpenAPI - Parameter annotation not taking effect on Data Class

### ISSUE THREAD

**Issue by Flavsditz** [jooby-project/jooby#2004]
I have a class such:

```
data class CompanyRequest(
        val baseYear: Int,
        val naceCode: List<String>,
        val region: Region = Region.world
)
```

and I am using it in a MVC controller such as:
```
@Operation(
        summary = "Get all companies",
        description = "Find all companies defined by the search parameters"
)
@GET
fun getAllCompanies(companyRequest: CompanyRequest): String {
    return companyRequest.toString()
}
```

I am trying to provide more information about the Parameters. I tried the following inside the CompanyRequest class:
```
@get:Parameter(required = false, description = "blablabla", example = "HEY")
val region: Region = Region.world
```
which didn't work. I also tried without the `@get:` pre appended to it.

I have also added the `KotlinModule` from Jackson in order to allow for default values, **but these are not reflected in the docs** (hence trying to annotate it)

I don't know if it is a bug or just isn't supported.

**Comment by jknack** [comment]
Try adding the `@QueryParam` annotation

**Comment by Flavsditz** [comment]
The `@QueryParam` annotation is from Jooby itself and I am trying to deal with the **openAPI** so in that case it doesn't help.

What I am trying to do is having more control to what is written to the App.json or App.yaml that are generated through the openAPI step.

**Comment by jknack** [comment]
Figured it out. We need to use `Schema` annotation:

```kt
data class CompanyRequest(
    val baseYear: Int,
    val naceCode: List<String>,
    @get:Schema(required = false, description = "blablabla", example = "HEY")
    val region: String
)
```

You can do the same at class level too:

```kt
@Schema(description = "This is a company request")
data class CompanyRequest(
    val baseYear: Int,
    val naceCode: List<String>,
    @get:Schema(required = false, description = "blablabla", example = "HEY")
    val region: String
)
```

This is not Jooby, is how OpenAPI/Swagger works.
