### ISSUE TITLE
question: Error handling at startup time

### ISSUE THREAD

**Issue by extbe** [jooby-project/jooby#2053]
Hi. Why does the cause propagated here instead of the source exception? If at startup time I throw an exception with custom message `throw new IllegalArgumentException("message", cause)`, then the message will be lost.

https://github.com/jooby-project/jooby/blob/76f04546e45611a120e32d790d3de280c0f8df10/modules/jooby-utow/src/main/java/io/jooby/utow/Utow.java#L122

**Comment by jknack** [comment]
Yea, it is bug/typo. Can you send a PR?

**Comment by extbe** [comment]
Yes, I'll do it
