### ISSUE TITLE
Jooby cli is broken on windows

### ISSUE THREAD

**Issue by rishavs** [jooby-project/jooby#2056]
Running any command gives;
```
C:\Users\Mockingbird>jooby
) was unexpected at this time.
```

**Comment by lospejos** [comment]
On my Windows 10 LTSC I successfully ran Jooby CLI v2.9.5:

```
c:\bin\jooby-cli-2.9.5\bin\jooby.bat
Dec 28, 2020 2:58:02 PM org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
jooby>

```

**Comment by riheldo** [comment]
For everyone with this error. When i updated java to JDK 11, it started work.

**Comment by ross-oreto** [comment]
This seems to still be an issue, running on JDK 17 and Windows:
Oct 07, 2023 11:24:05 AM org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
