### ISSUE TITLE
BUG: Context getHostAndPort without securePort set -> NPE

### ISSUE THREAD

**Issue by JohannesBeranek** [jooby-project/jooby#2074]
Currently trying to run a jooby powered server on AWS behind an https terminating ELB, which means jooby only needs to serve plain http. Unfortunately if I don't configure securePort, context method getHostAndPort will NPE, and as soon as I configure securePort, jooby will start up the listener on that port as well, which I don't want (and I don't get why, because I didn't configure any ssl certs or the like).

Edit: latest jooby 2.9.1

**Comment by jknack** [comment]
Odd, I need the stacktrace, can you please share it?

**Comment by JohannesBeranek** [comment]
Currently not, but I forgot that the issue is only present when setting trustProxy = true .
The issue comes from here:

` 
 @Override default @Nullable String getHostAndPort() {
    Optional<String> header = getRouter().isTrustProxy()
        ? header("X-Forwarded-Host").toOptional()
        : Optional.empty();
    String value = header
        .orElseGet(() -> header("Host").value(getServerHost() + ":" + getServerPort()));
`

Basically the stuff inside value(...) is always evaluated and getServerPort then does this:

`
  @Override default int getServerPort() {
    ServerOptions options = getRouter().getServerOptions();
    return isSecure() ? options.getSecurePort() : options.getPort();
  }
`

Behind an https proxy isSecure returns true, because the scheme is retrieved from X-Forwarded-Proto and thus would be https

I think the right fix would be to have getServerPort not use the X-Forwarded-Proto, but the actual scheme used / the actual port that is currently being served by.

**Comment by jknack** [comment]
Well, think the secure port is OK as it is, if we change it we are going to break existing functionality. We probably should to two things:

- lazy evaluate this `.value(getServerHost() + ":" + getServerPort())`. This will make `HOST` to jump in without running the secure port

- change secure port so we fallback to normal port if there is none.

**Comment by JohannesBeranek** [comment]
While this fixes my issue, it would be good if we could set securePort without having jooby listen on that port.
X-Forwarded-Proto is pretty standard and in this scenario only means that the client connected to the proxy via https, but not that jooby is/needs to be running on https.

**Comment by jknack** [comment]
yea, isn't possible. I would like to move `https` to his own module and that probably give us the option of setting a secure port without doing https.... still is very odd situation, so not sure.

Jooby try to keep configuration simply and that is why a simple set secure port configures the server for doing https.
