### ISSUE TITLE
Issue: gzip compression on assets

### ISSUE THREAD

**Issue by JohannesBeranek** [jooby-project/jooby#2075]
Doesn't currently seem possible to disable gzip compression for assetswhen it's enabled via server.gzip / server.compressionLevel.

Using latest jooby + undertow, but open to using a different server if that would help solve the issue

Did I overlook anything or could this be considered an open feature request? ;)

**Comment by jknack** [comment]
Gzip is enabled at server level (jetty, netty, undertow), not as middleware/filter. So yea isn't possible to enable for something and ignore to other.
