### ISSUE TITLE
App-class initialization errors don't get logged

### ISSUE THREAD

**Issue by imeszaros** [jooby-project/jooby#2107]
Using the following code:

```java
public class App extends Jooby {

  {
    install(new SomeModuleThrowingExceptionAtInstall());
    get("/", ctx -> "Welcome to Jooby!");
  }

  public static void main(String[] args) {
    runApp(args, App::new);
  }
}
```

The exception thrown in the `install()` method of the module is not visible in the log because neither `Jooby.runApp()` or `Jooby.createApp()` does not catch any exceptions. It's only visible on the standard error output which is not ideal if the app is already deployed. We experienced this with the Hibernate module which throws an exception if there is a schema-validation error.

I suggest to catch the exceptions in `createApp()` and log them. At that time logging is already available.

**Comment by jknack** [comment]
log and rethrow? I don't like to keep it

**Comment by imeszaros** [comment]
I'll make a PR.

**Comment by jknack** [comment]
Thank you. I probably merge the kafka module, then clean up a bit and prepare a new release.
