### ISSUE TITLE
[Docs] switch between Java-Kotlin code tabs

### ISSUE THREAD

**Issue by alladywek** [jooby-project/jooby#2117]
Hi, I am faced with a really annoying problem on the docs site, the problem is that I want to learn Jooby by Kotlin examples and currently I need to switch on the Kotlin tab manually on each code snippet, could you please switch on all tabs with specific language immediately by one click? Thanks)

**Comment by jknack** [comment]
Good idea, can you send a PR?

**Comment by alladywek** [comment]
I am not a jquery guru, but it works =)

**Comment by jknack** [comment]
Thank you for your PR. Just updated the web site with your tab selection
