### ISSUE TITLE
OpenAPI and routes operator

### ISSUE THREAD

**Issue by Flavsditz** [jooby-project/jooby#2121]
Again me bringing a OpenAPI issue (I have to apologize for it!)...

It seems that when I have this:
`mvc(UserSettingsController())`

openAPI correctly parses and displays the results.

However if I have this:
```
routes {
        decorator(RequireRole(StaffRole, CustomerRole))
        mvc(UserSettingsController())
    }
```

than openAPI will not show anything. The perpetrator here is the `routes{}` scoping. I need it since different routes have different decorators, but I also realized that removing it does give me my docs back.

Maybe someone can help

**Comment by jknack** [comment]
@imeszaros can you take this?

**Comment by imeszaros** [comment]
@Flavsditz which version of jooby are you using? I had a look on this and this should be fixed by #1999 in **2.9.1** (https://github.com/jooby-project/jooby/milestone/102)

I made a test case with Kotlin, instance controller, routes and a decorator as you showed and the test passes. Could you please verify?

**Comment by Flavsditz** [comment]
Hi @imeszaros indeed I am still on the 2.9.0.
I will update it and get back to you.

**Comment by Flavsditz** [comment]
So I've updated to version 2.9.3 and my docs are back...

However, for such a function:
`@Operation(
        summary = "Values for single ID",
        description = "Delivers full data for an ID for a given year",
        parameters = [
            Parameter(
                name = "year",
                example = "2018",
                description = "The year where the data will be retrieved",
                required = true
            ),
            Parameter(
                name = "id",
                example = "XD12345",
                description = "An ID value which belongs to a dataset",
                required = true
            )

        ]
    )
    @GET
    suspend fun listDataForID(
        @QueryParam year: Int,
        @QueryParam id: String,
    )`


 I get the following error:
```
Parameter not found: year at  position: 0 for annotation: {required=true, example=2018, name=year, description=The year where the data will be retrieved}
```

This is not happening in another project I have, which has the same input however it doesn't have the routes. That project is on version 2.9.0

Can this be related?

**Comment by imeszaros** [comment]
Thanks for the feedback. I could reproduce your issue, it only happens with coroutine functions. I'll have a look on it.

**Comment by imeszaros** [comment]
@Flavsditz  i've spoken too fast.. i was missing the `QueryParam` annotation.. so can't actually reproduce it. Could you please post a minimalist but complete example to get the error?

**Comment by Flavsditz** [comment]
I've created a test repo to see if that also happens here: https://github.com/Flavsditz/openAPITest

However I am not able to run the openAPI gradle task because it accuses:
`Unable to load class '.AppKt'.`

I will try to fix it later, I just wanted to give something asap.

**Comment by Flavsditz** [comment]
I've just pushed the updated project and I can now reproduce the problem.

It seems it is something with the gradle config that is affecting it.
I don't know if that is still in your interest so feel free to also check the project out. Else I have to figure it out on my own anyway. But I now have a good starting point

**Comment by Flavsditz** [comment]
Ok... it seems that adding:
```
/** Kotlin debug information: */
tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
    kotlinOptions.javaParameters = true
}
```

solves the problem. I don't understand the why. But it solves the problem

**Comment by imeszaros** [comment]
I'm glad you could solve it!

The Kotlin docs says: "Generate metadata for Java 1.8 reflection on method parameters". It seems w/o this the OpenAPI generator could not extract the parameters properly.

Did you use the jooby cli to init your project? I can see that it has this entry in it's template file: https://github.com/jooby-project/jooby/blob/2.x/modules/jooby-cli/src/main/resources/cli/build.gradle.hbs

If it was not added then maybe it's a bug of the CLI tool.

**Comment by Flavsditz** [comment]
tbh this project was there before me... on the newest project I've created I did use the cli and that was the one working. But my initial thoughts were around the **routes** as mentioned...

I now have something new:
On the test project everything runs (although I can't seem to see the Swagger page because it says openapi.json is not available...but this is something else) **however** on the original project I am now seeing:

```
Parameter type not found on method: listDataForID, parameter: continuation
```
(again on the same function previously posted)

**Comment by imeszaros** [comment]
Kotlin appends an argument called "continuation" for the generated bytecode of `suspend` functions, but the OpenAPI generator should ignore those... that's wierd.

**Comment by Flavsditz** [comment]
I can't explain... I also have updated all the dependencies and finally, I copied the whole src folder to the newly created project but I am still seeing the `continuation` error

**Comment by jknack** [comment]
Hi can't reproduce it. I added a test case and works OK: https://github.com/jooby-project/jooby/commit/e761210942bc24d810e383820d1e577fed15c1fb

Also, you have mixed version in your project. Looks here: https://github.com/Flavsditz/openAPITest/blob/main/build.gradle#L94 it says `2.8.9`, should be `2.9.3`

**Comment by Flavsditz** [comment]
Yes I am pretty sure it is on my side too. Maybe that is the problem. I'll try to fix with that.
I guess this issue can be closed and I appreciate the help :+1:
