### ISSUE TITLE
jasypt: encrypt properties

### ISSUE THREAD

**Issue by jknack** [jooby-project/jooby#2127]
```
{
   install(new JasyptModule(key));
}
```

application.conf:

```
jasypt.sensible.prop = encrypted
```

Module will process all the keys prefixed with `jasypt`, decrypt them and rewrite as `sensible.prop`

**Comment by imeszaros** [comment]
This is for encrypting passwords in conf files and similar?

**Comment by jknack** [comment]
yea key and passwords.
