### ISSUE TITLE
How can I configure debug port?

### ISSUE THREAD

**Issue by samarjit** [jooby-project/jooby#215]
When I tried 

    <plugin>
        <groupId>org.jooby</groupId>
        <artifactId>jooby-maven-plugin</artifactId>
        <version>0.11.2</version>
        <configuration>
          <mainClass>${application.class}</mainClass>
          <commands>
          </commands>
          <vmArgs>
            <vmArg>-agentlib:jdwp=transport=dt_socket,address=5004,server=y,suspend=n</vmArg>
          </vmArgs>
          <debug>true</debug>
          <includes>
            <include>**/*.class</include>
            <include>**/*.conf</include>
            <include>**/*.properties</include>
          </includes>
          <excludes>
          </excludes>
        </configuration>
      </plugin>

[DEBUG] cmd: java *-agentlib:jdwp=transport=dt_socket,address=5004,server=y,suspend=n* **-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n** -Dlogback.configurationFile=C:\projects\jooby\my-app\conf\logback.xml -cp C:\Users\samarjit.samanta\.m2\repository\org\jooby\jooby-hotreload\0.11.2\jooby-hotreload-0.11.2.jar;C:\Users\samarjit.samanta\.m2\repository\org\jboss\modules\jboss-modules\1.4.2.Final\jboss-modules-1.4.2.Final.jar org.jooby.hotreload.AppModule com.mycompany.my-app com.mycompany.App C:\projects\jooby\my-app\target\jboss-modules C:\projects\jooby\my-app includes=**/*.class:**/*.conf:**/*.properties:

**Comment by jknack** [comment]
try this:

```xml
<plugin>
    <groupId>org.jooby</groupId>
    <artifactId>jooby-maven-plugin</artifactId>
    <version>0.11.2</version>
    <configuration>
      <debug>5004</debug>
    </configuration>
  </plugin>
```

Debug can be any of these:

```false```: turn off the remote debugger
```true```:  turn on the remote debugger with defaults options: ```-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n```
```int```: which set a port to the defaults options
```string```: a custom debug options

I will improve the doc of the plugin: http://jooby.org/doc/maven-plugin/

**Comment by samarjit** [comment]
Perfect. And thanks for the quick response.

Regarding the document I faced two challenges. First was changing jetty port which I encountered, next was this debug port. I feel these are the first thing most people will encounter during their first run. -Dapplication.port=8081. Since jooby-maven-plugin was not by default included in the pom.xml so disabling debug or changing debug port or overriding debug options was not easy to figure out. An option like -Dmaven.debug.port=5001 would be great to have.

Another thing was the javascript application packaging and running was not obvious by looking at the document. 
A miniminalistic java application packaging and running step by step would be greatly appealing and will lower the entry barrier.

I hope another small bug will get resolved soon which is netty poll server shows error which I quickly averted by switching to jetty.

**Comment by jknack** [comment]
yea, I can probably add the jooby-maven-plugin to the pom.xml generated by the maven archetype.

your options from maven command line are:

````mvn jooby:run -Dapplication.port=8081 -Dapplication.debug=5001```

There are a few running examples at: https://github.com/jooby-starters. There you will find both js and java apps.

What is the small bug with netty? I'm not aware of any small bug with netty. Can you open a bug about it?

Thanks

**Comment by iamnk** [comment]
@jknack I have  used the command `mvn jooby:run -Dapplication.port=8081 -Dapplication.debug=5001` to start the server but still debugging is not working. Could you help me with this!

**Comment by jknack** [comment]
Hi, don't think this works... it is better to start maven in debug mode and attach a debugger.

```
mvnDebug jooby:run
``` 

The default mvnDebug script waits for an debugger to be attached before continue... I find it better to just let maven start and attach a debugger later.

mvnDebug:

    MAVEN_DEBUG_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000"

**Comment by iamnk** [comment]
I have tried `mvnDebug jooby:run` but **remote debugging** is not working
@jknack

**Comment by jknack** [comment]
it does work. I used it all the time. Are you on intellij? Intellij uses a 5000 port (or similar) while maven uses 8000. Make sure they both match.

**Comment by iamnk** [comment]
@jknack thanks it works

**Comment by iamnk** [comment]
But What about the remote debug command for gradle project. These would be helpful for others if you include in the documentation
@jknack
