### ISSUE TITLE
Memory leak in the jooby-netty implementation

### ISSUE THREAD

**Issue by steintore** [jooby-project/jooby#2167]
In our project we use Jooby, and have more recently upgraded to version 2, currently running on the latest version 2.9.4.

I've spent a couple of days hunting down a memory leak within our application and have found out that the class:
`io.netty.handler.codec.DefaultHeaders$HeaderEntry` is causing some issue.

**How to recreate:**
Create an empty project with latest version of Jooby + Netty and Gradle. Run a POST-request to the running server, examine that the above mentioned class increases for every call (which is normal), but GC only manages to handle about 60% of it.

I have also created a project with Ktor + Netty, but this does NOT happen there, GC manages to clear what it should.

I have not looked into the implementation here, but hopefully you might now where to look?
It does seem to only apply to POST-requests, and it is quite hard to see it, we found it because we did not deploy for 4-5 days straight.

We have swapped to Jetty to test, and cannot see any memory leakage like this.

Please let me know if more information is required to solve this issue

**Comment by jknack** [comment]
Kind of. What type of post is it? Are they form/multipart post? Probably not...

Netty is hard, will have to review where is it. Will be good if you can isolate the error in a reproducible manner.

As workaround: Jetty is OK and Undertow will be better/faster.

**Comment by steintore** [comment]
To recreate you can just send a curl-request like this:
`curl -X POST localhost:8080 -H 'Content-Type: application/json' --data-raw '{}'`
and this is with the following main-function:
```
fun Application.module(testing: Boolean = false) {
    val server = embeddedServer(Netty, 8080) {
        routing {
            get("/") {
                call.respondText("Hello, world!", ContentType.Text.Html)
            }
        }
    }
    server.start(wait = true)
}
```
So, as you can see, the server does not even accept POST-calls, but that does not matter, if I add a POST-endpoint here, the behaviour is the same

**Comment by steintore** [comment]
> As workaround: Jetty is OK and Undertow will be better/faster.
Can you please elaborate on this? Why would Undertow be faster?

**Comment by jknack** [comment]
Between the 3 web server implementation: Undertow is the best of them (more lightweight, less classes, less memory, better performance).

**Comment by jknack** [comment]
I was able to reproduce it. I sent a PR with that fix it.

Thank you.

**Comment by steintore** [comment]
Thanks! Nice work! 👏
