### ISSUE TITLE
RxJava's Single doesn't work as expected

### ISSUE THREAD

**Issue by TomerFi** [jooby-project/jooby#2173]
Hello

First off, I wanna say thank you for this great framework,  I really enjoy working with it.

I'm trying to use [RxJava](https://github.com/ReactiveX/RxJava)'s [Single](http://reactivex.io/documentation/single.html) as suggested in [Jooby's Documentaion](https://jooby.io/#responses-nonblocking-rxjava).
And...
It looks like `Jooby` doesn't treat the `Single` instance as a source for non-blocking code,
instead, it returns the `toString` implementation of the `Single` instance.

For demonstration purposes,
here is a basic `Jooby` app registering two routes, producing the same result for different patterns,
one as a `Single` instance and one as a `Flowable`:

```java
public class App extends Jooby {
  public App() {
    get("/singletest", ctx -> Single.just("Tested"));
    get("/flowabletest", ctx -> Flowable.just("Tested"));
  }

  public static void main(String[] args) {
    runApp(args, App::new);
  }
}
```

The test class (using `Junit5` and `Java 11`'s native `HttpClient`):

```java
@JoobyTest(value = App.class, port = 4321)
final class AppTest {
  private HttpClient client;

  @BeforeEach
  void initializeClient() {
    client = HttpClient.newHttpClient();
  }

  @Test
  void test_single() throws URISyntaxException, IOException, InterruptedException {
    var request =
        HttpRequest.newBuilder(new URI("http://localhost:4321/singletest")).GET().build();
    var response = client.send(request, HttpResponse.BodyHandlers.ofString());
    assertEquals("Tested", response.body());
  }

  @Test
  void test_flowable() throws URISyntaxException, IOException, InterruptedException {
    var request =
        HttpRequest.newBuilder(new URI("http://localhost:4321/flowabletest")).GET().build();
    var response = client.send(request, HttpResponse.BodyHandlers.ofString());
    assertEquals("Tested", response.body());
  }
}
```

Running these tests will result in one failure, the `test_single` test-case fails:

```shell
[ERROR] Failures: 
[ERROR]   AppTest.test_single:29 expected: <Tested> but was: <io.reactivex.rxjava3.internal.operators.single.SingleJust@f1f3d845>
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0
```

To fix the failing test, brake the passing one, and demonstrate the difference between the `Flowable` and `Single` inference by `Jooby`, I've modified the app, the `Single` pattern returns a `Flowable` and vice-versa:

```java
public class App extends Jooby {
  public App() {
    get("/singletest", ctx -> Single.just("Tested").toFlowable());
    get("/flowabletest", ctx -> Flowable.just("Tested").singleOrError());
  }

  public static void main(String[] args) {
    runApp(args, App::new);
  }
}
```

Running the tests again, will of course result in the failure of the `test_flowable` test-case:

```shell
[ERROR] Failures: 
[ERROR]   AppTest.test_flowable:37 expected: <Tested> but was: <io.reactivex.rxjava3.internal.operators.flowable.FlowableSingleSingle@37a15da9>
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0
```

For the record, using the `fromCallable` method as exemplified in [Jooby's documentation](https://jooby.io/#responses-nonblocking-rxjava):

``` java
get("/singletest", ctx -> Single.fromCallable(() -> "Tested"));
```

Results in a similar manner:

```shell
[ERROR]   AppTest.test_single:29 expected: <Tested> but was: <io.reactivex.rxjava3.internal.operators.single.SingleFromCallable@63be418e>
```

I'm working with version `2.9.4` of the `jooby-jetty` and `jooby-test` artifacts.

**Comment by imeszaros** [comment]
Hi,

i tried to reproduce it without success. Could you please verify this code works for you?

https://github.com/imeszaros/jooby-playground

**Comment by TomerFi** [comment]
@imeszaros Thank you for the quick response and for creating the demo project.
That's funny, I've named the one I wrote for this test, x-playground too.
:-)
https://github.com/TomerFi/rxjava-playground

I wasn't able to run your project, It screams about unsupported class file 59 as I'm using `Java15`.

Nevertheless, I found the issue.
You are using [RxJava2](https://github.com/imeszaros/jooby-playground/blob/master/build.gradle#L43), I'm using [RxJava3](https://github.com/TomerFi/rxjava-playground/blob/master/pom.xml#L24).

Bumping down my project from `3.0.8` to ` 2.2.20` solves the issue.
I can imagine that something was changed with the `Single` implementation between these major versions that broke `Jooby` inference of the `Single`.

**Comment by imeszaros** [comment]
@TomerFi  funny indeed :) There are plans to move the support for reactive types to extensions and then add support for RxJava 3.

( https://github.com/jooby-project/jooby/pull/2018 )

**Comment by TomerFi** [comment]
Yes.
I see that #2018 now, didn't find any issue related besides this one.

I'll bump down to `RxJava2` in my main project for now and follow #2018.
Thank you very much.
:-)

**Comment by TomerFi** [comment]
Is 'RxJava3` is supported in 2.9.5?
