### ISSUE TITLE
Netty json post error

### ISSUE THREAD

**Issue by witur** [jooby-project/jooby#218]
HTTP post with JSON body containing double amp (&&) causes error.
That is because NettyRequest class tries to parse body as multipart without checking Content-Type header (decodeParams method).

**Comment by jknack** [comment]
will review and fix it. but as a workaround you might want to try one of the other servers: http://jooby.org/doc/servers/

**Comment by witur** [comment]
right, jetty and undertow works, thanks

**Comment by jknack** [comment]
fixed in master, will release 0.12.0 this week.

do you like jooby? please add a star in github and/or follow us at https://twitter.com/joobyproject

thanks
