### ISSUE TITLE
MVC controller method is not picked up if its name is `case`

### ISSUE THREAD

**Issue by cbxp** [jooby-project/jooby#2187]
Probably some Java keyword issue?

This route is not addded (not listed on startup and returns 404):
```kt
@GET("/{caseId}")  fun case(@ContextParam("case") case: Case) = case
```

Changing method name makes it work:
```kt
@GET("/{caseId}")  fun get(@ContextParam("case") case: Case) = case
```

**Comment by jknack** [comment]
Seems isn't possible. APT seems to ignore the method, so jooby doesn't generate anything.

Workaround 1:

```
@GET("/{caseId}")  fun get(@ContextParam("case") case: Case) {
   return case(case)
}

fun case (case: Case) = case
```

Workaround 2:

```
@JvmName("validJavaName")
@GET("/{caseId}")  fun case(@ContextParam("case") case: Case) = case
```

Reference: https://stackoverflow.com/questions/44456977/calling-kotlin-functions-which-are-keywords-in-java-from-java
