### ISSUE TITLE
ssl: allow to configure custom SSL provider (conscrypt)

### ISSUE THREAD

**Issue by hc-codersatlas** [jooby-project/jooby#2194]
Hi, boringssl is in the BOM but not documented anywhere. How is it used? Do we just add it to the classpath? It's Netty only right? Would be good to get an Openssl option vs the built-in JDK ssl.

Thanks!

**Comment by jknack** [comment]
boringssl is there bc never clean it up. It is a netty only and not sure if works today in 2.x (it did work in 1.x)

**Comment by hc-codersatlas** [comment]
Looking at the source I can't see where it's used. Netty.java looks like it's hardcoded to java ssl. [Docs](https://netty.io/wiki/forked-tomcat-native.html#how-to-use) refer to setting an SslProvider.OPENSSL option that's not set. Possible to update it? If you need an OpenSSL solutions that works across all 3 - there's also [Conscrypt](https://github.com/google/conscrypt).
