### ISSUE TITLE
out of memory when using netty implementation and post with body content

### ISSUE THREAD

**Issue by humar82** [jooby-project/jooby#2200]
humar82 @humar82 13:16
Hi! Just found an OOM problem when using netty as the server implementation, here is the code i used. I am using go-hey as the load test tools and try to load the server with post body. With netty implementation, i get out-of-memory problem. With jetty implementation, the garbage collection works well, and no out-of-memory problem.

./hey -z 10s -m POST -d '{"key":"value"}' http://127.0.0.1:8080

Below is the code i used for testing:
```

package app;
import io.jooby.Jooby;
public class App extends Jooby {
  {
    get("/", ctx -> "Welcome to Jooby!");
    post("/", ctx -> "you are using post request!!!");
  }
  public static void main(final String[] args) {
    runApp(args, App::new);
  }
}
```

**Comment by jknack** [comment]
Probably same as #2171 which is fixed in master (not yet released it)
