### ISSUE TITLE
How to use application.redirect_https property?

### ISSUE THREAD

**Issue by silentcharacter** [jooby-project/jooby#221]
I'm trying to force user to login via https using application.redirect_https property, but all values in this property lead to redirect cycle detected error(ERR_TOO_MANY_REDIRECTS) and https just doesn't work. I tryed "https://localhost:8443/{0}", "https://localhost:8443", "https://localhost:8443/login", "/".
What is the correct way to do it?

**Comment by jknack** [comment]
something were missing, it is fixed now.

will release 0.12.0 this week.

do you like jooby? please give it a github star and follow us at https://twitter.com/joobyproject

thanks

**Comment by silentcharacter** [comment]
thanks a lot!
