### ISSUE TITLE
Wait for Websocket to finish send(...)

### ISSUE THREAD

**Issue by Dominilk** [jooby-project/jooby#2228]
Before I want to close my WebSocket I want to send a quick message to let the client know the details of why the connection was closed. Unfortunately, the message never arrives and I think the reason for that is that send(...) is asynchronous and close aborts the sending-process. A method to wait until the sending process has ended would be very convenient.

Thanks,
Dominik

**Comment by jknack** [comment]
- Added write callback

```java
  ws.send("Message", (session, cause) -> {
    if (cause != null) {
     // success
    }
  })
```
