### ISSUE TITLE
SessionRequest decorator always executed by TransactionalRequest

### ISSUE THREAD

**Issue by csisy** [jooby-project/jooby#2232]
Hi,

In our current codebase, our controller methods are following the same structure:

```
@Inject
private Provider<UnitOfWork> unitOfWorkProvider;

public void anyControllerMethod() {
    unitOfWorkProvider.get().accept(entityManager -> { /* ... */ };
}
```

And since a `TransactionalRequest` decorator is available in Jooby (which is basically the same thing but done implicitly), we thought that we'd like to port our code / allow both style to be used. However, we'd like to have the `UnitOfWork` concept as an opt-in mechanism, so after the registration of the `HibernateModule` (which sets up the `UnitOfWork` as well), we added the `TransactionalRequest` decorator with `enabledByDefault(false)` as well.

```
install(new HibernateModule());
decorator(new TransactionalRequest().enabledByDefault(false));
```

The expected behaviour is:

```
@Inject
private Provider<UnitOfWork> unitOfWorkProvider;

@Inject
private Provider<EntityManager> entityManagerProvider;

public void withUnitOfWork() {
    unitOfWorkProvider.get().accept(entityManager -> { /* use the entity manager */ };
}

@Transactional()
public void withoutUnitOfWork() {
    entityManagerProvider.get(); // use the (injected) entity manager
}
```

However, even if the `TransactionalRequest` is disabled by default, the `withUnitOfWork` controller method does not execute with the following error: `A session is already bound to the current thread. Don't nest UnitOfWork invocations or don't use UnitOfWork together with SessionRequest or TransactionalRequest`.

After investigating the code, this totally makes sense. The `TransactionalRequest::apply` uses the `SessionRequest` decorator and the `enabledByDefault` is only checked after that (so the session is already bound to the context). https://github.com/jooby-project/jooby/blob/21f97697fc6dbdab8725285ec6da5a437c4d96af/modules/jooby-hibernate/src/main/java/io/jooby/hibernate/TransactionalRequest.java#L98-L100

Is this the intentional behaviour? If not, then there are two possible solutions to this:

1. Change the order, so the flag is checked first, then the `SessionRequest` decorator is executed
2. Allow the `SessionRequest` to be disabled by default (similarly to the `TransactionalRequest`)

Thank you!

**Comment by jknack** [comment]
I didn't look yet, but your explanation makes sense. @imeszaros want to chime in?

**Comment by imeszaros** [comment]
I agree it makes sense.. I'll have a look on it and test whether we can implement proposal 1.)
