### ISSUE TITLE
Interrupted request leads to NPE using Netty + AccessLog

### ISSUE THREAD

**Issue by imeszaros** [jooby-project/jooby#2260]
If an HTTP request is interrupted (user closes the browser, etc.), an NPE is thrown using Netty and the AccessLog module. The access log tries to concat the remote IP to the log calling `getRemoteAddress()` on the context, but in case of `NettyContext` this leads to an NPE in line:

https://github.com/jooby-project/jooby/blob/17e2c1b1ad9052f21e62decf72afe9e68dfad4b4/modules/jooby-netty/src/main/java/io/jooby/internal/netty/NettyContext.java#L263

since `remoteAddress` is `null`.

After a brief look I guess `JettyContext` returns an empty string in this case, no idea about Undertow however.

What would be the expected behavior?

**Comment by jknack** [comment]
Open to suggestion, but let's normalize between implementations

**Comment by imeszaros** [comment]
Silently removing the `@NonNull` and returning `null` would be evil. :) I propose either returning an empty string or refactoring to `Optional<String>` which requires some minor migration for users but at least makes it clear. The question is, do we have any other property we should care about?

**Comment by csisy** [comment]
Additionally, the context could have a `boolean isOpen()` function, or something like that. It could be used in the access log handler to separate the cases, so a simpler "request was cancelled"-like message can be printed instead.
