### ISSUE TITLE
websocket.idleTimeout only working for whole minutes

### ISSUE THREAD

**Issue by jankeesvanandel** [jooby-project/jooby#2305]
Hi,

For a debugging session I set the websocket.idleTimeout to 10s, but was surprised to see that this didn't work. The docs mentioned: "websocket.idleTimeout = 1h" so I assumed it was valid to specify a custom duration (including seconds).

But the code in https://github.com/jooby-project/jooby/blob/34eb70cf2583e317d3c77f94d165bc8be7520bb5/modules/jooby-netty/src/main/java/io/jooby/internal/netty/NettyContext.java#L371 parses the config value to minutes, which breaks values less than one minute. Maybe you could add a remark to the docs that the idleTimeout only works for whole minutes?

Thanks!

**Comment by jknack** [comment]
next release will comes with milliseconds precision.
