### ISSUE TITLE
MVC annotations will never use custom Value Converters. @QueryParam and friends is confusing for custom objects.

### ISSUE THREAD

**Issue by agentgt** [jooby-project/jooby#2325]
Lets say we have a  `ValueConverter` that converts a **single** value to an object of type `MyID`.

The hope is to have something like:

```java
@GET("/somepath")
public ModelAndView getMy(@QueryParam MyID id) {
}
```

One would expect the annotation processor to generate code that does something analogous to:

```java
query("id").into(MyID.class)
```

Instead I believe it does:

```java
query().into(MyID.class)
```

That is it tries to convert the entire query string which is a `HashValue` and not a `SingleValue` and thus will kick off a `BeanConverter` if one is available. 

The above is actually pretty painful for us for two reasons:

 1. We actually do often have multple custom IDs in every request we have to convert to that ID type from string or UUID.
 1. We have an annotation processor (which might interest you) that generates methods to make URLs from Controller annotations. That is the example at the start will generate a method: `URI getMy(MyID id)`. 

Instead we have to do the conversion to and from everywhere manually.

There are two issues for me implementing this as a PR:

 1. Backwards compatibility with what `@QueryParam` and friends currently do
 2. I'm just not very good ASM generation. I'm very good with APT API and generating regular Java code but ASM is a little tricky for me.
 

For number 1  I propose that `@Param` have an additional parameter that specifies value type:

```java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.PARAMETER)
public @interface Param {

  /**
   * Parameter name.
   *
   * @return Parameter name.
   */
  String name() default "";

  /**
   * Parameter sources to search in, the order defines the search priority.
   *
   * @return Parameter sources to search in.
   */
  ParamSource[] value();

  ValueType[]  converter() = default ValueType.BEAN;
}

public enum ValueType {
  SINGLE,
  BEAN
}
```

This should allow everyone that currently relies on the current behavior to continue to work. For folks like myself we can just use `@Param(value=..., converter=ValueType.SINGLE)`.

Ideally I would like multiple new annotations with names like `@QueryBean` that do the hash and `@QueryParam` to use single value but the above is an easier change (perhaps in version 3 it will be different).

Because of the ASM code generation I don't have the time to implement this myself.

Perhaps in version 3 we can just generate Java code instead of ASM? Actually I  was writing an extension/plugin to: https://avaje.io/http/ to use Jooby as it uses plain Java code and it is so far so much easier to figure out than the ASM we do.

Anyway Thank You and we plan on donating soon.

**Comment by jknack** [comment]
I like the `QueryBean` vs `QueryParam` solution for 3.x.

Meanwhile we are going to favor named param over bean in 2.x:

```
@GET("/somepath")
public String getMy(@QueryParam MyID id) {
  return id.toString();
}


class MyID {
   private String value;

   public String getValue();

   public void setValue(String value);
}
```

A call like:

    GET /somepath?id=1234

will choose a ValueConverter due the `id` parameter is present on Request.

A call like:

    GET /somepath?value=1234

will choose the default bean converter due `id` parameter isn't present on Request.

Basically named parameter has higher precedence.
