### ISSUE TITLE
[MVC Annotation] Parameters that are called "name" cannot have other annotations on them besides *Param

### ISSUE THREAD

**Issue by agentgt** [jooby-project/jooby#2352]
The annotation processor seems to be confused if a parameter called "name" has additional annotations that are not Jooby annotations.

```
@POST("/blah")
public Stuff stuf(@Nullable @FormParam String name) {
}
```
 
Generates code like:

```
stuff(ctx.multipart().to(String.class));
```

It should be like:

```
ctx.multipart("name").to(String.class)
```

If you give the parameter a different name instead of "name" it works fine. I have a feeling this has something to do with injection features or maybe not.

**Comment by jknack** [comment]
I can't reproduce... probably bc of #2325. Adding a tests
