### ISSUE TITLE
jooby-utow (undertow) doesn't seem to support Expect 100 Continue on PUT

### ISSUE THREAD

**Issue by agentgt** [jooby-project/jooby#2363]
If a client use [Expect 100 continue](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/100) with undertow on a PUT body the upload will appear to hang for a second because the client is expecting the server to respond `100 CONTINUE`.

jooby-jetty does not have this problem. I'll test netty soon as well.

This is actually a pretty big deal for us so I'll try for a PR shortly. Its potentially a security concern as well (it has been in the past for Netty).

Perhaps it is a simple as Jooby is missing the Continue Handler: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#built-in-handlers

https://undertow.io/javadoc/2.1.x/io/undertow/server/handlers/HttpContinueReadHandler.html

Here project reactor had a similar problem that might be relevant albeit for Netty: https://github.com/reactor/reactor-netty/issues/293

**Comment by agentgt** [comment]
While Jetty mostly works for 100 Continue Jetty appears to call "onComplete" multiple times for 100 CONTINUE for the same request. 

I guess that is a separate bug.

**Comment by jknack** [comment]
Hi Adam,

 please share a way to reproduce it. Thanks

**Comment by agentgt** [comment]
Sorry Edgar for not getting back to you on this. I couldn't figure out how to get a unit test working for it and didn't have time to make a sample project.

Apache HTTP components is the only java library I know that can do expect 100 which is exactly what caused the bug to surface (we have  custom maven repository instead of sonatype written in Jooby).

**Comment by jknack** [comment]
verified the response with curl and all the 3 implementation works as expected.

There is a sightly difference: undertow/jetty generates the 100 response when body is about to read, netty always generates the 100 response (regardless if you read or not the body)
