### ISSUE TITLE
WebSocket compression

### ISSUE THREAD

**Issue by apaulau** [jooby-project/jooby#2364]
As far as I see, jooby doesn't support WebSocket compression at the moment. It would be really great to have an option to enable it along with the existing HTTP compression level.

WIth netty it's handled by the `WebSocketServerCompressionHandler`, not sure about other server implementation though.

**Comment by altmind** [comment]
It seems that w/ ws compression the jooby apps now receive TextWebSocketFrames with the message text that are padded to 16Mb with ascii NULs.

CompositeByteBuf, containing PooledUnsafeHeapByteBuf `.array()` method can return the array that is larger than the expected message(well, they are POOLED ByteBufs).

https://github.com/jooby-project/jooby/blob/34eb70cf2583e317d3c77f94d165bc8be7520bb5/modules/jooby-netty/src/main/java/io/jooby/internal/netty/NettyWebSocket.java#L245

Netty in Action, chapter 5.2.2 provides extra details on how to use array-backed ByteBufs. It seems that we need to copy bytes[] manually even for array-backed bytebufs.

**Comment by altmind** [comment]
Oh, nevermind, I see its already fixed in #2451

**Comment by apaulau** [comment]
> It seems that w/ ws compression the jooby apps now receive TextWebSocketFrames with the message text that are padded to 16Mb with ascii NULs.
> 
> CompositeByteBuf, containing PooledUnsafeHeapByteBuf `.array()` method can return the array that is larger than the expected message(well, they are POOLED ByteBufs).
> 
> https://github.com/jooby-project/jooby/blob/34eb70cf2583e317d3c77f94d165bc8be7520bb5/modules/jooby-netty/src/main/java/io/jooby/internal/netty/NettyWebSocket.java#L245
> 
> Netty in Action, chapter 5.2.2 provides extra details on how to use array-backed ByteBufs. It seems that we need to copy bytes[] manually even for array-backed bytebufs.

@altmind I described this issue in https://github.com/jooby-project/jooby/issues/2449. Could you please add your thoughts there?
