### ISSUE TITLE
Customize which error is considered connection lost

### ISSUE THREAD

**Issue by vellrya** [jooby-project/jooby#2369]
Hello, thank you for fantastic library!
I successfully use jooby in few microservice, now I need real-time event for new project and jooby come to rescue again)

Some interesting bug:
When sse event cannot be send because of client connection reset jooby log this:

> [2021-06-15 14:12:14,183]-[DefaultDispatcher-worker-1] ERROR io.jooby.ServerSentEmitter - server-sent-event resulted in exception: id 763861c7-51a7-4380-846f-953e376f9510 /sse
> java.io.IOException: Программа на вашем хост-компьютере разорвала установленное подключение
> 	at java.base/sun.nio.ch.SocketDispatcher.write0(Native Method)
> 	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:54)
> 	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
> 	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79)
> 	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
> 	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:506)
> 	at org.xnio.nio.NioSocketConduit.write(NioSocketConduit.java:153)
> ...
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
> [2021-06-15 14:12:17,137]-[DefaultDispatcher-worker-1] WARN  io.jooby.ServerSentEmitter - server-sent-event closed: 763861c7-51a7-4380-846f-953e376f9510

I checked source code:
- https://github.com/jooby-project/jooby/blob/34eb70cf2583e317d3c77f94d165bc8be7520bb5/modules/jooby-netty/src/main/java/io/jooby/internal/netty/NettyServerSentEmitter.java#L96-L98 
Okay, log should be suspended if connectionLost return true
- https://github.com/jooby-project/jooby/blob/34eb70cf2583e317d3c77f94d165bc8be7520bb5/jooby/src/main/java/io/jooby/Server.java#L137-L149
This solution can work only for english language, but for localized message "Программа на вашем хост-компьютере разорвала установленное подключение" of original exception "An established connection was aborted by the software in your host machine" connectionLost return false, but should be true. Also it seems this kind of exception also unnecessary logged in english - message doesn't contain any of provided substring. 

Probably we can only check IOException instance and don't rely on message?
Thanks in advance for investigating)

P.S. And one more question: did I get it right, in general, that I can save instances of sse or websocket objects in some collection and access them later from another place in the program, and remove those connections from the collection during onClose events?
```
val activeSSE = ConcurrentLinkedQueue<ServerSentEmitter>()
...
sse("/sse") {
    sse.onClose {
        println("closed sse")
        activeSSE.remove(sse)
    }
    println("Opened connection")
    sse.send("Opened: ${System.currentTimeMillis()}")
    activeSSE.add(sse)
}
```
P.S.S. Don't active connections take up an entire thread? If I have 10 active connections that don't send new data to, won't they take up 10 threads?

**Comment by jknack** [comment]
Ignoring IOException in general isn't a good solution. We can probably extend the decision of what is connection lost:

```
Server.addConnectionLost(cause -> {
   return true when cause is a connection lost
});
```

> P.S. And one more question: did I get it right, in general, that I can save instances of sse or websocket objects in some collection and access them later from another place in the program, and remove those connections from the collection during onClose events?

That looks OK, as long you don't care to lost data after restart (of course).

> P.S.S. Don't active connections take up an entire thread? If I have 10 active connections that don't send new data to, won't they take up 10 threads?

Nope, it is a non-blocking model. Threads are reused. The only way to have 10 threads-active running is when you have 10 or more real users.

**Comment by vellrya** [comment]
I think this is a good solution. I will be glad if such an opportunity appears in the new version.
