### ISSUE TITLE
SSL Configuration Incomplete in applicaiton.conf

### ISSUE THREAD

**Issue by cmitchell** [jooby-project/jooby#2371]
Currently, there doesn't seem to be a way to specify a trust certificate at all (neither x509 nor pkcs) in the application.conf. If I'm wrong, will you please post an example configuration that does so and consider updating the documentation.

In the code, the following works to configure the trust certificate
```
     serverOptions {
     ssl = SslOptions.from(config).get()
      .setTrustCert("/home/user/certs/foo-pki-root-4-crt.pem")
      .setPassword("changeme")
  }
```
but there's no way to make the equivalent configuration solely using the application.conf 

Just a few suggestions, which would make implementation easy(ier)

*You don't have to care about the "type" at all if you just inspect for the use of "key" to indicate x509, and password to indicate pkcs.
*Using the above suggestion, you could add "trustCert", "trustKey", and "trustPassword" properties to allow those to be configured and the type automatically detected 
*You also can't specify the ClientAuth value via the application.conf

Example of proposed application.conf configuration
```
server {
    securePort: 8443
    http2: true
    ...
    ssl {
        cert: "server.crt"
        key: "server.key"
        trustCert: "/home/user/certs/foo-pki-root-4-crt.pem"
        trustPassword: "changeme"
        clientAuth: REQUIRED
    }
}
```

Right now, I'm working around this by reading my own properties from the application.conf and setting them. but this would be better if it could be configured in the "jooby" way.

```
   serverOptions {
      ssl = SslOptions.from(config).get()
        .setTrustCert(config.getValue("server.ssl.trustCert").unwrapped().toString())
        .setPassword(config.getValue("server.ssl.trustPassword").unwrapped().toString())
        .setClientAuth(ClientAuth.valueOf(config.getValue("server.ssl.clientAuth").unwrapped().toString()))
  }
   ....
```
and the application.conf
```
server {
    securePort: 8443
    http2: true
    ...
    ssl {
        type: X509
        cert: "server.crt"
        key: "server.key"
        trustCert: "/home/user/certs/foo-pki-root-4-crt.pem"
        trustPassword: "changeme"
        clientAuth: REQUIRED
    }
}
```

**Comment by jknack** [comment]
😅 can you send a PR with doc update?

Thanks
