### ISSUE TITLE
Is it possible to get peer certificate from ctx when clientAuth == REQUIRED?

### ISSUE THREAD

**Issue by cmitchell** [jooby-project/jooby#2401]
Hi,

   I have been trying to get the certificate presented by the client from the request context, and I haven't found a way to do it. Mutual TLS works, so I know the server has the peer's certificate. It seems that all access to Netty's SSLEngine is blocked, so I can't pull it directly from Netty, and the context doesn't have any notion of channels, so I can't get it from there either.  I'm hoping this is just a difficult thing to find, and that it is possible to get the peer certificates from the request. (Other frameworks handle this use case, so this isn't a unique concern)

    Please let me know if I've misunderstood, and there is a way to get to the peer certificate/sslEngine.

**Comment by jknack** [comment]
yea, don't know how to do... can you try to send a PR?

and of course this need to be supported across netty, jetty and. undertow :S
