### ISSUE TITLE
Multiple pac4j clients and authorizers on the same url

### ISSUE THREAD

**Issue by leleuj** [jooby-project/jooby#241]
pac4j can globally support multiple clients and authorizers on the same url. Reference algorithms with `clientName` and `authorizerName` are designed that way.

It would be great to have the same feature in Jooby while keeping its incredibly compact syntax. For example, we could have:  `.client(String pattern, Function<Config, List<Client<C, U>>> provider)` and `.authorizers(Authorizer<?>... authorizer`

**Comment by jknack** [comment]
like it!

**Comment by jknack** [comment]
was not able to do: ```.client(String pattern, Function<Config, List<Client<C, U>>> provider)```, bc:

* got a few compilation error when you try to add/returns diff client types :S

syntax for multiple clients is:

```jaa
{
  new Auth()
        .client("/twitter/**", conf -> {
          return new FacebookClient(conf.getString("fb.key"), conf.getString("fb.secret"));
        })
        .client("/twitter/**", conf -> {
          return new TwitterClient(conf.getString("twitter.key"), conf.getString("twitter.secret"));
        });
}
```

It works just fine, but of course users will have to right the protected urls one per client.

Same for authorizers.

I will update the demo was 0.13.0 is out.

Thanks

**Comment by leleuj** [comment]
OK. Not a big deal. Things can get tricky with Java and lambdas now. That's why the default pac4j recommendation is based on client names in the protection filter and a centralized configuration with simple objects (list, map). More verbose.

Your solution does the job anyway. Thanks

One thing that comes out of my mind: error pages; I noticed that most "new" frameworks does not handle that really properly: for example in Play, I'm forced to have a specific implementation to handle the 401 / 403 error pages (https://github.com/pac4j/play-pac4j-java-demo/blob/master/app/controllers/DemoHttpActionAdapter.java#L14). And it's not the only framework that requires non trivial configuration for that.

It seems that Jooby proposes something really efficient (http://jooby.org/doc/#error-handling-custom-err-handler): when you'll update the demo, woudl you mind adding specific pages for "internal error" (500), "unauthorized" (401) and "forbidden" (403)? Thanks again

**Comment by leleuj** [comment]
On more thing: I just saw this mailing list: https://groups.google.com/forum/#!forum/jooby-project, but I don't see any post? Is it the right place? Thanks

**Comment by jknack** [comment]
np, will add err pages.

the group is correct, but no one post anything yet :) reason? people is usually lazy and ask questions in github, but of course we are a small community too.

**Comment by leleuj** [comment]
I like to post announcements from time to time, when new versions are released, just to keep people posted of the new features.

**Comment by jknack** [comment]
yea, is something I did on https://github.com/jknack/handlebars.java but then I forgot or too lazy.

will post there the nrext release.. specially bc I'm planning to make the first stable release 1.0.0 (api freeze) early in 2016
