### ISSUE TITLE
Where I can get jooq and jdbc modules for jooby 2.10.0?

### ISSUE THREAD

**Issue by advortsov** [jooby-project/jooby#2410]
I'm trying to use 
```
implementation("io.jooby:jooby-jooq:2.10.0")
implementation("io.jooby:jooby-jdbc:2.10.0")
```
with
```
repositories {
    mavenCentral()
    mavenLocal()
    gradlePluginPortal()
    google()
}
```

but get "Could not find..." gradle message

I see note that artifact was moved at https://mvnrepository.com/artifact/org.jooby/jooby
but I follow the link and don’t find it there

Where I can get jooq and jdbc modules for jooby 2.10.0?

**Comment by jknack** [comment]
Hi,

  Since 2.x release `jooby-jdbc` is now `jooby-hikari` and `jooby-jooq` wasn't migrated to 2.x

**Comment by advortsov** [comment]
How can I use jooq with 2.x? Is jooq migration supposed?

**Comment by jknack** [comment]
It should be pretty simple to add it. From Hikari module you get the datasource/jdbc connection.

> Is jooq migration supposed?

Not for now, unless someone send a PR. Can you send a PR?

**Comment by advortsov** [comment]
I'm afraid I'm not that familiar with jooby. Maybe someday

Thanks  for the answer!
