### ISSUE TITLE
[MVC] Annotations with array of annotations break annotation processor with UnsupportedOperationException

### ISSUE THREAD

**Issue by agentgt** [jooby-project/jooby#2417]
If you have an annotation that has an array of annotations as arguments on an MVC method and you are using JDK 11 or higher the APT processor will fail with:

```
Caused by: java.lang.UnsupportedOperationException
    at com.sun.tools.javac.code.Attribute.getValue (Attribute.java:58)
    at io.jooby.internal.apt.asm.RouteAttributesWriter.annotationValue (RouteAttributesWriter.java:196)
    at io.jooby.internal.apt.asm.RouteAttributesWriter.toMap (RouteAttributesWriter.java:184)
    at io.jooby.internal.apt.asm.RouteAttributesWriter.annotationMap (RouteAttributesWriter.java:172)
    at io.jooby.internal.apt.asm.RouteAttributesWriter.annotationValue (RouteAttributesWriter.java:198)
    at io.jooby.internal.apt.asm.RouteAttributesWriter.toMap (RouteAttributesWriter.java:184)
    at io.jooby.internal.apt.asm.RouteAttributesWriter.annotationMap (RouteAttributesWriter.java:172)
    at io.jooby.internal.apt.asm.RouteAttributesWriter.annotationMap (RouteAttributesWriter.java:143)
    at io.jooby.internal.apt.asm.RouteAttributesWriter.process (RouteAttributesWriter.java:121)
```

An example annotation that fails is `@Operation` from Swagger.

That being said this is kind of a JDK bug. I looked at the `com.sun` `Attribute` and all of its subclasses including `Error` implement `getValue` so it must be some weird synthetic class or a proxy.

The JDK bug is here: https://bugs.openjdk.java.net/browse/JDK-8201314

An easy workaround is to obviously catch that exception in `RouteAttributesWriter.annotationValue` and ignore it.

Alternatively the visitor pattern can be used on the `AnnotationValue` to build an array of maps to represent the annotation but that is more work.

**Comment by jknack** [comment]
Hi,

 Can you add an example to reproduce it?

**Comment by agentgt** [comment]
Yes. Do you want me to do it with a PR unit test that fails (like I did with this one: https://github.com/jooby-project/jooby/pull/2409) or just paste code here?

I don't think it will happen with JDK 8 though but it appears you have a build matrix with newer versions.

**Comment by jknack** [comment]
Yea, that helps too.

**Comment by agentgt** [comment]
I'll do the PR but it will take me a little bit to refresh my fork.

But for now it should be incredibly easy to replicate by just using the swagger annotations:

```
@GET("/blah")
@io.swagger.v3.oas.annotations.Operation
public String blah() {
  return "";
}
```

**Comment by agentgt** [comment]
I can't easily reproduce it in the jooby tests because the issue appears to happen when multiple annotation processors are present.

If Jooby is the only annotation processor or if its the first in the annotation path it doesn't happen however in our case we need ours to run before jooby runs. The reason is that the controllers are using some generated code.

Normally the above works fine (we generate code that is used by jooby controllers) unless we add those compound array annotations. The `@Operation` annotation has nothing to do with our annotation processor and we do not claim it so I'm not sure why the JDK generations an a proxy annotation value that has the weird behavior.

The only open source option I can think of using to make a test is Dagger. I think Dagger users haven't noticed it because they just haven't used MVC + an annotation that would trigger the problem (it only happens on annotations that contain annotations).

I can easily put in a PR for catching the `UnsupportedOperationException` and that would fix our problem for sure without impacting others that do not need it. I could even have it log a warning using the APT logging system if you like.

I'm fairly sure the above is a JDK bug and we just need a workaround so that we don't have to do a bunch of hacks using interfaces and separating out code generation.

**Comment by agentgt** [comment]
Where it happens is right here:

https://github.com/jooby-project/jooby/blob/34eb70cf2583e317d3c77f94d165bc8be7520bb5/modules/jooby-apt/src/main/java/io/jooby/internal/apt/asm/RouteAttributesWriter.java#L196

Just make:

    Object value = annotationValue.getValue();

```java

Object value;
try {
  value = annotationValue.getValue()
}
catch (UnsupportedOperationException e) {
  return null;
}
```

**Comment by agentgt** [comment]
Thanks Edgar! I was working on submitting a bug to Open JDK as it is clearly a JDK bug and then doing a PR for a workaround in Jooby but you beat me to it. Thanks you so much!

**Comment by jknack** [comment]
You're welcome.
