### ISSUE TITLE
Scala Futures Handling

### ISSUE THREAD

**Issue by carlcamilleri** [jooby-project/jooby#2430]
Hi,

Looking at integrating an HTTP front-end to an Akka Actor System with Jooby.

I'm using Scala and was wondering what would be the recommended way to send the response from an Akka actor to the HTTP client .

Currently have it working roughly as follows:

```
get("/{id}", (ctx: Context) => {
      val res: Future[String] = myActor ? myMsg
      res.asJava.toCompletableFuture
}
```

Is using `res.asJava.toCompletableFuture` correct or is there perhaps a better way to go about it?

Thanks

**Comment by jknack** [comment]
That should work. Other options:

- Choose one of the reactive types: https://jooby.io/#responses-nonblocking. This of course is more or less the same as your example.
- Another option will be custom https://www.javadoc.io/doc/io.jooby/jooby/latest/io/jooby/ResponseHandler.html and believe running everything on event loop: https://jooby.io/#execution-model
