### ISSUE TITLE
ctx.getPort() wrongly returns 80 if isTrustProxy = true

### ISSUE THREAD

**Issue by cbxp** [jooby-project/jooby#2444]
We have `isTrustProxy = true` enabled, which enables usage of `ProxyPeerAddress`.
However, if we don't provide the `X-Forwarded-Port` header, `ProxyPeerAddress` tries to derive it from the 'Host' header value, which works incorrectly because the port number is already stripped out from the value on line 123. It should use the full value of the `Host` header before the stripping for it to work.

**Comment by jknack** [comment]
Hi,

 I need more context and examples to better understand the change.

Thanks.
