### ISSUE TITLE
Support for running native 'mvn jetty:run'

### ISSUE THREAD

**Issue by cyberquarks** [jooby-project/jooby#2459]
Is there a way to natively run a Jooby app with `jetty run`? 

As such, we can run tools like XRebel https://manuals.jrebel.com/xrebel/support/index.html or similar that only works with supported web servers like Jetty.

And although `jooby:run` auto-reload, using tools like JRebel https://www.jrebel.com/products/jrebel in cases would be a better solution.

**Comment by jknack** [comment]
Thank you for your request. Unfortunately, this is not possible today. Jooby doesn't run inside a servlet container.
