### ISSUE TITLE
Origin of config entries are overriden by Jooby

### ISSUE THREAD

**Issue by imeszaros** [jooby-project/jooby#2467]
In class `Environment` when a file or classpath resource is parsed via calling `ConfigFactory` an origin description is specified explicitly which prevents the Config library to determine the origin as it should do it by default. This results all origin objects to have the type `GENERIC`, which prevents them returning name of the source file via calling `filename()`.

We configure logback from `application.conf` with the help of a library that supports reloading the logging configuration if it detects any change. This mechanism could not be set up correctly because all config origins return `null` when the lib calls `filename()` on them.

This can be easily fixed by letting the Config library to determine the origins instead of specifying them explicitly.

**Comment by jknack** [comment]
how did you configure logback? I'm curious to see it. I'm not happy on how it works today... it depends on how JVM load classes and/or if you have a static field for a logger.

**Comment by imeszaros** [comment]
I updated my playground repo with an example: https://github.com/imeszaros/jooby-playground

The library we use is: https://github.com/gnieh/logback-config

Logback provides an SPI that can be implemented to configure it programmatically. The above library does exactly this using a Typesafe `Config` object as input. It provides yet another SPI to acquire an instance of `Config`.

I impelented this in my repo (see [META-INF/services](https://github.com/imeszaros/jooby-playground/tree/master/src/main/resources/META-INF/services)). See the [`App`](https://github.com/imeszaros/jooby-playground/blob/master/src/main/java/demo/App.java) class how it's used. If you start the app you get something like this:

```
13:42:55,963 |-WARN in org.gnieh.logback.config.ConfigConfigurator@de3a06f - No configuration files to watch, so no file scanning is possible
it works from application.conf! [2021-11-26 13:42:55,965]-[main] INFO  demo.App - I'm alive.
it works from application.conf! [2021-11-26 13:42:56,216]-[main] INFO  demo.App - App started with:
it works from application.conf! [2021-11-26 13:42:56,216]-[main] INFO  demo.App -     PID: 16424
it works from application.conf! [2021-11-26 13:42:56,216]-[main] INFO  demo.App -     netty {port: 8080, ioThreads: 32, workerThreads: 128, bufferSize: 16384, maxRequestSize: 10485760}
it works from application.conf! [2021-11-26 13:42:56,216]-[main] INFO  demo.App -     env: [dev]
it works from application.conf! [2021-11-26 13:42:56,216]-[main] INFO  demo.App -     execution mode: default
it works from application.conf! [2021-11-26 13:42:56,216]-[main] INFO  demo.App -     user: conta
it works from application.conf! [2021-11-26 13:42:56,216]-[main] INFO  demo.App -     app dir: D:\work\jooby-playground
it works from application.conf! [2021-11-26 13:42:56,216]-[main] INFO  demo.App -     tmp dir: D:\work\jooby-playground\tmp
it works from application.conf! [2021-11-26 13:42:56,217]-[main] INFO  demo.App - routes: 

  GET /

listening on:
  http://localhost:8080/
```

The first line is an output from `StatusListenerImpl`, my pull request is about to eliminate that warning and enable the library to pick up changes in `application.conf`.
