### ISSUE TITLE
Post and Put always sends response before all decorators finished

### ISSUE THREAD

**Issue by csisy** [jooby-project/jooby#2477]
Hello,

This issue arises when the post/put handler itself does not throw an exception but another handler/decorator does, after the post/put handler already finished its execution. For example this can happen when the `TransactionalRequest` is used and the `commit()` throws an exception.

The current (IMO incorrect) flow is the following:

- TransactionalRequest begin transaction
- execute next handler in chain
- execute the PUT handler -> does not throw an exception
- it calls the `context.send`
- back to the TransactionalRequest, calls `commit()`
- commit throws an exception but the request is already sent with status code 200

The controller code is something like this:

```
@PUT("/{id}")
@Transactional
public void update(@PathParam int id, ...) {
   service.update(...);
}
```

While the generated module code is:

```
var2.setReturnType(Context.class);
var2.attribute("Transactional", true);
var2 = var0.put("/.../{id}", (var1x) -> {
	MyController var2 = (MyController)var1.get();
	var2.update(var1x.path("id").intValue(), ...);
	return var1x.isResponseStarted() ? var1x : var1x.send(var1x.getResponseCode());
});
```

As you can see the `var1x.send(...)` causes the response to be sent with status code 200.

**Expected behaviour**

Any response should ever be sent after the whole handler chain finished its job. This would result in a proper 500 status code that is currently only printed to the console since the response is already started. See

https://github.com/jooby-project/jooby/blob/d4f30f25324d5ccdecf7b3dd53ef18f45dfab550/jooby/src/main/java/io/jooby/DefaultContext.java#L555

**Comment by csisy** [comment]
What do you think? Should the generated code simply return the context instead? The affected part is: https://github.com/jooby-project/jooby/blob/b11404af63ee6698c1e91f7b4d063bada9df427d/modules/jooby-apt/src/main/java/io/jooby/internal/apt/HandlerCompiler.java#L233

Based on `git blame`, the source issue was #1378. Would returning context automatically for void methods break anything?

**Comment by jknack** [comment]
I do believe there is more work to do. I found the issue recently too in one of my private projects. I don't think it is related to returns or not the context.

**Comment by csisy** [comment]
What I meant was that if I change the `void` return type to something else (which is a `Context` in this case), the problem disappears, since the generated code won't cause the response to be sent.

So instead of `public void myFunc(...)` if I use `public Context myFunc(Context ctx) { return ctx; }` then the generated code simply returns the value that I returned from the controller function. And this means that the response will not be started and the appropriate error handler works as expected.

This was the reason why I thought that changing the `jooby-apt` part (linked above) to skip the `isReponseStarted` part and simply return the context instead would solve this problem. However, I'm not aware that this change would break anything else.
