### ISSUE TITLE
jooby-apt: Module class not generated when base class is an external class (from another project/jar)

### ISSUE THREAD

**Issue by JozefDropco** [jooby-project/jooby#2486]
Hello, 
I am a newbie in using Jooby. We are about to migrate all our applications from JavaEE to Jooby and Undertow. I am trying to do it for one of our simplest application. I was able to setup PAC4J for security, servlets to run them as we were used to before (we will decommission them later), get running most of our webservices with JAX-RS. But one of them is not working. We have a common library were we have OperationWebService which is used for health check and also some insight to the application settings. This service is then extended in each application.
**Common from library**
```java
public class OperationWebService {

    @GET
    @Path("/clue")
    @Produces({MediaType.APPLICATION_JSON, MediaType.TEXT_PLAIN})
    public final Response getClue(final @Context HttpHeaders headers) {
        //...
    }

    @GET
    @Path("/config")
    @Produces({MediaType.APPLICATION_JSON, MediaType.TEXT_PLAIN})
    public final Response getConfig(final @Context HttpHeaders headers) {
      // ...
    }

    @GET
    @Path("/state")
    @Produces({MediaType.APPLICATION_JSON, MediaType.TEXT_PLAIN})
    public final Response getState(final @Context HttpHeaders headers) {
        // ....
    }

    @GET
    @Path("/introspection")
    public final Response getIntrospection(final @Context HttpHeaders headers) {
     //.....
    }

    @GET
    @Path("/idle")
    @Produces({MediaType.APPLICATION_JSON, MediaType.TEXT_PLAIN})
    public final Response peekIdle() {
     //  .......
    }
```

Each application then extends this OperationWebService and can override few methods. But the JAX-RS annotated methods are final and cannot be overriden.

```java
@Path("/ws/ops")
public class FiestaOpsWebService extends OperationWebService {
}
```

Am I missing some settings for maven-compiler-plugin?
```xml
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>io.jooby</groupId>
                            <artifactId>jooby-apt</artifactId>
                            <version>${jooby.version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <compilerArg>
                            -Ajooby.debug=true
                        </compilerArg>
                        <compilerArg>
                            -Ajooby.services=true
                        </compilerArg>
                    </compilerArgs>
                </configuration>
            </plugin>
```
I am getting output as follows.
```
Incremental annotation processing is turned ON.
Generation of service provider configuration is turned ON.
Round #0
Round #1
Found method com.mycompany.fiesta.server.ws.FileService.copy(java.lang.String,java.lang.String,java.lang.String,org.pac4j.oidc.profile.azuread.AzureAdProfile)
  route POST /ws/file/v1/copy
Found method com.mycompany.fiesta.server.ws.FileService.delete(java.lang.String,java.lang.String,java.lang.String,javax.ws.rs.core.SecurityContext)
  route POST /ws/file/v1/delete
Found method com.mycompany.fiesta.server.ws.RunLogService.retrieve(java.lang.String,org.pac4j.oidc.profile.azuread.AzureAdProfile)
  route GET /ws/v1/runlog
Found method com.mycompany.fiesta.server.ws.UploadService.upload(java.lang.String,java.lang.String,java.lang.String,org.pac4j.oidc.profile.azuread.AzureAdProfile)
  route PUT /ws/upload/execute
META-INF/services/io.jooby.MvcFactory
  com.mycompany.fiesta.server.ws.FileService$Module
  commycompany.fiesta.server.ws.RunLogService$Module
  com.mycompany.fiesta.server.ws.UploadService$Module
```

**Comment by JozefDropco** [comment]
I went through the code of jooby-apt. Issue is not within the code of Jooby but more in a design of Java Annotation Processing. JavacRoundEnvironment is only retrieving classes from current project (estimating that the libraries used were already processed by annotation processing). However there is an option for my case to extract superTypes of my classes (as they are within code base of current compile) and crawl over them. I created a pull request which is adding the support. As it can involve additional compile time for huge project I decided to enable it only optionally as additional compilerArg

**Comment by jknack** [comment]
Hi,

Can you update the issue title to describe that inherited doesn't work when base class is an external class (from another project/jar)

**Comment by jknack** [comment]
Merged your pull, thank you.

I renamed the option to "extendedLookupOfSuperTypes"

**Comment by jknack** [comment]
Also, I documented all the options (best as I can) here: https://github.com/jooby-project/jooby/commit/b2397047379e9d07a3108b81730666de18b45e8a
