### ISSUE TITLE
Settings attributes on a group of routes

### ISSUE THREAD

**Issue by whitfin** [jooby-project/jooby#2493]
After looking through the documentation, I'm not clear on whether this should work or not. It doesn't in my case, so just thought I'd check for some clarification:

```
routes(() -> {
    attribute("foo", "bar");

    get("/", ctx -> {
      ctx.getRoute().attribute("foo"); // should this be "bar"?
      return ctx;
    }):
})
```

The attribute set at the top level of a routing group should be retrievable in the child routes, is this correct?

I ask because this is definitely not working for me, but adding the attribute on the route itself does. If so, is it possible to add this feature, or clarify exactly what `routes()` is intended to be used for?

**Comment by whitfin** [comment]
I also tried to use a scoped Decorator to attach attributes and that also did not work. Guess I'm just looking for clarification; my use case is to group routes that have a specific role attached to them via an attribute - rather than annotating every route individually.

**Comment by jknack** [comment]
Hi,

You are setting a global/application attributes. Those are accessible like: `ctx.getRouter().getAttributes();`

For route attributes, try this:

```
routes(() -> {

    get("/", ctx -> {
      ctx.getRoute().attribute("foo"); // should this be "bar"?
      return ctx;
    }):
}).attribute("foo", "bar");
```

**Comment by whitfin** [comment]
@jknack thanks for the reply! Is there a way to set attributes on a group of routes? e.g. if I have:

```
routes(() -> {
    get("/1", ctx -> {

    });
    get("/2", ctx -> {

    });
    get("/3", ctx -> {

    });
});
```

Is there a way to assign an attribute to all three routes in one place, or do I have to call `.attribute()` on each route?

**Comment by jknack** [comment]
yes, it is at the end of `routes` statement:

```
routes(() -> {
    get("/1", ctx -> {

    });
    get("/2", ctx -> {

    });
    get("/3", ctx -> {

    });
}).attribute("foo", "bar");
```

or expanded if you prefer:

```
RouteSet routes = routes(() -> {
    get("/1", ctx -> {

    });
    get("/2", ctx -> {

    });
    get("/3", ctx -> {

    });
});

routes.attribute("foo", "bar");
```

Any of those will set the attributes to all the routes inside the statement
