### ISSUE TITLE
OpenApi generation for java.util.Map

### ISSUE THREAD

**Issue by Xerxekyran** [jooby-project/jooby#2505]
Hi there, I am currently in the process of upgrading Joob 1.x to 2.x and am currently facing an issue with the swagger/openapi generation. The problem occurs with routes that return a Map:

```
@GET
public Map<String, String> route1() {}
```

With Jooby 1.x this resulted in the following json:

```
"responses": {
          "200": {
            "schema": {
              "type": "object",
              "additionalProperties": {
                "type": "string"
              }}}}
```
With Jooby 2.x the whole "additionalProperties" part is missing:

```
"responses" : {
          "200" : {
            "description" : "Success",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object"
                }}}}}
```

This Json is used to generate C# classes, but with the missing "additionalProperties" part this is not a propper Map type but Object. Am I doing something wrong or is the Map type just not implemented yet for the new OpenApi generation? And yes I am aware that now it generates OpenApi 3 and not swagger 2.

Thanks for any help in advance!

**Comment by jknack** [comment]
what is `type` in Map? Not sure why 1.x generates that

**Comment by Xerxekyran** [comment]
According to https://swagger.io/docs/specification/data-models/dictionaries/: 

> A dictionary (also known as a map, hashmap or associative array) is a set of key/value pairs. OpenAPI lets you define dictionaries where the keys are strings. To define a dictionary, use type: object and use the additionalProperties keyword to specify the type of values in key/value pairs. For example, a string-to-string dictionary like this: 
> {
>   "en": "English",
>   "fr": "French"
> }
> is defined using the following schema:
> 
> type: object
> additionalProperties:
>   type: string

So "type" of th schema is correctly "object", but the additionalProperties keyword is missing the type keyword with string in this case.

**Comment by Xerxekyran** [comment]
Hi, I created a PR that could fix this issue in my opinion, what do you think?

https://github.com/jooby-project/jooby/pull/2512

**Comment by Xerxekyran** [comment]
Thanks for the merge. For me this issue is resolved and can be closed now. Looking forward to the next version and using it productively.
