### ISSUE TITLE
CorsHandler not working in Kotlin decorator

### ISSUE THREAD

**Issue by sillen102** [jooby-project/jooby#2526]
I have an issue where I can't have a decorator for roles annotations and a CorsHandler in Kotlin/Kooby with MVC.

I'm using Jooby 2.13.0 on Kotlin 1.6.10 and Java 17

The following works:

```kotlin
routes {
        decorator(CorsHandler(cors))
        // Controllers
        ...
}
```

But the following doesn't:
```kotlin
routes {
        // Processing of annotations in controller
        decorator {
            authorizeRoles()
            CorsHandler(cors)
        }
      // Controllers
     ...
}
```

I've also tried the following (but that doesn't work either):
```kotlin
routes {
        // Processing of annotations in controller
        decorator {
            decorator(CorsHandler(cors))
            authorizeRoles()
        }
       // Controllers
      ...
}
```

**Comment by jknack** [comment]
Hi,

 It isn't supposed to be used like you are trying to. You need something like:

```kt

routes {
        decorator(CorsHandler(cors))
         decorator(authorizeRoles())
        // Controllers
        ...
}
```

In the other way you tried it kotlin is trying to create an inline-decorator/lambda function:

```kt
decorator {
      // my code:
      // ...
      // move to next
      next.apply(ctx)
    }
```

**Comment by sillen102** [comment]
> ```kotlin
> routes {
>         decorator(CorsHandler(cors))
>          decorator(authorizeRoles())
>         // Controllers
>         ...
> }

That doesn't work. It only runs the first decorator and skips the second one.

**Comment by jknack** [comment]
That only could happens if you are doing a wrong/bad cors request.
