### ISSUE TITLE
dynamic session cookie in 1.x 

### ISSUE THREAD

**Issue by martinbe1io** [jooby-project/jooby#2540]
Hi, 

I run a multi domain application and want to change attributes of the session cookie based on the domain of the application. The relevant code generating the cookie seems to be the create function within ServerSessionManager https://github.com/jooby-project/jooby/blob/85a50d5e894d14068b2e90a0601481cf52a0abec/jooby/src/main/java/org/jooby/internal/ServerSessionManager.java#L265

Overriding the function create in the class ServerSessionManager and registering the modified function would solve my issue.

It would look sth like this

```
@Override
  public Session create(final Request req, final Response rsp) {
    Session session = new SessionImpl.Builder(resolver, true, store.generateID(), timeout)
        .build();
    Cookie.Definition cookie = cookie(session);
//pseudo code
  if (req.header("Host").equals("xxx") cookie.secure(true)... else cookie.secure(false)
//pseudo code end
    rsp.cookie(cookie);
    return session;
  }
```

**Question1:** Is this the right way forward? It's important to have a functional Request object at the position where I set the cookie as I need to require a registered class with the business logic of my application. 

**Question2:** How can I overwrite an existing binding in Guice 

When I try to register the new SessionManager class in myapp.java

```
use((env, config, binder) -> {
			binder.bind(SessionManager.class).to(ServerSessionManager.class);
		
			});
```

I get an error: 

```
2022-03-11 20:05:34,329]-[Hotswap] ERROR io.be1.circular.App usr= sid= - An error occurred while starting the application:
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) A binding to org.jooby.internal.SessionManager was already configured at io.be1.circular.my-app//io.be1.circular.App.lambda$new$8(App.java:429).
  at io.be1.circular.my-app//org.jooby.Jooby.lambda$bootstrap$44(Jooby.java:2971)
```

I'm not familiar with Guice how can I override the existing binding or how can I delete it? 

I'm running jooby 1.6.9

Thx Martin

**Comment by jknack** [comment]
looks good.

> How can I overwrite an existing binding in Guice

This isn't possible.
