### ISSUE TITLE
Openapi: arraySchema with byte[] is not generated correctly

### ISSUE THREAD

**Issue by Xerxekyran** [jooby-project/jooby#2542]
The  following route is not generated correctly with the openapi generator:

```
@GET
@ApiResponse(content = @Content(array = @ArraySchema (schema = @Schema(implementation = byte.class, nullable = true))))
public byte[] getStuff() {
  return new byte[0];
}
```

The resulting json file looks like this:

```
"responses" : {
          "200" : {
            "description" : "Success",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "maximum" : 127,
                    "minimum" : -128,
                    "type" : "integer",
                    "format" : "int32",
                    "nullable" : true
                  }
                }}}}}
```

But a ByteArray should be encoded as:

```
"schema" : {
  "type" : "string",
  "format" : "byte"
}
```

I looked into the generator code and found the problem. The method "ParserContext::schema(Class type)" does not know about the array type but only converts the byte type, which therefor is encoded as an IntegerSchema with limits. The last part that knows about the array type is: "OpenAPIParser::toArraySchema(ParserContext ctx, Map<String, Object> annotation)". Maybe adding a ByteSchema (create a new one just to identify it later) and then have the OpenAPIParser checking for this special case to instead convert it to an ByteArraySchema (already existing) could help?

**Comment by jknack** [comment]
Fixed it, following your suggestion... it need to be improve it later.
