### ISSUE TITLE
Logout doesn't work in version 0.13.0

### ISSUE THREAD

**Issue by silentcharacter** [jooby-project/jooby#257]
After migration to version 0.13.0 AuthLogout handler doesn't terminate session, because Optional ifSession = req.ifSession() is empty.

**Comment by jknack** [comment]
Hi,

 Bug was fixed in ```0.13.1``` see: https://github.com/jooby-project/jooby/issues/254 and commits: https://github.com/jooby-project/jooby/commit/4b0c830883f3c8c9891a1f52baa6c294fbc4eeb0

Please upgrade to ```0.13.1```.

Thanks

**Comment by silentcharacter** [comment]
Oh, sorry! Thanks a lot !

**Comment by jknack** [comment]
no problem :)
