### ISSUE TITLE
Jooby Run hot reload for Eclipse compiler should group changes in a window as one change

### ISSUE THREAD

**Issue by agentgt** [jooby-project/jooby#2577]
Often times Eclipse the compiler will change like 5 files in less than a second which will trigger five restarts!

This happens mostly if you are using annotation processors including the official jooby mvc one.

If you use the official Jooby MVC annotation processor and m2e annotation support it will always restart twice. Once for the regular class and the other for the generated Module.

```
[DEBUG] Restarting application on file change: ..snip.. WebhookController.class
Application restarts
[DEBUG] Restarting application on file change: ..snip.. WebhookController$Module.class
Application restarts
```

The problem is jooby needs to group changes that happen in a configurable window of time. Currently it restarts immediately for each file change and this happens especially for MacOS as it is using native code for polling so it is pretty fast on finding granular changes. For example traditional polling this would probably not be a problem.

I looked at the [DirectoryWatcher project](https://github.com/gmethvin/directory-watcher) and could not find a configurable option for that so we will have to do that on our end.

There are two ways I think we can fix this:

1. The typical way to do this is to use a non blocking queue like ConcurrentLinkedQueue where you just drain it with a thread set on a timer (usually ScheduledExecutor).
2. Or just drop the events when jooby is restarting.

Speaking of which JoobyRun kind of looks not threadsafe. Need a couple of volatiles and some `compareAndSet` STATE variable to check if it is restarting if we go with number 2.

Edgar @jknack  let me know if you want me to do a whole PR as I feel fairly confident I can make the change in JoobyRun but you would probably do a better job than me.

**Comment by jknack** [comment]
Hi Adam,

 Please do the changes and send a PR. Happy to look

**Comment by agentgt** [comment]
@jknack add the PR. BTW my compliments on that Run Mojo reflection unit test... it worked. I had initially forgot to add the property to RunMojo.

Anyway I made the amount of time since last change configurable as well as add some concurrency safe guards and logging.

There is in an initial delay of when the polling of the queue happens. It is 2 seconds and is not currently configurable. This is for the initial start of the application. The idea on that hard coded setting is you make a change and then immediately manually start the application and Eclipse has a delay of changing other files.
