### ISSUE TITLE
[FR] Jooby Run should fire an event on restart to be use for SSE reloads

### ISSUE THREAD

**Issue by agentgt** [jooby-project/jooby#2584]
While working on #2577 I thought to myself wouldn't be nice if the web page reloaded automatically on restart (a jooby-run file change restart... not a manual restart).

Basically the Jooby class would have an `onRestart` and the Jooby Run SERVER_REF would have a method to call that.

Then people can register their own event handlers onRestart like doing an SSE to notify the page to reload. [Here is an example of someone doing that with Javalin](https://github.com/roscrl/econicles/blob/main/src/main/java/Dev.java) 

(off topic: its also notable that they are using the JetBrains (not JRebel) hotreload DECVM which probably won't work for us since IIRC JRebel didn't work either (#1396)... well at least for MVC).

**Comment by jknack** [comment]
I did it for 1.x: https://jooby.io/v1/doc/devtools/#liveReload

LiveReload is the correct/proper way of doing it... I didn't get it back for 2.x bc it is a very UI specific feature. You need to do it on your frontend (nodejs app).

**Comment by agentgt** [comment]
I thought Live Reload was just for web assets like javascript and css. I hadn't looked at it in some time.

Did v1 fire a reload (page) on Java change?

**Comment by jknack** [comment]
Yea, for js/css changes. So do you want on Java files? I don't find it useful :D

**Comment by agentgt** [comment]
It would be sort of nice because we do server side rendering as SEO and full page rendering speed is super important for our biz.

I know most have given up on that with Java (server side rendering) and just use it for JSON REST services w/ angular/react frontend but there has been some recent resurgence of traditional service side rending like PJAX style using things like [Hotwired Turbo](https://github.com/hotwired/turbo).

**Comment by agentgt** [comment]
@jknack I can do a PR on this once #2577 is accepted as it builds on it.

However this issue is just a nice to have. #2577 is more of an actual fix as without it is pretty painful to use jooby-run regardless of auto page reloading. So hopefully it gets in the next release ... pretty please :)

**Comment by jknack** [comment]
Are you going to send a PR for this one?

I don't see how SSE can refresh the page of any ServerSidePage/Rendering, how do you think that should work?

**Comment by agentgt** [comment]
At the moment this issue is low priority and I was going to do some more research on it but I can put it in quickly if you want but it will require the other PR changes (see #2583) . 

> I don't see how SSE can refresh the page of any ServerSidePage/Rendering, how do you think that should work?

I don't think we can make it generic in that since.

It would be up to the developer to take care of the event and do something.

All I was going to do is add a public method to `Jooby` like:

```java
  /**
   * Event is fired once all components have been re-initialized from jooby-run.
   *
   * @param body Restart body.
   * @return This application.
   */
  public @Nonnull Jooby onRestarted(@Nonnull SneakyThrows.Runnable body);

```

Then for implementation details (and this is nasty but I can't think of something better) add a setter to Jooby:

```
public void setRestarted(boolean restarted);
```


Then add a method to `io.jooby.run.ServerRef`:

```java
public static void setRestart() {
   jooby.setRestart(true);
}
```

Then in JoobyRun I call `ServerRef.setRestart(true)`;

Does that make since?

Now unfortunately the developer would have to use some nasty static singleton or something to signify whatever SSE they have open but that is problem for the developer.

**Comment by agentgt** [comment]
The above though would require at least a minor version change where as just adding PR #2583 (aka #2577) would be a patch level change.

**Comment by agentgt** [comment]
Oh I'm a moron.... I get it.. the SSE connection would always be closed because we restarted.

**Comment by agentgt** [comment]
Yeah so I guess I'm going to close this. You would need something external of Jooby to make it work and that seems massively out of scope.
