### ISSUE TITLE
[openapi] Duplicated endpoints for the mounted applications

### ISSUE THREAD

**Issue by walkman90** [jooby-project/jooby#2594]
Getting back to the example from https://github.com/jooby-project/jooby/issues/2457

After enabling the openapi module generated specification duplicates some endpoints now:

![image](https://user-images.githubusercontent.com/3409070/169707372-20579512-f6b8-47f9-9e5d-f7c5f405113d.png)

- `/healthcheck` endpoint from the root application was duplicated twice, under each of the mounted applications.   
- `/api/v1/should-not-be-duplicated-under-v2` endpoint present only under the first mounted application, but duplicated under the second one in the specification   
<br/>
<br/>

**Comment by jknack** [comment]
Sort of, there are two different routes: `v1` vs `v2` isn't?

**Comment by walkman90** [comment]
https://github.com/walkman90/jooby-sandbox

App:
```java
   mvc(HealthController.class);

   mount("/api/v1", new ControllersAppV1());
   mount("/api/v2", new ControllersAppV2());
```

ControllerV1:
```java
@Path("/")
public class ControllerV1 {

  @Inject
  private WelcomeService welcomeService;

  @GET("/welcome")
  public String sayHi() {
    return welcomeService.welcome("v1");
  }

  @GET("/should-not-be-duplicated-under-v2")
  public String demo() {
    return welcomeService.welcome("v1");
  }
}
```
ControllerV2
```java
@Path("/")
public class ControllerV2 {

  @Inject
  private WelcomeService welcomeService;

  @GET("/welcome")
  public String sayHi() {
    return welcomeService.welcome("v2");
  }
}
```

The expectation is that endpoint `/should-not-be-duplicated-under-v2`  won't be shown under `/api/v2/` cause it doesn't exist in `ControllerV2 ` class.

Same for `/healthcheck` - it belongs neither to `ControllerV1` nor to `ControllerV2`

**Comment by jknack** [comment]
Oh Ok, got it.
