### ISSUE TITLE
Request context parameters

### ISSUE THREAD

**Issue by paulovictorv** [jooby-project/jooby#260]
Hi, I have a question..

Lets suppose we have an authentication method defined via ``use("app/*", ...)`` . In this method, I'm supposed to parse a JWT Token, extract the user identity and its permissions and pass it to the following methods in the chain.

Lets suppose again that the next method is defined in a MVC class using ``@POST`` . 

The question is: how can I propagate this values (user identity and permissions) to this MVC method?

If it's not possible, do you see any other way for accomplishing this mission? Or where should I start if I intend to implement this myself in Jooby? 

As an PS: Play Framework and (if I remember correctly) JSR-like have ways to accomplish this by using a 'global request context' object that is shared by all methods invoked in the chain. Maybe this is something that jooby can also have.

**Comment by jknack** [comment]
we call them: ```locals```

local vars in jooby are set with ```req.set("name", value)``` and accessible via: ```req.get("name")```

forgot about MVC routes when I added them, so the only way to access to them is by requiring the ```Request``` in your mvc methods:

```java
public Object mvc(Request req) {
  MyLocal local = req.get("name");
}
```

I will add a ```@Local``` annotation, unless you have a diff idea:

```java
public Object mvc(@Local MyLocal local) {
}
```

Cool?

**Comment by paulovictorv** [comment]
Don't know what you think, but what about something more descriptive? I was fiddling with the code and ``req.set`` and ``req.get`` looked a bit too generic and I couldn't figure out what they mean at the first glance.

What do you think of an ``RequestContext`` object that can be injected in a route handler or straight into a MVC Class instance, as a field?

So if all methods in an MVC Controller (a class with ``@Path``) need access to the ``locals`` I don't need to inject it in each method.

Also, as PS: I'm curious to how the routing actually occurs under the hood. What is a good unit test where I can put a break point so I can step through from the Server layer to the Routing and application layer?

**Comment by jknack** [comment]
don't see a clear advantage by introducing a new class: RequestContext. If you need all the locals, you can inject the Request.

Routing is documented here http://jooby.org/doc/#routes-precedence-and-order and http://jooby.org/doc/#routes-request-handling

These two tests might help you too:  https://github.com/jooby-project/jooby/blob/48a03e2f1ce50d14e63c9b9bacc9f90e453fbb69/coverage-report/src/test/java/org/jooby/FilterFeature.java https://github.com/jooby-project/jooby/blob/48a03e2f1ce50d14e63c9b9bacc9f90e453fbb69/coverage-report/src/test/java/org/jooby/StackFeature.java

**Comment by paulovictorv** [comment]
Can I Inject the Request in the class instead of in each method?

OK, I will be taking a look at these tests, thanks!

BTW, I think the ``@Local`` approach a good one, I can't think of any other way to express this.

**Comment by jknack** [comment]
They can yes.

```java
class MyController {

   @Inject
   public MyController (Request req) {
    ...
   }
}
```

If your controller is a ```@Singleton```, you need to inject a ```Provider```:

```java
@Singleton
class MyController {

   @Inject
   public MyController (Provider<Request> req) {
    ...
   }
}
```

**Comment by paulovictorv** [comment]
Cool! 

I'll try it out later today and let you know.

**Comment by jknack** [comment]
injection of local attributes was done in #278
