### ISSUE TITLE
Memory leak in Undertow (2.15.1)

### ISSUE THREAD

**Issue by vellrya** [jooby-project/jooby#2607]
Hello.

For a long time I have been trying to detect a memory leak in my program, but after tests it turns out that the leak is not in my code. I built the project with Jooby 2.13.0 and Kotlin 1.4.32 - no leaks. Then I built the project with 2.15.1 and Kotlin 1.6 without any code changes and found memory leaks again.
I'm attaching a screenshot of heap analysis in MAT, maybe I should clarify some details from MAT (I haven't dealt with memory leaks before) - I'd be happy to share it, or maybe I should report it to Undertow?

I would like to note that the leak occurs in project with active SSE usage, in my other projects (without SSE) I haven't encountered OOM even on 2.15.1 version, but I haven't investigated their memory consumption carefully either.

![image](https://user-images.githubusercontent.com/13716114/177550446-f8a6ec95-3c1e-43cd-82b7-a81185443225.png)
![image](https://user-images.githubusercontent.com/13716114/177550578-e043b500-f94f-4ce3-bbe0-dbea388b8123.png)

**Comment by vellrya** [comment]
Hello, I am still using version 2.13.0 as it has no memory leaks. Should I try version 3.x, or has there been no change related to my problem?

**Comment by jknack** [comment]
Hi, nothing changed in Jooby and I couldn't find any bug related in Undertow.

Jooby 3.x has a new version of undertow you can try that or in 2.x you can override the undertow dependencies and try that too.

**Comment by vellrya** [comment]
Thanks, as soon as 3.0.0.M3 with Kotlin 1.8.0 appears, I will try the new version)

**Comment by jknack** [comment]
jooby 2.13.0 was released with undertow 2.2.14.Final

while jooby 2.16.1 (latest 2.x) uses: undertow 2.2.19.Final and xnio 3.8.7.Final

In your project try this:
- upgrade jooby to latest 2.16.1
- then on your pom do:

```xml
<!-- https://mvnrepository.com/artifact/io.undertow/undertow-core -->
<dependency>
    <groupId>io.undertow</groupId>
    <artifactId>undertow-core</artifactId>
    <version>2.2.14.Final</version>
</dependency>

<dependency>
    <groupId>io.jooby</groupId>
    <artifactId>jooby-utow</artifactId>
    <version>2.16.1</version>
    <exclusions>
       <!-- https://mvnrepository.com/artifact/org.jboss.xnio/xnio-api -->
         <exclusion>
              <groupId>org.jboss.xnio</groupId>
              <artifactId>xnio-api</artifactId>
         </exclusion>
    </exclusions>
</dependency>
```

**Comment by vellrya** [comment]
![image](https://user-images.githubusercontent.com/13716114/211547378-124645b2-5f8a-4a6d-a6ab-4388ac8d3cb0.png)
This is the dependency tree with Kotlin 1.6.21, I'll report on the result.

**Comment by vellrya** [comment]
I tried it first with the configuration you suggested and found no memory leaks. Then fully used 2.16.1 and in 64 hours of use there is no sign of any memory leaks. Hopefully the problem has been resolved,, I'm closing the issue)

**Comment by vellrya** [comment]
Unfortuanetely, the issue has not been fixed.
This is my mistake - I changed the dependencies in the .pom file, but forgot to change the output artifacts. In fact, there were no changes and I continued to use version 2.13.0 with Kotlin 1.4.32, where there really is no memory leak.
![image](https://user-images.githubusercontent.com/13716114/214602169-da62ef3d-52a6-4c36-a249-9271ee50f373.png)

I've updated the Jooby version in the output artifact and unfortunately the problem is relevant to version 2.16.1.
In the pictures below you can see that memory usage is constantly increasing, although on 2.13.0 memory usage was in the same range and did not increase.
![image](https://user-images.githubusercontent.com/13716114/214602889-32ef1187-6561-410c-8b83-d6b39b8114d0.png)
![image](https://user-images.githubusercontent.com/13716114/214602367-b9b7ee4d-53f5-402c-9f1d-1e2c825f25b0.png)

I captured two heap snapshot with 10 min difference and here the result of dump comparison:
![image](https://user-images.githubusercontent.com/13716114/214610410-9e148430-0083-4e42-8332-f3693bdc270a.png)

Leak suspect 1 in MAT:
![image](https://user-images.githubusercontent.com/13716114/214610943-9493e8a0-068b-48e6-9935-bd631ef6b9bb.png)

Leak suspect 2 in MAT:
![image](https://user-images.githubusercontent.com/13716114/214610869-408a107a-9d47-439d-88e7-0dc2fbb64f26.png)

I'll take your recommendation (https://github.com/jooby-project/jooby/issues/2607#issuecomment-1377134016) and check for memory leaks with the correct version of the undertow and xnio dependencies in the output artifact.

**Comment by vellrya** [comment]
So, here are the results using the dependency versions you specified in https://github.com/jooby-project/jooby/issues/2607#issuecomment-1377134016: 
> [2023-01-25 19:06:23,821]-[main] INFO  io.undertow - starting server: Undertow - 2.2.14.Final
> [2023-01-25 19:06:23,828]-[main] INFO  org.xnio - XNIO version 3.8.4.Final
> [2023-01-25 19:06:23,836]-[main] INFO  org.xnio.nio - XNIO NIO Implementation Version 3.8.4.Final
> [2023-01-25 19:06:23,942]-[main] INFO  org.jboss.threads - JBoss Threads version 3.1.0.Final
> 
(Jooby 2.16.1)

![image](https://user-images.githubusercontent.com/13716114/214695057-27501ad5-9224-42ca-b16b-88e121b8d469.png)
From 51 MB heap to 230 MB (after forcing GC) in five hours.

![image](https://user-images.githubusercontent.com/13716114/214696112-ba631ee0-67f2-4a28-bd7f-c69dcbcacf4d.png)

**Comment by vellrya** [comment]
Test on Jooby 2.13.0, no memory leaks. No changes made to code - just different versions of dependencies.
![image](https://user-images.githubusercontent.com/13716114/214729072-166b0e4f-7824-40c1-8674-bb75335409b8.png)

**Comment by vellrya** [comment]
I was curious to find out in which version the memory leak appeared in order to localise the problem. 
**Jooby 2.14.0 .. 2.14.2 - no leak:**
> [2023-01-26 11:55:34,780]-[main] INFO  io.undertow - starting server: Undertow - 2.2.17.Final
> [2023-01-26 11:55:34,788]-[main] INFO  org.xnio - XNIO version 3.8.7.Final
> [2023-01-26 11:55:34,797]-[main] INFO  org.xnio.nio - XNIO NIO Implementation Version 3.8.6.Final
> [2023-01-26 11:55:34,875]-[main] INFO  org.jboss.threads - JBoss Threads version 2.3.6.Final

![image](https://user-images.githubusercontent.com/13716114/214839439-adf2310b-53f2-4587-ad48-eb3c5f9442be.png)

**Jooby 2.15.0 - leak:**

> [2023-01-26 16:45:13,888]-[main] INFO  io.undertow - starting server: Undertow - 2.2.17.Final
> [2023-01-26 16:45:13,895]-[main] INFO  org.xnio - XNIO version 3.8.7.Final
> [2023-01-26 16:45:13,913]-[main] INFO  org.xnio.nio - XNIO NIO Implementation Version 3.8.6.Final
> [2023-01-26 16:45:13,936]-[main] INFO  org.jboss.threads - JBoss Threads version 2.3.6.Final 

![image](https://user-images.githubusercontent.com/13716114/214902414-12ac9c56-00ab-4ebd-8bff-c6e5a8824874.png)

Note that dependencies have not changed.

I'm not very good at using MAT, but perhaps this will give you an idea:
![image](https://user-images.githubusercontent.com/13716114/214903381-c75559cc-4b48-49cb-8056-170c84a3f27a.png)

Option "Merge shortest paths to GC Roots" on io.undertow.server.protocol.http.HttpOpenListener$1 objects on 2.14.2 heap dump gave the following results:
![image](https://user-images.githubusercontent.com/13716114/214915710-b8fd6356-cb48-46ab-a877-c7c7da7d0a2e.png)
Where 300+18 - is a real number of opened connection.

Output for 2.15.0:
 
![image](https://user-images.githubusercontent.com/13716114/214917362-674734f3-7cf3-4450-a658-a00cdfcd7dd0.png)
![image](https://user-images.githubusercontent.com/13716114/214918051-514b1650-0e75-4ddf-b3f9-051f7ea6e137.png)
![image](https://user-images.githubusercontent.com/13716114/214918380-441219c5-2534-4d9c-a857-2124484a6871.png)

Also io.undertow.server.HttpServerExchange objects:
2.14.0
![image](https://user-images.githubusercontent.com/13716114/214919992-ab2cc5a3-c1d4-4941-a09a-8add2ac127f3.png)

2.15.0
![image](https://user-images.githubusercontent.com/13716114/214920062-5ccc86da-6ece-46d0-8d91-6e9060cf52eb.png)

Huge number of references in 2.15.0 from sun.nio.ch.WEPollSelectorImpl, and the number keeps increasing.
Since the dependencies haven't changed, is it possible that the problem is inside the JDK and related to the switch to JDK 17? This commit was made between 2.14.2 and 2.15.0: https://github.com/jooby-project/jooby/commit/f25d3aebde3a054bd32dc997b9eaaf7fd0751f58
For reference, I use JDK 17 to build and run the project.

**Comment by vellrya** [comment]
I should have tried 3.0.0.M2 from the start :)

![image](https://user-images.githubusercontent.com/13716114/214956607-5e564fff-563e-485f-b5d6-21d0c7d9ecf5.png)

Looks great.
