### ISSUE TITLE
Request URI and an associated attributes are not available from request

### ISSUE THREAD

**Issue by alexanderfinn** [jooby-project/jooby#261]
I need to be able to get the original request URI from the Request object and I do not see any method doing that. More specifically, I need to be able to get the domain name that was used in the request as that determines the customer that is accessing the system in my multi-tenant environment. 

From what I see there is an easy option of exposing a uri() method that would delegate to the underlying NativeRequest implementation. Unless there are no reasons to avoid this I would submit a pull request for this.

**Comment by jknack** [comment]
did you try ```req.hostname()```?

**Comment by alexanderfinn** [comment]
According to comments in the code the `hostname` method returns "The fully qualified name of the client or the last proxy that sent the request" whereas I need a domain name that has been used in the request URI, i.e. when user goes to "https://clientId.mydomain.com/myapp" I need to be able to read at least the "clientId.mydomain.com" part.

**Comment by jknack** [comment]
are you behind a proxy? how are you going to the ```clientId.mydomain.com``` domain?

still think you should try ```.hostname()```

**Comment by alexanderfinn** [comment]
Ok, I tried the `.hostname()` and it does in fact return the hostname that is requested. This actually means the the documentation in the code is misleading, because the method returns fully qualified name of the _server_ not the _client_. The issue can be closed otherwise.

**Comment by jknack** [comment]
Can you update doc and send a pull request?

Thanks!

**Comment by alexanderfinn** [comment]
Sure, will do.

**Comment by jknack** [comment]
done here: https://github.com/jooby-project/jooby/pull/262
