### ISSUE TITLE
404 response code when using @FormParam with FileUpload

### ISSUE THREAD

**Issue by extbe** [jooby-project/jooby#2611]
Hello.

I have an MVC API endpoint that handles file upload:

```java
@POST
@Path("/files")
public StatusCode uploadFile(@FormParam FileUpload file) {
    // process the file
    return StatusCode.OK;
}
```

If I don't specify the `file` key in request then in response I get `404` code with the following body:

```json
{
    "message": "file",
    "statusCode": 404,
    "reason": "Not Found"
}
```

Shouldn't be returned a `400`/`422` code with a message that a form parameter is missing?

The root cause of this 404 response code is here:

https://github.com/jooby-project/jooby/blob/e10afbb69cd5c2563b7d4a933112cc671b5a671a/jooby/src/main/java/io/jooby/internal/MultipartNode.java#L44-L46

https://github.com/jooby-project/jooby/blob/e10afbb69cd5c2563b7d4a933112cc671b5a671a/jooby/src/main/java/io/jooby/internal/RouterImpl.java#L698-L700

**Comment by agentgt** [comment]
It also looks like a misuse of `FileNotFoundException`. That should be just reserved for local files not found not data missing in the request.

@jknack  I saw this myself recently but didn't dig into as I thought it might have been done (404) on purpose for some security reason (ie similar to how some people use 404 instead of 403).

**Comment by jknack** [comment]
No strong opinion. Should I change it to 400?

**Comment by extbe** [comment]
Yes, I'd suggest to change it to 400. Also it would be more user-friendly if the `message` field would contain something like `the 'file' field is missing`.

Thanks!

**Comment by jknack** [comment]
cool. can you send a PR?

**Comment by extbe** [comment]
Sure
