### ISSUE TITLE
Jooby does smth that causes ZipFileClosed error while reading resource from classpath.

### ISSUE THREAD

**Issue by dmitryb-dev** [jooby-project/jooby#2660]
I have some component that takes a lot of time to get initialised and I decided to start it in parallel. Everything was ok, until I packed it to the Jar file - I start to get errors like ZipFileClosed, ClosedStream, etc.

After some debug I found out that it caused by `assets` setup function of Jooby. It works with jar inside of `ClassPathAssetSource` and this prevents other threads to read the classpath resources, so I put my component async run after assets setup.

But today I got this error again. Running everything sequentially - ok; running everything in parallel, but after Jooby has started - ok; running everything in parallel while jooby is starting too - causes random errors related to reading of classpath resource.

**Comment by jknack** [comment]
Hi,

 Can you add an example to reproduce it?

Thanks.

**Comment by dmitryb-dev** [comment]
`main.kt`
```
import io.jooby.Kooby

fun main() {
    Thread {
        while (true) {
            Thread.currentThread().contextClassLoader
                .getResourceAsStream("static/resource.txt")!!
                .readAllBytes()
            Thread.sleep(10)
        }
    }.start()

    while (true) {
        Kooby {
            assets("/*", "/static")
        }.start().stop()
        Thread.sleep(10)
    }
}
```
`resources/static/resource.txt`:
 ```
Some text
```
`logback.xml` (to hide all logs except error)
```
<configuration>
</configuration>
```
`build.gradle.kts`
```
plugins {
    application
    kotlin("jvm") version "1.7.10"
    kotlin("kapt") version "1.6.21"
    id("com.github.johnrengelman.shadow") version "7.1.2"
}
application {
    mainClass.set("MainKt")
}
repositories {
    mavenCentral()
}
dependencies {
    implementation("io.jooby:jooby:2.15.1")
    kapt("io.jooby:jooby-apt:2.15.1")
    implementation("io.jooby:jooby-netty:2.15.1")
    implementation("ch.qos.logback:logback-classic:1.2.11")
}
```

Then `gradle shadowJar` and run `java -jar project-all.jar`. It's important to run jar.

My env - Macbook M1, JVM: azul-16.0.2. It gives me several errors, sometimes `ZipFile closed`, sometimes `Inflater has been closed`, etc. It's not caused by parallel reading of resources (if you duplicate thread, but comment out jooby code - it work fine), and seems caused by `assets`.
