### ISSUE TITLE
[3.0] Reproducible byte for byte jars

### ISSUE THREAD

**Issue by agentgt** [jooby-project/jooby#2670]
@jknack Sorry I have been out of pocket lately but I noticed that the jars in v2 have timestamps in them particularly the javadoc jars.

Luckily this is an easy fix (otherwise I would do a PR) and in theory could be applied to 2.0:

https://maven.apache.org/guides/mini/guide-reproducible-builds.html

Basically put this property in the root pom.xml

```xml
<project.build.outputTimestamp>10</project.build.outputTimestamp>
```

I believe the number is an epoc timestamp and I believe both the release plugin and the versions plugin will update it accordingly.

**Comment by jknack** [comment]
@agentgt Any idea what is the error here: https://github.com/jooby-project/jooby/actions/runs/3555980125/jobs/5972995698
