### ISSUE TITLE
how to use datasource in mvc class

### ISSUE THREAD

**Issue by paliwalsam** [jooby-project/jooby#2672]
How to use hikari datasource in MVC class

**File: App.java**
=======================
package app;

import io.jooby.Jooby;
import io.jooby.hikari.HikariModule;
import javax.sql.DataSource;

public class App extends Jooby {

	{
		install(new HikariModule());
		mvc(new Usercontroller());  
		DataSource DS = require(DataSource.class);
        }

    public static void main(final String[] args) {
        runApp(args, App::new);
    }
}

**File: Usercontroller.java**
=====================
package app;

import io.jooby.Jooby;
import io.jooby.annotations.*;
import io.jooby.MediaType;
import io.jooby.Context;

@Path("/api-v1")
public class Usercontroller {

  
    public String sayHi(Context ctx) {
        // want to use Hikari DataSource here
        ctx.setResponseCode(200);
        ctx.setResponseType(MediaType.json);
        String q = ctx.query("q").value();
        return "{\"message\": \"Hello Raw Response" + q + "\"}";
    }

    @Path("/pvc")
    @GET
    public String sayHi2(Context ctx) {
        //ctx.setResponseCode(401);                  
        ctx.setResponseType(MediaType.json);
        return "{\"message\": \"Hello PVC Response\"}";
    }

}

No documentation found, plz help

**Comment by jknack** [comment]
Hi:

```java
public String sayHi(Context ctx) {
    // want to use Hikari DataSource here
    DataSource ds = ctx.require(DataSource.class);

    ctx.setResponseCode(200);
    ctx.setResponseType(MediaType.json);
    String q = ctx.query("q").value();
    return "{\"message\": \"Hello Raw Response" + q + "\"}";
}
```
