### ISSUE TITLE
Supporting automatic TLS using lets encrypt

### ISSUE THREAD

**Issue by spinscale** [jooby-project/jooby#269]
Just up for discussion (feel free to close):

I took a look at the lets encrypt/acme client stuff, cause I love the automatic HTTPS feature from the [caddy webserver](https://caddyserver.com/docs/tls), which just updates its SSL certs while running.

I just checked the three server impls (netty, jetty, undertow) and none of those support this. Given that one would rather have a generic implementation, jooby would need to support this via its `Server` interface.

An idea might be to just support this in netty for now and simply replace the ssl handler in the pipeline after updating the cert. Found a couple of java implementations (two called acme4j, one called acme-client), [this one](https://github.com/shred/acme4j/blob/master/acme4j-example/src/main/java/org/shredzone/acme4j/ClientTest.java) looks pretty straight forward.

Do you think it makes sense to take this idea further? I really like this feature, but I think it is tricky to implement.

**Comment by jknack** [comment]
it makes sense! but not familiar with lets encrypt...

will probably ask to much :) but are you able to work with this?

**Comment by jknack** [comment]
do you have any update on this?

**Comment by spinscale** [comment]
hey. didnt have time to play around with this so far... feel to close for now and reopen, once I got time to check netty out further

**Comment by jknack** [comment]
no problem, going to do a new release and just want to see where we are here.
