### ISSUE TITLE
`AccessLogger` logs miss protocol and content length when using Kotlin Coroutines

### ISSUE THREAD

**Issue by lddelchev** [jooby-project/jooby#2710]
### Issue
`io.jooby.AccessLogHandler` logs miss the protocol and the content length when using [Jooby with Coroutines](https://jooby.io/#responses-nonblocking-kotlin-coroutines)

**Expected log message:**
`17:32:17.206 INFO io.jooby.AccessLogHandler - 127.0.0.1 - - [14/Dec/2022:17:32:17 +0200] "GET /status HTTP/1.1" 200 2 1`
**Actual log message:**
`17:32:17.206 INFO io.jooby.AccessLogHandler - 127.0.0.1 - - [14/Dec/2022:17:32:17 +0200] "GET /status null" 200 - 1`

Note that the message contains `null` instead of the HTTP protocol and `-` instead of content length in bytes as the content length is `-1` when creating the log message.

### How to reproduce
[Here](https://github.com/lddelchev/jooby-accesslogger-issue-example) you can find a barebone Jooby application that reproduces the problem.

### Solution
I don't have a proper solution yet.

**Comment by jknack** [comment]
Hi,

 The issue is around after/onComplete filter. I'm working to fix all these in 3.x

See #2367 and #2031
