### ISSUE TITLE
Conform locale matching with RFC4647

### ISSUE THREAD

**Issue by authchir** [jooby-project/jooby#273]
I just got strange results from the `Result.locale()` function and took a quick look at the implementation. If my understanding is correct, it seems that the [current locale detection algorithm][1] is a little naïve:

1. Set the default locale from the configuration file as the request's locale.
2. If the header `Accept-Language` is present, split naïvely the value to create a new locale.

It would be interesting if the locale matching was conforming to the [RFC4647][2], wich is already implemented in Java's [`Locale`][3].

[1]:https://github.com/jooby-project/jooby/blob/3d2e2994ff09979fddbec44ea91b90e623928a8e/jooby/src/main/java/org/jooby/internal/RequestImpl.java#L101-L102
[2]:http://tools.ietf.org/html/rfc4647
[3]:https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#LocaleMatching

**Comment by jknack** [comment]
I built a multi-language app (traditional chinese, japanese, spanish and portugal) without major issues.

But yea is probably not enough. Are you able to send a pull request?

Thanks

**Comment by authchir** [comment]
I am just starting with Jooby, but I can give it a try. It would be an opportunity to get to know the framework better.

**Comment by jknack** [comment]
got it, last time I check that I found some diff between ```-``` used by the browser, or ```_``` used by Locale.

will review and improve it, don't worry :)

can you add an example with the error or problem you get?

thanks.

**Comment by authchir** [comment]
```Java
import java.util.Locale;
import org.jooby.Jooby;

public class Main extends Jooby {
  {
    get("/", req -> {
      Locale l = req.locale();
      return String.format(
        "Language: %s\nCountry: %s\nVariant: %s\nScript: s\n",
        l.getLanguage(),
        l.getCountry(),
        l.getVariant(),
        l.getScript());
    });
  }

  public static void main(final String[] args) throws Exception {
    new Main().start(args);
  }
}
```

```
$ curl localhost:8080 -H 'Accept-Language:"de-DE,de;q=0.8,fr-CA;q=0.7,fr;q=0.5,en-CA;q=0.3,en;q=0.2"'
Language: "de
Country: DE,DE;Q=0.8,FR
Variant: CA;q=0.7,fr;q=0.5,en
Script: s
```

**Comment by authchir** [comment]
So I gave it a try and made [some modifications][1]. `mvn compile` reports `BUILD SUCCESS`, but `mvn package` reports `BUILD FAILURE` with many errors of this kind:

```
paramNames(org.jooby.internal.RequestImplTest)  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.AssertionError: 
  Unexpected method call Injector.getInstance(interface com.typesafe.config.Config):
        at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:44)
        at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:94)
        at com.sun.proxy.$Proxy33.getInstance(Unknown Source)
        at org.jooby.internal.RequestImpl.<init>(RequestImpl.java:102)
        at org.jooby.internal.RequestImplTest.lambda$paramNames$11(RequestImplTest.java:128)
```

So it seems that I cannot extract the `Config` from the `Injector`.

[1]: https://github.com/authchir/jooby/commit/33357c522d46b62a7a7d3ee583f606009b46c02f

**Comment by jknack** [comment]
seems some tests are failing now.. but that stacktrace doesn't help to figure it out the problem.

I do have a few questions, will comment in your commit.

I can pick your changes and review the tests, sounds good?

**Comment by authchir** [comment]
Hello,
First of all, I am sorry for the time it took me to provide this feedback, but I moved to a new city and had an urgent project I had to work on.

So I experimented with the new version containing the changes and realized that my understanding of the subject still needed improvement. After some unexpected result and failure from the Jooby locale detection, I started to play directly with the Java functions. Here is the code I experimented with:

```Java
import java.util.*;

public class Main {
  public static void main(String[] args) {
    Locale[] locales = {
      Locale.forLanguageTag("fr-CA"),
      Locale.forLanguageTag("fr-FR"),
      Locale.forLanguageTag("en"),
      Locale.forLanguageTag("en-CA"),
      Locale.forLanguageTag("en-GB"),
      Locale.forLanguageTag("en-US"),
      Locale.forLanguageTag("de"),
    };
    List<Locale.LanguageRange> ranges = Locale.LanguageRange.parse(args[0]);
    List<Locale> ls = Locale.filter(ranges, Arrays.asList(locales));
    Locale l = Locale.lookup(ranges, Arrays.asList(locales));
    System.out.printf("Filter: %s\n", ls);
    System.out.printf("Lookup: %s\n", l);
  }
}
```

This program presents the three cases for the supported languages which I believe to be the more frequent:
 - Country-specific language tags only (French).
 - Country-independent and country-specific language tags (English).
 - Country-independent language tag only (German).

Here are a few tests:

```
$ java Main "fr"
Filter: [fr_CA, fr_FR]
Lookup: null
$ java Main "en"
Filter: [en, en_CA, en_GB, en_US]
Lookup: en
$ java Main "de"
Filter: [de]
Lookup: de
$ java Main "es"
Filter: []
Lookup: null
$ java Main "fr-*"
Filter: [fr_CA, fr_FR]
Lookup: fr_CA
$ java Main "en-*"
Filter: [en_CA, en_GB, en_US]
Lookup: en_CA
$ java Main "de-*"
Filter: []
Lookup: de
$ java Main "es-*"
Filter: []
Lookup: null
$ java Main "*-CA"
Filter: [fr_CA, en_CA]
Lookup: fr_CA
$ java Main "*-GB"
Filter: [en_GB]
Lookup: en_GB
$ java Main "*-DE"
Filter: []
Lookup: en
$ java Main "*-IT"
Filter: []
Lookup: en
$ java Main "de-DE"
Filter: []
Lookup: de
$ java Main "fr-BE"
Filter: []
Lookup: null
```

Here are my `Accept-Language` from my different browsers:

```Shell
Firefox: fr-CA,fr;q=0.8,en-CA;q=0.7,en;q=0.5,de-DE;q=0.3,de;q=0.2
Chromium: fr-CA,fr;q=0.8,en-CA;q=0.6,en;q=0.4,en-US;q=0.2,de-DE;q=0.2,de;q=0.2
```

So it seems that browsers do not use the functionality provide by the * selector. Considering that browsers are the most frequent clients of an HTTP server and that filtering provide some better responses in cases where the * selector is used, I believe this algorithm should be the default one in Jooby.

Also, I discovered that the `Request.locales` function is returning wrong results when the * selector is used. The problem is that the `Locale.forLanguageTag` function only truncate instead of reporting the error. For proper handling of validation, `Locale.Builder` should be used.

But I have doubts about the feature itself. The `Accept-Language` is not designed to create locales, only to filter/lookup. I also fail to see a  legitimate use case where we could want to do such a thing. Here is an alternative design proposal.

# Proposal

## Configuration

A single configuration `app.lang` which is a comma separated ordered list of supported locales. The first value is the default locale.
e.g. `en, en-CA, en-GB, fr, fr-CA, fr-FR, de`

This means that those who do not care about internationalization can simply write their language as is currently the case.
e.g. `en`

## Request interface
```
List<Locale> locales() {
  return Locale.filter(Accept-Header, localesFromConfig)
}
```
```
default Optional<Locale> locale() {
  return locales().stream().findFirst();
}
```
```
default Locale localeOrDefault() {
  return locale().orElse(defaultLocalFromConfiguration);
}
```

I think this would keep the design very simple but should satisfy the needs of the vast majority of users. Any more advance handling can be done manually based on the value of the `Accept-Language` header.

**Comment by jknack** [comment]
what about the other method we introduced already, like:

```
/**
   * Select a locale in the provided <code>collection</code> based on the content of the
   * <code>Accept-Language</code> header using the lookup algorithm of RFC4647. If the request
   * doens't specify such header, this method return the global locale:
   * <code>application.lang</code>.
   *
   * @param locales Locales to test for.
   * @return A locale.
   */
  Locale locale(Iterable<Locale> locales);
```

is still useful?

also, what if we have a empty Accept header and/or a value that isn't support by our app?

what will be the output of the new ```locales()``` method?

**Comment by authchir** [comment]
> what about the other method we introduced already
> [...]
> is still useful?

You are right. While the `List<Locale> locales()` method would work for a resource available in all locales supported in the application configuration, one can imagine that some specific resource could only be available in other resource-specific locales. It is a good idea to keep it.

> also, what if we have a empty Accept header and/or a value that isn't support by our app?
> what will be the output of the new locales() method?

Assuming the following configuration: `app.lang = "fr-CA, fr-FR, en, en-CA, en-GB, en-US, de"`.
The default locale being the first element of the list.

The former situation is twofold:

 - The header is absent.
 - The header contains some invalid value (e.g. "", "1234", "Lorem ipsum", etc.).

We handle both cases in the same way:

```
req.locales() == Collections.EMPTY_LIST
req.locale() == Optional.none()
req.localeOrDefault() == Locale.forLanguageTag("fr-CA")
```

The later corresponds the following case in my tests:

```
$ java Main "es"
Filter: []
Lookup: null
```

Spanish not being a supported locale, the returned list is empty, thus:

```
req.locales() == Collections.EMPTY_LIST
req.locale() == Optional.none()
req.localeOrDefault() == Locale.forLanguageTag("fr-CA")
```

**Comment by authchir** [comment]
I would be glad to implement a prototype, the only thing is that I don't really understand how the `Config`, `Env` et al.  works. I think reading the configuration file should parse the list and provide (somewhere) the list of locales and the default locale (i.e. first element of the list). This somewhere should obviously be available in `RequestImpl`.

**Comment by jknack** [comment]
done.

This is what we have today:

+ application.lang could be a comma separated list of lang tags
+ first defined locale is the default
+ new req.locales(BiFunction) method.
+ new req.locale(BiFunction) method.

The new methods allow users to do things like:

```
req.locales(Locale::filter)
or
req.locale(Locale::lookup)
```

Test+examples are here https://github.com/jooby-project/jooby/blob/2eca216b312f5444ffbca18b235c22813d12fad8/coverage-report/src/test/java/org/jooby/issues/Issue273b.java

**Comment by authchir** [comment]
I find the `req.locales(BiFunction)` and `req.locale(BiFunction)` functions interesting. With this API, it is to expect that most people will write a helper function such as the following for the usual case of page translation:

```Java
private static Locale negotiate(List<Locale.LanguageRange> ranges, List<Locale> locales) {
  return Locale.filter(ranges, locales).stream()
    .findFirst()
    .orElse(locales.get(0));
}

Locale locale = req.locale(negotiate);
// do stuff with locale (Handlebars, date formating, etc.)
```

All existing functions could be removed since the two newly introduce functions are so flexible but, to simplify the API for the usual case, I suggest the following modifications:

`List<Locale> locales()` can either removed or default defined as `locales(Locale::filter)`. Whichever the choice, one has to keep in mind that the current implementation sometime returns some incorrect results.

`Locale locale()` can be defined as `locale(negotiate)` (see above for the definition of `negotiatie`).

`Locale locale(Iterable<Locale> locales)` can be remove, it is made redundant by the new two functions.

`Locale locale(final Locale... locales)` can be remove, it is made redundant by the new two functions.

With those changes, the API will be lean, simple and most importantly correct.

See <https://github.com/jooby-project/jooby/pull/298>

**Comment by jknack** [comment]
> locale() = negotiate

yea I thought on this too... but wasn't sure bc was still trying to use ```locales().first()``` and the new ```locales()```  function might returns an empty list...

anyway, like what you did and I will merge your pull as soon you explain me one comment that I left in your pull request.

thanks
thanks.
