### ISSUE TITLE
OpenApi jooby-maven-plugin incorrect generation in multi module maven project

### ISSUE THREAD

**Issue by tpoll** [jooby-project/jooby#2756]
I have a multi module maven project that looks like 

```
<modules>
    <module>Api1</module>
    <module>Api2</module>
  \\... other irrelevant modules
  </modules>
  ```

Both `Api1` And `Api2`  are Jooby projects that use the MVC code generation to create APIs. Note that `Api2` does not depend on Api2.

I'm enabled OpenApi generation follow the guide in https://jooby.io/modules/openapi/ for _only_  `Api2`, specifying the single API I have in `Api2`.

However, when I generate the `OpenApi.json` file via `mvn`, the file only contains the routes defined in `Api1` and non of the routes in `Api2`

When looking at the maven debug info, I can see that both `Api1` and `Api2` are on the classpath of the classload the maven plugin is using. I'm still reading through the maven-plugin code, but my current best guess is that somehow the duplicate `io.jooby.MvcFactory` on the classpath is causing this.

If I simply remove the `Api1` module from my maven project, everything works as expected and `Api2` generates the `OpenApi.json` file correctly.

**Comment by jknack** [comment]
Hi,

 Can you please add a sample project?

Thank you

**Comment by tpoll** [comment]
https://github.com/tpoll/jooby-example Here's a sample project. Can be run via `mvn clean verify` and then inspecting the `target` folders and looking at the APIs.


Right now I'm unable to reproduce the exact behavior I described (hard to replicate my exact setup without leaking private source code).

You can see in this example though that the spec for  `Api1` is correct and then the spec for `Api2` includes every resources in the maven project.

**Comment by agentgt** [comment]
@jknack I saw this problem as well #2186 but never got around to reproduce it. IIRC it has something to do with Maven resolving dependencies.

**Comment by agentgt** [comment]
@tpoll Try `mvn -X` and see if you are getting the same exception as I got in #2186

**Comment by tpoll** [comment]
@agentgt Interesting, I'm not getting that exception when trying to run the generation locally, but I do see that same `execution of openapi resulted in exception: Cannot invoke "java.io.File.toString()" because "it" is null` exception running in our CI environment (fully fresh clone and build on a docker instance).

**Comment by kevin70** [comment]
java.io.FileNotFoundException: D:\projects\ucenter2\build\classes\java\main\META-INF\services\io.jooby.MvcFactory

**Comment by jknack** [comment]
Hi @kevin70,

I need a sample project to reproduce the issue, thank you.

**Comment by jknack** [comment]
is it a multi-module gradle setup? Make sure you don't setup openapi on project without MVC Controllers.

I tried it in single project and path/location is valid:

<img width="358" alt="Screen Shot 2023-03-07 at 9 17 34 AM" src="https://user-images.githubusercontent.com/1301129/223419836-f40a7007-92d8-4d30-95dd-260eb1fafa64.png">

**Comment by kevin70** [comment]
@jknack 
This is a single module project. jooby version is `3.0.0.M4`.
The openapi file is generated, but the corresponding request information in the controller is not generated.

![微信截图_20230308124055](https://user-images.githubusercontent.com/4236414/223621508-601165ff-4e22-4c7b-8ff9-efdf549abe70.png)

I will submit a sample project later.
