### ISSUE TITLE
Guava Cache official support

### ISSUE THREAD

**Issue by s10908** [jooby-project/jooby#276]
I've been using Guava Cache in my jooby project for ~4 months and didn't experienced any problems yet. It's part of google libs already used in jooby, so my fat-jar is a few Mb's lighter.

It would be great to see Guava Cache module official implementation - just like hazelcast or ehcache.

**Comment by jknack** [comment]
sorry, but what do you mean by official implementation? and "like hazelcast or ehcache"

**Comment by s10908** [comment]
I mean implementing `org.jooby.Jooby.Module`, `org.jooby.Session.Store` , adding some default configuration, `how to use` documentation, tests, making it as easy to use as possible and don't let people worry about version compatibility during jooby upgrade. 

Just a suggestion.

**Comment by jknack** [comment]
It make sense.

If you like jooby don't forget to star/follow the project at github/twitter.

Thanks

**Comment by s10908** [comment]
thanks. Star, watch - clicked. Twitter - done a long time ago.  That's really cool project, you're doing great job guys.

Best regards

**Comment by jknack** [comment]
Hi,

 It will be nice if you can share your development experience, what type of app you built, did you deploy to prod? and ideally your company and job title

 Want to get feedback from users and display them in the web site

Thanks
