### ISSUE TITLE
Support Virutal Threads (Discussion)

### ISSUE THREAD

**Issue by Blquinn** [jooby-project/jooby#2779]
Based on a discussion started in https://github.com/jooby-project/jooby/issues/1712 it would be nice for jooby to support project loom's virtual threads.

There is already support for virtual threads in Jetty > v10 as well as the new Helidon Nima server.

I have taken a stab at creating a server for helidon nima [here](https://github.com/Blquinn/jooby/tree/helidon-nima).

I have also created a separate jooby-jetty-loom module [here](https://github.com/Blquinn/jooby-jetty-loom).

Finally I have created a techempower benchmark for jooby-jetty-loom [here](https://github.com/Blquinn/FrameworkBenchmarks/tree/jooby-jetty-loom). I've had to base it off of the prerelease jooby 3.x.

It would be nice to get some kind of review / feedback for any or all of these branches.. thanks!

@jknack @agentgt

**Comment by jknack** [comment]
Thank you! Benjamin. Will review shortly. I'm currently in holidays.

**Comment by Blquinn** [comment]
Sounds good, enjoy your holiday!

**Comment by jknack** [comment]
@Blquinn is the Nima server created from scratch? Or is it a Netty or something based on?

I usually don't like to add more servers implementation... we do have 3 already which is more than enough. Beside Nima doesn't seem to perform well  in tech empower benchmark (compared to Netty/Undertow/Jetty)... The other major concern is that Nima owners keep the implementation over time, seems to soon to add it to Jooby.

**Comment by Blquinn** [comment]
@jknack Yea nima is a new server, it's in alpha. It is written from scratch. I don't think that's probably smart to add at the moment, perhaps it could be kept as a 3rd party module. I more did that for fun.

The Jetty server requires a much smaller change. It's basically just a 2 line change of code to support green threads.

I would like to figure out how to simply enable virtual threads in the existing Jetty module, but I'm not totally sure how to accomplish that.

**Comment by agentgt** [comment]
> Beside Nima doesn't seem to perform well in tech empower benchmark 

It hasn’t been tested yet. 

The date of the techempower last benchmark was before loom was released.


What was tested was Helidon which uses Jersey which used Grizzly (I think).

**Comment by jknack** [comment]
@agentgt There is a helidon-nima here: https://www.techempower.com/benchmarks/#section=test&runid=1e601092-a540-4651-8a6b-932aa5cdc152

but didn't look to see if was jersey/grizzly or not.

**Comment by agentgt** [comment]
Oh I didn’t know about the continuous runs. That’s pretty neat.
