### ISSUE TITLE
[3.x] jooby-apt in classpath with Maven will fail on modular projects

### ISSUE THREAD

**Issue by agentgt** [jooby-project/jooby#2780]
There is a known problem with how Maven does annotation processing if you do not specify
`<annotationProcessorPaths>` and have an annotation processor as a dependency.

Let us say I have some `module-info.java`:

```java

module blah {
    requires io.jooby;
}
```

And my maven pom for that project has a dependencies either transitive or whatever of `io.jooby:jooby-apt`.

The build will fail with `Caused by: java.lang.ClassNotFoundException: io.jooby.annotations.GET` or something similar.

Why this happens is because maven puts module `io.jooby` on the module-path when it compiles and not the classpath and unfortunately the maven annotation processor will always use the classpath unless you set `annotationProcessorPaths`. So the annotation processor will try to run and access `io.jooby` but it can't because classpath jars can't access module-path jars (mostly).

See  https://issues.apache.org/jira/browse/MCOMPILER-391

I got around this in some of my other libraries (see https://jstach.io/jstachio/#maven_classpath) by literally making my apt jars have no dependencies and referencing all classes that I generate code for by String literal.

There are several solutions:

 1. Make the annotation processor check if the io.jooby classes are available and if they are not log a warning that the dep should not be there (exclude or something similar).
 1. I guess document for it
 1. Do what I did and shade everything in one jar

I'm fairly sure the last one will not work out easily given how much the io.jooby.apt depends on io.jooby.

**Comment by jknack** [comment]
@agentgt here is the thing... I removed all jooby deps from `jooby-apt/src/main/java` and also updated module-info.java to remove `jooby` dependency... all good.

Problem is with tests... bc I want to use `jooby` dependency as test scope to run ALL existing tests but so far is just impossible to do it.

do you have a suggestion on how to solve this?

**Comment by agentgt** [comment]
At times I just do:

https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#useModulePath

`<useModulePath>false</useModulePath>`

The only issue with the above is IDEs are often too stupid to read that configuration.... so what I do sometimes is for the APT projects I just have no `module-info.java` and generate one with moditect.

I know man its a pain in the ass. There are a few more tactics but with APT it gets complicated because of various maven bugs and or IDE bugs.

Regardless what you did is the right thing and I'm grateful!

**Comment by jknack** [comment]
> I just have no module-info.java and generate one with moditect.

Thank you, this did it.
