### ISSUE TITLE
[2.x] Return type analysis fails for some (Kotlin) lambdas

### ISSUE THREAD

**Issue by zzj37** [jooby-project/jooby#2803]
One of my post router failed to respond.  After changing the final lines of the lambda from:

```kotlin
    post("some-url-path") {
        // some code omitted...

        val result = someMethod().anotherMethod()
        result         
    }
```
to:
```kotlin
    post("some-url-path") {
        // some code omitted...

        someMethod().anotherMethod()         
    }
```
The router handler works as expected.

I find that `io.jooby.internal.asm.ReturnType.localVariable()` was picking the wrong variable for the return type.  The code snippet is:

```java
// io.jooby.internal.asm.ReturnType.localVariable()
 
      LocalVariableNode var = vars.stream()
          .filter(v -> v.index == varInsn.var)
          .findFirst()
          .orElse(null);
```

While in my handler lambda there were 2 vars with the same index.  One should be used as the lambda result, the other had type `io.jooby.Context`.  Jooby picked `Context` as the return type, so the render/encoder phase was skipped.

According to [this stackoverflow answer](https://stackoverflow.com/a/54984955) 

> However the same index might be reused for different purposes inside the same method, so you also need to verify that your instruction is between the `LabelNode` instructions indicated by `LabelNode start` and `LabelNode end` instructions in the `LocalVariableNode` as well.

So picking the variable ONLY by its index is not sufficient.

A workaround to avoid local variable analysis could be using typed lambda.  Change `route()` method in `Kooby.kt`

```kotlin
   @RouterDsl
   fun route(method: String, pattern: String, handler: HandlerContext.() -> Any): Route {
        return super.route(method, pattern) { ctx -> handler(HandlerContext(ctx)) }.setHandle(handler).   
    }
```
to
```kotlin
    // using generics, so the compiler will decide the lambda return type, instead of "Any"
    @RouterDsl
    fun <T : Any> route(method: String, pattern: String, handler: HandlerContext.() -> T): Route {
        return super.route(method, pattern) { ctx -> handler(HandlerContext(ctx)) }.setHandle(handler)
    }
```
 
and other router methods (get, post...), for example:

```kotlin
    @RouterDsl
    fun <T : Any> post(pattern: String, handler: HandlerContext.() -> T): Route {
        return route(Router.POST, pattern, handler)
    }
```

As long as the handler result is not `Any`(or `Object` in java), return type analysis will be skipped.

**Comment by jknack** [comment]
Type analysis is gone in 3.x. Can you try on 3.x?

I recommend you to fallback and have a local variable set, like in your first example.

**Comment by zzj37** [comment]
Yes I have noticed the changes in 3.x. 

Could you give a hint when 3.x be finally released?  And, do you have a link to 3.x docs? 

Thank you.

**Comment by jknack** [comment]
Jooby 3.0.0.M2 is out already. This week going to release 3.0.0.M3.

There is no public doc for 3.x yet, but you won't need it. Jooby 3.x is fully compatible with 2.x. major changes are around reactive and Java 17 minimum

**Comment by zzj37** [comment]
The var set version runs without problem with 3.0.0.M2 as expected.  Thank you.

The only compatibility issue:  `decorator` dsl has changed to `use`.

**Comment by jknack** [comment]
decorator is still there, but it was deprecated.

Glad it works well.
