### ISSUE TITLE
support send websocket binary

### ISSUE THREAD

**Issue by Test-mycode** [jooby-project/jooby#2818]
i want write a nonvc server embedded in web service use jooby websocket but i can't send websocket binary

part of undertow websocket implement
  @NonNull @Override
  public WebSocket send(@NonNull byte[] message, boolean broadcast) {
    if (broadcast) {
      for (WebSocket ws : all.getOrDefault(key, Collections.emptyList())) {
        ws.send(message, false);
      }
    } else {
      if (isOpen()) {
        try {
          WebSockets.sendText(ByteBuffer.wrap(message), channel, this);
        } catch (Throwable x) {
          onError(channel, x);
        }
      } else {
        onError(
            channel, new IllegalStateException("Attempt to send a message on closed web socket"));
      }
    }
    return this;
  }

send bytearray should use binary and add an bytebuffer api will more better

**Comment by jknack** [comment]
This has been addressed in 2.16.2 or 3.0.0.M4

**Comment by Test-mycode** [comment]
i have tried 3.0.0.M4 version it only support handle binary message not send binary message

**Comment by jknack** [comment]
There is WebSocket.send(byte[]): https://github.com/jooby-project/jooby/blob/3.x/jooby/src/main/java/io/jooby/WebSocket.java#L191

**Comment by jknack** [comment]
No, wait. I know what you mean... yea I forgot about it. Will add in next release
