### ISSUE TITLE
[FR] JStachio module

### ISSUE THREAD

**Issue by agentgt** [jooby-project/jooby#2864]
Hey @jknack I have a simple PR I am working on that adds my templating engine JStachio to 3.x `jooby/modules`. 

https://github.com/jstachio/jstachio

Doc: https://jstach.io/jstachio/

JStachio is basically a mustache implementation that compiles to Java code.

The PR will be similar to the Rocker implementation as JStachio is type-safe and compiled. Currently JStachio outperforms Rocker but is negligible slower than JTE which is pretty good IMO because I consider the other two basically JSP (aka Java code pretending to be a templating). 

While I love handlebars.java for user generate templates I/we have been using my library for server side templates as well as for code generation. I would love your input on the library as I have used Handlebars.java for many years. I plan on making it 1.0.0 this month.

As you might recall I have been sort of against modules :) so it is ironic making this feature request but my hope is to perhaps to replace the techempower rocker `fortunes.html` with my library as well as offer a fast type safe templating language to Jooby.

If Jooby is too late in the 3.x RCing and/or you do not want the distraction I can try to make it a module on JStachio itself.

**Comment by jknack** [comment]
> As you might recall I have been sort of against modules :) so it is ironic making this feature request but my hope is to perhaps to replace the techempower rocker fortunes.html with my library as well as offer a fast type safe templating language to Jooby.

Indeed 😄 

Happy, to adding your JStachio as jooby module

**Comment by agentgt** [comment]
@jknack I did some perf testing with TechEmpower benchmark and replaced Rocker with JStachio without any buffering... just raw new StringBuilder on each request and it appears to perform roughly 25% faster on the Fortunes test than rocker (which is the only test that I know of that uses templating).

I have to finish making the test truly apples to apples as Rocker had some issues with JDK 17 which JStachio requires. This is also jooby 2.9. 

I thought for sure I was going to have to do some byte caching and or threadlocal magic but it appears that it doesn't matter at least on my machine.
My guess is the techniques that Rocker did with byte arrays probably matter far less with modern JVMs.

I would imagine JTE (rockers major competitor) would perform similarly better albeit I'm hoping we go with JStachio given the example by [TechEmpower is a mustache template](https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview#minimum-template).

BTW the other java frameworks cheat on the fortune test when it comes to templates.... I mean look at what officefloor did: https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/officefloor/src/woof_benchmark_woof/src/main/java/net/officefloor/benchmark/FortunesSendResponse.java

They hard coded the the bytes of the template.

**Comment by agentgt** [comment]
Hmm never mind it appears most of the difference in speed might have been JDK. JStachio will outperform Rocker but it has to use threadlocals to do it (which is what rocker is doing as well).

I'll make a branch TechEmpower Framework for you to look at later.

**Comment by jknack** [comment]
@agentgt can you help me to design the thread-local buffer thing?

In my mind:

- must be optional, off by default.
- set it up when you set execution mode EVENT_LOOP
- change the MessageEncoder

```java
Buffer encode(@NonNull Context ctx, @NonNull Object value) {
     var factory = ctx.bufferFactory();
     var buffer = factory.newBuffer();
     ....
}
```

Buffer can be wrapped as Writer, OutputStream. direct access to byte[] or bytebuffer, etc...
Factory is the one that will works as pool/cache/thread-local.

Some questions I have:

- does buffer is another abstraction over `byte[]` or `ByteBuffer`? which one is best `byte[]` or `ByteBuffer` direct?
- does buffer need to grow based on response? how much?

Thoughts?

**Comment by agentgt** [comment]
I was largely doing the Techempower testing for research on jooby 3.0 as well as jstachio to find out what model is best (for both).

The recent JDKs seem to change some things. Also sort of related but it appears Java String -> bytes is fast till extended UTF-8 characters kickin (by extended I think chars greater than 255 which techempower does test for) come into play and that is where rockers zero copy byte stuff wins vs JStachio. I might need try JTEs https://github.com/casid/jte/blob/main/jte-runtime/src/main/java/gg/jte/output/Utf8ByteOutput.java . I know that is sort of separate to designing the encoder but that is currently what I'm investigating.

My guess is the ideally a wrapper around whatever the lower level framework is using as buffer should have advantages if you can pool reuse those buffers and provide a pass through interface like a Sink (Guava's terminology). Thread affinity probably plays a part as well but I'm not sure if netty or whatever exposes that (ie give me buffer for this thread). I'm not sure how loom plays into that.

Regardless with the giant giant exception of Rocker you definitely do not want an extension point where you return `byte[]` as that implies you recreate the array. 

I'm liking the buffer factory. I think there probably should be someway to mark the buffer that it is in read mode similar to flipping bytebuffers or setting a StringBuilder to 0. Maybe make the buffer closeable to handle that but then you are recreating wrapping objects but that is less of a problem these days. 

[Let me look around to see what others are doing](https://www.techempower.com/benchmarks/#section=data-r21&l=zik0vz-6bj&test=composite). 

I would imagine most are probably just exposing some Writer like interface or a full reactive Publisher.

**Comment by agentgt** [comment]
@jknack I'm still looking into it. 

I'm sorry my last response was so long winded and confusing. I was tired that day. 

> * does buffer is another abstraction over byte[] or ByteBuffer? which one is best byte[] or ByteBuffer direct?

I think byte[] is better. The reason is statically pre-converting Strings to UTF-8 by things like Rocker (and JStachio soon). It seems more natural combining parts of the template output with System.arraycopy as well as resizing. I couldn't find examples of ByteBuffer really outperforming `byte[]` for stream like writing and it seems most HTTP low level libraries have their own buffer abstraction (e.g. Netty IIRC has its own). That being said some OutputStream abstraction as the buffer could do the byte copying I think so I'm not sure we need to even expose the underlying buffer implementation (e.g we find out with JMH which one is best):

```java
try (var b = ctx.bufferStream(someEstimateOfSize)) {
  b.write(array, offset, length);
}
```

One thing I'm not sure is how to deal with is content-length but I suppose if its entirely buffered and not reactive that is not really a problem?

**Comment by agentgt** [comment]
OK @jknack after extensive testing with modern JDKs and using techempowers benchmarks as well as some JMH on templating we can completely disregard almost everything I said previously.

* ThreadLocal buffering offers minimal speed advantages. Like 2%. In some cases not using threadlocal is faster.
* I don't think `byte[]` is the best abstraction. ByteBuffer has some advantages with `wrap` but ultimately if you cannot push data directly to lower level buffers without intermediate copying it does not matter what the abstraction is.

For high performance template engines there are two models for rendering UTF-8 with a known content-length. 

* Push - the template engine gets an OutputStream/Writer/Consumer writes to it and returns a length. The consumer-like passed in interface is essentially the buffer
* Pull - the template engine returns:
    * byte[] - slow. even if the template engine is provided a reusable array (aka buffer) this is still slow as the template engine has to recreate the array every time. Thus the templating engine is responsible for buffering.
    * InputStream - possibly faster than byte[] because static pre-encoded byte arrays do not have be copied. 
    * ReadableByteChannel - this can be the fastest provided you get access to the frameworks low level channel buffers if they offer it. This is where providing buffering mechanism matters.
* Reactive - This is basically a special pull but unlike ReadableByteChannel the buffer is not provided so the templating engine has to do it itself.


Rocker is inherently designed for `ReadableByteChannel`. See https://github.com/fizzed/rocker/blob/master/rocker-runtime/src/main/java/com/fizzed/rocker/runtime/ArrayOfByteArraysOutput.java

I suppose the MessageEncoder interface was designed before Rocker and hence why you made `ByteBufferOutput` which is more or less a [ByteArrayOutputStream](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/ByteArrayOutputStream.html). However Rocker's `ArrayOfByteArraysOutput` `toByteArray` is faster than your custom implementation based on my JMH benchmarks (this is because the system.arraycopy doesn't happen till the very end).

JTE on the other hand wants a push model: https://github.com/casid/jte/blob/523bff8ece60de3315bcfaa69cb6af70692db799/jte-runtime/src/main/java/gg/jte/output/Utf8ByteOutput.java#L291

That DataConsumer is essentially an OutputStream. 

Because of this I think `MessageEncoder` probably needs to provide both Push and Pull abstractions.

```java

interface Buffer {} // our buffer abstraction mimics ByteBuffer

// The BufferFactory could just be put in the ctx but I just separated it out
interface MessageEncoderPush { // we can bikeshed names later
  // The nullable is to indicate completed 
  void encode(Context ctx, Object o, Consumer<@Nullable Buffer> consumer, BufferFactory f) {}
}

interface ReadableByteChannelLike {
  int read(Buffer dst);
}

interface MessageEncoderPull {
  // The nullable is to indicate completed 
  ReadableByteChannelLike encode(Context ctx, Object o) {}
}

interface MessageEncoderReactive {
  Flow.Publisher<Buffer> encode(Context ctx, Object o, BufferFactory f) {}
}
```

You can see there is a huge advantage to the pull model in that the buffer factory does not have to be exposed at all.
