### ISSUE TITLE
Change log level for SSE closed event

### ISSUE THREAD

**Issue by vellrya** [jooby-project/jooby#2886]
Hello.

What do you think about lowering this event to DEBUG?
https://github.com/jooby-project/jooby/blob/022808622d660cb7cce126b9c67a19b2a683d533/modules/jooby-undertow/src/main/java/io/jooby/internal/undertow/UndertowSeverSentEmitter.java#L54

Since SSE is a one-way connection, as far as I understand it, we cannot know immediately when a client closes the connection on its side. Therefore these situations are normal and do not require WARN or INFO level logging.

**Comment by vellrya** [comment]
https://github.com/jooby-project/jooby/pull/2887#issue-1678699334

**Comment by agentgt** [comment]
@jknack I agree with the OP. My feeling with most logging OOB is that web clients should not be able to easily trigger WARNING or higher.
