### ISSUE TITLE
Configuring jetty max header size

### ISSUE THREAD

**Issue by softprops** [jooby-project/jooby#2909]
How would one go about configuring the max header size of a jooby server module like jetty?

I believe the default is 8k. I’m aware you can configure the max request body size but in my case I can’t find the documentation on how to adjust the max header size.

**Comment by jknack** [comment]
next release you can do:

```java
{
   use(
     new JettyServer()
         .configure(http -> {
             http.setRequestHeaderSize(16 * 1024);
         })
   )
}
```

**Comment by softprops** [comment]
Awesome. Great to hear!

**Comment by softprops** [comment]
incase anyone comes across this thread for the same reason the method to call is `install`, not `use`

```java
{
    install(
        new JettyServer()
            .configure(
                http -> {
                  http.setRequestHeaderSize(16 * 1_024);
                }));
}
```
