### ISSUE TITLE
kotlin: split kotlin code base into his own module

### ISSUE THREAD

**Issue by jknack** [jooby-project/jooby#2934]
Kotlin causes all kind of issues with module-info.java.

Going to move kotlin code to his own module: jooby-kotlin

**Comment by agentgt** [comment]
@jknack piggy backing on this there appears to be an issue with reproducible builds w/ moditect: https://github.com/moditect/moditect/issues/199

In the mean time I'm going to fork moditect and fix it and see if they can accept my PR as it is blocking me from releasing 1.0.0 of JStachio.

Its annoying in that the only place I need moditect is the actual annotation processor jar which is precisely the one place I want a a reproducible jar.

**Comment by rjaros** [comment]
Hello
After this change kotlin inline functions with reified type parameters are no longer avaialble (e.g. `inline fun <reified T> Context.body(): T`). Was this an intended change?

**Comment by jknack** [comment]
Hi,

 Yes, they were causing conflicts with the existing methods. I tried to described here the replacement: https://jooby.io/migration/3.x/#upgrading-from-2-x-to-3-x-method-renames
