### ISSUE TITLE
Include information about the properties used by Jooby in the documentation

### ISSUE THREAD

**Issue by felvid** [jooby-project/jooby#2981]
Jooby has some properties used by default, like `application.tmpdir`, `application.env`, etc.

But some properties do not have information in the documentation.

For example, there is no information about the `application.tmpdir` property. The developer needs to go into the source code to find out how to change the tmp directory.

So I think it would be interesting to have a list of all the properties Jooby uses along with some description. Maybe a new subsection in the section "15. Configuration".

If it makes sense, that's what I suggest. What do you think?

**Comment by jknack** [comment]
It does. Would you like to send a PR? They are just a few: https://github.com/jooby-project/jooby/blob/3.x/jooby/src/main/java/io/jooby/Environment.java#L365-L377

**Comment by felvid** [comment]
Yes, I would.

This is the complete list of properties, right?

application.charset
application.env
application.lang
application.logfile
application.package
application.pid
application.startupSummary
application.tmpdir

**Comment by felvid** [comment]
I just saw that the `___app_name__` property is also used.

**Comment by jknack** [comment]
Right:

```
application.charset
application.env
application.lang
application.logfile
application.package
application.pid
application.startupSummary
application.tmpdir
```

Please ignore `___app_name__ ` I used to quickly identify test failures

**Comment by felvid** [comment]
To show the properties I made a table with columns for the name, a short description, and the default value. What do you think?

```
[options="header"]
|===
|Property name | Description | Default value
|application.charset | Charset used by your application. | `UTF-8`
|application.env | The active https://jooby.io/#configuration-environment[environment] names. | `dev`
|application.lang | The languages your application supports. | A single locale provided by `Locale.getDefault()`.
|application.logfile | The logging configuration file your application uses. You don't need to set this property, see https://jooby.io/#configuration-logging[logging configuration]. |
|application.pid | JVM process ID. | The native process ID assigned by the operating system.
|application.startupSummary | The level of information logged during startup. |
|application.tmpdir | Temporary directory used by your application. | `tmp`
|===
```

I don't know whether `application.package` should be included, or what description to use.

**Comment by jknack** [comment]
looks good! The `application.package` is the package of your `App` (a.k.a as base package) It could be used by modules for classpath scanning, like the HibernateModule.

**Comment by felvid** [comment]
I added `application.package` to the table and sent a pull request.
