### ISSUE TITLE
gradle kotlin script configuration for jooby run plugin

### ISSUE THREAD

**Issue by softprops** [jooby-project/jooby#3049]
I'm running into some struggles getting the jooby gradle plugin set up. I think it relates to some gaps in documentation here https://jooby.io/#development-compilation-restart

I found the plugin id is actually io.jooby.run from this plugin registry page https://plugins.gradle.org/plugin/io.jooby.run

I'm now having a bit of struggle translating to groovy example to kotlin script. In the current docs it lists

```groovy
joobyRun {
  mainClassName = "${mainClassName}"                               
  restartExtensions = ["conf", "properties", "class"]              
  compileExtensions = ["java", "kt"]                               
  port = 8080                                                      
  waitTimeBeforeRestart = 500                                      
}
```

When entering this as is it seems I hit a wall immediately.

```
* What went wrong:
Script compilation errors:

  Line 53: joobyRun {
           ^ Expression 'joobyRun' cannot be invoked as a function. The function 'invoke()' is not found
```

Can you provide some pointers on how to translating this to a gradle build script using kotlin script, ie. build.gradle.kts?

**Comment by jknack** [comment]
Hi,

 The [jooby-cli](https://jooby.io/#getting-started) should generates something ready to use:

```gradle
buildscript {
  ext {
    kotlinVersion = "1.8.21"
    joobyVersion = "3.0.0"
  }
}

plugins {
  id "application"
  id "org.jetbrains.kotlin.jvm" version "1.8.21"
  id "io.jooby.run" version "${joobyVersion}"
  id "io.spring.dependency-management" version "1.1.0"
  id "com.google.osdetector" version "1.7.3"
  id "com.github.johnrengelman.shadow" version "8.1.1"
}

group "app"
version "1.0.0"
mainClassName = "app.AppKt"
sourceCompatibility = 17

repositories {
  mavenLocal()
  mavenCentral()
}

dependencyManagement {
  imports {
    mavenBom "io.jooby:jooby-bom:$joobyVersion"
  }
}

dependencies {
  implementation "io.jooby:jooby-netty"
  implementation "io.jooby:jooby-kotlin"
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.21"
  implementation "ch.qos.logback:logback-classic:1.4.7"

  testImplementation "org.junit.jupiter:junit-jupiter-api:5.9.3"
  testImplementation "org.junit.jupiter:junit-jupiter-engine:5.9.3"
  testImplementation "io.jooby:jooby-test"
  testImplementation "com.squareup.okhttp3:okhttp:4.11.0"
}

test {
  useJUnitPlatform()
}

/** Kotlin debug information: */
tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
  kotlinOptions.javaParameters = true
}


shadowJar {
  mergeServiceFiles()
}

joobyRun {
    restartExtensions = ["conf", "properties", "class"]
    compileExtensions = ["java", "kt"]
    port = 9000
    waitTimeBeforeRestart = 500
}

```

I can't help you with `build.gradle.kts` due I'm not a gradle user (either a kotlin :D). Would you submit an example of `kts`? I'm happy can add it in `jooby-cli` code generator

I will review doc in detail later.

**Comment by softprops** [comment]
Here's a slimmed down version of the configuration Im using

I use a [libs.versions.toml file](https://docs.gradle.org/current/userguide/platforms.html#sub:conventional-dependencies-toml) file

```toml
[libraries]
jooby = "io.jooby:jooby:3.0.0"
jooby-jetty = "io.jooby:jooby-jetty:3.0.0"

[plugins]
# https://plugins.gradle.org/plugin/io.jooby.run
jooby = { id = "io.jooby.run", version = "3.0.0" }
```


and then in my build.gradle.kts i'm using

```kts
plugins {
    `java-library`
    application
    alias(libs.plugins.jooby)
}

// 👀  haven't figured out how to translates this to the kotlin script style of plugin configuration
// joobyRun {
//   mainClassName = "${mainClassName}"
//   restartExtensions = ["conf", "properties", "class"] 
//   compileExtensions = ["java", "kt"]
//   port = 8080
//   waitTimeBeforeRestart = 500
// }

application {
  mainClass = "com.path.to.Main"
}

dependencies {
    implementation(libs.jooby) 
    implementation(libs.jooby.jetty)
}
```

**Comment by softprops** [comment]
I've almost got this

`lib.versions.toml`

```toml
[versions]
jooby = "3.0.0"

[libraries]
jooby = { module = "io.jooby:jooby", version.ref = "jooby" }
jooby-jetty = { module = "io.jooby:jooby-jetty", version.ref = "jooby" }

[plugins]
jooby = { id = "io.jooby.run", version.ref = "jooby" }
```

build.gradle.kts

```kts
plugins {
    alias(libs.plugins.jooby)
}

tasks { // <- tasks was needed
  joobyRun {
      mainClassName = "com.foo.Main"
      restartExtensions = listOf("conf", "properties", "class")
      compileExtensions = listOf("java")
      port = 8080
      waitTimeBeforeRestart = 500
  }
}
```

how ever my application is using preview features with the gradle `application` plugin I can run with the application with a jvm arg like so

```kts
application {
  mainClass = "com.meetup.graphql.server.GraphqlServer"
  applicationDefaultJvmArgs = listOf(
    "--enable-preview"
    )
}
```

how I can pass jvm args to joobyRun ?

**Comment by jknack** [comment]
I don't know how to setup gradle properly for this. Here is an full gradle.kts https://github.com/rjaros/jooby-issue-3061/blob/main/build.gradle.kts

may be @rjaros can help you?

**Comment by rjaros** [comment]
In my opinion you can't currently pass jvm args with `joobyRun`. The task doesn't spawn new java process, it only runs the main class with a fixed array of arguments (and only `server.port` can be configured). See:
https://github.com/jooby-project/jooby/blob/3.x/modules/jooby-run/src/main/java/io/jooby/run/JoobyRun.java#L100-L104

**Comment by jknack** [comment]
> The task doesn't spawn new java process

That is right, you can't pass such args to `joobyRun`. You need to start the Gradle process with `--enable-preview ` and also the Gradle compiler.
