### ISSUE TITLE
open-api generation doesn't work with indirection in jooby 3.0

### ISSUE THREAD

**Issue by tpoll** [jooby-project/jooby#3059]
In the process of upgrading from jooby 2.16.1 to 3.0.1, I noticed an issue with the open-api maven plugin generation.

While the plugin does run, it ends up not able to find any paths and produces a file like:

```json
{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Api1 API",
    "description" : "Api1 API description",
    "version" : "1.0"
  },
  "paths" : { }
}
```

I have a reproducible example here https://github.com/tpoll/jooby-example. You can replicate by running `mvn clean package`.

I believe the issue is related to the extra level of indirection I have via the `runner-core` module which accepts resources and then binds them directly.

If I remove the level of indirection in this project, the open-api spec seems to run fine.

**Comment by jknack** [comment]
are you sure this same project work in 2.x?

Open API has no way of finding resources when bootstrap looks like:
```
public class Api1 {
  public static void main(String[] args) {
    JoobyRunner.create(args)
      .bindResource(new Resource1())
      .bindResource(new Resource2())
      .run();
  }
}
```

**Comment by tpoll** [comment]
Yeah, I think it's actually taking advantage of the earlier issue I mentioned https://github.com/jooby-project/jooby/issues/2756 here. Since the old version seems to pick up on ever resource in the classpath, I believe it's still able to find the resources even with indirection. 

Is openapi specifically looking for the `mvc(new Controller()` calls to be in the same class where jooby itself is bootstrapped? I'm fine with adding some extra code on my side to make sure jooby can find the classes it needs to generate the openapi spec. 

I realize my use case is a little less common, but having a wrapper class around jooby is nice since I have multiple distinct APIs and we like to enforce common setup of various settings, filters, etc.

What do you think about adding an option into jooby-openapi to allow users to manually specify what resources they would like to be included. If that's something that sounds reasonable, I would be happy to try and work on a PR to add that functionality.

**Comment by jknack** [comment]
yea, I'm not sure how 2.x could do it. The #2756 and their fix was a different isssue.

OpenAPI starts from the `applicationClass` you set as property in Maven/Gradle. From there it parses and scan all possible jooby idioms to find resources.

example::
```
runApp(args, App::new) => will scan from App
```

```
runApp(args, app -> {
  // will scan from lambda
});
```

It is the same for kotlin.

> What do you think about adding an option into jooby-openapi to allow users to manually specify what resources they would like to be included. If that's something that sounds reasonable, I would be happy to try and work on a PR to add that functionality.

This sounds good. Except you need to make sure order is exactly you have in your code, but probably "order" isn't an issue for OpenAPI (not sure).
