### ISSUE TITLE
Static `assets` doesn't work with non-ASCII file names

### ISSUE THREAD

**Issue by ogrammer** [jooby-project/jooby#3070]
When using the `assets` method to declare a static directory to serve files from, I can not access the files with the browser. I think this is because maybe the requests are not properly URL-decoded.

**Comment by jknack** [comment]
Can you add an example to reproduce it?

Thank you.

**Comment by ogrammer** [comment]
Sure, first you need this structure:

```
test
  |--- test.txt - any content, just not empty so you know if it works or not
  |--- tést.txt - any content, just not empty so you know if it works or not
```

And in your Jooby app:
```java
assets("/test/*", Path.of("test"));
```

Now, attempt to access `http://localhost:port/test/test.txt`, it works fine. But, attempt to access `http://localhost:port/test/tést.txt`, and you will get a 404 error.

**Comment by jknack** [comment]
Thank you. Would you like to send a PR?

**Comment by ogrammer** [comment]
@jknack I can attempt to do so.

**Comment by ogrammer** [comment]
@jknack There are build errors with the master 3.x branch (when I tried to maven install jooby-project), `[ERROR] io.jooby.test.FeaturedTest.locales(ServerTestRunner)` I can't work on a fix for this when there are errors I have no idea about. If you could fix those errors first, that could be great.

**Comment by ogrammer** [comment]
I have written a fix but I need advice on what to do regarding `%2F` appearing in the path. `%2F` decodes to `/`, but it is clearly not part of the directory structure, so I made the decision to not decode this sequence and interpret it as just `%2F`, but maybe an exception should be thrown, or null be returned, I do not know how the standard is in this project.

**Comment by jknack** [comment]
Send a PR with tests and we can discuss from there.
