### ISSUE TITLE
Can't create an endpoint that contains non-ASCII characters

### ISSUE THREAD

**Issue by ogrammer** [jooby-project/jooby#3071]
I want to create some routes, that contain characters outside of the ASCII range. I think, this is a pretty reasonable request. All that needs to be done, is to, at compile time, encode the non-ASCII letters of endpoints (I am using the MVC style and the annotation processor). Otherwise, I need to write my endpoints with %ab%cd all over the place and it's not really nice. This could be an option as well. If my endpoints were not MVC, I would be able to just do the encoding myself, but for annotation, the values passed must be constant, so no concatenations nor encodings can be done.

I also considered adding some kind of handler or filter that would rewrite the path of my endpoints to be URI-encoded when they are added, but I am a new user of the Jooby library, and I have no idea if this is possible to do.

Example:
```java
public class Test {
    @GET(path = "/tést")
    public String test(Context ctx) { return "hello"; }
}
```

After adding this with `mvc(new Test())`, try accessing this endpoint. You will not be able to access it.

**Comment by jknack** [comment]
It suppose to work with UTF-8 chars, but something isn't working.

**Comment by jknack** [comment]
> I also considered adding some kind of handler or filter that would rewrite the path of my endpoints to be URI-encoded when they are added, but I am a new user of the Jooby library, and I have no idea if this is possible to do.

I don't get this. I need an example.

**Comment by ogrammer** [comment]
> It suppose to work with UTF-8 chars, but something isn't working.

The reason is, when HTTP requests are sent they are percent-encoded, and the percent-encoded route does not match the unencoded characters. So one of two things must be done: Encode the route path, or decode the request path. I think the 1st is better, because it will only be encoded once while the 2nd approach would need a decode for everything. Additionally, decoding carelessly could lead to improper management of URIs.

> I don't get this. I need an example.

I thought about hooking into the MVC reader or something, to adapt where the `@Path`, `@GET` and so on are read, and encode the non-ASCII characters right then and there. Probably not a good solution, but I just thought if Jooby has a feature like this I could make use of it instead of having to compile my own build of Jooby.

**Comment by jknack** [comment]
This came up before, look here https://github.com/jooby-project/jooby/issues/900#issuecomment-338430304

**Comment by ogrammer** [comment]
@jknack It is the same topic but the not the same issue, as that is talking about PathParams while I'm talking about just the path itself. There is no decoding to be done here, just that it would be really helpful if Jooby (with the help of a config option maybe) would encode the non-ASCII paths so that they get matched.
