### ISSUE TITLE
Jooby coverage-report BeanvalidationFeature fails with German locale

### ISSUE THREAD

**Issue by DerDackel** [jooby-project/jooby#309]
When building jooby from git, I get some test failures in the coverage report, which apparently are due to my locale:

```
Failed tests: 
  BeanValidationFeature.validate:56 expected:<{"manufacturer":"[may not be empty","seatCount":"must be greater than or equal to 2]"}> but was:<{"manufacturer":"[darf nicht leer sein","seatCount":"muss größer oder gleich 2 sein]"}>
  BeanValidationFeature.validate:56 expected:<{"manufacturer":"[may not be empty","seatCount":"must be greater than or equal to 2]"}> but was:<{"manufacturer":"[darf nicht leer sein","seatCount":"muss größer oder gleich 2 sein]"}>
  BeanValidationFeature.validate:56 expected:<{"manufacturer":"[may not be empty","seatCount":"must be greater than or equal to 2]"}> but was:<{"manufacturer":"[darf nicht leer sein","seatCount":"muss größer oder gleich 2 sein]"}>
```

This occurs in the most recent commit 344446c36e40a75b63fdc1a749e583c179351645. When I set my LANG to en_US, the test works fine.

Steps to reproduce:
```
~/jooby-project $ LANG=de_DE.UTF-8 mvn clean install
```

This might be a minor issue in some stupid, naggy, little coverage test, but I just thought I'd report it anyway.

**Comment by jknack** [comment]
yea multi-lang tests are always a challenge (or always forgot about them). two options:

1. can you update and fix the failing tests in a multi-lang way? I'm sure there are more tests to fix.

2. Or, we can just add a note on how to run tests in no-english computers.

Thoughts?

**Comment by DerDackel** [comment]
TBH, I couldn't really come up with anything I'm sufficiently proud of. The simplest solution I found was to hardcode the message attribute of the bean validation annotations to the US locale.

**Comment by jknack** [comment]
That's OK. but can you confirm this is the only test that fails?

Thanks

**Comment by DerDackel** [comment]
Nope, there were a few others that failed due to a missing locale setting for date formatter instances. Just amended my PR

**Comment by jknack** [comment]
cool! thanks for your pull!

if you like jooby, please start/follow us at github/twitter.
