### ISSUE TITLE
Whitespace in `headers.Accept` seems to bug out

### ISSUE THREAD

**Issue by nedtwigg** [jooby-project/jooby#3112]
My website (Jooby 3.0.5) is getting crawled by bots that put whitespace into the `Accept` header:

```
  env.headers.User-Agent=Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)
  env.headers.Accept=text/html, application/rss+xml, application/atom+xml, text/xml, text/rss+xml, application/xhtml+xml
```

Which is triggering this stacktrace:

```
  stacktrace=io.jooby.exception.NotAcceptableException: text/html, application/rss+xml, application/atom+xml, text/xml, text/rss+xml, application/xhtml+xml
	at io.jooby.MessageEncoder.lambda$static$0(MessageEncoder.java:28)
	at io.jooby.internal.HttpMessageEncoder.encode(H
```

https://github.com/jooby-project/jooby/blob/4b613504eb6c265856b2aa6035d26827eef33f00/jooby/src/main/java/io/jooby/MessageEncoder.java#L25-L28

**Comment by jknack** [comment]
The issue are not the white spaces. This is what is going on:

The default response type is set to: `text/plain`. Basically bc the default encoder: `TO_STRING` all it does is just `ctx.send(value.getBytes())`

Now with: `text/html, application/rss+xml, application/atom+xml, text/xml, text/rss+xml, application/xhtml+xml`

There is no match, resulting in `406` error.

If `text/html` is your default response type... probably is just enough to setup at the very beginning of the HTTP pipeline:

```
{
    use(next -> ctx -> {
        ctx.setDefaultResponseType("text/html");
        return next.apply(ctx);
    })
}
```

A more appropriated question is why we end-up with this encoder and none of the other encoders kick-in before?


Also:

- probably wanted to remove the media type check from TO_STRING and just render??
- and/or allow to set/override the "default" encoder

**Comment by nedtwigg** [comment]
You are correct that the problem was about content-type negotiation, thanks for pointing me in the right direction!
