### ISSUE TITLE
Add support for Gradle

### ISSUE THREAD

**Issue by authchir** [jooby-project/jooby#312]
The current state of integration with Maven is impressive and very useful. Unfortunately, this also means that users using other build tools have a suboptimal experience. [Gradle](https://gradle.org/) is one such newer tool that is becoming [increasingly popular](http://zeroturnaround.com/rebellabs/java-build-tools-part-2-a-decision-makers-comparison-of-maven-gradle-and-ant-ivy/).

I want to raise the question, whether it could be a mid-term goal, to add support for an alternative build tool. This support could range from instructions in the documentation to a plugin _à la Maven_.

As an example, here is a slightly edited version of the build script I am using for a project:

``` Groovy
apply plugin: 'application'

version = 0.1
mainClassName = "foo.bar.baz.Main"
sourceCompatibility = 1.8

// The `javac` does not have that much warning, but it is still worth enabling them all.
compileJava {
  options.compilerArgs = [ "-Werror", "-Xlint:all" ]
}

// We want a `.tgz` instead of a plain `.tar`
tasks.withType(Tar){
  compression = Compression.GZIP
}

repositories {
  mavenCentral()
}

dependencies {
  compile group: 'org.jooby', name: 'jooby', version: '0.16.0'
  compile group: 'org.jooby', name: 'jooby-netty', version: '0.16.0'
  compile group: 'com.github.jknack', name: 'handlebars', version: '4.0.4'
  compile group: 'io.jsonwebtoken', name: 'jjwt', version: '0.6.0'
}

// Override project defaults to reproduce Jooby's structure.
sourceSets.main.resources {
  srcDirs = ["conf", "public"]
}

// The `java.util.PropertyResourceBundle` class only support ISO-8859-1, so we
// must manually convert the UTF-8 files.
processResources.doLast {
  new File(destinationDir, "i18n").listFiles().each { File f ->
    if (f.getName().endsWith(".properties")) {
      def path = f.getPath()
      "native2ascii -encoding UTF-8 $path $path".execute()
    }
  }
}
```

**Comment by jknack** [comment]
It sounds great! but unfortunately I have no experience with gradle.

Can you do it? These are the areas where I think we need to work:

1. mvn archetype: creates a new archetype with a gradle build or find a alternative tool for gradle.
2. mvn jooby:run: we need to launch a Jboss modules app... All these logic is in a Maven mojo. Here I can extract that logic into something simpler (Java class with a main method)... but still we need to figure it dependencies and provide them to the launcher.
3. there are a few integrations provided as maven profile, example of these are: http://jooby.org/doc/stork http://jooby.org/doc/capsule, http://jooby.org/doc/ebean
4. parent pom handle dependencies very efficiently. This includes jooby artifacts and external dependencies. For example you can upgrade a dependency by just setting a property in your pom.xml. This is something I would like to keep.
5. doc and website need to be updated. I probably can do this.

Anyway I would love to see Gradle support as we do/have today with Maven.

**Comment by authchir** [comment]
My experience with Gradle is limited to a simple occasional use, but I am willing to write a section in the documentation describing how I use it with Jooby right now. When I have more time to investigate deeper, I could try to port some of the Maven functionality.

Concerning the documentation, it seems to be generated from the [`md/`][1] directory, but where is the generation script? And where would you like me to write a section about Gradle?

[1]: https://github.com/jooby-project/jooby/tree/master/md

**Comment by jknack** [comment]
> Concerning the documentation, it seems to be generated from the md/ directory

Correct. Just write a gradle.md file inside the ```md``` directory.

> but where is the generation script?

It is [here](https://github.com/jooby-project/site-generator/blob/master/src/main/java/org/jooby/JoobySiteGenerator.java). It generates a ```target/gh-pages``` directory, from there you need to run [jekyll serve](https://jekyllrb.com/)

Just write the md/gradle.md and I will take of adding it somewhere later.

Thanks for contributing!

**Comment by jknack** [comment]
I opened #337 it will the basis for this and lot more

**Comment by jknack** [comment]
Hi @authchir 

 I made some changes to jooby:run in master (1.0.0.CR6) and think is now possible to use it with gradle, but unfortunately I lack from experience and probably will take me too long to do it.

 The new source code is available here https://github.com/jooby-project/jooby/tree/master/jooby-run

  Checkout the new [Main](https://github.com/jooby-project/jooby/blob/master/jooby-run/src/main/java/org/jooby/run/Main.java) class

You can instantiated this new class like:

```
File[] cp = ...;
Main app = new Main(appId, mainClass, cp);
app.run();
```

This will give you the features of jooby:run (app reloads)

Challenges from gradle are:

* Includes the ```jooby-run.jar``` (and dependencies) from gradle build. This jar (and dependencies) are not part of the application dependencies, just for build.
* Resolve application dependencies from gradle build and transform them to array of files 

Are you able to work on this?

Thanks and please let me know

**Comment by jknack** [comment]
@authchir It id here: https://github.com/jooby-project/jooby/commit/0ac70c364926a5399e85e515d106284b420532f1

Think we are good. I used the jetty:run gradle task as inspiration.

Still not sure how to recompile on change... I try with ```--continuous``` but got a weird error... will test again after 1.0.0.CR6 release

Feel free to review and comment later.

**Comment by authchir** [comment]
Hello,
I upgraded and performed a quick test. I can confirm the following:
 - Hot reloading of resources (.js, .css, .hbs and .properties) is working.
 - Hot recompiling of Java classes is not working.

Moreover, I am currently executing a command on some resources when building (`native2ascii(1)`). Since the hot reloader fetch the file every time a modification is detected, I cannot run this command any more. Where should I put the call so it is executed on each resource reloading?

**Comment by jknack** [comment]
Hmm not sure where.. seems we need to trigger a gradle task while reloading but no idea how to do it.

Hot reloading is off for .js, .css and .hbs. Those files just works while running in development mode.

Thought hot reload should work with:

```
gradle --continuous joobyRun
```

But once I made a change got:

```
modified: /Users/edgar/Temp/my-app/src/main/java/com/mycompany/App.java
Change detected, executing build...


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'my-app'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve org.jooby:jooby-gradle-plugin:1.0.0.CR6.
     Required by:
         :my-app:unspecified
      > Could not resolve org.jooby:jooby-gradle-plugin:1.0.0.CR6.
         > Provider __redirected.__SAXParserFactory not found

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.033 secs

Exiting continuous build as no executed tasks declared file system inputs.
[2016-07-04 08:24:58,257]-[Thread-9] INFO  com.mycompany.App - [netty] Server stopped
```

Any idea why do I get this error?

**Comment by authchir** [comment]
> Thought hot reload should work with:
> ```
> gradle --continuous joobyRun
> ```
> But once I made a change got:
> ```
> ...
> ```
> Any idea why do I get this error?

The way I understand [the `--continuous` feature][1], it is designed for a batch build (e.g. just compilation, or compilation+test) and not for a build who's last task is to launch the executable...

I found [this thread] but it did not proved helpful.

The best would probably be to contact the Gradle's developers and ask them.

[1]: https://gradle.org/blog/feature-spotlight-continuous-build/
[2]: https://discuss.gradle.org/t/could-not-resolve-all-dependencies-for-configuration-classpath/5241/2

**Comment by jknack** [comment]
Yea, I [asked already](https://discuss.gradle.org/t/continuous-build-and-classpath-dependencies/18336)

joobyRun dependsOn compileJava.. The idea was to let gradle recompile and jooby detect the changes and restart.

You probably know this already but launching 2 gradle process works (of course)

    gradle joobyRun
    gradle --continuous compileJava

**Comment by nesl247** [comment]
Since there is the gradle plugin, any chance it could be submitted to the Gradle Plugin Portal? https://plugins.gradle.org/docs/submit for instructions.

This allows the use of the plugins DSL instead of the older apply method.
