### ISSUE TITLE
Jooby run breaks JTE Templates on Kotlin  & Gradle 

### ISSUE THREAD

**Issue by Rattlyy** [jooby-project/jooby#3194]
Source file or directory not found: /home/myname/.gradle/daemon/8.2/src/main/jte/jte-classes

**Comment by agentgt** [comment]
I don't know if this will help but I recommend upgrading Gradle to 8.4. Try it and see if it works.

**Comment by marcospereira** [comment]
I'm running on Gradle 8.4 and seeing the same problem. Running the application directly (inside IDEA, for example) works as expected but with no hot-reload.

**Comment by jknack** [comment]
There is a configuration option that you can set for now:

`public JteModule(@NonNull Path sourceDirectory, @NonNull Path classDirectory)`

So there you set explicitly which dirs you want.

The issue with gradle daemon is that the JVM reports the daemon directory as current dir (or something like that). 

Also, will be good if you show how did you setup JteModule
