### ISSUE TITLE
Some thoughts about the docs from a first timer

### ISSUE THREAD

**Issue by gel-hidden** [jooby-project/jooby#3197]
Cool project! Just started to check it out, seems awesome.

A few initial thoughts:

* Maybe the required Java version should be mentioned in the getting started section. I got a LinkageError and had to look up what java version was related to class file version 61.0.
* The DI section for dagger seems to use `net.ltgt.apt` as a plugin for kotlin. Should not `org.jetbrains.kotlin.kapt` be used? It is used when you generate a mvc project with the cli.
* I never used dagger, and I did not understand that `DaggerAppComponent` was a generated source. Is it possible to add a note to this? Maybe even link the the docs/user guide for Dagger.

**Comment by jknack** [comment]
We love jooby!

Would you like to send a PR? You can find doc here https://github.com/jooby-project/jooby/tree/3.x/docs/asciidoc

**Comment by gel-hidden** [comment]
Will do!

Also (off topic): is it possible to join the Slack channel? Is it active?

**Comment by jknack** [comment]
It is active.
