### ISSUE TITLE
Get service from service registry with dependency injection?

### ISSUE THREAD

**Issue by gel-hidden** [jooby-project/jooby#3200]
Lets say I populate the `ServiceRegistry` with some class and have a `MVC` controller like so:

```
@Path("/my-controller")
@Module
class MyController @Inject constructor(private val myService: MySerivce) {

    @GET
    fun helloWorld(ctx: Context): String {
        val serviceFromRegistry = ctx.require(ServiceFromRegistry::class.java, "serviceFromRegistry")
        ...
    }
}
```

Do I always need to use the contxt to get my service from the registry (`ServiceFromRegistry`)? Or is it possible to use guice as with the other service (`MyService`)?

**Comment by jknack** [comment]
The `@Inject` constructor will be provisioned by Guice.

Context is also a registry, so:

`
@GET
    fun helloWorld(ctx: Context): String {
        val myService = ctx.require(MyService::class.java)
        ...
    }
`

**Comment by gel-hidden** [comment]
I see, but can you do the other way around?

**Comment by jknack** [comment]
of course yea, all services from registry are exposed to Guice.

**Comment by gel-hidden** [comment]
Huh, I see. I tried it out but I got some strange Guice errors. But then I know it works. I'll figure it out! 

(I might do another PR just to clarify that this two-way communication works).

**Comment by gel-hidden** [comment]
Just to clarify, if I use `Named` i could reference the name of the service key in the registry as shown above?

**Comment by jknack** [comment]
Name is available if you set/put the service with a name: 

`registry.put(ServiceKe("name", MyService.class))`
