### ISSUE TITLE
Update GraphQLHandler to use graphQLContext instead of context

### ISSUE THREAD

**Issue by mrguamos** [jooby-project/jooby#3203]
`context` has been deprecated since 2021 maybe we should use the replacement?

<img width="736" alt="image" src="https://github.com/jooby-project/jooby/assets/8675872/73785b73-56a2-413a-b84c-ed6215bbeeab">

**Comment by jknack** [comment]
@mrguamos sure, would you like to send a PR?

**Comment by mrguamos** [comment]
> @mrguamos sure, would you like to send a PR?

sure. thanks!
