### ISSUE TITLE
Get named, optional query param

### ISSUE THREAD

**Issue by MrRawbin** [jooby-project/jooby#3290]
I am aware that it is possible to get optional query params by `ctx.queryMultimap() ` and then look for the existence of the wanted param, but I think it would be nice to have the option of using something like `ctx.optionalQuery(name)` to get an optional query param by name.

**Comment by jknack** [comment]
Try this:

 `ctx.query(name).value(null)`

 `ctx.query(name).toOptional()`

**Comment by MrRawbin** [comment]
Great! That is very nice. I think this should be clearly documented. Want me to give it a shot?

**Comment by jknack** [comment]
You are welcome to improve it: 

- https://jooby.io/#context-value-api-default-and-optional-value
- Source: https://github.com/jooby-project/jooby/blob/3.x/docs/asciidoc/value-api.adoc#default-and-optional-value
