### ISSUE TITLE
Support Java 21 for Jooby 1.x

### ISSUE THREAD

**Issue by pushkinser** [jooby-project/jooby#3359]
Hi teams,

Is there a technical possibility to support the current version of java by analogy with this issue https://github.com/jooby-project/jooby/issues/3195? 

I can do a PR if you give the green light

**Comment by pushkinser** [comment]
Hey Edgar @jknack, 

Why can't we support small changes in Jooby 1.x version? I'm all for making a merge request. 

Best, Sergey

**Comment by jknack** [comment]
Hi @pushkinser,

 Jooby 1.x is just too old and it is not supported anymore. You need to move/migrate to 2.x/3.x
