### ISSUE TITLE
decoders not shared to the mounted routes

### ISSUE THREAD

**Issue by kliushnichenko** [jooby-project/jooby#3400]
Unlike jooby2 in 3.x decoders installed in the main app is not applied to the routes were mounted from another app

```java
class AppA extends Jooby {
    {
        post("/pets", ctx -> ctx.body(Pet.class));
    }
}

class MainApp extends Jooby {
    {
       install(new JacksonModule());
       mount(new AppA());
    }
  }
```

Now hit `post("/pets")` and you will catch `UnsupportedMediaType` error, cause Jackson decoder was overridden at the copy route stage.
Hope it wasn't changed intentionally and we can return the Jooby2 behaviour

**Comment by jknack** [comment]
there is a slightly difference between `mount(Router)` and `install(Router)`. In your case `install` should work. Mount only import routes into the main app.

**Comment by kliushnichenko** [comment]
yeah, indeed `install` works as expected, thank you
