### ISSUE TITLE
Reload TLS certificate from disk without server restart

### ISSUE THREAD

**Issue by U1F984** [jooby-project/jooby#3410]
We would like to change our short-lived certificates without restarting the server.

Previous work in other projects: https://github.com/Hakky54/sslcontext-kickstart?tab=readme-ov-file#support-for-reloading-ssl-at-runtime

**Comment by U1F984** [comment]
Alternative implementation idea: the SSLContext could be set as an option into the server context, overriding any other SSL config. I would be willing to contribute this alternative, as I think the original idea requires much deeper integration.

**Comment by jknack** [comment]
like it, yea. Please send a PR
