### ISSUE TITLE
Is there built in support for subdomains

### ISSUE THREAD

**Issue by ogrammer** [jooby-project/jooby#3418]
Is it possible for a subdomain under the same domain to have different routes? It would be necessary to use the "Host" http header. Making a hidden path for each subdomain page and then writing a handler to modify the request path if "Host" is the subdomain seems like a possible solution, though I'm not sure whether it will work.

**Comment by jknack** [comment]
There is something: https://jooby.io/#router-dynamic-routing. That method allow you to do whatever you want before dispatching to a router.

There is one specialized version that rely on domain (Host header): https://github.com/jooby-project/jooby/blob/3.x/jooby/src/main/java/io/jooby/Router.java#L309

**Comment by ogrammer** [comment]
That is great thank you

**Comment by ogrammer** [comment]
@jknack Hi, I have just found out that there is a method install(path, supplier<jooby>). This seems very useful but it does not seem to support predicates other than path, is there a way to use that with domain?

**Comment by ogrammer** [comment]
I have realised that there is a discussions section, sorry for having made an issue instead.

**Comment by ogrammer** [comment]
@jknack?

**Comment by edgarespinawt** [comment]
That's right: `install` doesn't support routing predicates. Are you sure you need `install` and not simply `moun`?
