### ISSUE TITLE
jooby-pac4j oidc: never renew profile?

### ISSUE THREAD

**Issue by tkarlinski** [jooby-project/jooby#3425]
Hello,

I'm having an issue with renewing the profile after  has expired (for OIDC flow).

The problem arises because the profile is cleared every time in the ProfileManager, as the class has not set the config. Consequently, the profile is never renewed.

Take a look at the code:
In [Pac4JModule](https://github.com/jooby-project/jooby/blob/3.x/modules/jooby-pac4j/src/main/java/io/jooby/pac4j/Pac4jModule.java#L584) the current user is set as follows:
```java
application.setCurrentUser(new Pac4jCurrentUser());
```

The current user class has the following method:
```java
  public Object apply(Context ctx) {
    Pac4jContext pac4jContext = Pac4jContext.create(ctx);
    ProfileManager pm = new ProfileManager(pac4jContext, pac4jContext.getSessionStore());
    return pm.getProfile().orElse(null);
  }
```
Here, we have an initialized [ProfileManager](https://github.com/pac4j/pac4j/blob/5.7.x/pac4j-core/src/main/java/org/pac4j/core/profile/ProfileManager.java) without a config. The config should probably be set using the public method of ProfileManager setConfig(Config config).

The getProfile method calls the ``removeOrRenewExpiredProfiles`` method in ``ProfileManager``, which includes the following condition:
```java
    protected void removeOrRenewExpiredProfiles(final LinkedHashMap<String, UserProfile> profiles, final boolean readFromSession) {
        var profilesUpdated = false;
        for (final var entry : profiles.entrySet()) {
            final var key = entry.getKey();
            final var profile = entry.getValue();
            if (profile.isExpired()) {
                LOGGER.debug("Expired profile: {}", profile);
                profilesUpdated = true;
                profiles.remove(key);
                if (config != null && profile.getClientName() != null) {
                    final var client = config.getClients().findClient(profile.getClientName());
                    if (client.isPresent()) {
                        try {
                            final var newProfile = client.get().renewUserProfile(profile, context, sessionStore);
                            if (newProfile.isPresent()) {
                                LOGGER.debug("Renewed by profile: {}", newProfile);
                                profiles.put(key, newProfile.get());
                            }
                        } catch (final RuntimeException e) {
                            logger.error("Unable to renew the user profile for key: {}", key, e);
                        }
                    }
                }
            }
        }
        if (profilesUpdated) {
            saveAll(profiles, readFromSession);
        }
    }
```
In the method you see the condition
```java
if (config != null && profile.getClientName() != null) {
```
I suspect that this condition will always be null when ProfileManager is called by Pac4jCurrentUser, resulting in the profile always being cleared.

Could you please advise me on how to bypass this problem? Or perhaps it should be fixed?

Thank you.

**Comment by tkarlinski** [comment]
ps. The setCurrentUser we can't override because the method add new "current user" instead of set 
```java
application.setCurrentUser(new Pac4jCurrentUser());
```

**Comment by edgarespinawt** [comment]
Would you like to send a PR?

Thanks

**Comment by tkarlinski** [comment]
Ok, I created PR. That works for me.
