### ISSUE TITLE
How to set application environment when using joobyRun?

### ISSUE THREAD

**Issue by nonetallt** [jooby-project/jooby#3438]
### Question

Is it possible to set the application environment when executing the application via `./gradlew joobyRun`? 

There's an example in the docs for `java -jar myapp.jar application.env=foo` but I couldn't find any way of passing the argument to `joobyRun` task. Based on the `JoobyRunOptions` class in the module source code, I guess `application.env` is not one of the supported options?

How should I set the environment to use my local testing configuration while using `joobyRun`?

**Comment by jknack** [comment]
Try with JVM variable: `./gradlew -Dapplication.env=dev joobyRun`

**Comment by nonetallt** [comment]
> Try with JVM variable: `./gradlew -Dapplication.env=dev joobyRun`

Thank you. 

I tried running `./gradlew -Dapplication.env=local joobyRun` but ended up with error: `Task '.env=local' not found in root project`.

I managed to fix this by quoting the variable: `./gradlew -D"application.env=local" joobyRun`.
