### ISSUE TITLE
Jooby 2.16.3: Guice version has issues with Java 21

### ISSUE THREAD

**Issue by imeszaros** [jooby-project/jooby#3441]
The current Guice version (5.0.1) included with the latest 2.16.3 release has some issues with Java 21. It works fine in most cases, but if there's a provisioning error Guice is not able to produce the correct error message but instead fails with some "bytecode version not supported" error.

Quoted from the Guice 6.0.0 change notes:

> Support Java 21 (via updating ASM to 9.5 and other changes). ([#1671](https://github.com/google/guice/issues/1671), [#1657](https://github.com/google/guice/issues/1657), [#1654](https://github.com/google/guice/issues/1654))

I forced Gradle to pull 6.0.0 to my project and indeed it solved the problem and I was able to see the real issue.

**Comment by jknack** [comment]
jooby 2.16.4 is out in central. Please try and let me know... it was a bit hard to make a new release on my new laptop (modern java + mac aarm). The gradle plugin failed to release/publish, will try again shortly.

**Comment by jknack** [comment]
Gradle plugins published.
