### ISSUE TITLE
How does Jooby handle gzip encoding for requests and responses?

### ISSUE THREAD

**Issue by nonetallt** [jooby-project/jooby#3443]
From the [documentation](https://jooby.io/#server-options), I noticed that `ServerOptions` has a method called [setCompressionLevel](https://www.javadoc.io/doc/io.jooby/jooby/latest/io.jooby/io/jooby/ServerOptions.html#setCompressionLevel(java.lang.Integer)).

The documentation from the javadoc for the method is as such:

> Set compression level to use while producing gzip responses.
   Gzip is off by default (compression level is null).

This raises some questions regarding the gzip support:

1) When compression level has a non-null value, are *all* responses encoded or only ones for requests that have an `accept-encoding: gzip` header?

2) Can Jooby automatically decode incoming requests with a `content-encoding: gzip` header? If not, what is the recommended way of achieving this? My current solution is to read from input stream produced by `GZIPInputStream(context.body().stream()))` but I have a suspicion that the performance of this approach isn't ideal.

PS. I'm using netty as the underlying server in case that's relevant.

**Comment by jknack** [comment]
Hi

1. Only the one that request gzip: `accept-encoding: gzip`
2. there is nothing built in for gzip requests

**Comment by nonetallt** [comment]
> Hi
> 
>     1. Only the one that request gzip: `accept-encoding: gzip`
> 
>     2. there is nothing built in for gzip requests

Thank you for the clarification.
