### ISSUE TITLE
Java strings not escaped properly in mvc source code generation.

### ISSUE THREAD

**Issue by tpoll** [jooby-project/jooby#3455]
Example:

Take an endpoint like 

```
  @GET("/required-string-param")
  @Schema(description = "test\"ttttt")
  public String requiredStringParam(@QueryParam @NonNull String value) {
    return value;
  }
 ```
 
 Jooby apt generation creates a file that includes the line 
 
 ```
 java.util.Map.entry("Schema.description", "test"ttttt"),
```

This produces and invalid java file since we have a dangling `"`.

It seems like https://github.com/jooby-project/jooby/blob/ea03e757de238474e1304fcaaacab43f1589e5ca/modules/jooby-apt/src/main/java/io/jooby/internal/apt/RouteAttributesGenerator.java#L93 this line needs to be updated to ensure that escaped characters our output in the string. e.g. we need to transform the string to be `"\\\""`. There's a bunch more cases that would need to be handled too (see https://docs.oracle.com/javase/specs/jls/se22/html/jls-3.html#jls-3.10.7)

**Comment by tpoll** [comment]
Thanks for the fast fix!

**Comment by jknack** [comment]
You're welcome. I'll release later today/tomorrow.
