### ISSUE TITLE
Mutant API design question

### ISSUE THREAD

**Issue by authchir** [jooby-project/jooby#348]
I was reviewing some of my code and realized that much of it consists of instances of the following:

```Java
Optional<String> opt = req.header("Some-Http-Header").toOptional();
Optional<String> opt = req.cookie("some-cookie").toOptional();
```

This led me to explore the `Mutant` interface in more details and it seems to me that it consists mainly of functions to convert from `String` to other types. I am interested to learn more about the motivations, uses and future of this interface.

I am personally a fan of lean APIs and I think it is a desirable goal, to use as much of the standard library as possible, since everybody is already expected to know its components and how they work. It seems to me that many uses of this interface could be made simpler and more explicit this way.

e.g. Assuming the `cookie` functions would return an `Optional<String>` directly, we know that the following code will throw a `NumberFormatException` if there is some non-integer in the cookie.

```Java
Optional<Integer> opt = req.cookie("some-cookie").map(Integer::parseInt);
```

Maybe there are some important and obvious design reasons that I fail to see, that’s why I am asking the question.

**Comment by jknack** [comment]
It is a valid argument, but I do find more simple and powerful the Mutant API. For example, your int cookie can be express as:

```java
Optional<Integer> opt = req.cookie("some-cookie").toOptional(Integer.class);
```
Or via ```intValue```

```java
int someCookie = req.cookie("some-cookie").intValue();

// alternative with a default value
int someCookie = req.cookie("some-cookie").intValue(6);
```

The real power of the Mutant API probably more visible in will dealing with HTTP params. For example, if you expect for an ```Integer``` and ```parseInt``` throws a NumberFormatException we treat that error as a ```BAD_REQUEST(400)```

Even more let said you POST a form with urlenconded or multipart... but for some business decision you have a param encoded as JSON, then you can do things like:

```
int id = req.param("id").intValue(); // normal param
MyObject json = req.param("myobject").to(MyObject, "json"); // form param in json format
```

Another example is in header and date params. Dates in header have a special format or date pattern.. don't want user to deal with that. Want they to just get a date:

```
Date date = req.header("mydate").to(Date.class);
```

Finally the Mutant API is the basis for MVC route and method params injection:

```
public Object(int id, String name, Optional<Status> status) {
  ....
}
```

This is translated to ```req.param``` call and want/need the same behaviour in script or mvc routes.

Hope it makes more sense now.

**Comment by authchir** [comment]
Thanks, it is good explanation.

I do realize that request parameters are a different situation (that's why I did not mention them in my initial question). An example of the way I am using them is to configure a Handlebars object with the correct locale (for the `i18n` helper) on every request. I store it in a request parameter and extract it at the beginning of my real request handler. Such behaviour is fundamentally different of cookies and HTTP headers, because there is no (de)serialization process involved.

On the other hand, HTTP headers and cookies must always be deserialized. To parse a date, I use something similar to this:

```Java
Optional<ZonedDateTime> opt = req.header("mydate").toOptional().map(str ->
  ZonedDateTime.parse(str, DateTimeFormatter.RFC_1123_DATE_TIME));
```

I think your date example is a very good one because it: a) is much more complex than my integer example and b) exposes another difficulty: there are different formats and different classes. What if I have a date in ISO 8601? What if I have a date in RFC 1123? What if I have a date in some horrible country-specific format? What if I want to use some third party date class? What if I want to use the old `Date` class? What if I want to use a `ZonedDateTime` or just a `ZonedDate`?

By the way, I just tried to the `to(ZonedDateTime.class)` and got a

```
Bad Request(400): No parser for java.time.ZonedDateTime
```

**Comment by jknack** [comment]
Exactly. The ```correct way``` of doing it is via a [custom parser](http://localhost:4000/doc/#parser-and-renderer-parser-custom-parser)

```java
{
  parser((type, ctx) -> {
    if (type.getRawType() == ZonedDateTime.class) {
      return ctx.param(values -> ZonedDateTime.parse(values.get(0), DateTimeFormatter.RFC_1123_DATE_TIME);
    }
    return ctx.next();
  });

  get("/mydate", req -> {
      ZonedDateTime zdt = req.header("mydate").toOptional(ZonedDateTime.class);
  }); 

```

It will be nice if you raise a issue for built-in date parsers (or ideally sent a pull request):

```java
import static org.jooby.Parser.zonedDate;
{
   parser(zonedDate(DateTimeFormatter.RFC_1123_DATE_TIME));
}
```

About your use case and:

>  because there is no (de)serialization process involved.

You're right and you are looking for request locals. I successfully implement a ```hbs helper``` in one of my application, doing something like this:

```java
{
    use("GET", "*", (req, rsp) -> {
       // get locale from cookie and save in local scope
       String locale = req.cookie("locale").value("en");
       req.set("lang", locale);
    });

   use(new Hbs().doWith((hbs, conf) -> {
      hbs.registerHelper("msg", (key, opts) -> {
         // get back lang from request local scope
         String lang = opts.get("lang", "en");
         // dynamically create "locale" hash required by i18n
         Options i18nopts = new Options.Builder(opts.handlebars, "i18n", TagType.VAR, opts.context, opts.fn)
              .setHash(ImmutableMap.of("locale", lang))
              .build();
        // call i18n
        return I18nHelper.i18n.apply(key.toString(), i18nopts);
   });
}
```

There is a bit involve here.. but from your views you can set do:
```
{{msg 'mykey'}}
```

So, if you don't need (de)serialize a value, then you need [req locals](http://jooby.org/doc/#request-local-variables)

Also, the handlebars module give you access to [request local variables](http://jooby.org/doc/hbs/#handlebars-req-locals)
