### ISSUE TITLE
How to validate parameters using Jooby?

### ISSUE THREAD

**Issue by zsf513** [jooby-project/jooby#3496]
I couldn't find how to validate request parameters in the documentation.

**Comment by jknack** [comment]
There is nothing yet in 3.x. We started a discussion last week: https://github.com/jooby-project/jooby/pull/3494

**Comment by agentgt** [comment]
My comments on this are here https://github.com/jooby-project/jooby/pull/3494#issuecomment-2278170227 . I'm not sure if this will be future place for this kind of discussion so I linked it.
