### ISSUE TITLE
jooby-run: Hot reloading not working when .class file is changed by external process

### ISSUE THREAD

**Issue by blazmrak** [jooby-project/jooby#3505]
I'm using neovim + LazyVim and jooby maven plugin restarts the server, but does not pick up the code changes. The docs say that the plugin is looking for `.classpath` file and leaves the compilation to eclipse. I'm using jdtls, which should compile the changes I think, but changes are not visible (even after running jdtls.compile manually and getting "compilation completed" message). Do I have incorrect configuration or am missing something obvious?

**Comment by jknack** [comment]
try without `.classpath` file and see if works.

**Comment by blazmrak** [comment]
When I delete the `.classpath` it works. But when running jdtls (Eclipse language server) it doesn't, as it autocreates `.classpath`. Would it be possible to add an option to override this behavior?

**Comment by jknack** [comment]
where jdtls ouput class files?

**Comment by blazmrak** [comment]
At the root, I'm guessing the same as Eclipse, since it's the same language server that Eclipse uses. Sure, I'll have minimal repro up in a sec.

**Comment by blazmrak** [comment]
Here it is https://github.com/blazmrak/joobytest

**Comment by blazmrak** [comment]
I added `jdtls-build` branch, where I rmrf'd  target and bin and just opened the editor, no leftover maven build.

**Comment by jknack** [comment]
So, is eclipse/jdtls compiling source code? It should works as long as compiled code is save on `target/classes`. Try to run jooby run in debug mode and check if you see something on logs: `mvn jooby:run -X`

**Comment by blazmrak** [comment]
Yes, it should compile, it says it compiles (I even ran it manually), I ran jooby in debug, it just prints what has changed, but the change is not visible. Here is the log

```
[DEBUG] Jooby is now state: RUNNING
[DEBUG] ENTRY_MODIFY [...joobytest/target/classes/app/App.class]
[DEBUG] ENTRY_MODIFY [...joobytest/target/classes/application.conf]
[DEBUG] ENTRY_MODIFY [...joobytest/target/classes/logback.xml]
[DEBUG] ENTRY_MODIFY [...joobytest/target/classes/app/App.class]
[DEBUG] -> MODIFY [...joobytest/target/classes/app/App.class] (isDirectory: false)
[DEBUG] Restarting application on file change: ...joobytest/target/classes/app/App.class
[DEBUG] ENTRY_MODIFY [...joobytest/target/classes/application.conf]
[DEBUG] ENTRY_MODIFY [...joobytest/target/classes/logback.xml]
[DEBUG] Closing server. state: RESTART
[2024-08-19 22:29:14,403]-[pool-2-thread-1] INFO  app.App - Stopped App
[2024-08-19 22:29:14,417]-[pool-2-thread-1] INFO  app.App - App (dev) started
[2024-08-19 22:29:14,417]-[pool-2-thread-1] INFO  app.App - routes: 

  GET /

listening on:
  http://localhost:8080/
```

**Comment by blazmrak** [comment]
I'm losing it, it's way too late for me, but I think you are never unloading the module if it is not compiled. I might be wrong on this, as I didn't try it out, but just looked at the code on github. I can fork it and try to change it to confirm, and maybe make a PR if I find anything...

https://github.com/jooby-project/jooby/blob/d2f41ddf5a0ee07d777969b3c33550202617dfd0/modules/jooby-run/src/main/java/io/jooby/run/JoobyRun.java#L438

**Comment by jknack** [comment]
Yes! You're right. We never fired the restart wonder when started to failed 🤔
