### ISSUE TITLE
Support `Problem Details for HTTP APIs` RFC7807

### ISSUE THREAD

**Issue by kliushnichenko** [jooby-project/jooby#3543]
`Problem Details` is a well-known and widely adopted standard.
Described in [rfc7807](https://www.rfc-editor.org/rfc/rfc7807) (and a bit improved [rfc9457](https://www.rfc-editor.org/rfc/rfc9457.html))
It defines a "problem detail" to carry machine-readable details of errors in HTTP response content to avoid the need to define new error response formats for HTTP APIs.

@jknack would you mind if I send PR to support it?

**Comment by jknack** [comment]
Sure, go for it
