### ISSUE TITLE
Does Jooby support R2DBC?

### ISSUE THREAD

**Issue by jtlapp** [jooby-project/jooby#3548]
I have not been able to get Jooby to use R2DBC. I think I deceived myself seeing that Jooby supports Monos, but revisiting the docs, it seems that it only supports Reactor Monos.

I'm not calling for support of R2DBC. I happened to implement it for Spring and thought I'd try it out in Jooby to compare performance.

I've tried a few approaches, including the following two:

```java
    // My expectation of what should work in Jooby

    @POST("/query/{queryName}")
    public Mono<ResponseEntity<String>> query(
            String queryName, String jsonBody, Context ctx
    ) {
        return sharedQueryRepo.get(queryName)
                .flatMap(sq -> sq.executeUsingGson(db, jsonBody))
                .map(json -> ResponseEntity.ok().body(json))
                .onErrorResume(e -> Mono.just(ResponseEntity
                        .status(HttpStatus.INTERNAL_SERVER_ERROR)
                        .body(toErrorJson(queryName, e))));
    }
```

```java
    // works in Webflux with Spring annotation

    @POST("/query/{queryName}")
    public Mono<String> query(String queryName, String jsonBody, Context ctx) {
        return sharedQueryRepo.get(queryName)
                .flatMap(sq -> sq.executeUsingGson(db, jsonBody))
                .onErrorResume(e -> {
                    ctx.setResponseCode(StatusCode.SERVER_ERROR);
                    return Mono.just(toErrorJson(queryName, e));
                });
    }
```

Jooby tries to serialize the type of object returned by the last method. In the above cases, the body of the response ends up being `MonoOnErrorResume`. When I tried to instead provide a `ServerResponse`, I got a Jackson error saying it couldn't serialize the class.

**Comment by SentryMan** [comment]
do you have the jooby reactor dependencies?

**Comment by jtlapp** [comment]
Oh wow. That was it. It works! Thank you so much!

It wasn't clear to me reading the docs that I needed to include `Reactor`. I think the docs assume I know what this `Reactor` dependency is for.

Reading through the docs in restrospect, I can see that maybe I should have guessed to try either Reactor or RxJava, but I would have thought of it as a shot in the dark.

**Comment by SentryMan** [comment]
I mean it's all [there in the docs](https://jooby.io/#responses-nonblocking-reactor)

**Comment by jtlapp** [comment]
I had never heard of Reactor and assumed it was an adaptor for some 3rd party dependency called "Reactor", akin to its sibling listings of Mutiny and RxJava, and therefore ignored it.

Use my feedback to improve docs or not, as you please.

**Comment by SentryMan** [comment]
I guess it does assume, but the thing is Mono/Flux are specifically unique to reactor. If you're talking about monos and fluxes, you can only be talking about project reactor. (Spring Webflux and R2DBC use reactor)

**Comment by jtlapp** [comment]
Ah! Thank you! I did not know that. That would have helped.
