### ISSUE TITLE
`onStarted` and `onStarting` footgun

### ISSUE THREAD

**Issue by nedtwigg** [jooby-project/jooby#3550]
I spent a couple hours on a weird bug that was only happening on CI, couldn't get it to reproduce locally. It turned out to have this shape:

```java
public class LatestCache implements io.jooby.Extension {
	@Override
	public void install(@NonNull Jooby app) throws Exception {
		app.getServices().put(LatestCache.class, this);
		app.onStarted(() -> update(registry));
	}
```

On CI, the test application was accepting requests before `onStarted` method could run. Took me a while to figure out that this was happening, and it seemed like a bug, so I started to file one.

When I realized that there are two methods:

- `onStarting` which runs before requests are accepted
- `onStarted` which runs right after requests are eligible to be accepted

Across two separate applications, we had a smattering of both, but we *always* meant `onStarting`, and never `onStarted`.

IMO, it would be a good idea to

- mark `onStarted` as deprecated
- name it `onRunning` or something else
- maybe get rid of `onRunning` and instead call it `onFirstRequest`, which is different semantics, but it's a big deal whether it's possible that a request has already been processed or not, I have a hard time imagining when I would ever want to run initialization code that has maybe already had a request go by before the initialization

**Comment by agentgt** [comment]
> maybe get rid of onRunning and instead call it onFirstRequest, which is different semantics, but it's a big deal whether it's possible that a request has already been processed or not, I have a hard time imagining when I would ever want to run initialization code that has maybe already had a request go by before the initialization

I would imagine that such determination would incur overhead. At minimum some atomic counter. Worse a lock.

I think the idea is that `onStarted` is when Jooby can handle requests and I see value in that particularly in a mixed microservice/monolithic environment where you may use an HTTP client to do something and the very same server may indirectly handle it. 

Furthermore often times folks do some sort of "wait a little bit after boot" and this fits the bill (`onStarted`)... as in you don't care to be exact just that it has to be after it is started. This could trigger a flag on a health check status etc.

**Comment by jknack** [comment]
found the name to be correct. There is some javadoc on both that describe when/how they work.

@agentgt yes, I filled #3551
