### ISSUE TITLE
Guice @Inject doesn't create default constructor for MVC routes

### ISSUE THREAD

**Issue by tpoll** [jooby-project/jooby#3567]
I'm attempting to upgrade to jooby 3.4.2.

currently, our jooby is set up with following  [guice-module docs](https://jooby.io/#dependency-injection-guice-mvc-routes) to power the router generation. It's working fine for us on 3.0.5.

When updating, I consistently am getting `Router not found: **** . Make sure Jooby annotation processor is configured properly.`.
I've tried to register the routers via the `mvc` method like `MyRouter.class` and `MyRouter_.class`, but both give me the same error.

Is there a new way to make DI injection for mvc work in the generated code world? It seems like the docs for guice haven't updated, so I assumed the old way would work without any changes.

**Comment by jknack** [comment]
Hi

The `mvc(class)` must be avoided. Try: 

```
mvc(new MyRouter_());
```

This is preferred way. The `mvc(class)` requires the service locator pattern and I kept `mvc(object)` for compatibility reason. You probably are missing something, any of these variants should work too.

Preferred:
```
mvc(new MyRouter_());
```

Requires jooby processor to generate META-INF entry:

```
mvc(new MyRouter());
```

```
mvc(MyRouter.class);
```

**Comment by tpoll** [comment]
I'm using `com.google.inject.Inject`.

@jknack  I'm trying to avoid  `mvc(new MyRouter_())` because otherwise I will have to manually construct all the dependencies I pass in, which sort of defeats the purpose of using Guice/DI it seems.

I have verified locally the the meta/INF file is being generated.

**Comment by jknack** [comment]
you need to use jakarta(preferred) or javax. If you do that you will see that the generated router `MyRouter_` will have a default constructor bc of the Inject annotation. 

But yea you need to switch to jakarta

**Comment by tpoll** [comment]
ah, okay that makes sense. I didn't realize this would require switching to jakarta.

verified locally that switching to jakarta does work.

**Comment by tpoll** [comment]
I can close this out then. 

I know it's a long shot, but is there any appetite for adding guice inject as a supported annotation for the default constructor?

I can double up `@Inject` annotations to prevent a full if needed, but that feels a little error prone.

**Comment by jknack** [comment]
Can you rename the ticket? Should be simple to support due we actually have jakarta/javax (not sure who many people will find it useful)
