### ISSUE TITLE
Uncaught exceptions in io.jooby.internal.netty.NettyHandler.offer

### ISSUE THREAD

**Issue by tpoll** [jooby-project/jooby#3580]
We are seeing several instances of uncaught exceptions from https://github.com/jooby-project/jooby/blob/3.x/modules/jooby-netty/src/main/java/io/jooby/internal/netty/NettyHandler.java#L175.

For example, we are seeing the underlying Netty decoder throw exceptions like `HttpPostRequestDecoder$TooLongFormFieldException` , there also seem to be some underlying NPEs in netty  like:

```
NullPointerException
Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "delimiter" is null

io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder in readDelimiterOptimized at line 1116
io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder in findMultipartDelimiter at line 699
io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder in decodeMultipart at line 541
io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder in parseBodyMultipart at line 506
io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder in parseBody at line 472
io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder in offer at line 384
io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder in offer at line 55
io.jooby.internal.netty.NettyHandler in offer at line 175
...
```

is there any appetite for have the jooby code be more defensive here about uncaught exceptions and translating them into http status codes?

**Comment by jknack** [comment]
would you like to send a PR?

**Comment by tpoll** [comment]
yes, I can send a PR later this week.
