### ISSUE TITLE
jetty: JettyServer no longer takes a QueuedThreadPool

### ISSUE THREAD

**Issue by jtlapp** [jooby-project/jooby#3590]
The documentation includes the following example:

```
  QueuedThreadPool worker = new QueuedThreadPool();
  worker.setReservedThreads(0);
  worker.setVirtualThreadsExecutor(Executors.newVirtualThreadPerTaskExecutor());

  install(new JettyServer(worker));
```

However, there is no JettyServer constructor taking a thread pool at present.

Are we supposed to be doing this a different way now?

**Comment by jknack** [comment]
yea, I removed when upgrade to 12.x find it far more complex to setup in 12.x... but I can probably added it back.
