### ISSUE TITLE
jooby should probably have a bom (bill of materials) pom.

### ISSUE THREAD

**Issue by agentgt** [jooby-project/jooby#363]
As mentioned in #337 it would be nice if Jooby had a BOM pom file. It lists all the Jooby components in a pom file that can be imported `<dependencyManagement>` section.

The springframework has a nice example: http://central.maven.org/maven2/org/springframework/spring-framework-bom/4.2.5.RELEASE/spring-framework-bom-4.2.5.RELEASE.pom

**Comment by agentgt** [comment]
Oh I forgot here is a crappy little groovy script I wrote to generate the BOM pom. I could never find a plugin to generate it.

https://gist.github.com/agentgt/f82c5b8c2a240f78997ddf2df9e9c9c3

```
$ mvn-bom.groovy pom.xml > jooby-bom/pom.xml
```

**Comment by jknack** [comment]
👍  with that awesome script feel we can do it for next release 👍
