### ISSUE TITLE
Extending routes

### ISSUE THREAD

**Issue by gdrte** [jooby-project/jooby#365]
Jooby doesn't support extending routes. The usage is, define some common API(CRUD) in Abstract route and extend this router to add additional APIs. What exactly I mean is as follows.
`@RestController
abstract public class AbstractController<Model> {
    /**
     * List the Models
     *
     * @return List<Model>, a list of Models.
     */
    @RequestMapping(method = RequestMethod.GET)
    public List<Model> list() {
        return dao.find().asList();
    }
    /**
     * Get the Model given by an ID
     *
     * @return Model.
     */
    @RequestMapping(method = RequestMethod.GET,value="/{id}")
    public Model findOne(@PathVariable  final String id) {
        return dao.get(new ObjectId(id));
    }

    /**
     * Create a new Model
     *
     * @param model Model The Model object
     * @return Model, On success returns saved Model with generated id.
     */
    @RequestMapping(method = RequestMethod.POST)
    public Model create(@RequestBody Model model) {
        dao.save(model);
        return model;
    }
}
@RestController
@RequestMapping("/api/user")
public class UserController extends AbstractController<User> {

    @Autowired
    public UserController(DAO dao) {
        super(dao);
    }

    @RequestMapping(method= RequestMethod.POST, value = "/login")
    void login(){

    }
    @RequestMapping(method= RequestMethod.POST, value="/logout")
    void logout(){

    }

}`
![screen shot 2016-04-25 at 3 13 40 pm](https://cloud.githubusercontent.com/assets/2367122/14800804/4ab45d76-0af9-11e6-91e1-2160a2a75df3.png)

**Comment by danielfireman** [comment]
Sorry for chiming in late. As far as I could understand, the main goal is to have an easier/faster way to implement CRUDs, right?

If the answer is yes, maybe we could get away without inheritance (I could see some complications with this implementation, in particular, regarding consistency checks between implementation of the super class and sub classes). @jknack @gdrte have you guys thought of using @Crud Annotation? Something like:

`
@CrudController(methods={CREATE, READ, UPDATE, DELETE}, dao = UserDao.class)
public class UserController  {
   ,,,
}
`
Then we would have some processor that implements CRUD in a very simple way.

We could use Guice to create a new instance of UserDao.

Any thoughts?

**Comment by gdrte** [comment]
@danielfireman I am afraid, the implementation will be complex. How should it support, if I want all my CRUDs are non-blocking?

**Comment by jknack** [comment]
Agreed with @gdrte.

@danielfireman what do you mean with:

> I could see some complications with this implementation, in particular, regarding consistency checks between implementation of the super class and sub classes

can you provide an example?
