### ISSUE TITLE
undertow server doesn't work with jooby:run

### ISSUE THREAD

**Issue by elaatifi** [jooby-project/jooby#396]
I tried to use Undertow Server with 1.0-RC4, I get this exception, seems that ServiceLocator can't find XNIO implementation even if it's included in the classpath of POM (runtime scope). 
java.lang.IllegalArgumentException: XNIO001001: No XNIO provider found
	at org.xnio.Xnio.doGetInstance(Xnio.java:255)
	at org.xnio.Xnio.getInstance(Xnio.java:182)
	at io.undertow.Undertow.start(Undertow.java:95)
	at org.jooby.internal.undertow.UndertowServer.start(UndertowServer.java:191)
	at org.jooby.Jooby.start(Jooby.java:3534)
	at org.jooby.Jooby.start(Jooby.java:3474)
	at org.jooby.Jooby.start(Jooby.java:3419)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jooby.hotreload.AppModule.lambda$startApp$1(AppModule.java:198)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jknack** [comment]
Hi,

 Thanks for trying jooby. Where did you get 1.0-RC4?

  Latest release is **1.0.0.CR3**

  Also, our integration tests run against the 3 available server. I'm 99% sure that works :)

**Comment by elaatifi** [comment]
From the GIT Repo (build locally)
BTW, it is really awesome what you're doing with jooby (opinionated but still very educated choices)

**Comment by jknack** [comment]
Join https://gitter.im/jooby-project/jooby and will help with your build

Also, I would like to know why do you think is opinionated... part of me see jooby as expressjs for java and expressjs isn't opinionated :)

**Comment by jknack** [comment]
did you figure it out? is it working?

**Comment by elaatifi** [comment]
I tried a couple of time, checked the maven dependency tree, the XNIO provider is there (runtime scope)
I'm not familiar yet with the way jooby set the classpath for the server.

**Comment by jknack** [comment]
hmm ok, can you share your pom.xml?

**Comment by elaatifi** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.jooby</groupId>
		<artifactId>jooby-project</artifactId>
		<version>1.0.0.CR4</version>
	</parent>

	<artifactId>app</artifactId>
	<groupId>project</groupId>
	<version>1.0-SNAPSHOT</version>

	<name>app</name>
	<description>generated by Jooby archetype</description>

	<properties>
		<jooby.version>1.0.0.CR4</jooby.version>

		
		<application.class>project.App</application.class>
	</properties>

	<dependencies>
		
		<dependency>
			<groupId>org.jooby</groupId>
			<artifactId>jooby</artifactId>
		</dependency>

		
		<dependency>
			<groupId>org.jooby</groupId>
			<artifactId>jooby-undertow</artifactId>
		</dependency>

		<dependency>
			<groupId>org.jooby</groupId>
			<artifactId>jooby-assets</artifactId>
		</dependency>

		
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
		</dependency>



		<dependency>
			<groupId>org.jooby</groupId>
			<artifactId>jooby-executor</artifactId>
		</dependency>
		<dependency>
			<groupId>org.jooby</groupId>
			<artifactId>jooby-ebean</artifactId>
		</dependency>

		<dependency>
			<groupId>org.avaje.ebeanorm</groupId>
			<artifactId>avaje-ebeanorm-agent</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.avaje</groupId>
			<artifactId>avaje-agentloader</artifactId>
			<scope>test</scope>
		</dependency>


		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<version>9.4.1208.jre7</version>
		</dependency>


		<dependency>
			<groupId>org.jooby</groupId>
			<artifactId>jooby-gson</artifactId>
			<version>${jooby.version}</version>
		</dependency>

		<dependency>
			<groupId>org.jooby</groupId>
			<artifactId>jooby-pebble</artifactId>
		</dependency>

		<dependency>
			<groupId>org.jooby</groupId>
			<artifactId>jooby-jackson</artifactId>
		</dependency>

		<dependency>
			<groupId>org.jooby</groupId>
			<artifactId>jooby-quartz</artifactId>
		</dependency>


		
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.jooby</groupId>
			<artifactId>jooby</artifactId>
			<scope>test</scope>
			<classifier>tests</classifier>
		</dependency>

		
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>fluent-hc</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpmime</artifactId>
			<scope>test</scope>
		</dependency>

	</dependencies>

	<build>
		<resources>
			<resource>
				<directory>templates</directory>
				<filtering>true</filtering>
			</resource>
		</resources>

		<plugins>
			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
			</plugin>

			<plugin>
				<groupId>org.jooby</groupId>
				<artifactId>jooby-maven-plugin</artifactId>
				<configuration>
					<vmArgs>
						<vmArg>-Xms512m</vmArg>
						<vmArg>-Xmx1024m</vmArg>
						<vmArg>-XX:MaxDirectMemorySize=512m</vmArg>
					</vmArgs>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>assets</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>

**Comment by jknack** [comment]
odd, looks good. I can't see why do you have an error

**Comment by huysamen** [comment]
I am experiencing the same issue.  Standard pom from using the archetype, and changing `jooby-netty` to `jooby-undertow` causes the issue.

**Comment by huysamen** [comment]
Just tried with CR5 and it is still an issue.

**Comment by huysamen** [comment]
OK, so it only seems to be happening when starting the application with `mvn jooby:run`.  Works fine when just running the main class.

**Comment by jknack** [comment]
Correct. Bug is present in jooby:run will look at this soon.

**Comment by jknack** [comment]
@huysamen @elaatifi should work on 1.0.0.CR6
