### ISSUE TITLE
Can we have Flash scope added to request object ?

### ISSUE THREAD

**Issue by elaatifi** [jooby-project/jooby#397]
A feature request regarding flash messages pattern 
something as simple as https://github.com/decebals/pippo/blob/0d2565893b283fd56e1513fe5796f487356d5978/pippo-core/src/main/java/ro/pippo/core/Flash.java
 accessible from request  for  convinience

**Comment by jknack** [comment]
released: http://jooby.org/doc/#request-flash-scope
