### ISSUE TITLE
Use config default applicationConfig

### ISSUE THREAD

**Issue by wenerme** [jooby-project/jooby#419]
So I can change the config file, config allowed specify config.file, config.url,etc, Jooby should not force to use application.conf.

I use a very hacky way to achieve this, load extra config file as args.

![image](https://cloud.githubusercontent.com/assets/1777211/16771786/64da1ee8-4884-11e6-91c4-cfbaf9cc3c60.png)

The hacky

![image](https://cloud.githubusercontent.com/assets/1777211/16771852/9662ed46-4884-11e6-8fde-199e01721987.png)

**Comment by jknack** [comment]
Hey, thanks for trying jooby!

I'm not sure I got the problem. You are able to use the a custom conf file, we don't force you to use  `application.conf`, just defaults to it.

```java
{
  use(ConfigFactory.parseResources("config.file"));
}
```

Cool?

**Comment by wenerme** [comment]
Thanks, so what I need is just

```java
use(ConfigFactory .defaultApplication());
```

**Comment by nfleury** [comment]
@jknack 
Sorry but I can't figure out how this works . 

With jooby 1.1.1 I'm trying to use an external configuration file to override some configurations in application.conf

I'm launching my server with something like this: 

`java -jar -Dconfig.file=/tmp/application.prod.conf ./target/server.jar env=prod`

I am expecting configurations present in /tmp/application.prod.conf to override those in application.conf

I tried 

`use(ConfigFactory .defaultApplication());`
and 
`  use(ConfigFactory.parseResources("config.file"));`

but none of the previous worked ...
