### ISSUE TITLE
Add Socket.IO support

### ISSUE THREAD

**Issue by wenerme** [jooby-project/jooby#420]
Socket.IO is based on WS, this is doable.

**Comment by jknack** [comment]
have no experience with socket.io, but will like to know what is need it?

thought it can connect to WebSocket and jooby provides web socket supports, what else do we need?

**Comment by wenerme** [comment]
Currently we use [mrniko/netty-socketio](https://github.com/mrniko/netty-socketio), same stack as Jooby.
