### ISSUE TITLE
jdbc settings programmatically

### ISSUE THREAD

**Issue by SergiX44** [jooby-project/jooby#429]
About the jdbc module [http://jooby.org/doc/jdbc/](url) it's possible to setup the database configuration (connection string, database user, database password, etc) programmatically without setting in application.conf? (picked up from other config file or from user input)

**Comment by jknack** [comment]
not now, but was thinking on this today.. bc new/recent db modules supports url programmatically:

```java
{
   use(new Cassandra("cassandra://localhost/db"));
}
```

will add this for next release.

BUT! configuration is very powerful, you can use your own .conf file, not need to use `application.conf`

```java
  use(ConfigFactory.parseResources("mydb.conf"));
```

I just created #428 which is just syntax sugar for this line.

Also, you can specify db property from command line or environment

```
java -jar myapp.jar db.url=... db.user=... db.password=...
```

args/environment variables take precedence over properties from .conf file

let me know if you have questions

thanks

**Comment by FreVecc** [comment]
Thanks for the suggestions.
I was wondering, when you will add this freaking awesome new features to this beautiful framework?

**Comment by jknack** [comment]
@FreVecc which feature?

Guys, do you like jooby?

Please star/follow us on [jooby-project](https://github.com/jooby-project/jooby) and [@joobyproject](https://twitter.com/joobyproject)!!!

**Comment by FreVecc** [comment]
I meant the `new Cassandra(...)` feature
