### ISSUE TITLE
Empty parameters are treated as missing

### ISSUE THREAD

**Issue by authchir** [jooby-project/jooby#431]
Given the following server:
```Java
import org.jooby.*;

public class Main extends Jooby {
  {
    get("/test", req -> req.param("foo").toOptional().toString() + "\n");
  }

  public static void main(final String[] args) throws Throwable {
    run(Main::new, args);
  }
}
```

Empty parameters are treated as missing:

```
$ curl localhost:8080/test
Optional.empty
$ curl localhost:8080/test?foo
Optional.empty
$ curl localhost:8080/test?foo=
Optional.empty
$ curl localhost:8080/test?foo=abc
Optional[abc]
```

One sometime wants to distinguish between an absent and empty parameter. I believe the result should be:

 - `Optional.empty`
 - `Optional[]`
 - `Optional[]`
 - `Optional[abc]`

Any thought on this?

**Comment by jknack** [comment]
I introduced this change in previous release. The motivation was form submits where if you leave some field blank  you get an empty string for me this should be treat as missing, simplify form validation.

What is the use cas for trying empty parameter as empty list? For example:

```
get("/test", req -> req.param("foo").toList() + "\n");
```

Give you `[]` for `?foo` or `?foo=`

**Comment by wenerme** [comment]
Elasticsearch have a `?pretty` to pretty format the json result.

**Comment by jknack** [comment]
Odd, but how an empty list will help there? Still not sure if `?pretty` is a valid use case... feel empty string as optional works better in general.

**Comment by jknack** [comment]
well, got some issues/questions about this in the google group... think going to revert the changes I did... will that work for you guys?

**Comment by authchir** [comment]
Hello, I am a little bit late on the train, but @wenerme gave the exact example I was referring to: a flag to enable a functionality.

**Comment by jknack** [comment]
was reverted found another way of handling absent/empty string while submitting forms

👍
