### ISSUE TITLE
revert: unify absent of HTTP parameter and empty strings

### ISSUE THREAD

**Issue by jknack** [jooby-project/jooby#437]
Change was introduced here #407 in `1.0.0.CR6`

See #431 
See https://groups.google.com/forum/#!topic/jooby-project/HRJLfmUqzWs

@kshep92 I'm sorry but will have to revert the change I did around empty vs absent params

**Comment by kshep92** [comment]
So it looks like my original solution where I registered a custom parser is what I should continue using? Or would the fix be included in CR7?

**Comment by jknack** [comment]
will try something else to fix this in CR7
