### ISSUE TITLE
Rapidoid Server Module

### ISSUE THREAD

**Issue by noboomu** [jooby-project/jooby#440]
Maybe it's a stretch but given Rapidoid's benchmark results, it would be awesome to try and provide a Rapidoid server module for Jooby. I'm part way into an implementation but unclear about what exactly Jooby needs.

**Comment by jknack** [comment]
that's awesome!!  best to do is to start with the Servlet* implementation it is probably easier to follow https://github.com/jooby-project/jooby/tree/master/jooby-servlet/src/main/java/org/jooby/servlet

**Comment by noboomu** [comment]
Great, thanks!

**Comment by jknack** [comment]
not sure if rapidoid has websockets... we probably want to skip the web socket tests and the server-sent-events at least as first implementation... HTTP? should be pretty straightforward 

let me know how it goes and/or if you have questions

**Comment by noboomu** [comment]
So I created a limited prototype here: https://github.com/noboomu/jooby-rapidoid. For some reason the ETags and Last-Modified headers are causing problems, but it seems to function when they are dissabled. I don't have a particularly strong working knowledge of Jooby's inner workings and Rapidoid has no documentation, so if someone with either expertise could lend a hand that's be great :)
