### ISSUE TITLE
mvn jooby:run with multiple modules dependencies does not reload

### ISSUE THREAD

**Issue by nfleury** [jooby-project/jooby#447]
Working with multiple module dependencies and jooby:run does not work.

I have the following project structure:

parent-project
 |_model
 |_service
 |_app (contains jooby project)
 
- model, service and app are modules of parent-project.
- app uses service as dependency

mvn jooby:run works fine with reload on changes in app folder but I would like jooby:run to reload when when making changes in model or service.

I tried many configurations with build-helper-maven-plugin to add model and service as sources, that did not work, I also tried to include model and services sources with jooby
configuration "<includes>" it did not worked either ...

Thanks

**Comment by jknack** [comment]
done. There is a `watchDirs` property now, but... in theory you don't need to do anything... `jooby:run` now detects multi-module project and configure everything for you ;)

**Comment by nfleury** [comment]
Thanks for the quick update! 

Running jooby:run on 'app' does include 'service' in watchDirs. Changing sources in 'service' reloads the app but only on the first change. If I edit 'service' sources more than once the application won't reload again.

**Comment by jknack** [comment]
@nfleury good catch!

will fix it later today.

**Comment by jknack** [comment]
fixed in master. Again: good catch!

**Comment by nfleury** [comment]
@jknack Many thanks ! Works great now !!!
