### ISSUE TITLE
Stork packaging fails with default config - missing display_name

### ISSUE THREAD

**Issue by dajester2013** [jooby-project/jooby#449]
When using the maven archetype documented on the website, a stork.yml is created.  However, packaging fails with a missing config.displayName variable.  

Adding `display_name="${project.name}"` to stork.yml fixes this.

**Comment by jknack** [comment]
Thanks! I created an app yesterday and didn't find any problem, but adding displayName seems nice to me.

Can you please send a pull request with this?

The stork.yml file is [here](https://github.com/jooby-project/jooby/tree/master/jooby-archetype/src/main/resources/archetype-resources/src/etc)
