### ISSUE TITLE
XSS vulnerability in the 404 page

### ISSUE THREAD

**Issue by S66D** [jooby-project/jooby#453]
I was able to effectively execute an XSS in Jooby 404 page
to reproduce the vulnerability : `http://127.0.0.1/404<script>alert('xss');</script>`
Adding XSS filter will solve the issue.

**Comment by jknack** [comment]
Hi, yes! a xss filter will be good! but what do you mean with a 404 page? there is no `404` page in jooby unless you provide one. Can you please post an example app to reproduce the problem?

What do you think about a xss filter with some defaults regex and let users to provide their own regex if need it? anything else?

**Comment by S66D** [comment]
There is a `"Not Found(404)"` stack trace 
![image](https://cloud.githubusercontent.com/assets/9611868/17895759/c60931ca-6956-11e6-823c-870be46e72a1.png)

[https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet](url)

**Comment by jknack** [comment]
Got it, it's the default error handler.

what a about the solution? do you have any opinion/preference on that?

will add a simply xxs filter into core and probably add a xss module with EASPI/AntiSamy and https://github.com/coverity/coverity-security-library

cool?

**Comment by S66D** [comment]
Yup that should be good.
