### ISSUE TITLE
Caffeine cache support

### ISSUE THREAD

**Issue by ben-manes** [jooby-project/jooby#461]
[Caffeine](https://github.com/ben-manes/caffeine) is a Java 8 rewrite of Guava's cache. It includes a few new features (e.g. async loading), higher performance, and an improved eviction policy. There are Guava adapters for simpler migrations and `CaffeineSpec` supports all of `CacheBuilderSpec` except `concurrencyLevel` which is unnecessary.

I can take a crack at this, but you might prefer to instead. I think about 90% of the Guava code is applicable (either c&p or a sharable). There are differences such as async, specifying the executor, etc. that probably require your perspective on how to expose.

**Comment by jknack** [comment]
Sounds great! let me know if you need help to setup code coverage... you need to edit pom.xml of `coverage-report` and add the java and test source code for the new caffeine module. Here is an example of how I did this for Guava: https://github.com/jooby-project/jooby/blob/master/coverage-report/pom.xml#L67

Also, if you didn't star the proyect yet, please do and follow us at twitter too: https://twitter.com/joobyproject

Thanks

**Comment by ben-manes** [comment]
Thanks for the tips! I added support, which was really easy.
