### ISSUE TITLE
Cookie Session - destroy() does not destroy session

### ISSUE THREAD

**Issue by marcinc81** [jooby-project/jooby#466]
Hi, today I've found some issue with `req.session().destroy()`. According to the doc it shall remove all data from session, but actually it does nothing. Session cookie is still there with all variables. `unset()` removes all variables from session, but leaves empty cookie - I expected this behavior.

This is my code:
```
        group.get("/logout", (req, res) -> {
            req.session().destroy();
            res.redirect("/");
        });
```

Cheers! :)

**Comment by jknack** [comment]
sounds odd, there a lot of tests around sessions... but will look and get back to you

**Comment by jknack** [comment]
I read to fast.. sorry.

What do you mean with `cookie-session`?

Server-side session? or Client-side session?

Both uses a `cookie` :)

**Comment by marcinc81** [comment]
oops :) I meant client session (signed cookie).

Initiated by `cookieSession();`

Config:
```
session.cookie.maxAge=86400
session.cookie.name=user
```
