### ISSUE TITLE
review documentation prepare for 1.0.0 release

### ISSUE THREAD

**Issue by jknack** [jooby-project/jooby#495]
make sure documentation is up-to-date and fix typo, better description and more examples

**Comment by paulovictorv** [comment]
I have a question that may be pertinent to this issue: are there any documentation on how to do testing when using Jooby? 

I'm specifically asking if there's a standard way to, lets say, inject mocked Jooby Modules or other classes that are ``@Inject```ed? If this is a question that is more related to Guice than with Jooby, please forgive me, since I've rarely used Guice before.
