### ISSUE TITLE
Q: How to access raw query string from request object

### ISSUE THREAD

**Issue by nikos** [jooby-project/jooby#514]
When handling a route, how would one retrieve the path including all parameters (ie. /path?foo=bar...) from `org.jooby.Request` ?

**Comment by jknack** [comment]
Not possible today. It is a valid question and think will be nice to add it but what are you trying to do?

**Comment by nikos** [comment]
My usecase is to save the original URL with all of its query parameters to a separate database for tracking purposes, many thanks @jknack for directly implementing it with #518 (I wished I had more time and provide a PR my own next time :-)
