### ISSUE TITLE
Security issue: upgrade to pac4j v1.9.4

### ISSUE THREAD

**Issue by leleuj** [jooby-project/jooby#516]
Unfortunately, we have a critical security issue in pac4j v1.9.2 and v1.9.3, if you use `DbAuthenticator` or `MongoAuthenticator` and the default password encoder `NopPasswordEncoder`.

You MUST upgrade to pac4j v1.9.4.

Hopefully, you haven't released any final version (only 1.0.0.CR8 is affected).

**Comment by leleuj** [comment]
@jknack : the trivial PR to fix the issue: https://github.com/jooby-project/jooby/pull/517

**Comment by jknack** [comment]
@leleuj Thank you.

**Comment by leleuj** [comment]
Thanks for your swiftness.
