### ISSUE TITLE
Swagger example not working

### ISSUE THREAD

**Issue by jschneider** [jooby-project/jooby#530]
On:
http://jooby.org/doc/spec/#swagger

in section "Usage", one should add the line 
new Swagger().install(this);

This line doesn't seem to work (at least for me). The class io.swagger.models.Swagger (which is imported) obviously has no method "install".
Probably 
new SwaggerUI().install(this);
is meant(?)

**Comment by jschneider** [comment]
https://github.com/jooby-project/jooby/pull/531

**Comment by jknack** [comment]
Fixed in #531
