### ISSUE TITLE
Swagger: Wrong comment

### ISSUE THREAD

**Issue by jschneider** [jooby-project/jooby#532]
I get a wrong comment when doing the following:

- Register a route class (containing javadoc)
- Register a route using "use" and lambdas

Swagger copies the comment from the route class to the route created by the lambda.

**Comment by jknack** [comment]
Can you provide an example?

Thanks

**Comment by jschneider** [comment]
It is really hard to reproduce.
Currently I do not get any comments when using the sample application :-/

**Comment by jschneider** [comment]
Well, after a clean, I just get a NPE:

Caused by: java.lang.NullPointerException: null
	at org.jooby.internal.spec.RouteCollector.accept(RouteCollector.java:89)
	at org.jooby.spec.RouteProcessor.processInternal(RouteProcessor.java:227)
	... 17 common frames omitted

I think I am missing something...

**Comment by jschneider** [comment]
Ok. I can no longer reproduce the problem. It seems that a "mvn cleam" is necessary sometimes.
