### ISSUE TITLE
executor() causes com.google.inject.ProvisionException

### ISSUE THREAD

**Issue by dhonek** [jooby-project/jooby#570]
Following code causes com.google.inject.ProvisionException:

```
import org.jooby.Jooby;
import org.jooby.Results;
import java.util.concurrent.Executors;

/**
 * @author jooby generator
 */
public class AppSimple extends Jooby {

    {
        executor("db", Executors.newCachedThreadPool());  /* <---- This seems causes the exception */

        get("/nonblocking", () -> "I'm nonblocking");

        get("/list", deferred("db", req -> {
            int id = req.param("id").intValue();
            DB db = req.require(DB.class);
            db.delete(id);
            return Results.noContent();
        }));

    }

    public static void main(final String[] args) throws Exception {
        new AppSimple().start(args);
    }
}
```
-------------

com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=deferred) was bound.
  while locating java.lang.String annotated with @com.google.inject.name.Named(value=deferred)
  at org.jooby.internal.HttpHandlerImpl.<init>(HttpHandlerImpl.java:198)
  at org.jooby.internal.HttpHandlerImpl.class(HttpHandlerImpl.java:79)
  while locating org.jooby.internal.HttpHandlerImpl
  at org.jooby.Jooby.lambda$bootstrap$48(Jooby.java:2613)
  while locating org.jooby.spi.HttpHandler
    for the 1st parameter of org.jooby.internal.netty.NettyServer.<init>(NettyServer.java:80)
  while locating org.jooby.internal.netty.NettyServer
  at org.jooby.netty.Netty.configure(Netty.java:36)
  while locating org.jooby.spi.Server

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at org.jooby.Jooby.start(Jooby.java:1959)
	at org.jooby.Jooby.start(Jooby.java:1919)

**Comment by jknack** [comment]
Duplicates of #567

**Comment by dhonek** [comment]
tx for the workaround
