### ISSUE TITLE
Initializer block for scripting vs invocation flow - makes debugging difficult

### ISSUE THREAD

**Issue by dhonek** [jooby-project/jooby#571]
I like the simple scripting model jooby uses (like sinatra DSL) compared to the mvc model. It is quite simple & elegant. 

For scripting jooby seems using Initializer block. (Hope this is the only model available for now for scripting?) which makes all scripting code execute once (except for call backs). I guess, internally, this helps call flow optimizations? However, this causes debugging difficult as it is not possible to identify which branch get executed in each request - e.g. each HTTP request can only be debug in the call back method, rather on the script flow, to figure out which statement get executed.
  
So, if there is no other way (for now?) I suggest adding a mechanism other than Initializer block - which makes e.g. netty, handler flows (with Jooby handlers & chains)  to eventually call user code on each request. Hope this makes sense :)?

thanks.

**Comment by jknack** [comment]
Hi @dhonek,

 Not sure I follow, can you provide an example?
