### ISSUE TITLE
WebSockets: #isOpen

### ISSUE THREAD

**Issue by jschneider** [jooby-project/jooby#574]
There is no possibility to ask the WebSocket whether it is open.
Could you delegate that method?

org.jooby.spi.NativeWebSocket#isOpen

**Comment by jschneider** [comment]
Maybe also throw a special exception if the web socket has been closed and somebody tries to write to the socket?

**Comment by jknack** [comment]
Does the `onClose` not working?

```
ws(ws -> {
  // connected

  ws.onClose(status -> {
    // closed
    ...
  });
});
```

**Comment by jschneider** [comment]
onClose is working. But I think there might be some issues with threading(?).


The pattern I use looks like that:
- WS opened
- register listener that is notified about changes and writes them to the WS
- write initial data to the WS

onClose unregisters the listener.
But since the listener is called from another thread it might happen, that those calls happen at the same time.
That means the WS has already been closed but onClose not yet been finished.
Therefore the listener tries to write data to the WS.

A simple "WebSocketHasBeenClosedException" would solve this. I could just catch that exception and ignore the exception and/or unregister the listener.
