### ISSUE TITLE
Callback  when the server has started

### ISSUE THREAD

**Issue by jschneider** [jooby-project/jooby#575]
I would like to have the possibility to register a callback, that is notified when the server has been started and is available.
That callback could be used to open a browser, send some status messages to other systems etc.

It would be just nice to be informed, when everything has been set up.

**Comment by jknack** [comment]
There is one already: http://jooby.org/doc/#application-life-cycle

**Comment by jschneider** [comment]
Yes. I have seen (and tried) the onStart() method.
Unfortunately this methods is called way too early. A long time before the server has finished loading.

I want to know when everything has loaded and startet up.

**Comment by jknack** [comment]
oh now I get it what you want. `onReady` or `onStarted`?
