### ISSUE TITLE
allow to rethrow bootstrap exceptions

### ISSUE THREAD

**Issue by jschneider** [jooby-project/jooby#576]
When there is an exception when starting up, this exception is caught and only logged.
I think it is not a very good style to just hide these exceptions.

I'd prefer them to be thrown - I want to know when something went wrong.

**Comment by jknack** [comment]
It doesn't hide the exception, it is logged but also any services already started is stopped.

You known that something goes wrong bc application isn't running.

**Comment by jschneider** [comment]
Logging is some kind of hiding. Because I want to have that exception in my hands to show it to the user (or do whatever I want).
And yes - the application is not running - but I have no idea to know why. I'd really prefer to know how without having to parse the log file: I am starting Jooby programmatically. Therefore I need that exception.

If the methods could be overridden, I would tweak the implementation myself...

**Comment by jknack** [comment]
Ok, now I get it. I create a new method to handle exception after everything has been stopped.

The method will log the error, but you can override and rethrow

**Comment by jschneider** [comment]
That sounds great. Thanks.

**Comment by jknack** [comment]
Here is an example on how to bootstrap exceptions:

```java
public class App extends Jooby {
  {
    throwBootstrapException();
    ...
  }
}

App app = new App();

try {
  app.start();
} catch (Err err) {
  Throwable cause = err.getCause();
}
```

**Comment by jschneider** [comment]
Looks good. Thanks a lot.
