### ISSUE TITLE
Make private methods in Jooby protected / add more methods to override

### ISSUE THREAD

**Issue by jschneider** [jooby-project/jooby#577]
A lot of methods in Jooby are private and can not be overridden.
I would like to have the possibility to add my own code at some locations (e.g. error handling in start(String...).

Also some methods are really long. It would be great to have some smaller methods that can be overridden (e.g. create the Injector).

**Comment by jknack** [comment]
I'm sorry but you need to be more specific on what you need, because I won't expose internals of Jooby.

If you need to do something that isn't supported today, it must be discussed as a feature and will provide a hook/module or property to make it configurable (if worth it).
