### ISSUE TITLE
Absolute filesystem path for assets

### ISSUE THREAD

**Issue by AmaranthLIS** [jooby-project/jooby#585]
I looked code, but not found how can set up assets absolute filesystem path?
I build jar, but won't include big files (which often changing)

**Comment by jknack** [comment]
Yea there isn't... BUT is you package and startup your application with [stork](http://jooby.org/doc/deployment/#stork) then if you just add more files into the `public` directory it will work even if you change them.

Still going to add a fs path for assets but give it try and confirm how it goes.
