### ISSUE TITLE
allow a websocket to access initial request parameters

### ISSUE THREAD

**Issue by jknack** [jooby-project/jooby#6]
Today, it is possible to access to path params, but not req params. It might be useful to allow initial req params

**Comment by anacarlagb** [comment]
Ok, so, it's possible to acess file path as MVC route argument?

**Comment by jknack** [comment]
there is no mvc support around websockets

**Comment by anacarlagb** [comment]
So.. but using  @Path("/{path:.*}") annotation, mvc support  file path as MVC route argument. 
Thanks.

**Comment by jknack** [comment]
hehe, I don't follow you.. this issue is all about web-sockets, has nothing to do with MVC.

doc for MVC routes is here: http://jooby.org/doc/#mvc-routes and yes you can annotate a method with: ```@Path("/{path:.*}")``` and path var will give you the whole path.

**Comment by wenerme** [comment]
The initial request is useful for customize handshake,e.g auth.

I think add an handshake in WebSocket is enough for this and I will try to add this.
