### ISSUE TITLE
Custom build does not include org.ow2.asm classes

### ISSUE THREAD

**Issue by krisztiankocsis** [jooby-project/jooby#601]
Hi!

I want to add some stuff needed for me to main jooby module but when I build the current master branch (using: mvn -DskipTests=true clean deploy). Note that I only changed the distribution related URLs and removed the nexus-staging plugin.

When I build an app against my version I got:

2017-01-01T21:59:13.030 INFO [main] (eu.optimaster.miw.service.application.Application) Stopped
2017-01-01T21:59:13.033 ERROR [main] (eu.optimaster.miw.service.application.Application) An error occurred while starting the application:
java.lang.NoClassDefFoundError: org/jooby/internal/asm/$ClassVisitor
        at org.jooby.Jooby.bootstrap(Jooby.java:2532)
        at org.jooby.Jooby.start(Jooby.java:1958)
        at org.jooby.Jooby.start(Jooby.java:1940)
        at org.jooby.Jooby.run(Jooby.java:1870)
        at eu.optimaster.miw.service.application.Application.main(Application.java:99)
Caused by: java.lang.ClassNotFoundException: org.jooby.internal.asm.$ClassVisitor
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 5 common frames omitted

Note that JarJar plugin produces a lot of errors during 'deploy' stage:

[INFO] --- jarjar-maven-plugin:1.9:jarjar (default) @ jooby ---
[INFO] Processing: /Users/krisztiankocsis/Documents/Projects/jooby/jooby/target/jooby-1.0.2-SNAPSHOT.jar
[INFO] Building zip: /Users/krisztiankocsis/Documents/Projects/jooby/jooby/target/jarjar/uber-jooby-1.0.2-SNAPSHOT.jar
[INFO] JarJar'ing to: /Users/krisztiankocsis/Documents/Projects/jooby/jooby/target/jooby-1.0.2-SNAPSHOT.jar
Error reading org/jooby/Asset$Forwarding.class: null
Error reading org/jooby/AsyncMapper.class: null
Error reading org/jooby/Cookie$Definition.class: null
Error reading org/jooby/Cookie$Signature.class: null
Error reading org/jooby/Cookie.class: null
Error reading org/jooby/Deferred$Handler.class: null
Error reading org/jooby/Deferred$Initializer.class: null
Error reading org/jooby/Deferred$Initializer0.class: null
Error reading org/jooby/Deferred.class: null
Error reading org/jooby/Env$1.class: null
Error reading org/jooby/Env$Builder.class: null
Error reading org/jooby/Env$Resolver.class: null
Error reading org/jooby/Env$ServiceKey.class: null
Error reading org/jooby/Env.class: null
Error reading org/jooby/Err$DefHandler.class: null
Error reading org/jooby/Err$Handler.class: null
Error reading org/jooby/Err$Missing.class: null
Error reading org/jooby/Err.class: null
Error reading org/jooby/FlashScope.class: null
Error reading org/jooby/Jooby$1Success.class: null
Error reading org/jooby/Jooby$EnvDep.class: null
Error reading org/jooby/Jooby$EnvPredicate.class: null
Error reading org/jooby/Jooby$Module.class: null
Error reading org/jooby/Jooby$MvcClass.class: null
Error reading org/jooby/Jooby.class: null
Error reading org/jooby/LifeCycle.class: null
Error reading org/jooby/MediaType$1.class: null
Error reading org/jooby/MediaType$2.class: null
Error reading org/jooby/MediaType$Matcher.class: null
Error reading org/jooby/MediaType.class: null
Error reading org/jooby/Mutant.class: null
Error reading org/jooby/Parser$BodyReference.class: null
Error reading org/jooby/Parser$Builder.class: null
Error reading org/jooby/Parser$Callback.class: null
Error reading org/jooby/Parser$Context.class: null
Error reading org/jooby/Parser$ParamReference.class: null
Error reading org/jooby/Parser.class: null
Error reading org/jooby/Registry.class: null
Error reading org/jooby/Renderer$2.class: null
Error reading org/jooby/Renderer$Context.class: null
Error reading org/jooby/Renderer.class: null
Error reading org/jooby/Request$Forwarding.class: null
Error reading org/jooby/Request.class: null
Error reading org/jooby/RequestLogger.class: null
Error reading org/jooby/Response$Forwarding.class: null
Error reading org/jooby/Response.class: null
Error reading org/jooby/Result.class: null
Error reading org/jooby/Results.class: null
Error reading org/jooby/Route$After.class: null
Error reading org/jooby/Route$Before.class: null
Error reading org/jooby/Route$Chain.class: null
Error reading org/jooby/Route$Collection.class: null
Error reading org/jooby/Route$Complete.class: null
Error reading org/jooby/Route$Definition.class: null
Error reading org/jooby/Route$Filter.class: null
Error reading org/jooby/Route$Forwarding.class: null
Error reading org/jooby/Route$Group.class: null
Error reading org/jooby/Route$Handler.class: null
Error reading org/jooby/Route$Mapper$1.class: null
Error reading org/jooby/Route$Mapper.class: null
Error reading org/jooby/Route$OneArgHandler.class: null
Error reading org/jooby/Route$Props.class: null
Error reading org/jooby/Route$ZeroArgHandler.class: null
Error reading org/jooby/Route.class: null
Error reading org/jooby/Router.class: null
Error reading org/jooby/Session$Builder.class: null
Error reading org/jooby/Session$Definition.class: null
Error reading org/jooby/Session$Mem.class: null
Error reading org/jooby/Session$Store.class: null
Error reading org/jooby/Session.class: null
Error reading org/jooby/Sse$Event.class: null
Error reading org/jooby/Sse$Handler.class: null
Error reading org/jooby/Sse$Handler1.class: null
Error reading org/jooby/Sse$KeepAlive.class: null
Error reading org/jooby/Sse.class: null
Error reading org/jooby/Status.class: null
Error reading org/jooby/Upload.class: null
Error reading org/jooby/View$Engine.class: null
Error reading org/jooby/View.class: null
Error reading org/jooby/WebSocket$Callback.class: null
Error reading org/jooby/WebSocket$CloseStatus.class: null
Error reading org/jooby/WebSocket$Definition.class: null
Error reading org/jooby/WebSocket$ErrCallback.class: null
Error reading org/jooby/WebSocket$FullHandler.class: null
Error reading org/jooby/WebSocket$Handler.class: null
Error reading org/jooby/WebSocket.class: null
Error reading org/jooby/handlers/AssetHandler$Loader.class: null
Error reading org/jooby/handlers/AssetHandler.class: null
Error reading org/jooby/handlers/Cors$Matcher.class: null
Error reading org/jooby/handlers/Cors.class: null
Error reading org/jooby/handlers/CorsHandler.class: null
Error reading org/jooby/handlers/CsrfHandler.class: null
Error reading org/jooby/internal/AbstractRendererContext.class: null
Error reading org/jooby/internal/AppPrinter.class: null
Error reading org/jooby/internal/BodyReferenceImpl.class: null
Error reading org/jooby/internal/BuiltinParser$1.class: null
Error reading org/jooby/internal/BuiltinParser$2.class: null
Error reading org/jooby/internal/BuiltinParser$3.class: null
Error reading org/jooby/internal/BuiltinParser$4.class: null
Error reading org/jooby/internal/BuiltinParser$5.class: null
Error reading org/jooby/internal/BuiltinParser$6.class: null
Error reading org/jooby/internal/BuiltinParser.class: null
Error reading org/jooby/internal/BuiltinRenderer$1.class: null
Error reading org/jooby/internal/BuiltinRenderer$2.class: null
Error reading org/jooby/internal/BuiltinRenderer$3.class: null
Error reading org/jooby/internal/BuiltinRenderer$4.class: null
Error reading org/jooby/internal/BuiltinRenderer$5.class: null
Error reading org/jooby/internal/BuiltinRenderer$6.class: null
Error reading org/jooby/internal/BuiltinRenderer$7.class: null
Error reading org/jooby/internal/BuiltinRenderer$8.class: null
Error reading org/jooby/internal/BuiltinRenderer$9.class: null
Error reading org/jooby/internal/BuiltinRenderer.class: null
Error reading org/jooby/internal/ByteRange.class: null
Error reading org/jooby/internal/CookieImpl.class: null
Error reading org/jooby/internal/CookieSessionManager.class: null
Error reading org/jooby/internal/DefaulErrRenderer.class: null
Error reading org/jooby/internal/DeferredExecution.class: null
Error reading org/jooby/internal/EmptyBodyReference.class: null
Error reading org/jooby/internal/Headers.class: null
Error reading org/jooby/internal/HttpHandlerImpl$1.class: null
Error reading org/jooby/internal/HttpHandlerImpl$RouteKey.class: null
Error reading org/jooby/internal/HttpHandlerImpl.class: null
Error reading org/jooby/internal/HttpRendererContext.class: null
Error reading org/jooby/internal/InputStreamAsset.class: null
Error reading org/jooby/internal/LocaleUtils.class: null
Error reading org/jooby/internal/MappedHandler.class: null
Error reading org/jooby/internal/MutantImpl.class: null
Error reading org/jooby/internal/ParamReferenceImpl.class: null
Error reading org/jooby/internal/ParameterNameProvider.class: null
Error reading org/jooby/internal/ReaderInputStream.class: null
Error reading org/jooby/internal/RegexRouteMatcher.class: null
Error reading org/jooby/internal/RequestImpl.class: null
Error reading org/jooby/internal/RequestScope.class: null
Error reading org/jooby/internal/RequestScopedSession.class: null
Error reading org/jooby/internal/ResponseImpl.class: null
Error reading org/jooby/internal/RouteChain$1.class: null
Error reading org/jooby/internal/RouteChain.class: null
Error reading org/jooby/internal/RouteImpl$1.class: null
Error reading org/jooby/internal/RouteImpl.class: null
Error reading org/jooby/internal/RouteMetadata$1$1.class: null
Error reading org/jooby/internal/RouteMetadata$1.class: null
Error reading org/jooby/internal/RouteMetadata.class: null
Error reading org/jooby/internal/RoutePattern$1.class: null
Error reading org/jooby/internal/RoutePattern.class: null
Error reading org/jooby/internal/RouteSourceImpl.class: null
Error reading org/jooby/internal/ServerLookup.class: null
Error reading org/jooby/internal/ServerSessionManager.class: null
Error reading org/jooby/internal/SessionImpl$Builder.class: null
Error reading org/jooby/internal/SessionImpl.class: null
Error reading org/jooby/internal/SessionManager.class: null
Error reading org/jooby/internal/SimpleRouteMatcher.class: null
Error reading org/jooby/internal/SseRenderer.class: null
Error reading org/jooby/internal/StaticMethodTypeConverter.class: null
Error reading org/jooby/internal/StatusCodeProvider.class: null
Error reading org/jooby/internal/StrParamReferenceImpl.class: null
Error reading org/jooby/internal/StringConstructTypeConverter.class: null
Error reading org/jooby/internal/TypeConverters.class: null
Error reading org/jooby/internal/URLAsset.class: null
Error reading org/jooby/internal/UploadImpl.class: null
Error reading org/jooby/internal/UploadParamReferenceImpl.class: null
Error reading org/jooby/internal/WebSocketImpl.class: null
Error reading org/jooby/internal/WebSocketRendererContext.class: null
Error reading org/jooby/internal/WsBinaryMessage.class: null
Error reading org/jooby/internal/handlers/FlashScopeHandler.class: null
Error reading org/jooby/internal/handlers/HeadHandler.class: null
Error reading org/jooby/internal/handlers/OptionsHandler.class: null
Error reading org/jooby/internal/handlers/TraceHandler.class: null
Error reading org/jooby/internal/js/JsJooby.class: null
Error reading org/jooby/internal/js/JsRequest.class: null
Error reading org/jooby/internal/js/JsResponse.class: null
Error reading org/jooby/internal/mapper/CallableMapper.class: null
Error reading org/jooby/internal/mapper/CompletableFutureMapper.class: null
Error reading org/jooby/internal/mvc/MvcHandler.class: null
Error reading org/jooby/internal/mvc/MvcRoutes.class: null
Error reading org/jooby/internal/mvc/RequestParam$GetValue.class: null
Error reading org/jooby/internal/mvc/RequestParam.class: null
Error reading org/jooby/internal/mvc/RequestParamNameProviderImpl.class: null
Error reading org/jooby/internal/mvc/RequestParamProvider.class: null
Error reading org/jooby/internal/mvc/RequestParamProviderImpl.class: null
Error reading org/jooby/internal/parser/BeanParser.class: null
Error reading org/jooby/internal/parser/DateParser.class: null
Error reading org/jooby/internal/parser/LocalDateParser.class: null
Error reading org/jooby/internal/parser/LocaleParser.class: null
Error reading org/jooby/internal/parser/ParserBuilder.class: null
Error reading org/jooby/internal/parser/ParserExecutor$1.class: null
Error reading org/jooby/internal/parser/ParserExecutor.class: null
Error reading org/jooby/internal/parser/StaticMethodParser.class: null
Error reading org/jooby/internal/parser/StringConstructorParser.class: null
Error reading org/jooby/internal/parser/bean/BeanComplexPath.class: null
Error reading org/jooby/internal/parser/bean/BeanFieldPath.class: null
Error reading org/jooby/internal/parser/bean/BeanIndexedPath.class: null
Error reading org/jooby/internal/parser/bean/BeanMethodPath.class: null
Error reading org/jooby/internal/parser/bean/BeanPath.class: null
Error reading org/jooby/internal/parser/bean/BeanPlan.class: null
Error reading org/jooby/internal/ssl/JdkSslContext.class: null
Error reading org/jooby/internal/ssl/JdkSslServerContext.class: null
Error reading org/jooby/internal/ssl/PemReader.class: null
Error reading org/jooby/internal/ssl/SslContext.class: null
Error reading org/jooby/internal/ssl/SslContextProvider.class: null
Error reading org/jooby/scope/Providers.class: null
Error reading org/jooby/spi/HttpHandler.class: null
Error reading org/jooby/spi/NativePushPromise.class: null
Error reading org/jooby/spi/NativeRequest.class: null
Error reading org/jooby/spi/NativeResponse.class: null
Error reading org/jooby/spi/NativeUpload.class: null
Error reading org/jooby/spi/NativeWebSocket.class: null
Error reading org/jooby/test/JoobyRule$NoJoin.class: null
Error reading org/jooby/test/JoobyRule.class: null
Error reading org/jooby/test/MockRouter$MockResponse.class: null
Error reading org/jooby/test/MockRouter.class: null

**Comment by jknack** [comment]
Hi,

 We re-package and bundle `asm` as part of jooby using the `jar-jar` maven plugin, see [here](https://github.com/jooby-project/jooby/blob/master/jooby/pom.xml#L25-L56).

 I don't know why you get a `NoClassDefFoundErr`, it should never happens.

 You can safely ignore the `Error reading...` message, not totally sure why `jar-jar` complains but it works for sure.

**Comment by krisztiankocsis** [comment]
The issue comes in when you build like:
* mvn clean package
* mvn deploy

For some reason, when deploy called later, JarJar stores the previously normally built JAR as original JAR but omits the entire internal/asm directory in the new. This works:

* mvn clean deploy

Running package or deploy again without clean pulls in this issue.

**Comment by jknack** [comment]
Oh good to know! And yes!!! travis and release script uses `clean`
