### ISSUE TITLE
Swagger: POST with Query Parameters

### ISSUE THREAD

**Issue by noboomu** [jooby-project/jooby#611]
It may not be the best practice, but what about an MVC route with a POST body using query parameters? I see the RouteParamType parses arguments as query types except when the method is a POST. In that case it makes them FORM types. Perhaps a way to override this? I'm working on an API that is already in production and we are migrating away from Play. This is currently our only blocker.

**Comment by jknack** [comment]
Probably the route spect/export is outdated, will look soon. Meanwhile, can you add an example and expected output?

Thanks

**Comment by noboomu** [comment]
Of course.

	 * Find users by email address.
	 * @param userId
	 * @param context
	 * @param emails
	 * @return Returns a list of matching users
	 */
	@POST
	@Path("/friends/email")
	public Deferred findUsersByEmail( Long userId ,  Optional<String> context,  @Body  ArrayNode emails )

Thanks!

**Comment by jknack** [comment]
Hehe, Ok. But what is the issue here?

**Comment by noboomu** [comment]
Sorry, the issue is that swagger/spec are interpreting the first two parameters as formData types not query types.
