### ISSUE TITLE
RouteSpec Attributes

### ISSUE THREAD

**Issue by noboomu** [jooby-project/jooby#617]
Was wondering if it makes sense to add the route attributes to the RouteSpec? I was able to work around an issue I had with generating our Swagger docs by doing this. I understand the desire to keep the spec clean and parse only the comments and existing annotations, however, I feel that greater customization should be at least an option. By adding something like

```
   route.attributes().ifPresent( a -> {
        	
        	a.entrySet().stream().forEach( e -> {
        		
        		if(e.getKey().equals("nickname"))
        		{
            		         op.setOperationId(e.getValue().toString()); 
        		}
        		else if(e.getKey().equals("apiOperation"))
        		{
            		         op.summary(e.getValue().toString()); 
        		}
        		else if(e.getKey().equals("notes"))
        		{
            		         op.setDescription(e.getValue().toString()); 
        		} 
        		
        	}); 
        });
``` 

to the Swagger builder and the following annotation to an mvc path

`@ApiOperation(value="Find users by email address",nickname="findUsersByEmail")`

I was able to get what I wanted. Is there any downside to adding the attributes to the RouteSpec? That way users can build their own routing modules for Swagger/RAML without having to alter the core code base.

**Comment by jknack** [comment]
So you want route attributes as part of the route spec? but then how did you hack the existing swagger module with this?

Also, do you know how to run Swagger and process Swagger annotations?

**Comment by noboomu** [comment]
I piggybacked off of the Jooby Swagger implementation. I added the code from by first comment to the the SwaggerBuilder build function after the existing code for "Doc and summary." Then added  `Optional<Map<String, Object>> attributes(); ` to the RouteSpec.  I've had to build custom Swagger generators and parsers in the past so that part was pretty familiar.
