### ISSUE TITLE
Hikari configuration problem with multiple datasources

### ISSUE THREAD

**Issue by tryIO** [jooby-project/jooby#622]
With the following configuration:

```
db.spock.url = "jdbc:mysql://localhost:3306/spock?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Europe/Rome"
db.spock.user = "root"
db.spock.password = "password"
db.spock.cachePrepStmts = true

hikari.spock.autoCommit = true
hikari.spock.maximumPoolSize = 100

db.vulcan.url = "jdbc:mysql://localhost:3306/vulcan?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Europe/Rome"
db.vulcan.user = "root"
db.vulcan.password = "password"
db.vulcan.cachePrepStmts = true

hikari.vulcan.autoCommit = true
hikari.vulcan.maximumPoolSize = 100
```

Jooby at runtime complains about 'vulcan.autoCommit'

`
INFO: An exception was caught and reported. Message: java.lang.RuntimeException: Property vulcan.autoCommit does not exist on target class com.zaxxer.hikari.HikariConfig
java.lang.RuntimeException: Property vulcan.autoCommit does not exist on target class com.zaxxer.hikari.HikariConfig
`

by just using the following code:

`
{
...use(new Flywaydb("flyway.spock"));
...use(new Flywaydb("flyway.vulcan"));
...use(new Jdbc("db.spock"));
...use(new Jdbc("db.vulcan"));
}
`

**Comment by jknack** [comment]
Done in #640
