### ISSUE TITLE
Link to example on (or documentaiton for) Dependency Injection please

### ISSUE THREAD

**Issue by ph-ms** [jooby-project/jooby#632]
I've tried searching the documentation site - and I can't see DI documentation, or an example.

There are hits for AngularJS DI, but not Jooby's Java DI for user written Java bits and pieces

**Comment by jknack** [comment]
You're right, will see how to update the doc to reflect usage of dependency injection.

Meanwhile here are some good links:

- First of all checkout [Guice documentation](https://github.com/google/guice/wiki/GettingStarted).
- Here is prototype of a MVC route with dependency injection: http://jooby.org/doc/#routes-mvc-routes. Have a look at the `@Inject` annotation
- Each modules has an `exports` section.

For example, the [jdbc module](http://jooby.org/doc/jdbc/#jdbc-exports) exports a `Datasource` then you can inject datasource into a service or mvc class:

```java
public class UserManager {
   private DataSource ds;

   @Inject
   public UserManager(DataSource ds) {
     this.ds = ds;
   }
}
```

Let me know if you have questions.
