### ISSUE TITLE
Way to instantiate/start a Jooby server per Junit test method needed

### ISSUE THREAD

**Issue by ph-ms** [jooby-project/jooby#633]
I see the following for one Jooby server for all the @Test method is a test class:

```
@ClassRule public static JoobyRule app = new JoobyRule(myAppInstance); 
```
I see the following for one Jooby server for each @Test method is a test class:

```
@ClassRule public JoobyRule app = new JoobyRule(myAppInstance); 
```

^ the same **exact same thing** instantiated over and over again

But how to have a **different** app per test method? Like `new MyTestOverideOfMyAppOne();` for the first test method and `new MyTestOverideOfMyAppTwo();` for the second method (etc). Basically a way of doing it without the JoobyRule annotation doing some magic?

Example of that needed please :)

**Comment by jknack** [comment]
If you want a Jooby instance per test all you have to do is:

1. Replace `@ClassRule` by `@Rule`
2. Remove the static modifier

**Comment by ph-ms** [comment]
I know about that. I'm asking about something different to that. I have three test methods and three subclasses of my 'App'. I want each of the three test methods to instantiate it's own subclass of App (and have it initialized and listening on 8080).  

Basically can I write JUnits **without** annotations on JoobyRule variables (static or member).

**Comment by jknack** [comment]
Got you wrong, but think you can do this without problem:

```java
class App extends Jooby {...}

class App1 extends App {...}

class App2 extends App {...}

class App3 extends App {...}
```

Your tests looks like:

```java
class TestApp1 {

  @Rule
  public JoobyRule boot = new JoobyRule(new App1());

  @Test
   public void test1() {
     ....
    }
}

class TestApp2 {

  @Rule
  public JoobyRule boot = new JoobyRule(new App2());

  @Test
   public void test2() {
     ....
    }
}

class TestApp3 {

  @Rule
  public JoobyRule boot = new JoobyRule(new App3());

  @Test
   public void test3() {
     ....
    }
}

```

Each test define a `JoobyRule` to each of your `apps`. That's all each test method will create/start/stop an App.

Cool? Or I miss something?

**Comment by ph-ms** [comment]
That's what I suspected I had to do.  There's no test-time way of instantiating a Jooby app w/o the annotations then.

**Comment by jknack** [comment]
Well you can do it like:

```java
public void test1() {
   App1 app = new App1();
   try {
     app.start();
     // client code to call your app goes here
   } finally {
      app.stop();
   }
}
```

This is exactly what JoobyRule does.

**Comment by ph-ms** [comment]
Happy to know there's no magic. I did wonder if everything was done in the constructor (and overrideable methods) or not.
