### ISSUE TITLE
Adding LetsEncrypt 

### ISSUE THREAD

**Issue by S66D** [jooby-project/jooby#638]
Hi @jknack could it be beneficial to add a `Let’s Encrypt` an certificate authority as a `jooby` module.
There are `Java` clients already built  for the (CA).
[https://letsencrypt.org/docs/client-options/](https://letsencrypt.org/docs/client-options/)
It could be as simple as:
```java
{
    use(LetsEncrypt());
}
```
Good luck.

**Comment by jknack** [comment]
Duplicated of https://github.com/jooby-project/jooby/issues/269
