### ISSUE TITLE
Send message to all connected web socket clients

### ISSUE THREAD

**Issue by mer23** [jooby-project/jooby#645]
I'm using Jooby's MVC routes for an API. I have also set up a websocket, to which a few clients connect. What I'm trying to do is send a message to all connected websocket clients whenever a specific http request is received in the server. This is how my route method looks like:

```
    @Path("/player")
    @Produces("application/json")
    public class PlayerRoute {
        @POST
        public Result newPlayer(Request req, @Body Player player) {
            //this is what I'm trying to achieve..
            allWebsocketSessions.foreach(session ->
                    session.send("a new player has been created")
            );
            return Results.ok();
        }
}
```

I've read jooby's documentation but can't figure out how to do it.

Thanks in advance.

**Comment by jknack** [comment]
Correct, there is no way to do such thing today. But what you showed me should works.

Go to your application do something like:

```java

public static final List<WebSocket> allWebsocketSessions = new CopyOnWriteArrayList<>();

{
    ws("/ws", ws -> {
       sessions.add(ws);

       ws.onClose(() -> sessions.remove(ws));
    }); 
}
```

From your controller you can access to `allWebsocketSessions`.

It is a (not that ugly) workaround.

Let's keep this open and will find a way to do it automatically.

**Comment by mer23** [comment]
Worked perfectly! Thanks!
