### ISSUE TITLE
Datastax DSE a Separate Module? 

### ISSUE THREAD

**Issue by noboomu** [jooby-project/jooby#653]
Would it make sense to subclass the existing Cassandra module or create a new one if a user wants to use the DSE java driver?

**Comment by jknack** [comment]
what is different and/or how hard is to use the dse driver?

**Comment by noboomu** [comment]
Session is replaced by com.datastax.driver.dse.DseSession 
Cluster is replaced by com.datastax.driver.dse.DseCluster
The rest is identical but additional dependency on:
```
 <dependency>
        	<groupId>com.datastax.cassandra</groupId>
        	<artifactId>dse-driver</artifactId>
        	<version>1.1.1</version>
</dependency>
```
It was easy for me to implement as a one off so may not be worth the trouble.
