### ISSUE TITLE
Questing regarding scalable authentication

### ISSUE THREAD

**Issue by krisztiankocsis** [jooby-project/jooby#666]
I would like to implement the following authentication mechanism and I have some questions regarding it:

* Use a single endpoint with form-based direct authentication (user + password)
  * Is it possible to use Pac4J to perform form-based authentication for only one endpoint that performs only the authentication within Pac4J and no actual endpoint is needed or I have to make a fake one?
  * This endpoint will generate a JWT and return it as a response header or body
  * The JWT will be cached for performance reasons
* After authentication all other endpoints (including the logout) should authenticate the requests with the previous issued JWT
* No sessions is required, also it would be a very good to actually don't have session at all
  * JWTs are self-contained, caching is only needed for performance reasons
  * With disabled session I don't have to cluster the session database between multiple nodes, JWT can be interpreted by other nodes too and cached when valid

Is it possible to implement this behavior with **jooby-pac4j** or I may have to patch it and provide a PR? What do you think about it?

**Comment by jknack** [comment]
Hi @krisztiankocsis,

 Think is possible... the `Auth` module has few overloaded method that let you specify a path, like:

```java
new Auth()
   .form("/this/path/has/form/login")
   .client("*", new ParameterClient(...));
```

Here is example/demo with all the available pac4j clients: https://github.com/pac4j/jooby-pac4j-demo/blob/master/src/main/java/org/pac4j/demo/jooby/App.java. It is probably outdated but it is good as starting point.

In general, think is possible.. still not sure how to avoid session usage if you used a `form` auth.

Another good option will be to add a [JWT](https://connect2id.com/products/nimbus-jose-jwt) module.

Anyway, let me know how it goes and if you have questions.

**Comment by jknack** [comment]
Here is another useful link for pac4j: http://www.pac4j.org/1.9.x/docs/clients.html
