### ISSUE TITLE
HttpServletRequest Attributes not available to jooby App

### ISSUE THREAD

**Issue by andrenpaes** [jooby-project/jooby#674]
We're trying to use jooby inside a Servlet container. In that setup, we also have a Filter that adds request scoped info into each request (using [`HttpServletRequest#setAttribute`](http://docs.oracle.com/javaee/7/api/javax/servlet/ServletRequest.html#setAttribute-java.lang.String-java.lang.Object-)).

Unfortunately, there's no way to access those attributes using jooby's `Request` object. We have an ugly workaround in place, using a ThreadLocal and a jooby before filter:
```java
before((req, rsp) -> {
    req.set("attributeName", someThreadLocal.get());
});
```

A possible solution, would be merging the `HttpServletRequest#attributes` into jooby's `locals` attributes. I have a patch that implements that, I can open a PR if it seems like a good enough solution. Let me know.

**Comment by jknack** [comment]
Sounds very good. Please send your patch.

Thanks
