### ISSUE TITLE
Using flash scope with an object does not work in view/template

### ISSUE THREAD

**Issue by nfleury** [jooby-project/jooby#689]
Using the following code:

```
Message message = new Message();
message.title = "test";

req.flash("message",message);
```

and in template:

```
{%if flash.message!=null%}
		
				<div class="ui {{flash.message.type}} message">
					<div class="header">{{flash.message.title}}</div>
					<p>{{flash.message.description}}</p>
				</div>
{%endif%}
```

flash.message is not null => I can see the message box displaying meaning the object is properly passed through session, but title, descirption ... are empty ... could it be a serialization issue ?

Using primitive type with flash does work properly within template.

Thanks

**Comment by jknack** [comment]
That's correct. The `request.flash` accept an object to "simplify" usage and allow the usage of primitives and string... realize this is confusing. Reason? Flash scope use a cookie and in general we should limit the usage to just status messages (or similar).

Will add a doc comment mentioning this.

**Comment by nfleury** [comment]
I confirm this is a little bit confusing with current method signature and worth mentionning in the documentation.

Thanks !
