### ISSUE TITLE
ebean: add query-beans maven integration

### ISSUE THREAD

**Issue by jknack** [jooby-project/jooby#697]
See http://ebean-orm.github.io/docs/query/typesafe

**Comment by jknack** [comment]
Query-beans doesn't work after a jooby:run reload... I wasted lot of time but couldn't figure it out :(

I will leave it open if someone else want to give it try, but probably the best thing to do is to use a IDE plugin enhancement

**Comment by huysamen** [comment]
@jknack I've been away for a while, will see if I can have a look, but AFAIK you need to use the IDE plugin for it to work properly anyway.

**Comment by ajcamilo** [comment]
I'm having the same problem.

The solution is to execute de goal `process-classes` instead of `compile` at the `setupCompiler`.
