### ISSUE TITLE
Incorrect groupId for Ebean maven plugin

### ISSUE THREAD

**Issue by huysamen** [jooby-project/jooby#699]
Ebean changed their domain from org.avaje.ebean to io.ebean when they moved to version 10.  I missed the maven plugin specified in the main pom when I did the upgrade.

**Comment by jknack** [comment]
It is Ok, always a pain. They also have very different version number for their projects :(

Are you going to send a pull request for this? If so, can you also look at #697

**Comment by jknack** [comment]
BTW this one is more or less working: https://github.com/jooby-project/ebean-starter

**Comment by huysamen** [comment]
Yeah I think Rob is trying to keep the versions closer together these days, but it is still a pain.  I have made a PR already.  I'll have a look at #697 when I get a change sure.
