### ISSUE TITLE
Interceptor with MVC Api

### ISSUE THREAD

**Issue by olabomba** [jooby-project/jooby#704]
Hi,
It seems interceptors aren't compatible with MVC Api,
It only works for now with non-MVC API.
Regards,

**Comment by jknack** [comment]
That's right. Filter are supported via script API (sorry)

**Comment by olabomba** [comment]
So, I've no way to add an interceptor to my MVC routes ? Is it planned ?

**Comment by jknack** [comment]
No plans yet. Usually think it is clear to see filter inside the bootstrap class.

Why script filter isn't an option?

**Comment by olabomba** [comment]
I want to use the script filter, but keep my routes with controller logic with the MVC API.
Unfortunately, the script filter only works with routes scripts.

**Comment by thomasguo** [comment]
@olabomba  You can still use script interceptors to affect the MVC routes. The key point is order. You must  declare the interceptors before registering MVC routes/controllers.

**Comment by juan-conde** [comment]
I open again the question, i cant find a way to make it work. 
Right now, im using MVC API to create all my controllers, and adding them with mvc(Router class) method. 

Im in need of adding to certain controllers/paths a custom rate limit handler, but i cant find a way to do this with de mvc api. Can you help me? do you have any example of how this could be donde?
