### ISSUE TITLE
allow to run code in the IO Thread?

### ISSUE THREAD

**Issue by jknack** [jooby-project/jooby#706]
We don't today. Application code always run in a worker thread.

Do you think we should allow it?

**Comment by huysamen** [comment]
I think so.  It works really well in other reactive frameworks like Vert.x for example.  Let's say you want to do something like check a JWT token in a filter, or just parse some headers before handing off your request to a controller that needs to do something more intensive (e.g. DB access), having the ability to run those in the IO thread can be quite advantageous.
