### ISSUE TITLE
WebSocket Client

### ISSUE THREAD

**Issue by jschneider** [jooby-project/jooby#716]
Hey guys,

would love to have a web sockets client for my integration tests. Any suggestions what to use? Maybe add a dependency and a sample to the tests?

**Comment by jknack** [comment]
```xml
<!-- Async Http Client -->
    <dependency>
      <groupId>com.ning</groupId>
      <artifactId>async-http-client</artifactId>
      <scope>test</scope>
    </dependency>
```

Example: https://github.com/jooby-project/jooby/blob/abec5e85904b36c30ee1f9f4eed945d8549a4a15/coverage-report/src/test/java/org/jooby/ws/OnTextMessageFeature.java

If you find a better one let me know.

ps: In future please use [gitter](gitter.im/jooby-project/jooby)  for these type of questions. Thanks

**Comment by jschneider** [comment]
Ok. Thanks and sorry.
