### ISSUE TITLE
Upgrade Freemarker to latest stable (2.3.26)

### ISSUE THREAD

**Issue by hansjorg** [jooby-project/jooby#719]
It would be great to have the latest stable Freemarker version (2.3.26) for jooby-ftl. Using 2.3.23 now.

**Comment by jknack** [comment]
Sure thing. You can upgrade today using the `freemarker.version` property:

```xml
<properties>
  <freemarker.version>2.3.26</freemarker.version>
</properties>
```

**Comment by jknack** [comment]
Just checked and there isn't a .26 stable release yet.

**Comment by hansjorg** [comment]
I thought so as well at first, but it seems that the "-incubating" in the version is related to the Apache project status and not with code maturity.

> Latest stable release: 2.3.26-incubating
> This is a stable, final release. The "incubating" suffix is required by the Apache Software Foundation until the project becomes a fully accepted (graduated) Apache project

**Comment by jknack** [comment]
Oh yes, now I remember it is an Apache project now.
