### ISSUE TITLE
Jooby overriding Content-Type header

### ISSUE THREAD

**Issue by leonardosnt** [jooby-project/jooby#730]
Code:
![](http://i.imgur.com/1nN12NJ.png)

Response headers:
![](http://i.imgur.com/RKZtiLw.png)

Why? Is this supposed to happen?

**Comment by jknack** [comment]
Hi,

 There is a specific method for content-type header: ```rsp.type("application/json")``` or just ```rsp.type("json")```

But got your point, it should work too.
