### ISSUE TITLE
[documentation] Using Lightbend's "Config Library" could have more examples

### ISSUE THREAD

**Issue by paul-hammant** [jooby-project/jooby#752]
One that is missing, is how to connect command-line arguments to the result of `require(Config.class)`. 

Lightbend's own documentation doesn't show that either.

**Comment by jknack** [comment]
Command-line arguments are documented here: http://jooby.org/doc/#conf-env-and-logging-precedence

**Comment by paul-hammant** [comment]
Suggestion:

automatically translate to:
`java -jar myapp.jar application.port=8888 application.path=/myapp`
and be accessed in the application, like so:
```
Config cfg = require(Config.class);
String myPath = cfg.get("application.path")
// more examples in Lightbend's Config documentation above
```

It is couple of the lines of Java code that is missing from the conf-env-and-logging-precedence section.
