### ISSUE TITLE
I18N support in jooby.

### ISSUE THREAD

**Issue by thomasguo** [jooby-project/jooby#755]
Hi @jknack ,

I searched the whole online documentation of Jooby and didn't find content about i18n.  Is there any built-in support for i18n in Jooby?  Could you please provide some hints or suggestion path to do i18n in my jooby application?  Thanks.

**Comment by jknack** [comment]
i18n is/should-be a template engine concern. which template engine are you?

**Comment by thomasguo** [comment]
Yes you are right, mostly it is  a  template engine concern.   I am going to choose one from Freemarker and Pebble.  I haven't seen information about i18n in Freemarker's documentation. Pebble provides a function i18n(basename, key, args...), which works well.  But  I don't like to specify the resource bundle basename in every call in template.  I prefer it like  i18n(key, args...) because I hope:
1) Template authors should't care the resource bundle basename.  She only needs to know the unique message keys.  
2) End user can specify what locale she like to see from the UI and system should remember this setting in following requests  via cookie, session... something like that.  SpringMVC works this way if I am not wrong.
3) Further,  I wish to split my large application into many small subApp/modules vertically. Every subApp has its own message bundle files with different subApp-related names.  wherever in template file we just need to call i18n(key, args...) to retrive the messages. Besides,  in routes we could call similar class mthod to get localized messages when necessary.

That's why I post this issue/request.   If Jooby doesn't provide this support on framework level,  I would have to implement it on application level, or maybe in the form of an jooby extension module.

Would appreciate to have your suggestion.  Thanks.

**Comment by jknack** [comment]
Good points.

I implemented an i18n application with handlebars.java and jooby. It was a mix of request local variable and cookie.

A generic module which expose locale to request local variable will be a good addition. Locale might come from cookie, accept-lang header, etc..

**Comment by thomasguo** [comment]
Hi @jknack,
I wrote some code for this to organize all resource bundles, and wrote an pebble extension to add a new function named message(key, params).  So far so good.   But then I found it is impossible to get the dynamic locale information within the function code, beceause the template object was created with a fix locale. I checked the source code of class `org.jooby.pebble.PebbleRenderer`  and saw the code is: 
 ` template.evaluate(writer, model);`
I think we'd better use the other evaluate method with 3 parameters:
`PebbleTemplate.evaluate(Writer writer, Map<String, Object> context, Locale locale)`,  
so that I could retrieve the locale information from pebble function execution context.

So,  I proposal that Jooby should provide some built-in support for i18n. Briefly it can dynamically parse locale information from client-side request,  store it as a request or session variable, and pass it to the view engine(not limited to Pebble) before rendering.    With this supoport we can easily make i18n extensions for all kind of template engines.

**Comment by jknack** [comment]
Going to update pebble (and any other engine with built-in support for locale object).

This is how will works:

`firstNonNull(locals.get("locale"), req.locale(), app.locale())`

If you do nothing locale is resolved against the `Accept-Language` header (if present) or fallback to `application.lang` property.

If none of those works for you, you can set a req local attribute:

```
use("*", (req, rsp, chain) -> {
  Locale locale = ...; //compute locale from cookie, header or whatever you want
  req.set("locale", locale);
});
```
Will send a pull request shortly, so you can review it

**Comment by thomasguo** [comment]
Perfect.  Looking forward to use it in the coming release.
