### ISSUE TITLE
gradle starter project 

### ISSUE THREAD

**Issue by jknack** [jooby-project/jooby#756]
demo/starter project using gradle

**Comment by vjames19** [comment]
@jknack I want to create the starter project, but I don't have sufficient permission to create the repo. Can you create one maybe named "kotlin-gradle-starter" and give me access to it?

I'm thinking that this one should also showcase the jooby gradle plugin.

Is there anything else that comes to mind that this project should showcase?

**Comment by jknack** [comment]
Try now, (think) give you write access now. It is Ok if you want to create new repositories, but please don't push directly to them, do it via pull request.

There is an issue about gradle-starter project #756, so will be great to have a gradle java and gralde kotlin project. There is an issue with gradle while using netty (default server), it is related to OS specific jars.

Also, for kotlin will be nice to add integration tests using Spek.

**Comment by vjames19** [comment]
@jknack I can work on having both.

I will start with the kotlin-gradle-starter, because I already have a working example doing integrations tests with Spek.

Here is an example:

```kotlin
object UsersFeatureTest : Spek({

    jooby(app()) {
        describe("Getting a user") {
            given("that the user doesn't exist") {
                it("should return 404") {
                    get("/users/${Long.MIN_VALUE}")
                            .then()
                            .statusCode(Status.NOT_FOUND)
                }
            }

            given("a user that exists") {
                it("should return the user") {
                    val user = get("/users/1")
                            .then()
                            .statusCode(Status.OK)
                            .As<User>()

                    user.id shouldBeGreaterOrEqualTo 0L
                    user.username.isEmpty() shouldBe false
                }
            }
        }
    }
})
```

Given the absence of Junit rules in Spek, I came up with the following extension function to handle the app lifecycle.

```kotlin
fun SpecBody.jooby(app: Jooby, body: SpecBody.() -> Unit) {
    beforeGroup {
        app.start("server.join=false")
    }

    body()

    afterGroup {
        app.stop()
    }
}
```

Should the extension function be part of a testing module for Kotlin? Just like you have the Junit rules be part of the library.

**Comment by jknack** [comment]
Like it! yea we could put the test funtion in `src/test/kotlin` at `jooby-lang-kotlin`

**Comment by vjames19** [comment]
@jknack I don't have permission to create the repo. Can you create one named kotlin-gradle-starter? Then I will fork that one.

**Comment by jknack** [comment]
@vjames19 https://github.com/jooby-project/kotlin-gradle-starter

**Comment by vjames19** [comment]
Hey, thanks for doing this. Unfortunately, I'm going to beon vacation until
the 27th. When I'm back if nobody has done it yet I will take care of it.

In the meantime here is an example project for inspiration
https://github.com/vjames19/kotlin-microservice-example

**Comment by vjames19** [comment]
@jknack I just did a PR for this https://github.com/jooby-project/kotlin-gradle-starter/pull/1

**Comment by jknack** [comment]
Gradle project ready: https://github.com/jooby-project/gradle-starter
