### ISSUE TITLE
pac4j: logout doesn't work with MongoSessionStore

### ISSUE THREAD

**Issue by silentcharacter** [jooby-project/jooby#759]
Hi Edgar!
I've tried using session(MongoSessionStore.class) and noticed that logout doesn't work. 
Found out that session.unset() is not applied in mongo session collection. During next request unset parameter exists again.

**Comment by jknack** [comment]
Think there is a bug here with `unset` but for logout you should use `destroy`

**Comment by silentcharacter** [comment]
@jknack  I'm using jooby-pac4j\1.1.0\jooby-pac4j-1.1.0.jar!\org\jooby\internal\pac4j\AuthLogout.class
...
Optional<String> profileId = ((Session)ifSession.get()).unset(Auth.ID).toOptional();
...
