### ISSUE TITLE
Pebble template file not found if packaging into jar

### ISSUE THREAD

**Issue by thomasguo** [jooby-project/jooby#765]
Hi @jknack,

I use pebble as the template engine.  It works well in dev mode. Bu after packaging the app into jar file and running "java -jar myapplicationname.jar",  I got the stack trace error message says:
java.io.FileNotFoundException: Template not found: pet/show in [pebble]

I import pebble in main app like this:
		use(new Pebble("/views", ".pebble"));

BTW, I have tried to use Freemarker in the same application, it goes well.

**Comment by thomasguo** [comment]
I got more information.

If I import Pebble on the default way like:  
  `use(new Pebble());`
or use the one-parameter constructor like :
  `use(new Pebble(".pebble"));`

Both works.

But it doesn't work if using the two-parameters constructor like:
`use(new Pebble("/views", ".pebble"));`

**Comment by jknack** [comment]
Do a quick try without `/` like `use(new Pebble("views", ".pebble"));`

**Comment by thomasguo** [comment]
Yes it works if I remove the leading '/'.  

Great and Thanks!

**Comment by jknack** [comment]
Going to fix, so it works regardless `/`

**Comment by thomasguo** [comment]
Yeah it works  regardless `/` .

I like to know how would you fix it.   Make it works both in case  with or without `/` ?

**Comment by jknack** [comment]
Exactly.
