### ISSUE TITLE
Ability to interact with cached responses for dynamic endpoints

### ISSUE THREAD

**Issue by paul-hammant** [jooby-project/jooby#769]
This is about skipping Jackson invocation for a tiny perf boost....

Consider this code:

```
get("/foo", (req, rsp) -> {
    if (userIsAuthorized(req)) {
        rsp.send(foo);
    }
});
```

I'd like to be able to do:

```
get("/foo", (req, rsp) -> {
    if (userIsAuthorized(req)) {
        rsp.sendAndCacheIfNotCached(foo, ALL_SESSIONS);
    }
});
```

In this instance I have a route that only certain people are authorized to, but a response that all users will see that is exactly the same.

Jooby would check if it had that sendee before, and if it had, then it sends the pre-serialized JSON **instead of passing the object through Jackson again**.  The ALL_SESSIONS enum says that the scope of the caching is for all sessions. I don't know what the alternates to that would be - that is because a 204 might suffice for the same session, and there's no third permutation, I think.

There's pros and cons on whether == or .equals() is how equality is tested, of course.

**Comment by jknack** [comment]
Hi Paul,

 Think is very application specific and isn't a good fit for addition.

**Comment by paul-hammant** [comment]
So I guess I could implement a cache myself inside the handler method. I'd also employ ObjectMapper myself inside the handler method and save (ConcurrentHashMap) the JSON.

How to respond with JSON though?  I see that rsp.send(x) takes any object but even for strings it passes it through Jackson to end up as text .. and ends up with more " wrappers around the string, which is undesired.

**Comment by jknack** [comment]
If you are going to manually do json, don't install/use the Jackson module.
