### ISSUE TITLE
Let ebean module support multiple named dataSources 

### ISSUE THREAD

**Issue by thomasguo** [jooby-project/jooby#771]
Sometimes we need to connect to multiple databases within the same application. Currently with Jdbc 
module  we can do like this: 
```
{
  use(new Jdbc("db.main"));
  use(new Jdbc("db.audit"));

  get("/db", req -> {
    DataSource maindb = require(DataSource.class);
    DataSource auditdb = require("db.audit", DataSource.class);
    // ...
  });
}
```
But with ebean module,  we cannot name the EbeanServer bean on the same way.  Currently Jooby just parses the url to 'guess' a database name, that makes it difficult to inject the ebeanserver via name.  Why not we just use the Ebeanby's name as the datasource name?

**Comment by jknack** [comment]
Can you explain why database name isn't enough? The reason why jdbc module allow to use the `key` as name is bc of backward compatibility.

New jdbc-like modules use the database name.

**Comment by thomasguo** [comment]
Because in case there are many datasources, we need to specify its name when retrieve the instance via require() or injection in code. On the other hand, when the applications is deployed to prod environment, the datasource.url is determined by users, not by developers.  We want more flexibility.    
When I review the ebeanby code,  I find it could append a 'database' or 'databaseName' parameter to the URL to specify database name.  So now I think this is not a big problem any more.  Please just ignore this request if it doesn't fit the whole desgin.

BTW,  in multi-datasource case with ebean module,  the hot-reload feture doesn't work in dev mode.  I mean, using  `mvn jooby:run`  command.  Seems the ebean enhancement cause it.

**Comment by jknack** [comment]
> On the other hand, when the applications is deployed to prod environment, the datasource.url is determined by users, not by developers. We want more flexibility.

That's a good argument.

> BTW, in multi-datasource case with ebean module, the hot-reload feture doesn't work in dev mode. I mean, using mvn jooby:run command. Seems the ebean enhancement cause it.

Raise a new issue, add an example and error output. I will look later

**Comment by thomasguo** [comment]
OK.  I am going to raise a new issue now.
