### ISSUE TITLE
SSIHandler bug - too indiscriminate on looking for includes

### ISSUE THREAD

**Issue by paul-hammant** [jooby-project/jooby#773]
The example include where `/` is the pattern ...

```
<-- /static/chunk.html -->
```
... suggest that any thing between `<!-- /` and `-->` in a line is eligible to be found on the file system and included.

Maybe instead of `/` for the default pattern, `JOOBY-SSI/` is a better and clearer choice?

**Comment by jknack** [comment]
There is a `delimiters` specialization: 

```
get("/static/**", new SSIHandler().delimiters("<!-- JOOBY-SSI", "-->");
```

**Comment by paul-hammant** [comment]
I saw that, and would use it, was just saying that the default `/` is too broad, and it is possible to match unexpected things. In Html comments are not unusual, and one that just accidentally begins with a `/` might cause exceptions in static resource handling.
