### ISSUE TITLE
Documentation for jooby-livereload - not 100% clear

### ISSUE THREAD

**Issue by paul-hammant** [jooby-project/jooby#774]
1. How does the JS resource get listed as an asset to serve?

2. Does `env=dev` also control the inclusion of livereload.js into the uber-jar ... that's headed towards production Would you employ Maven profiles somehow as part of this?

**Comment by jknack** [comment]
1. Via `assets` handler? or whatever works for you. The livereload listen for changes in the `public` directory (if present). Or you can add a new path via [livereload.register](http://jooby.org/apidocs/org/jooby/livereload/LiveReload.html#register-java.nio.file.Path-java.lang.String...-)

2. application.env=dev turn on the module, any other value turn it off:

* livereload.js is not serve
* watcher is off

But the jooby-livereload.jar (including the livereload.js) isn't excluded from final jar. Unless, you define the dependency as `provided` (think, not 100% sure)

**Comment by paul-hammant** [comment]
A scope of 'provided' won't work I don't think

Maybe a profile is best - I've had a huge amount of success with them before. -Pproduction wouldn't have the dep on jooby-livereload.jar, whereas a default profile would.  That now leaves the difficulty of programmaticaly setting it up:

```
IF_IN_CLASSPATH LiveReload.class:
    use(new LiveReload());
```

... if you know what I mean.

One more thing - https://github.com/jooby-project/jooby/blob/master/jooby-livereload/README.md doesn't say that the actualy Javascript resource has to be copied into src/main/resources/static/js/ (etc). And I think that's what you're saying with "is not serve[d]"

**Comment by jknack** [comment]
You don't need to copy the livereload.js. It is included in the jooby-livereload.jar.

> livereload.js is not served

The route is turned off so there is no way to access to the file from browser.

**Comment by paul-hammant** [comment]
ok, thanks
