### ISSUE TITLE
Could org.jooby.test.ServerFeature go into the main Jooby jar so that we may more easily report bugs in reproducible way.

### ISSUE THREAD

**Issue by paul-hammant** [jooby-project/jooby#795]
I'm wanting to write things like:

```
package org.jooby.issues;
import org.jooby.Err;
import org.jooby.test.ServerFeature;
import org.junit.Test;
public class Issue791 extends ServerFeature {
  {
    get("/791", req -> req.param("missingParam").value());
    err(Err.Missing.class, (req, rsp, x) -> {
      rsp.send("Missing");
    });
  }
  @Test
  public void specializedErrHandlerShouldCatchErrExceptions() throws Exception {
    request()
        .get("/791")
        .expect("Missing");
  }
}
```

In bug reports bodies like this, but in order to do so I want to easily depend on `ServerFeature` in my application codebase as I temporarily (and in-situ) make a reproduction.

**Comment by paul-hammant** [comment]
You know, was nearly as easy as adding ...

```
   <dependency>
      <groupId>org.jooby</groupId>
      <artifactId>jooby</artifactId>
      <classifier>tests</classifier>
    </dependency>
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>fluent-hc</artifactId>
      <scope>test</scope>
    </dependency>
```

... to my project's POM

**Comment by paul-hammant** [comment]
`ServerFeature` and the above idiomatically correct way of reporting bugs, is not detailed in otherwise excellent `http://jooby.org/doc/`.  

 https://gist.github.com/paul-hammant/1988dec650feddf9c6cf1209a06e0a12  being an example of what you'd want to receive I presume.

**Comment by jknack** [comment]
Hi @paul-hammant 

 ServerFeature is something internal to Jooby. I wrote that without too much thinking at very beginning of the project. There is no documentation and you should not used it at all.n The `jooby-tests` jar is available for historical reasons and bc child modules need it, but again is something internal and it might change without notice.

The supported and documented way of writing is test is available here: http://jooby.org/doc/#tests

Appreciated the test with the use case, it really helps. Unfortunately, not every single user take the time to write them and it's OK.

**Comment by paul-hammant** [comment]
I've no problem writing tests at all for Jooby. I've a super speedy Unit->Integration->Functional sequence in a Maven build :)

I'm writing about how we report bugs to you. I hear you say, "not every single user take the time to write them and it's OK", but still want to write bug reports **and feature requests** in code in a way that's easy for you to consume. I'm sure I'm not alone, and if we can get you to runaway success, then you'll be glad you made a "how to a report a defect" section of the documentation :)

**Comment by jknack** [comment]
Got it. Yea so ServerFeature it is OK for reporting or you can use documented way.

Need to add a Contributing.md we details and there we can add specific details... so much to do :)

**Comment by jknack** [comment]
There was a small typo/bug in the lines you submitted:

```java
err(WhoaNow.class, (req, rsp, x) -> {
  rsp.send(Results.ok(x.getCause().getMessage()).type("plain"));
});
```

Or:

```java
err(WhoaNow.class, (req, rsp, x) -> {
  rsp.send(Results.ok(x.getCause().getMessage()).type("tex/plain"));
});
```

:)
