### ISSUE TITLE
Optional Upload with malformed file multipart part

### ISSUE THREAD

**Issue by DrorBuhnik** [jooby-project/jooby#803]
When we have this endpoint:
```
@POST
public Result create(Optional<Upload> file, String other) {...}
```
And the client upload a multipart with 'file' part where the 'filename' doesn't exists we get weird result, file.isPresent() return true but he is a 'Object' type instead of 'Upload'
Currently we manually check it:
```
if (file.isPresent()) {
    if (!(file.get() instanceof Upload)) {
        throw new Exceptions.BadRequest("Upload 'file' is missing (did you put 'filename'?)");
    }
}
```

**Comment by jknack** [comment]
Will have to look, didn't know the filename attribute was optional

**Comment by DrorBuhnik** [comment]
I'm not sure it is optional
I'm completely fine if such malformed part will result in Bad Request 400
