### ISSUE TITLE
Multipart with json part

### ISSUE THREAD

**Issue by DrorBuhnik** [jooby-project/jooby#804]
Question
Is there a way to get Object parsed from json as part of a multipart?
(automatic, aka jooby does all the work :smile:)

Meaning:
```
@POST
public Result create(Upload> file, MyObject myObject) {...}
```
And 'MyObject' is a JSON part

Currently we are doing it manually:
```
@POST
public Result create(Upload> file, @Named("MyObject") String raw) {
    MyObject myObject = gson.fromJson(raw, MyObject.class);
}
```

**Comment by jknack** [comment]
Found and reported the bug to netty: https://github.com/netty/netty/issues/6800.

Still need to figure it out how to do it from MVC routes. From script routes it is quite easy... for mvc you need to inject the Request object, like:

```
   @POST
    @Path("/804")
    public String handle(final Upload myfile, final Request req) {
      MyObject object = req.param("myObject").to(MyObject.class, "json");
    }
```

Not sure if it's better than what you did :)
