### ISSUE TITLE
RequestLogger with query params

### ISSUE THREAD

**Issue by DrorBuhnik** [jooby-project/jooby#805]
Currently RequestLogger log url path only without query params
I look but didn't find if NCSA format define what exactly needs to go into the request part of the log

Can we add query params to the log?
I can create pull request with the change (If I do, do you want it to be controllability, so the users can turn it on or off like they config the data format?)

**Comment by jknack** [comment]
Pull request with ability to turn on (off by default) will be great:

```
use(new RequestLogger().queryString());
```
