### ISSUE TITLE
Jooby's Roadmap

### ISSUE THREAD

**Issue by thomasguo** [jooby-project/jooby#811]
Hi guys:
Being a jooby user, I like to know what the roadmap/direction of Jooby framework is.  Or maybe we can discuss in this thread.  Thanks.

**Comment by jknack** [comment]
Roadmap is usually the list of open and accepted issue here in Github :)

Having said that I'm happy to discuss and design a roadmap if we (as community) need one.

**Comment by asm0dey** [comment]
@jknack as jooby user I would also like to know when I can wait for next version and what will be included in it. For example, pac4j2 is very wanted change and some issues on the list (like the upgrade to rxjava 2) look like they won't be completed in near future.

**Comment by jknack** [comment]
@asm0dey 

When?
Hard to say, mainly bc do this in my free time.

What?
At any time you can go and see the open milestones: https://github.com/jooby-project/jooby/milestones

You will see there: 1) next version; 2) what is included in next version

Always try to avoid major library upgrades (like rxjava 2), but sometimes there are some exceptions (pac4j2) and we end up having to modules for the same library (pac4j1 and pac4j2).

Rxjava2 is going to be added in the next major release of Jooby 2.x

**Comment by asm0dey** [comment]
@jknack  thank you for the link to milestones page! Now I can see that 1.3.0 is on its way and that's enough for me.

Is there any way I can help you with release?
