### ISSUE TITLE
How to access session object in template?

### ISSUE THREAD

**Issue by thomasguo** [jooby-project/jooby#821]
Hi @jknack ,

How can we acccess the session object in template view code ?    I expected there has been a 'session' object injected so that I could use it like  `${session.username}` ,  supposing we are in freemarker template .  But that seems not working.

**Comment by jknack** [comment]
You need to set/do it manually as request local variable:

```
{
  get(..., req -> {
    req.set("session", req.session());
  })
}
```

After that you will be able to access to session attributes
