### ISSUE TITLE
Facilitate component marketplace by changing 'prefix' to predicate++ in Jooby ctor

### ISSUE THREAD

**Issue by paul-hammant** [jooby-project/jooby#825]
In order to facilitate a component marketplace where people make Jooby applications that can later be recomposed by others into solutions that use multiple Jooby applications mounted in the same 'site', there needs to be a way setting additional config, long after the component was made and shipped.  Config to do with it's URL prefix (as possible today in the constructor to the Jooby class), but also other things like binding to domains in a declarative (predicate) style (one app instance serving different things for two different domains).

Best practice for apps for that future component marketplace today would be:

1. From the reusable/embeddable/composable app makers...

```java
public class FooApp extends Jooby {

  public FooApp(String prefix) {
    super(prefix);
  }

  public FooApp() {
     // nothing
  }

  {
    get("/", () -> Results.html("foo"));
    // etc
  }
}

public class BarApp extends Jooby {

  public BarApp(String prefix) {
    super(prefix);
  }

  public BarApp() {
    // nothing
  }

  {
    get("/", () -> Results.html("bar"));
    // etc
  }
}
```

And for the end-user pulling several usable/embeddable/composable apps from the component marketplace:

```java
public class MyApp extends Jooby {
  {
     // me doing domain switching here (but it could be any delegator or this implicit front-controller routing thing reminiscent of 'model2' from 2001) ...
     use("*", (req, rsp, chain) -> {
       if (req.hostname().equals("foo.com")) {
         chain.next("/something-unique-for-foo", req, rsp);
       } else if (req.hostname().equals("foo.com")) {
         chain.next("/something-unique-for-bar", req, rsp);
       } else {
           rsp.send("oops");
       }
     });

     // me composing other people's apps into my larger app ...
     use(new FooApp("something-unique-for-foo"));
     use(new BarApp("something-unique-for-bar"));
  }
}
```
Which means best practice would be to ask people making apps for the future component marketplace, would be for them to provide a range of constructors for Jooby with the string prefix.

Which means they could not use the default constructor fragment, as numerous code examples show

```java
// Can't have a prefix at all :-(
public class App extends Jooby {{
   // Jooby setup
}}
```

I'm thinking that prefix as is today, become one implementation of a `JoobyRoutingPredicate' that allows for other more elegant declarative possibilities for in overloaded method.  Specifically, the overloading of:

```java
use(new FooApp());
use(new BarApp());
```
More towards:

```java
use(new FooApp(), new WhenAndIfToUseFooPredicate());
use(new BarApp(), new WhenAndIfToUseBarPredicate());
```

Key is that FooApp and BarApp don't have to participate in the prefix setting. In my proposal, they are a separate concern of the person assembling them, and in a declarative style (rather than if/else centric).

Note: This issue replaces the incorrectly described #812.

**Comment by jknack** [comment]
Done in 2.0.0

https://jooby.io/#router-composing-routes

https://jooby.io/#router-dynamic-routing

**Comment by paul-hammant** [comment]
yay!
