### ISSUE TITLE
Calling itself from within

### ISSUE THREAD

**Issue by mer23** [jooby-project/jooby#828]
I'm getting a request with a shared autogenerated link (something like **_api.mywebiste.com/shared/cf23df2207d99_**)
That link should lead to _**api.mywebsite.com/myroute/to/somewhere**_.
The only ways I can think of right now are either explicitly calling the function that deals with the route:
`req.require(MyRoute.class).somewhereMethod(req);` or using something like OkHttp to call _**localhost/myroute/to/somewhere**_.

Is there a more elegant way of doing that?

Thanks in advance.

**Comment by mer23** [comment]
The problem is that the shared links are dynamically generated, I don't know them beforehand :(

**Comment by jknack** [comment]
Probably missing something but still you can: `@Path({"shared/:id", "myroute/to/somewhere"})`
