### ISSUE TITLE
Keep (some) interceptors when exception is thrown

### ISSUE THREAD

**Issue by DrorBuhnik** [jooby-project/jooby#834]
Currently when we throw an exception the error handling flow create a new response instance,thus, ignoring all the 'before' interceptors work that was done
Example:
Some endpoint doing actual work and should return json but there is and interceptor before it that sets custom header, if we throw an exception then the we won't get the custom header
Another, more common example - CORS, when error is thrown the client cannot access the status code as there are not CORS headers in the response

I can understand the reasons for this kind of behavior, it's only logical that error handling doesn't continue the regular flow
But, is there a way to have my (special) interceptor even on error handling?

**Comment by jknack** [comment]
Correct, we do reset response entirely when error happens. You could apply the custom headers using a custom error handling, no?

**Comment by DrorBuhnik** [comment]
I can but that mean duplication of code and there won't be any separation of concerns which is the main point of interceptors

Can I start a new manually crafted chains of routes on demand?

**Comment by jknack** [comment]
Well it depends on how you organize your code. You could try request locals, locals are kept on err handlers, but you will need to set header and locals on your interceptor :S

> Can I start a new manually crafted chains of routes on demand?
Like what? Give me an example please

**Comment by DrorBuhnik** [comment]
For example the CORS interceptor that I want to have even on error.
Without it the web client can't even get the status code

How do you suggest using request locals?

**Comment by DrorBuhnik** [comment]
So I'm doing it manually until a better I have a better way

```
MySpecialHandler mySpecialHandler = new MySpecialHandler();
use("*", mySpecialHandler);

err((req, rsp, ex) -> {
    // "regular" error flow handling
    ...
    ...
    // fire the special handler that we need
    mySpecialHandler.handle(req, rsp, new Route.Chain() {
        @Override
        public void next(String prefix, Request req, Response rsp) throws Throwable {
            rsp.end();
        }
        @Override
        public List<Route> routes() {
            return null;
        }
    });
});
```

**Comment by jknack** [comment]
Clever and elegant
