### ISSUE TITLE
How to do redirect or forward in route?

### ISSUE THREAD

**Issue by thomasguo** [jooby-project/jooby#839]
Hi @jknack ,

How can we do redirect or forward in Jooby's routes as those in traditional servlet programming ?   I saw there is a `redirect() ` method in Response object, But nothing like` forward()`.  And the documenation doesn't say much about this topic. Could you please clarify it more?

Thank you.

**Comment by jknack** [comment]
Correct, no forward method.

Redirect is available from resopnse and results object:

```
post ("/save", () -> {
   return Results.redirect("/");
}
```

**Comment by thomasguo** [comment]
Got it. Thanks

**Comment by zhanghelook** [comment]
Hi!
I wonder how to do above in MVC route way?
`
@POST
@Path("/save")
public String save() {
    // Redirect
}
`

**Comment by jknack** [comment]
it is the same:

public Result save () {
  ...
  return Results.redirect("/");
}

:)

**Comment by zhanghelook** [comment]
@jknack Thanks!
Is it possible to do it conditionally?
For example:
If logged in, return user profile.
else, redirect to login page.
