### ISSUE TITLE
deprecate jooby-spec, jooby-swagger and jooby-raml

### ISSUE THREAD

**Issue by jknack** [jooby-project/jooby#843]
Next release will come with a new apitool module that is going to replace the existing route-spec: http://jooby.org/doc/spec

All the requirements described in #758 will be applied to the new module and also:

- have a support for kotlin
- better support for documentation
- upgrade to latest swagger and raml

The existing modules: jooby-spec, jooby-swagger and jooby-raml are going to be deprecated in favor of the new module.

**Comment by brandonlamb** [comment]
👍

**Comment by jknack** [comment]
Work done here: #858
