### ISSUE TITLE
cannot use abstract module classes

### ISSUE THREAD

**Issue by aronneberg** [jooby-project/jooby#847]
Hi,

as it seems, the route method "commonMethod" tries to instantiate abstract module classes.

I encountered this problem while writing some services that share several common methods and each service adds its own methods. The common methods are implemented in an abstract base class.

### how to reproduce

Use the following example to reproduce this error and create a service with an abstract base class.

```
public interface IService {

	String commonMethod();
}
```

```
public abstract class AbstractService implements IService {

	@Override
	public String commonMethod() {
		return "Hello World.";
	}
}
```

```
public interface IMyService extends IService {
	
	String myMethod();
}
```

```
public class MyService extends AbstractService implements IMyService {

	@Override
	public String myMethod() {
		return "Hello My World";
	}
}
```

The controller is split into an abstract part and a service specific part as well.

```
public abstract class AbstractController <T extends IService> {

	protected final T service;

	protected AbstractController(T service) {
		this.service = service;
	}

	@GET
	@Path("/commonMethod")
	@Produces("text/plain")
	public Result commonMethod() {
		return Results.ok(service.commonMethod());
	}
}
```

```
@Singleton
@Path("mycontroller/")
public class MyController extends AbstractController<IMyService> {

	@Inject
	public MyController(IMyService myService) {
		super(myService);
	}
	
	@GET
	@Path("/myMethod")
	@Produces("text/plain")
	public Result myMethod() {
		return Results.ok(service.myMethod());
	}
}
```

Finally I use the module to bind the service to its interface and load it in the application.

```
public class MyModule implements Module {

	public MyModule(final Jooby application) {
		application.use(MyController.class);
	}

	@Override
	public void configure(Env env, Config conf, Binder binder) throws Throwable {
		binder.bind(IMyService.class).to(MyService.class);
	}
}
```

```
...
use(new MyModule(this));
...
```

### encountered behaviour

The example above produces the following error:

No implementation for AbstractController was bound.
  at org.jooby.Jooby.lambda$bindService$53(Jooby.java:3058)

### expected behaviour

The class MyModule is bound and Abstract module is ignored.

Cheers
Andreas

**Comment by derKrischan** [comment]
Example given above by Andreas works with fix applied in PR #876 .
