### ISSUE TITLE
linked routes 

### ISSUE THREAD

**Issue by weisebrazil** [jooby-project/jooby#849]
In javax-rs we have SubResources.. Is it supported here?

```
@Path("/foo")
public class Foo {
   @GET @Path("/hello")
   public String hello() { return "hello"; }
}

@Path("/bar")
public class Bar { 
   @Path("/overridePath")
   public Foo overrideResource() { return new Foo() }

   public Foo fooResource() { return new Foo() }
}
```

**Comment by jknack** [comment]
It isn't. Can you described what is the final output? I probably can guess, but not sure how does it play the `fooResource` method without any annotation.

**Comment by weisebrazil** [comment]
HI!

In my sample, when a request hits `/bar/overridePath`or `/bar/foo` he will have a "Foo" resource

This way I can doo stuffs like using configured Resources coming from other paths. Like a address from a person, where Address is some generic resource mounted on `/person/{id}/address` and returned from a method in the Person class.

You can see more details here:
http://docs.jboss.org/resteasy/docs/3.1.4.Final/userguide/html_single/index.html#JAX-RS_Resource_Locators_and_Sub_Resources

**Comment by jaytheking** [comment]
@weisebrazil I was asking about the samething in the gitter chat. If it is of any help i ended up using the path [patterns](http://jooby.org/doc/#routes-path-patterns) to get similar functionality. Though its limited in what you can get done. In my case i just needed two top level routes with repeated sub routes which i ended up using `/**:subResourceType/**:subResourceTypeId` and used a switch case to delegate database access from there.
