### ISSUE TITLE
Can't change default application config file name

### ISSUE THREAD

**Issue by fabuloso** [jooby-project/jooby#854]
I face the ambiguos behavior by using the `conf` method for customizing the configuration file name.
For instance: 

```java
class App extends Jooby {
  {
    conf("myconfigfile.conf");

    // ...
  }

  public static void main(String... args) {
    run(App.class, args);
  }
}
```

But by default Jooby always starts with `application.conf` and catches other properties (by the way `application.conf` is another configuration file for another app not releated to Jooby). I would expect if I'm using the `conf` method to change such behaviour.

We met such issue using the Jdbc module that always complain about `db.url` property missing.

**Comment by jknack** [comment]
Looks like a bug, but wonder what `launch` does?

**Comment by tryIO** [comment]
sorry a typo
