### ISSUE TITLE
Add ability to turn of stack traces for Err,handle results in production

### ISSUE THREAD

**Issue by jaytheking** [jooby-project/jooby#856]
As of now, when an error occurs in production of a restful service the stack trace gets sent with the response which is not exactly good thing to show.

I propose that when the `env = prod` is set that the result be something like this `{"message":"For input string: \"asd\"","status":400,"reason":"Bad Request"}`

**Edit** : In the meantime im doing something like this.
```
        err((req, rsp, ex) -> {

            Map<String, Object> err = ex.toMap();
            err.remove("stacktrace");

            rsp.send(
                    Results
                            .when(MediaType.html, () -> Results.html(VIEW).put("err", err))
                            .when(MediaType.all, () -> err));
        });
```

**Comment by jknack** [comment]
As workaround you can create a custom error handler like:

```
