### ISSUE TITLE
jooby-run's Eclipse hot-reload terminates the application

### ISSUE THREAD

**Issue by dustContributor** [jooby-project/jooby#857]
Hi! I was trying out jooby-run from Eclipse, with the steps it specified creating the run configuration with the arguments and so on.

Trying a simple:

```java
public class App extends Jooby {
	{
		get( "/", () -> "Hello World!" );
	}
}

public static void main ( final String[] args ) {
		run( App::new, args );
}
```
Straight from the project generator that Jooby's site Quick Start section details. 

If I change anything, hot-reload successfully detects the changes, stops my previous App instance, creates the new one, and starts it.

The issue is that it does a System.exit right here:
https://github.com/jooby-project/jooby/blob/master/modules/jooby-run/src/main/java/org/jooby/run/Main.java#L438

It seems it calls it by checking if the app instance here says it isn't started:
https://github.com/jooby-project/jooby/blob/master/modules/jooby-run/src/main/java/org/jooby/run/Main.java#L431

From what I've debugged, it is calling "isStarted" on my old App instance, not the new one. So the old App instance says it isn't started (which is true, it just got stopped), and the code does a System.exit on my VM which shut downs everything (without exceptions since it's all handled properly).

I'm not sure where that atomic reference should be updated with my new App instance, I don't see anywhere where that JoobyRef is updated.

And for reasons I don't understand, doing mvn jooby:run works just fine with the hot reloading. It seems I can only reproduce it if I run the application from Eclipse (which would be really handy since I can use the  debugger that way).

I'm just starting with Jooby so no idea if I'm missing anything.

**Comment by jknack** [comment]
Why did you exactly run from Eclipse? Application restarts are available via Maven/Gradle, but not if you run from Eclipse.

**Comment by dustContributor** [comment]
I was following instructions from here:
https://github.com/jooby-project/jooby/blob/a6b1e460db317dbe8d05edd31bce29c3fac22961/md/doc/maven-plugin/maven.md

Bottom section details how to launch from Eclipse.

But now that you mention it, I can't find that in master, and that's pretty old. Was that feature deprecated?

**Comment by jknack** [comment]
Ohh completely forgot about that :(

It is an unused feature.. and not tested feature. Probably better to skip for now.

Still you can use Eclipse/Intellij remote debugger. Just make sure to start maven in debug mode and everything will works:

    mvnDebug jooby:run

**Comment by dustContributor** [comment]
Ah I see, well I guess I'll just set up the remote debugger then.

Anyway, great work you're doing here! :smile: I'll be closing this, thanks!

**Comment by jknack** [comment]
Thank you, you can support my work by staring/follow the project :)

**Comment by dustContributor** [comment]
Done!
