### ISSUE TITLE
Gradle 4.0 with shadowJar fails to properly build jooby application

### ISSUE THREAD

**Issue by jaytheking** [jooby-project/jooby#882]
I am able to build a fat jar using the gradle shadowJar plugin mention in the docs. However when building with gradle 4.0 i get a series of [exceptions](https://gist.github.com/jaytheking/4a630064ffb480f87715ef010cfbd02e).

I am able to fix this issue by using gradle 3.xx, its not ideal because i am using features from gradle 4.x in my project.

**Comment by nlochschmidt** [comment]
@jaytheking our last jooby project was build with Gradle 4.0.2 without any problem, however we have used Netty instead of Jetty as our server.

**Comment by jaytheking** [comment]
@nlochschmidt did you use shadow jar? Reckon you can try build with jetty and see if you get similar problem? I can reproduce same stack trace on two different computers

**Comment by nlochschmidt** [comment]
@jaytheking Ah, which version did you use, I remember we used an older version:
```
plugins {
  id "com.github.johnrengelman.shadow" version "1.2.4"
}
```

**Comment by jaytheking** [comment]
@nlochschmidt using version 1.2.4. I might have to create an issue on shadow jar repo too.

**Comment by nlochschmidt** [comment]
@jaytheking FYI, I just tried it in our project and I can confirm that `runShadow` with Gradle 4.0.2 and the shadow plugin 1.2.4 on Jooby 1.1.3 works for Netty and Undertow but **fails for Jetty**.

**Comment by jknack** [comment]
Add these lines to your build.gradle

```
shadowJar {
  mergeServiceFiles()
}
```

Then `runShadow`  (make sure you clear the build directory before runShadow)

You need `mergeServiceFiles` so Jetty can read all the services
