### ISSUE TITLE
Jooby env

### ISSUE THREAD

**Issue by nedtwigg** [jooby-project/jooby#886]
I have an `application.dev.conf` and an `application.prod.conf`.

I also have these classes:

```java
public static class Prod extends Jooby { {
    use(ConfigFactory.parseResources("application.prod.conf"));
    ...
} }
public static class Dev extends Jooby { {
    use(ConfigFactory.parseResources("application.dev.conf"));
    ...
} }
```

If I run `Jooby.run(Prod.class)`, then my configuration values are from `.dev.conf`, not `.prod.conf`.  This is fixed if I instead call `Jooby.run(Prod.class, "prod")`.  It seems like `ConfigFactory.parseResources()` has no effect.

Is this because config loading is hierarchical?  E.g. a property is first loaded from whatever env suggests (happens to be `dev` if nothing is specified at command line), and then the `use(ConfigFactory...)` is looked at next?  Is there any way to suppress the loading of the env config?

**Comment by jknack** [comment]
> Is this because config loading is hierarchical? E.g. a property is first loaded from whatever env suggests (happens to be dev if nothing is specified at command line), and then the use(ConfigFactory...) is looked at next? Is there any way to suppress the loading of the env config?

Exactly.

The way you control dev vs prod conf files is via `application.env` property, which you can set from `.conf` or application arguments.

> Jooby.run(Prod.class, "prod")

Is a shortcut that translate to: `application.env=prod`

> use(Conf)
It is a way to use another property file rather than `application.conf`

use(ConfFactory.parseResources("myapp.conf"));

cool?

**Comment by nedtwigg** [comment]
Almost cool ;-)

If I do `Jooby.run(Prod.class)`, and Prod has `use(ConfigFactory.parseResources("application.prod.conf"));`, *I still get .dev.conf*.  And that appears to be the intended behavior.

I *love* Jooby, because it's so unopinionated.  I guess I'm a little surprised that there's this one magic env conf part that I can't seem to disable.

**Comment by jknack** [comment]
You don't have to explicitly tell Jooby about the .[env].conf file. Instead you start with a single file: `application.conf` then if you need to override one or more properties per environment, you create `application.[env].conf`

If you need prod mode, then `Jooby.run(Prod.class, "prod")`. That is the recommended way of using it.

If still want to go like in your example, go to your `application.prod.conf` and add `application.env=prod`. In your example, you never set this property that is why .dev.conf is loaded (`application.env=dev` is the default environment)

**Comment by nedtwigg** [comment]
Gotcha.  Thanks!
