### ISSUE TITLE
Surprising param encoding

### ISSUE THREAD

**Issue by nedtwigg** [jooby-project/jooby#900]
I have a route like this:

```java
env.router().get("/confirm/:code", req -> {
    return req.param("code").value();
});
```

I would expect that `/confirm/a+b` would parse to `a+b`, but instead it is `a b`.  Is this the intended behavior?  And if it is, where can I find the docs on what other transformations are applied?

**Comment by nedtwigg** [comment]
One kinda nasty workaround:

```java
env.router().get("/confirm/:code", req -> {
    return req.rawPath().substring("/confirm/".length());
});

**Comment by jknack** [comment]
I see, will have a closer look soon

**Comment by jknack** [comment]
Which server is this?

**Comment by nedtwigg** [comment]
netty, jooby 1.1.3

**Comment by nedtwigg** [comment]
Wow!  Quick turnaround!  Love Jooby, hate to be open a huge can of worms, but now I think there's a deeper issue about routes and route parameters being matched after decoding, which opens a security vuln.

## breaking change

Let's say I used Jooby to make a Medium.com clone, and I had a path `/:user/:title`, and I expect `/nedtwigg/My+essay` to turn into `My essay`, as it has so far.  Now it will turn into `My+essay`.  That's a pretty big change - I'd rather change my new app than break your loyal users' existing apps.

## hard to document

I was surprised by the original behavior, and couldn't figure out what the intent was.  If I knew the intent, then I could workaround myself.  I see now from the commit that the behavior was `URLDecoder.decode()`, and I see that it is been changed to `URLDecoder.decode(path.replace("+", "%2b")`, which is arbitrary.

Instead of changing the behavior, I would encourage instead to document what the behavior is.  I see now that for the URL `this%3Dthat?this=other`, `rawPath` is the `this%3Dthat`, and `path` is `URLDecoder.decode(rawPath(), "UTF-8")` = `this=that`.

## deeper issue - path matching before or after decoding

Let's say I'm building a login system that protects user data.  A user hits a link `mypage.com/privateData?key=value`.  They're not logged in, so I want to redirect them to a login page, and I want that login page to have a `redirect` parameter so that after they login I can redirect them back to their original request.

One way I can do this is `application/x-www-form-urlencoded`.

```java
get("/login", req -> {
    String redirect = req.params("redirect")
    ...
})
```

In that case, the URL would look like this: `/login?redirect=%2FprivateData%3Fkey%3Dvalue`.  Note that the `/?=` marks of the original request have been encoded, but not `/login?redirect=`.  The values in the query string are decoded *after* the original has been parsed as raw.

Another way I could implement this is with a route parameter:

```java
get("/login/:redirect", req -> {
    String redirect = req.params("redirect")
    ...
})
```

In that case, my URL would look like this: `/login/%2FprivateData%3Fkey%3Dvalue`.  But in Jooby, I get `Not Found(404): /login//privateData?key=value`.  Because routes are matched *after* decoding, nesting is impossible.

It also opens a kind of injection vulnerability.  Let's say I have two routes, `/:user/:title`, and `/:user/:title/delete`.  Alice wrote an article called "vulnerable", which lives at `/alice/vulnerable`.  If I can set my username to `alice%2Fvulnerable`, and then write an article called `delete`, then Jooby will call `/alice/vulnerable/delete`, even though I'm not alice.

## proposed fix

To demonstrate the confusion the best that I can, let's go back to this app:

```java
get("/login/:redirect", req -> {
    return "rawPath=" + req.rawPath() +
        "<br>path=" + req.path() +
        "<br>params="+ req.params();
});
```

Here's the output for some troublesome URLs:

```
/login/somewhere?redirect=smashed
  rawPath=/login/somewhere
  path=/login/somewhere
  params={redirect=[somewhere, smashed]}

/login%2Fsomewhere
  rawPath=/login%2Fsomewhere
  path=/login/somewhere
  params={redirect=[somewhere]}

login%2Fsomewhere?redirect=smashed
  rawPath=/login%2Fsomewhere
  path=/login/somewhere
  params={redirect=[somewhere, smashed]}

login/somewhere%3Fredirect%3Dsmashed?redirect=doublesmashed
  rawPath=/login/somewhere%3Fredirect%3Dsmashed
  path=/login/somewhere?redirect=smashed
  params={redirect=[somewhere?redirect=smashed, doublesmashed]}
```

In a `2.x`, I think it would be good if:

- `path` was marked as deprecated
- route matching was based on `rawPath`
- `params` only held parameters from the query string, and there was a separate `routeParams` map for parameters decoded from the route.  *Maybe* the parameters, once parsed, could be run through URLDecoder, but I think it would be best if they remained raw.  Query strings are standardized, but route parameters are not, so best to leave that to the application I think.

Sorry to have opened such a can of worms ;-)

**Comment by nedtwigg** [comment]
> Query strings are standardized, but route parameters are not, so best to leave that to the application I think.

I think this is probably wrong.  Maybe better if `Route.Definition::reverse` did URLEncode, and then routeParams had URLDecode.  That way so long as people build routes using Route.Definition and not string concatenation, they'll be immune to injection attacks.

**Comment by jknack** [comment]
Well the .path function works as in the majority of the web framework available today. The `+` is a special case that was missing while decoding the path (`+` is allowed in path).

Still think your suggestions for 2.x sounds good

**Comment by nedtwigg** [comment]
Even if most frameworks do this, I'd be hesitant to break your existing users, especially if there are other changes that will require a `2.x` to fix anyway.  Jooby is quite popular, and I seem to be the first to complain about the `+` - it seems very likely that the current change will break existing apps, possibly in hard to track ways (e.g. random single-sign-in links),

**Comment by jknack** [comment]
Are you suggesting to revert this change?

I think `+` is not used so much as part of the path, that is why I think the change is minor today.

**Comment by nedtwigg** [comment]
I would revert this change.  I agree that `+` is not part of the path often, but I think it is part of route parameters fairly often.

I bumped into this bug because we generate random bytes, Base64 encode them, and create a link.  They don't include a `+` very often, but sometimes they did.  When they did, it didn't work, and it was hard to track down.

If I generated these links by URL encoding the Base64, I would not have had a bug.  But after this change, I would have a bug, and it would be hard to track down.

**Comment by jknack** [comment]
> but I think it is part of route parameters fairly often.

What do you mean query parameters?
+ in query parameters are decoded as space
+ in path parameter were decoded also as space, but now it is not

> If I generated these links by URL encoding the Base64, I would not have had a bug. But after this change, I would have a bug, and it would be hard to track down.

I don't get why, please show me

**Comment by nedtwigg** [comment]
Our app sends account confirmation links that look like this: `https://ourapp.com/confirm/8J2FsCzLuSa0glPuqPz0hKuYawcKXOEKhAnFQeYg9nE=`

We generate them like this:

```java
byte[] bytes = new byte[32];
random.nextBytes(bytes);
String code = Base64.getEncoder().encodeToString(bytes);
code = code.replaceAll("/", "0"); // the '/' messes up routing
```

Sometimes the code had a `+`, but not always, so it was very hard to diagnose.  When we figured it out, we briefly used this to fix it:

```java
// '+' turns into ' ' for some reason.  Whatevs, we'll pretend it's always a space
code = code.replaceAll('+', ' ');
```

So whichever way it should be, your current users have adapted or worked around, and this will break them.  A better example of why this is a breaking change is:

```
/:user/:title"
1.1.3: /nedtwigg/My+essay -> My essay
1.2.0: /nedtwigg/My+essay -> My+essay
```

As a user, I would be frustrated if a change of this type happened without a bump in the major version.

**Comment by nedtwigg** [comment]
Thanks!  As a first step towards safer and easier reverse routing, I submitted PR #917.  It's fully `1.x` compatible, but would really shine if the `2.x` escaping improvements discussed above were implemented.
