### ISSUE TITLE
Safe reverse routing

### ISSUE THREAD

**Issue by nedtwigg** [jooby-project/jooby#920]
While investigating #900, we bumped into some ideas on reverse routing.  The gist of it is that building routes with string concatenation is brittle and dangerous, and it would be cool if we could do something better.

The use case is this:

```java
static final RoutePattern USER_TITLE = new RoutePattern("GET", "/:user/:title");

{
  get(USER_TITLE.pattern(), req -> {
    return req.param("title").value() + " written by " + req.param("user").value();
  });
}
```

Ideally, we would never build URLs by `"/" + user + "/" + title`, but instead use `USER_TITLE.reverse(user, title)`.  The vulnerability is if the username or title contains `/` or a url-encoded slash `%2F`.  Because Jooby routes based on `path()` instead of `rawPath()`, if a user is able to put `%2f` into their username, they can access paths that they were not intended to.

To make this bulletproof, we'd need to make the following changes:

1. `RoutePattern.reverse()` would need to call UrlEncode on its arguments.
2. `Route.vars()` would need to call UrlDecode when each of its arguments is parsed.
3. Jooby would need to route based on `rawPath()` instead of on `path()`.

I submitted a quick-n-dirty PR of this concept in #919.  I think it's a smell right now that `RoutePattern` is in the `org.jooby.internal` package, and that it includes the HTTP verb.  Perhaps we could refactor it into `org.jooby.PathPattern`, and remove the verb.  `Route.Definition::matches` contains the HTTP verb anyway, so I don't think it would be hard to move this responsibility out of `RoutePattern`.

Obviously, this would be a breaking change, not sure if it's worth the churn.  Maybe it can be a candidate for things to improve in a 2.0.

Thumbs up if you'd want this, thumbs down if not :)

**Comment by nedtwigg** [comment]
Congrats on getting jooby 2 to the RC phase!!  Does it have anything to offer for reverse routing?

**Comment by jknack** [comment]
2.x matches using raw path (thank you) but nothing has been done for reverse routing... we do have the chance to define the API for it

**Comment by nedtwigg** [comment]
Great!  With matching done based on rawPath, then it should be possible to do all the rest even without direct support from jooby.

I just peeked around the jooby 2 source, and it looks like (at least for the kind of routing I have in mind) there's nothing in Jooby's guts which is helpful.  Jooby 1.x's RoutePattern was helpful, but it looks like some of that has been soaked up by the radix tree in 2.x.

But it's totally possible to add it as a third-party lib, and just generate a `String` pattern at the end.

Migrating to 2.x is super low on my priorities because we're so happy with 1.x, but matching on raw path is a really nice improvement that will lean us towards to 2.x

Very happy to see that it looks like a modest evolutionary improvement :)
