### ISSUE TITLE
Scanner does not find annotated classes in Jooby 1.2.0 when run via Maven task

### ISSUE THREAD

**Issue by gwbrown** [jooby-project/jooby#923]
# Steps to reproduce:

1. Generate an Archetype project as [in the Quick Start guide](http://jooby.org/quickstart/).
2. Add a class, annotated with `@Path("/endpoint")` including a method annotated `@GET` that returns some string.
3. Add jooby-scanner in the pom.xml and App.java as indicated [in the Jooby Scanner documentation](http://jooby.org/doc/scanner/)
4. Run the app with `mvn jooby:run`
5. Make an HTTP request to `localhost:8080/endpoint` using a browser

# Expected Behavior:
The HTTP call will return the string set in step 2.

# Observed Behavior:
The HTTP call returns a 404 error.

# Notes:
- When I switch the `jooby` and `jooby-scanner` versions to 1.1.3, this behaves as expected.
- When I run the application via IntelliJ, rather than via Maven, this behaves as expected.

# Environment
MacOS 10.12.6 (Sierra)
Java 1.8.0_121
Maven 3.5.0

# Attachments
Minimal reproduction case: [my-app.zip](https://github.com/jooby-project/jooby/files/1416690/my-app.zip)

**Comment by jknack** [comment]
I submitted a patch to fastscanner: https://github.com/lukehutch/fast-classpath-scanner/pull/150

As workaround you can downgrade jboss-modules:

```xml
   <plugin>
        <groupId>org.jooby</groupId>
        <artifactId>jooby-maven-plugin</artifactId>
        <dependencies>
          <dependency>
            <groupId>org.jboss.modules</groupId>
            <artifactId>jboss-modules</artifactId>
            <version>1.5.4.Final</version>
          </dependency>
        </dependencies>
    </plugin>
```
