### ISSUE TITLE
jooby 2: ideas, design and implementation

### ISSUE THREAD

**Issue by jknack** [jooby-project/jooby#926]
This is an open discussion of what we want for Jooby 2.x. For now we will start a discussion here and then cleanup ideas and feature to a wiki page (or similar).

Here are some ideas for 2.x:

- Reduce the gap with the web servers
  - Should we open Netty/Utow/Jetty API as we do with existing modules?
  - Closely bind a Jooby handler to a server handler.
  - Should we allow to run a server handler directly?
- Allow to run code in IO thread
- Add semantics for blocking handler
- Still default execution mode should be as it is today
- RadixTree for a routing/path matcher?
- Dynamic, mutable and thread safe pipeline? So, we are able to resolve issues like #825 
- Replace Request & Response with Context object
- Remove side effect handler and only keep functional handlers
  - Make the .send method to return a value
- Implement a ctx.write method, so we can incrementally build a response

This is just a start, I'm sure there is more to discuss.

**Comment by miklever** [comment]
I wiil be glad if Jooby route matching will be more flexible. As for me for now it really lacks some essential features:

- request forwarding (internal redirect)

```java
get("/author/{id}/books", (req) -> {
    req.forward("/books?authorID=" + req.param("id").value()
});
```

or

```java
get("/author/{id}/books", (req, chain) -> {
    chain.next("routeName", req);
});
```

- query string matching

```java
get("books?authorID={id}", (req) -> { /*...*/ });
get("books?format={format=short}", (req) -> { /* optional param */ });
```

**Comment by paulovictorv** [comment]
what about #864?

**Comment by nedtwigg** [comment]
I'd like to see safer reverse routing. issue #920, PR #919

**Comment by jaytheking** [comment]
I'd like to see the use of [webjars](https://www.webjars.org/) as a module to make use of external asset libraries in gradle or maven build scripts.

**Comment by jknack** [comment]
@jaytheking never found webjars useful... but they are supported today as part of asset handler:

```
assets("/assets/**", "/META-INF/resources/webjars/{0}");
```

**Comment by jaytheking** [comment]
@jknack aahh cool, never mind then ill just use what you showed here.

**Comment by brandonlamb** [comment]
* Any way to somehow provide a Kotlin implementation around start of the world to implement Kotlin coroutines?
* Implement some kind of backpressure feature?
* Circuit breaker?

**Comment by feffi** [comment]
A close focus on InfoSec and OWASP (especially A9) would be very nice.

**Comment by feffi** [comment]
How about structuring the tests in Test-suites, so every module can test it’s own files with module-test and depend also on core tests?

**Comment by feffi** [comment]
Enhance documentation for more examples/use cases.

**Comment by JavierFuentes** [comment]
Hi @jknack, 
please, **provide a CLI** (like JHipster or Micronaut do) to generate dynamic starter template projects combining modules and options like Java vs Kotlin, scripting vs MVC, Securization alternatives, ORM alternatives, Database alternatives, HTML Template Engines alternatives, Maven vs Gradle, Dockerization and so...

Templates could apply best recommended practices using jooby for performance, modularity, scalability, testing...

I have not found any benchmark comparing the performance of jooby using MVC vs Script mode, but if there is significant differences, a **transpiler from MVC to scripting code style** would be good...

I've been testing Jooby 1.6 with Kotlin and MVC for a few days and I really love it... I don't know what jooby 2.x could improve, but provide a CLI and a transpiler for Jooby 1.x could help make it more popular between beginners like me.

Congratulations for your work.

**Comment by jknack** [comment]
Almost 2 years later... Jooby 2.0.0 is out
