### ISSUE TITLE
Content-Encoding : gzip doesn't work

### ISSUE THREAD

**Issue by bludwik** [jooby-project/jooby#934]
I try to enable compression without success.
When I set Content-Encoding : gzip (or deflate) content seems to be cmpressed  but the  Content-Encoding header is absent in response in browser (it seems to be replaced by connection : keep-alive)

I've tested on netty  and jetty

Anyway I havn't found any information on: how to compress assets or json responses in Jooby documetation...

**Comment by jknack** [comment]
Correct, we don;t support gzip yet. See #762

**Comment by bludwik** [comment]
Thank you for fast answer. 
Do you plan to implement it? When?

**Comment by jknack** [comment]
Yea, it supposed to go in 1.2.0 but then time wasn't enough.

The issue is still open bc want to add gzip someday... probably for 2.x (but there isn't a time yet)

would you like to submit a pull request?

**Comment by bludwik** [comment]
Thank you. I'll wait

**Comment by feffi** [comment]
Hi, I wouldn't suggest to implement this on SPDY because of the CRIME attack. I would suggest to do some research where to put this, also see https://github.com/netty/netty/issues/991

**Comment by jknack** [comment]
Added to 2.0.0 https://static.javadoc.io/io.jooby/jooby/2.0.0/io/jooby/ServerOptions.html#setGzip-boolean-
