### ISSUE TITLE
Run CLI tool

### ISSUE THREAD

**Issue by Pedramrn** [jooby-project/jooby#950]
I want to run a CLI tool before every jooby start up, I'm thinking of writing a task in gradle that would run on every jooby run task. Is it the right way to do this?

**Comment by jknack** [comment]
I'm not sure what you exactly need.. but I'm curious about:

> I'm thinking of writing a task in gradle that would run on every jooby run task

I'm not a gradle user, so I will appreciate if you can share once you do it.

Thanks and sorry for late response
