### ISSUE TITLE
Routes precedence bug-hancement

### ISSUE THREAD

**Issue by paul-hammant** [jooby-project/jooby#952]
From the documentation:

```
Will the server print all of them? “first”? “third”?

It prints “first”. The act of doing a rsp.send() will terminate the flow of the request then and there; the request is not passed on to any other route handler.
```

`rsp.status(nnn)` should behave as rsp.send does and terminate the flow of the request there and then, but does not.

**Comment by jknack** [comment]
req.status can't by any means terminate the response.

now if you need that for one specific use case, you must call: end.

    req.status(nnn).end();

**Comment by paul-hammant** [comment]
Thanks
