### ISSUE TITLE
Detect connection closed

### ISSUE THREAD

**Issue by kevin-stuart** [jooby-project/jooby#954]
Is it possible to detect if a client closes/looses the connection before a response is written and intercept this event? The idea is to cancel some expensive operation made by the request in this case.

**Comment by jknack** [comment]
not possible today :(

**Comment by kevin-stuart** [comment]
I think it would be a very good feature to add. Maybe it could already be done with effort by using a custom Netty server.

I also found an older thread here: https://github.com/jooby-project/jooby/issues/207
I think that it could be used to implement this feature.

It would be great to be able handle connection closed events for different routes so you could free resources.

**Comment by jknack** [comment]
It sounds good, but:

1. not sure if we can rely on this 100%
2. we need to find a way to do the same in the other servers: utow and jetty
