### ISSUE TITLE
Feature request: Have an offline version of jooby-apitool

### ISSUE THREAD

**Issue by hwacookie** [jooby-project/jooby#957]
It would be great if we could have an offline version of the apitool module that generates the OpenAPI specs on request while the application is running. It's good to have it at runtime so new clients can easily create client access code on demand. However, in some cases it would also be great if this generated *.yml/*.json could also be created "offline", e.g. when building the app with maven. It is not allways adviseable or even possible to run the application on the buildsystem just to have the *.yml created with e.g. a wget call.

**Comment by jknack** [comment]
As a workaround you can generate the swagger.json or swagger.yaml and then load it using a path/file  option:

```java
{
  use(new ApiTool()
    .swagger("/swagger").path("myswagger.json")
  )
}
```
