### ISSUE TITLE
2nd thymeleaf code snippet (in the documentation) not tested in integration test

### ISSUE THREAD

**Issue by paul-hammant** [jooby-project/jooby#965]
https://github.com/jooby-project/jooby/blob/master/modules/jooby-thymeleaf/src/test/java/app/ThymeleafApp.java doesn't show

```
// Or Thymeleaf API:
  get("/thymeleaf-api", () -> {
    TemplateEngine engine = require(TemplateEngine.class);
    engine.processs("template", ...);
  });
```

I'd expect an interoperation with Results, or a return to handler in the .process(..) line.

Also: s/processs/process/ :)

**Comment by jknack** [comment]
Just an example to see how to use the  `thymeleaf` API (no need for test)

will fix the typos.

**Comment by paul-hammant** [comment]
Thx dude.
