### ISSUE TITLE
Kotlin Unit Testing with MockRouter?

### ISSUE THREAD

**Issue by squarism** [jooby-project/jooby#966]
I'm new to Kotlin and Jooby.  I've got integration tests working (where it really hits the network) with rest-assured.  I'm trying to do more stubbed or mocked testing where I don't have to have the server running.

This was taken and modified from the examples but I'm not sure why the instance coming back is my app when I'd expect this to be like a body or something.

```kotlin
// inside of a unit test
val router = MockRouter(App())  // the first argument to MockRouter is an instance of my app

// now the tricky bit ...
val result = router.get("/pies")  // this won't work because it can't infer the type

// ok .. maybe it's a String?
val result = router.get<String>("/pies")
// ClassCastException com.squarism.Pie cannot be cast to String -- hmm

// When I debug with IDEA, I get some strange results.
// If I get it a wrong path, it takes one code path where I can see the result object coming back.
router.get<MockRouter.MockResponse>("/foo")
```

org.jooby.Err object has attributes like
```
status=404
detailMessage="Not Found(404): /1"
...
```

Note that `MockResponse` is a private class and actually arbitrary because any <T> will make Jooby take the Err codepath and not get the runtime ClassCastException.

In the Java examples, it seems like the response is supposed to be a string.  I've tried
```kotlin
val result : String = router.get("/pies") as String
```
But this is essentially the same thing.

Here is the result my spike app returns when running.  This is sort of the MockResult I'd test.  I can test this fine with an integration test (hits the network).
```json
[
  {
    "name": "Apple",
    "calories": 42
  },
  {
    "name": "Cherry",
    "calories": 56
  }
]
```

I saw the gradle starter project but that seems to boot the app, test it on the network and then shut it down.  Maybe Maven and Unit Testing with Kotlin isn't done yet?

**Comment by jknack** [comment]
Going to test and get back to you

**Comment by jknack** [comment]
I added a unit test to [kotlin-starter](https://github.com/jooby-project/kotlin-starter/commit/c7d482415d625fecbdc3771f8e4157efb90451c7) with mocks using mockito.

You need to check what your route returns and update the test. For example if your route returns a list of Pie, then:

```kt
  val result = router.get<List<Pie>>("/pies")
```

The response is whatever your route returns.

Let me know if you have questions

**Comment by squarism** [comment]
Excellent.  Worked.  Thanks for going a bit outside of the project to answer I guess what was really a Kotlin question.
