### ISSUE TITLE
Jooby.pathPrefix("*/") has a strange result

### ISSUE THREAD

**Issue by paul-hammant** [jooby-project/jooby#967]
`Jooby.pathPrefix("*/")` gives a result of "/*" which isn't what I wanted. I'd have typed it if I wanted it ;)

I'm trying to map a route to any directory.  That would I prefix with "*" or "**" and terminate the path string with "/".  For some reason the pathPrefix code morphs that into something completely different. I don't understand the code in question (I looked).

I could do an `if (route.endsWith("/")){ .. }` around the block of code, but I'd rather the route dispatcher fell through to the next route handler instead of stepping into this one.

**Comment by jknack** [comment]
Hi Paul,

 `prefixPath` is a private method, not sure how are you using it 😄 

 Jooby paths are `normalized` and the trailing slash is always removed so request to `/foo` or `/foo/` are the same.

No matter what you send.. if ends with `/` it will be removed.

**Comment by paul-hammant** [comment]
Sorry for the lack of context . I'm using it via normal route setup:
```
get("**/", () -> "yeehaaaa");
```
When that wasn't handling my routes I cranked up the debugger to learn more. Hence the very specific bug report.

- Paul
