### ISSUE TITLE
log4jdbc driver support for Jdbc module

### ISSUE THREAD

**Issue by vksiva** [jooby-project/jooby#972]
I am trying to use log4jdbc (Java JDBC driver that can log SQL and/or JDBC calls). I get the following error when initializing the application

**application.conf entries**
db.url = "jdbc:log4jdbc:mysql://host:port/db"

**Error**
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'databases.log4jdbc'

Is there any other way I can get JDBC logging/timing data or enable log4jdbc to work out of the box when configuring Jdbc module.

Please advise.

**Comment by jknack** [comment]
Not possible today, but will add support for it

**Comment by vksiva** [comment]
A workaround till the time this enhancement goes to GA.
```
# Setup a dummy url property and later override with HikariCP's jdbcUrl property
db.url = "jdbc:mysql://localhost/db"
db.dataSourceClassName = ""

# Override using HikariCP properties
db.hikari.jdbcUrl = "jdbc:log4jdbc:mysql://localhost/db"
db.hikari.driverClassName = net.sf.log4jdbc.sql.jdbcapi.DriverSpy

```
