### ISSUE TITLE
jooby-gradle - netty tcnative fails to load

### ISSUE THREAD

**Issue by vksiva** [jooby-project/jooby#973]
When using the jooby-gradle project, netty tcnative fails to load. It throws the below error

DEBUG [Hotswap] netty_transport_native_epoll_x86_64 cannot be loaded from java.libary.path, now trying export to -Dio.netty.native.workdir: /tmp/web
java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path

After some trial and error, and adding the netty epoll dependency, the following line gets printed in the log
DEBUG [Hotswap] Successfully loaded the library /tmp/web/libnetty_transport_native_epoll_x86_64563245363943117440.so

**build.gradle**
```
- compile "io.netty:netty-tcnative-boringssl-static:${dependencyManagement.importedProperties['boringssl.version']}:${osdetector.classifier}"
+ compile "io.netty:netty-transport-native-epoll:${dependencyManagement.importedProperties['netty.version']}:${osdetector.classifier}"
+ compile "io.netty:netty-tcnative-boringssl-static:${dependencyManagement.importedProperties['boringssl.version']}"
```
Hope it is a valid change ...

**Comment by jknack** [comment]
Yes, I couldn't find a clean way to load OS dependencies via gradle :(

Adding the dependency is the right thing to do.

Still, the [gradle-starter](https://github.com/jooby-project/gradle-starter) project should do it, did you try it?

**Comment by jknack** [comment]
Oh wait I see, there is one dependency missing. can you send a pull request to https://github.com/jooby-project/gradle-starter?

Thanks

**Comment by vksiva** [comment]
@jknack I have created a pull request for the same. 

Thanks
