### ISSUE TITLE
MockRouter - Mockito example needed - this'll do for documentation

### ISSUE THREAD

**Issue by paul-hammant** [jooby-project/jooby#981]
public void fooTest() throws Throwable {
    Response rsp = mock(Response.class);
    when(rsp.status(200)).thenReturn(rsp);
    when(rsp.type("application/json")).thenReturn(rsp);

    String result = new MockRouter(new App(), mock(Request.class), rsp)
            .get("/some/route.json");

    assertThat(result, equalTo("{ \"foo\": \"bar\" }"));

    // optional mockito verifications.
    verify(rsp).type("application/json");
    verify(rsp).status(200);
  }

**Comment by jknack** [comment]
There is a better doc in 2.0.0 https://jooby.io/#testing-unit-testing
