### ISSUE TITLE
Ability to set jvm args for joobyRun task in jooby-gradle-plugin

### ISSUE THREAD

**Issue by murrayju** [jooby-project/jooby#985]
My application depends on `java.library.path` being correctly set as a jvm arg. I cannot figure out how to configure the `joobyRun` gradle task to set this property correctly. Can this be added as a feature (if it doesn't already exist)? It looks like the Maven equivalent supports passing `vmArgs`.

**Comment by jknack** [comment]
This need to be done at gradle level due we don't start a new JVM
