### ISSUE TITLE
ApiTool misses routes in swagger doc when variable used for path

### ISSUE THREAD

**Issue by murrayju** [jooby-project/jooby#986]
Given this simple example:
```
class RestServer : Kooby({
  // JSON support
  val mapper = ObjectMapper().registerModule(KotlinModule())
  use(Jackson(mapper))

  val test = "/api/foobar"
  get(test) { "get test" }
  delete(test) { "del test" }

  // API documentation via Swagger
  use(ApiTool().swagger("/docs").filter({
    it.pattern().startsWith("/api/") && it.method() != "*"
  }))
})
```
The first route is documented, but not the second:
![image](https://user-images.githubusercontent.com/508461/35303672-026c8a40-0050-11e8-9d7f-1e430903ad30.png)

If I use two string literals instead, it works as expected:
```
  get("/api/foobar") { "get test" }
  delete("/api/foobar") { "del test" }
```
![image](https://user-images.githubusercontent.com/508461/35303616-d1b85c26-004f-11e8-9d14-fdb7884bc6e1.png)

**Comment by jknack** [comment]
Will look, but we should use the `path` operator for such uses cases:

```
path("/api/foobar") {
   get { "get test" }
   delete { "del test" }
}
```

👍

**Comment by murrayju** [comment]
Confirmed that using `path()` is a good workaround for this problem.
