### ISSUE TITLE
Guava version is out of date - and threre's breaking API changes

### ISSUE THREAD

**Issue by paul-hammant** [jooby-project/jooby#993]
https://github.com/jooby-project/jooby/search?utf8=%E2%9C%93&q=%22guava.version%22&type=

Of course Jooby works fine.  Its other libraries that are further ahead with their dep on Guava that won't work with the older version.  This happens so often in Java-land with .. with Guava in particular :-(

Latest is  presently <version>23.6-jre</version>

**Comment by paul-hammant** [comment]
24.0-jre now

**Comment by feffi** [comment]
also see https://github.com/jooby-project/jooby/issues/1129
